### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by Alloyd854** [Sketchware-Pro/Sketchware-Pro#100]
Hi. I'd like to make a translations for this mod of Sketchware.

**Comment by JavkhlanK** [comment]
Sketchware already supports language packs.

**Comment by Alloyd854** [comment]
No, I want to translate a mod, not Sketchware.

**Comment by Alloyd854** [comment]
All mod

**Comment by JavkhlanK** [comment]
What part exactly? Most of the Mod uses Sketchware's strings, so it's not needed, but most Modder's classes use hardcoded strings, so translation will be hard, unless switching to resource strings

**Comment by Alloyd854** [comment]
I translated strings.xml, but it translates only Sketchware, not mod.

**Comment by JavkhlanK** [comment]
Well, if it's Sketchware's strings.xml only, upload it as Language pack in Sketchware instead, for a more consistent experience.

**Comment by Alloyd854** [comment]
I want to translate, for example, Blocks manager.

**Comment by JavkhlanK** [comment]
Alright then! I think that translations from strings.xml are best though, so we'll have to rewrite Modders' classes to use them, and then you can start writing translations for them! We'll notify you then

**Comment by Alloyd854** [comment]
How long you rewrite Modders' classes?

**Comment by JavkhlanK** [comment]
I can't tell exactly when, but it's not too high on our to do list.

**Comment by ToastcodeDev** [comment]
May I ask about the percentage?

**Comment by ILY4553** [comment]
May I ask about the percentage?
