### ISSUE TITLE
Stack trace - Native crash of com.android.bluetooth

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1016]
backtrace:
  #00  pc 0x0000000000051994  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x00000000006d27f8  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+108)
  #02  pc 0x0000000000016ea8  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80)
  #03  pc 0x0000000000009de0  /system/lib64/liblog.so (__android_log_assert+292)
  #04  pc 0x0000000000a22f14  /apex/com.android.btservices/lib64/libbluetooth_jni.so (base::internal::Invoker<base::internal::BindState<bluetooth::hal::HciHalHidl::Start()::'lambda'()>, void ()>::RunOnce(base::internal::BindStateBase*)+32)
  #05  pc 0x0000000000a0ffd8  /apex/com.android.btservices/lib64/libbluetooth_jni.so (bluetooth::os::Alarm::on_fire()+108)
  #06  pc 0x0000000000a115b8  /apex/com.android.btservices/lib64/libbluetooth_jni.so (bluetooth::os::Reactor::Run()+584)
  #07  pc 0x0000000000a122b4  /apex/com.android.btservices/lib64/libbluetooth_jni.so (bluetooth::os::Thread::run(bluetooth::os::Thread::Priority)+176)
  #08  pc 0x0000000000a1243c  /apex/com.android.btservices/lib64/libbluetooth_jni.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (bluetooth::os::Thread::*)(bluetooth::os::Thread::Priority), bluetooth::os::Thread*, bluetooth::os::Thread::Priority> >(void*)+68)
  #09  pc 0x00000000000b63b0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #10  pc 0x00000000000530b8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

Google Pixel 2 (Arm) (virtual)

**Comment by JavkhlanK** [comment]
Same as #1014.

**Comment by subhash16** [comment]
Ok I will not report anymore
