### ISSUE TITLE
DirectDataEditor still using his FileUtils Class

### ISSUE THREAD

**Issue by hosni-fraj** [Sketchware-Pro/Sketchware-Pro#102]
`DirectDataEditor` (IndoSW) still using his `FileUtils` Class

**Comment by JavkhlanK** [comment]
I don't think we should touch DirectDataEditor. It's working, and that's enough.

**Comment by hosni-fraj** [comment]
Then why you change `FileUtils` class in others mods act even they are working perfectly

**Comment by hosni-fraj** [comment]
Then why you change `FileUtils` class in others mods act even they are working perfectly 
add to that we need to implement **one** `FileUtils` class so , we will be able to update the codes if there is _Deprecated_ code

**Comment by JavkhlanK** [comment]
okay yeah you got me lol 😅

I've got much going on, and AFAIK (almost) all files in the repo are compiling. So could you replace IndoSW's FileUtils with Agus' FileUtil class?

**Comment by hosni-fraj** [comment]
@JavkhlanK ok **I will** after some _hours_

**Comment by hasrat-ali** [comment]
@JavkhlanK Is it not fixed yet?

**Comment by JavkhlanK** [comment]
Oh right, it **is** fixed! I forgot about that lol
