### ISSUE TITLE
New Blocks for Android 11+

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#1022]
As per Google's Developer Policy the applications should have a target level 33 and become Sketchware Pro doens't has capability to handle new Android Versions file handing is not working for Android devices. Please update the Sketchware application with some additional blocks if possible.
![Screenshot_20231031-161411](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/92568876/4b9d23e8-341b-4e5e-996d-26b4baebe21e)

**Comment by JavkhlanK** [comment]
Duplicate of #293
