### ISSUE TITLE
VirusTotal and DrWeb found viruses in the Sketchware Pro

### ISSUE THREAD

**Issue by BaNaN4Ik-STOP** [Sketchware-Pro/Sketchware-Pro#1023]
**Describe the bug**
I found 4 viruses/trojans in Sketchware Pro

**To Reproduce**
Put file to VirusTotal

**Expected behavior**
4 viruses/trojans

**Screenshots**
[Screenshot_20231101-003222_Chrome](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/86436113/26149809-ab2d-4586-9743-09afc6f8b133)

Device and Sketchware Pro-related info:
 - Device: Samsung Galaxy J7
 - OS: Android 9
 - Sketchware Pro version: v6.4.0-rc05-minApi26

**Additional context**
I don’t trust these results because the definitions include a popular antivirus, is this a false positive?

**Comment by JavkhlanK** [comment]
See #901
