### ISSUE TITLE
Compiler problems Google Pixel 8

### ISSUE THREAD

**Issue by whazza1983** [Sketchware-Pro/Sketchware-Pro#1024]
**Describe the bug**
Compiling doesn't work

**Screenshots**
![Screenshot_20231101-232937](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/51747568/23dfb3c0-e194-4d09-913b-e826cbc305b2)

Device and Sketchware Pro-related info:
 - Device: Google Pixel 8
 - OS: Android 14
 - Sketchware Pro version: v6.4.0-rc05-minApi26

**Additional context**
As soon as I try to compile my created app, the error appears as shown in the screenshot!  The error didn't happen on the Google Pixel 6 even though I also have Android 14 on it.

Sorry for my Bad Englisch

**Comment by JavkhlanK** [comment]
Seems to be related to aapt2 only being 32-bit in that version, but that should've been fixed already. Can you [try out this nightly build](https://nightly.link/Sketchware-Pro/Sketchware-Pro/actions/runs/6519680142)?

**Comment by whazza1983** [comment]
First of all, thanks for the link.  The compiler is now working.  But the app I created no longer starts when I compile it

**Comment by whazza1983** [comment]
The created apps crash if you have activated Admob :(

**Comment by JavkhlanK** [comment]
See #943 then

**Comment by whazza1983** [comment]
Very very nice.  Thanks so much!

**Comment by dardo1515** [comment]
Hello everyone there

Thank you for your attention to this message 

Currently I just have installed the app sketchware pro 6.4 beta version, and it's not working, I just make a little program and when I start to run the system gives me a following error

/data/user/0/com.sketchware.remod/files/tmp/aapt2[1]: syntax error: unexpected '�4\D4'

I already have used the same app in other smartphone without problem, the difference is the cellphone version, the first one is Poco F3 with hyperOS 1.0 and it's working and compiling, the second one is a poco X7 with hyperOS 2.0 and sketchware doesn't compile

If you need I can send you the debug.txt file

I tried to follow the link above "Can you [try out this nightly build](https://nightly.link/Sketchware-Pro/Sketchware-Pro/actions/runs/6519680142)? (That was only valid at the time of writing.)" but certainly it doesn't work yet

Please help me to continue my learning in this app

Thanks a lot
