### ISSUE TITLE
These should be changed or Update

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1026]
The links in the image not working anymore. 
remove , change or update them
![Screenshot_20231105-074519](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/87515236/126d15be-7e1c-4410-8730-63c1647fbbb7)

**Comment by JavkhlanK** [comment]
Feels wrong to change stuff from vanilla Sketchware, idk

**Comment by araafroyall** [comment]
As these are not usable , so it is best to change or remove Non-usable things timely

**Comment by araafroyall** [comment]
As these are not usable , so it is best to change or remove Non-usable things timely

**Comment by JavkhlanK** [comment]
Is anyone forcing you to click on those buttons?

**Comment by araafroyall** [comment]
> Is anyone forcing you to click on those buttons?

No.
But i go their and see these not working links. 

i just suggesting if you dont want to remove or change that , just close this issue 👍

**Comment by JavkhlanK** [comment]
Just closing this now isn't a good way to deal with GitHub Issues though. I haven't yet seen a good argument for removing them, but neither to keep them. Until one of them is fulfilled, let's wait

**Comment by araafroyall** [comment]
ok..
You can replace it with github link or telegram links

**Comment by JavkhlanK** [comment]
Let's see how this screen turns out after the M3 redesign. After that, those broken links should have been removed.

**Comment by araafroyall** [comment]
Ok. Thanx 👍

**Comment by ilyassesalama** [comment]
These links are updated in the M3 redesign btw.

<a href="https://github.com/Sketchware-Pro/Sketchware-Pro/assets/46769766/b97dbfab-3f03-4ec0-a5f8-0aad7abab86f">
  <img src="https://github.com/Sketchware-Pro/Sketchware-Pro/assets/46769766/b97dbfab-3f03-4ec0-a5f8-0aad7abab86f" width="200" height="100%" alt="Awesome About SWPro Screen">
</a>

**Comment by araafroyall** [comment]
> These links are updated in the M3 redesign btw.
> 
> <a href="https://github.com/Sketchware-Pro/Sketchware-Pro/assets/46769766/b97dbfab-3f03-4ec0-a5f8-0aad7abab86f">
>   <img src="https://github.com/Sketchware-Pro/Sketchware-Pro/assets/46769766/b97dbfab-3f03-4ec0-a5f8-0aad7abab86f" width="200" height="100%" alt="Awesome About SWPro Screen">
> </a>
> 

Nice. 👍
