### ISSUE TITLE
How to import from Github to Sketchware pro

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1029]
i want to import a project from github source codes or repo to Sletchware

how can i do this.
Help me

**Comment by JavkhlanK** [comment]
This isn't a general purpose help forum for Sketchware Pro.

**Comment by araafroyall** [comment]
but i urgently need such .
for example we can use sketchware pro to amdroid studio.
i want method as reverse.
like studio to sketchware

**Comment by JavkhlanK** [comment]
You can never easily reverse transformations, such as cooking an egg, or going from an Android Studio project to a Sketchware (Pro) project.

**Comment by araafroyall** [comment]
ok. 😐
