### ISSUE TITLE
Sketchware - Support Full Kotlin project

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#1033]
Is this possible to make full kotlin project in Sketchware?

I mean files change to Kotlin and block codes too.

**Comment by JavkhlanK** [comment]
You're literally using Blocks. Why care about the language used under-the-hood? Java and Kotlin have full interoperability anyway.

**Comment by AmirSinaRZ** [comment]
I'm using codes directly too much and just using blocks for simple things. I learned java by Sketchware + books+ tutorials....
Because we work with Sketchware all the time and see the direct code, it helps to learn, so it would be great if Kotlin was added to the blocks.

**Comment by JavkhlanK** [comment]
Then it's time to find another way to learn the language. There'd be no way to mix Kotlin and Java Blocks and also no way one would realistically convert all existing built-in Blocks to Kotlin.

Anyway, how would you even be realistically learning any language when you're mostly just using those Blocks anyway?

**Comment by Citra-Standalone** [comment]
Agree, Kotlin become more popular this year, if possible, please add Kotlin/Java button when creating new project.
