### ISSUE TITLE
M3: `MenuItem#setIconTintList` called on API levels < 26

### ISSUE THREAD

**Issue by JavkhlanK** [Sketchware-Pro/Sketchware-Pro#1036]
**Describe the bug**
See title. Only in `material-redesign` builds.

**To Reproduce**
1. Open any Event on a device with API level < 26

**Expected behavior**
No crash

Device and Sketchware Pro-related info:
 - Device: ?
 - OS: ?
 - Sketchware Pro version: unspecified, but probably after commit ef4775b and before any commits to branch `material-redesign` as of creation of this issue.

**Additional context**
Continuation of #1035

**Comment by rexfernandezluciano** [comment]
Haven't fixed yet?

**Comment by JavkhlanK** [comment]
Definitely not. Just look at this: https://github.com/Sketchware-Pro/Sketchware-Pro/blob/material-redesign/app/src/main/java/com/besome/sketch/editor/LogicEditorActivity.java#L1956

**Comment by remaker17** [comment]
I think, we need to use drawable selectors there instead.
e.g: `res/drawable/selector_save_tinted`.

**Comment by hasrat-ali** [comment]
Fixed with 09feb2f
