### ISSUE TITLE
Hardware access

### ISSUE THREAD

**Issue by chiaravalle** [Sketchware-Pro/Sketchware-Pro#1037]
Hello everybody.
Call me stupid, but I didn't get how to:
- Use the flashlight
- Query the battery
- Output arbitrary signals to the speakers
- Send/receive calls/SMSes

I was trying to build a battery monitor App which on low power does:
- Flash SOS morse code with flashlight and speaker
- If the user allows, send a "I'm running low on battery, call you later" to incoming callers, via SMS.

But I can't find the needed blocks.
What should I do?

Thanks for any help.
Regards, he a nice day. =)

**Comment by JavkhlanK** [comment]
This isn't a general purpose help forum for Sketchware (Pro). Anyway, everything you just described can be done with Custom Blocks or code in add source directly Blocks.
