### ISSUE TITLE
Hardware access components

### ISSUE THREAD

**Issue by chiaravalle** [Sketchware-Pro/Sketchware-Pro#1039]
Please, add components to interface with device's hardware:
- Flashlight
- Battery
- Microphone
- Speaker
- Printer service

Thanks a lot, regards, have a nice day.

**Comment by JavkhlanK** [comment]
There won't be any more built-in Components, Blocks, Widgets, etc., unless there are important bugs to be fixed. Use Custom Components, Blocks, etc. instead.

**Comment by chiaravalle** [comment]
Oh, I see, thanks.
