### ISSUE TITLE
Firebase notifications are not showing  sdk31+

### ISSUE THREAD

**Issue by kaat656** [Sketchware-Pro/Sketchware-Pro#1046]
Firebase notifications no longer arrive in our apps when...to lift SDK To 31+
Even if we have enabled notification permission .Only works with SDK30 -
I hope to fix this problem or explain the solution because our applications are almost dead without sending notifications to users

**Comment by JavkhlanK** [comment]
Duplicate of #910. Why create another Issue if you can just comment there like you already did?

**Comment by kaat656** [comment]
I created this post because when I commented on this problem, we did not find a response or help
