### ISSUE TITLE
Bug java.util.Comparator class Not Found

### ISSUE THREAD

**Issue by appt2** [Sketchware-Pro/Sketchware-Pro#1053]
Device and Sketchware Pro-related info:
 - Device: [e.g. Poco x5]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT- be51bbb-minApi26]

Error Class Not Found See Image ..
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Comparator$-CC;
![Screenshot_2023-12-30-13-39-15-331_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/143449333/f6f8ab01-f98c-4b5f-9b1c-207dfac5e460)

**Comment by JavkhlanK** [comment]
Fill out the bug report template.

**Comment by appt2** [comment]
@JavkhlanK Hello, I told you the necessary explanations in Telegram. I think Sketchware cannot insert the java.util class in the project, so it gives the error of not finding the class.
