### ISSUE TITLE
The latest beta version cannot delete the layout

### ISSUE THREAD

**Issue by anthony-china** [Sketchware-Pro/Sketchware-Pro#1062]
![Uploading Screenshot_2024-01-13-17-43-02-344_com.sketchware.remod.jpg…]()
**Describe the bug**
Please give us a clear and concise description of what the bug is.

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 10]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by adesonob** [comment]
When I try to delete the layout, the drag bin doesn't appear either.

**Comment by ilyassesalama** [comment]
This is a known issue. Also, please fill in the issue template and not keep it like that.
