### ISSUE TITLE
Unable to download this specific lib

### ISSUE THREAD

**Issue by AbrishPhoenix** [Sketchware-Pro/Sketchware-Pro#1063]
Not downloading this specific lib :
Google Generative AI 
"com.google.ai.client.generativeai:generativeai:0.1.2"

![Screenshot_20240112-171536_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/91604252/a48faafa-5d2b-4dea-ab01-270a9b6db657)

**Comment by JavkhlanK** [comment]
Fill out the entire bug report template, and also show the entire error message.
