### ISSUE TITLE
3 bugs for material-redesigns latest nightly build.

### ISSUE THREAD

**Issue by pixeldotgit** [Sketchware-Pro/Sketchware-Pro#1064]
**Describe the bug**
Deletion button doesn't show.
Code doesn't save.
Library manager buttons bring you to the exact opposite.

**To Reproduce**
1: Drag an element.
2: Leave your code.
3: Open a menu in Library Manager (the manager with admob and fb)

**Expected behavior**
1: Deletion button shows.
2: Code saves.
3: Opens the correct menu.

**Screenshots**
Has been happening normally, so not really needed.

Device and Sketchware Pro-related info:
 - Device: Galaxy Tab S6 Lite
 - OS: Android 13
 - Sketchware Pro version: Latest nightly build

**Additional context**
Material redesign is unusable because of these bugs.

**Comment by pixeldotgit** [comment]
As of Janurary 14th all has been fixed. Thanks @ilyassesalama

**Comment by ilyassesalama** [comment]
How this is fixed? All the issues mentioned are still there and I already identified the reason but haven’t fixed it yet?
