### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1065]
**Describe the bug**
Everything I did was not saved

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/af4a0363-11a6-4087-91ff-d302515163bf

Device and Sketchware Pro-related info:
 - Device: SamSungA51 
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-SNAPSHOT-c751559-minApi26

**Comment by hasrat-ali** [comment]
Probable duplicate of #1062
