### ISSUE TITLE
Error displayed when adding component event

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1069]
**Describe the bug** 
When I add event of FirebaseDB component,Then this error appears, it's silly 

![Screenshot_20240116_205236_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/6da95f7e-1386-4b0e-8375-04ef8fae125f)

![Screenshot_20240116_210556_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/c09c39aa-1e8a-4cda-b2bd-bda96688511e)

Device and Sketchware Pro-related info:
 - Device: SamSungA51 
 - OS: Android 13
 - Sketchware Pro version:v 6.4.0-SNAPSHOT-43c8203-minApi26

**Comment by TanTai97o** [comment]
> I couldn't reproduce it. Maybe you have some custom components with same `typeName`. That's why that happened.

I don't have any custom components same TypeName

**Comment by TanTai97o** [comment]
> I couldn't reproduce it. Maybe you have some custom components with same `typeName`. That's why that happened.

So can this error be fixed? It annoys me because it keeps crashing and Wrong display

**Comment by remaker17** [comment]
I think, it happened after removing some stable IDs.

**Comment by hasrat-ali** [comment]
Well, i think that was happened because of `stable-ids` changes, but now it's seems working. 
So yeah, closing it.
