### ISSUE TITLE
Please Add feature to edit moreblocks

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1070]
It would be great if you could add moreblock editing feature 
For example adding new variables or new views to Moreblock previous 
Or delete unused variables.

I don't know if anyone has requested this feature yet, but I hope you can add this feature to Sketchware

**Comment by araafroyall** [comment]
i too nead this 

Please make this fast @hasrat-ali

**Comment by hasrat-ali** [comment]
No, not possible
