### ISSUE TITLE
When Iam  adding new items to Listview it's not showing items value, it's showing always textview in the whole listview . please give solution for this problem.

### ISSUE THREAD

**Issue by PremKPS777** [Sketchware-Pro/Sketchware-Pro#1078]
**Describe the bug**
Please give us a clear and concise description of what the bug is.

**To Reproduce**
1. Step 1
![Screenshot_2024-01-26-22-48-48-85_c947bc2f01334259469c7019cdd76aca](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/156833796/d909c5c2-b530-44ac-be9d-a2861ca0c012)

2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 10]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by JavkhlanK** [comment]
Fill out the template and don't put every single detail of your problem into the title, that's not what titles should be.
