### ISSUE TITLE
All compiled projects contain viruses and trojans.

### ISSUE THREAD

**Issue by Official-Mlx** [Sketchware-Pro/Sketchware-Pro#1079]
**Describe the bug**
Entire projects are strangely flagged as malicious by virus checkers, and indeed contain trojans and viruses. for example:
🧬 Detections: 12 / 63

⛔️ Skyhigh
  ╰ Artemis
⛔️ McAfee
  ╰ Artemis!36CAB19F73AF
⛔️ Trustlook
  ╰ Android.PUA.General
⛔️ SymantecMobileInsight
  ╰ AppRisk:Generisk
⛔️ Cynet
  ╰ Malicious (score: 99)
⛔️ F-Secure
  ╰ Malware.ANDROID/AVE.Evo.wzydk
⛔️ Ikarus
  ╰ Trojan.AndroidOS.Agent
⛔️ Avast-Mobile
  ╰ Android:Evo-gen [Trj]
⛔️ Google
  ╰ Detected
⛔️ Avira
  ╰ ANDROID/AVE.Evo.wzydk
⛔️ BitDefenderFalx
  ╰ Android.Riskware.TestKey.rA
⛔️ Fortinet
  ╰ Android/Agent.BSR!tr

**To Reproduce**
It is clear.

**Expected behavior**
The problem should be solved as soon as possible.

**Screenshots**
![Screenshot_2024-01-28-08-41-27-264_tw nekomimi nekogram](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/74877307/6947f9c3-eab2-4773-a04d-50dd0490dc06)

Device and Sketchware Pro-related info:
 - Device: [Xiaomi Note 8 Pro]
 - OS: [Android 10]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**
This is a serious problem.

**Comment by JavkhlanK** [comment]
You ignored important parts of the bug report template. In the future, fill everything out, especially the version info and reproduction steps part, and not just "it is clear".

Anyway, see #901.

**Comment by kenockrmz-alt** [comment]
[Target.zip](https://github.com/user-attachments/files/32527545/Target.zip)
