### ISSUE TITLE
Cannot select Image to ImageView

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1089]
**Describe the bug**

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/e7c8c768-b327-4682-8a97-aa9cc2644541

Device and Sketchware Pro-related info:
 - Device: SamSungA51 
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-SNAPSHOT-0d21c6c-minApi26

**Comment by hasrat-ali** [comment]
You can use other platforms like YouTube

**Comment by TanTai97o** [comment]
> You can use other platforms like YouTube 

Okay,wait a minute

**Comment by TanTai97o** [comment]
> You can use other platforms like YouTube 

I have uploaded it here

https://streamable.com/gl48jl

**Comment by adesonob** [comment]
This bug is also happening on mine

**Comment by TanTai97o** [comment]
@hasrat-ali
Can you fix this faster?
I waited and the error still hasn't been fixed

**Comment by JavkhlanK** [comment]
If you need a bug-free experience, don't use nightly builds. Get v6.4.0-rc05 if you need the app to work.

**Comment by TanTai97o** [comment]
> If you need a bug-free experience, don't use nightly builds. Get v6.4.0-rc05 if you need the app to work.

That version cannot use material 1.10.0

**Comment by hasrat-ali** [comment]
Fixed with d478373
Also closing this because it's in non-released version
