### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by ImNotDario** [Sketchware-Pro/Sketchware-Pro#1105]
iOS support:

I used to use sketchware. It was a cool app and used it a lot. Suddenly, it vanished from the play store. I switched to an iPhone X, and i cant use it anymore.

**Solution:**
Make an ios version (since apple doesn't allow sideloading, you could make an app list inside the app and use the apps there), or you could make a jailbroken version (.ipa/.deb) that generates ipas.

**Comment by PranavPurwar** [comment]
Sketchware Pro wasn't entirely developed by us, but rather just includes modifications to the original Sketchware app. We don't yet have a deep understanding of how exactly it works under the hood. In addition, most of us aren't even experienced iOS devs, neither do we have any motivation to port it. Even if we manage to do so, it won't be much useful as iOS prevents any and every sideloading techniques except on jailbroken ones. The apps created through it would need to be manually installed on the device via a computer that would ruin the whole point of developing on mobile. And there are possibly further legal problems with this too. Sketchware Pro was created for continuing the legacy of Sketchware, so we won't be *officially* working on one.
