### ISSUE TITLE
Sketchware's compiler doesn't support multi-user devices

### ISSUE THREAD

**Issue by HehehBoiii78** [Sketchware-Pro/Sketchware-Pro#1106]
**How it occurred**
I imported or restored a project in Sketchware that used local libraries for the first time. It asked me if I wanted to import the libraries or not and I said yes to the dialog. Then I tried to compile the app once but it failed with a dialog that said "A directory important for building is missing. Sketchware Pro can try creating the directory at storage/emulated/0/.sketchware/libs/local_libs/my_project/res if you'd like to."
**The issue**
The issue is that it is trying to access and write a folder to /storage/emulated/0 which is not my user's directory. I am using this app in a Samsung tablet which supports multi-user, and my directory is not /storage/emulated/0 but instead /storage/emulated/10. Android doesn't allow the user or an app to access another user's directory, and that's why when I try to say yes to the dialog asking to try to create the folder because it doesn't exist, I always get an error. And that's why I cannot compile the app no matter what, even after deleting that local library from the app that it was using.
**How to reproduce**
In a device that supports multiple users, switch to another user, install or open Sketchware Pro, import or open an app which uses a local library, and try to compile the app. You will not be able to, because it can't search for or create the folder in the directory which "is important for building".
**The picture of the error dialog**
![Screenshot of the error dialog in Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/6995ad45-f272-4767-8125-d9ef7137fb81)

**Comment by hasrat-ali** [comment]
There's limitation on swpro, but it should be fixed.
Any you can just click on `Create' button,  that will fixed your problem.

**Comment by HehehBoiii78** [comment]
That's the issue. The create button itself does not work. When I try to click it shows Failed to create folder. Try again later.

**Comment by HehehBoiii78** [comment]
And also, please clarify the reason of closing this issue.

**Comment by JavkhlanK** [comment]
how's it "not our bug"? i'm 100 % sure some code by agus hardcoded `/storage/emulated/0` for dumb reasons, and that's why this isn't working

**Comment by hasrat-ali** [comment]
1. ?
2. There's not any hardcoded `/storage/emulated/0`. 
3. How it's working for me?

**Comment by JavkhlanK** [comment]
yeah nvm this is plainly wrong, I just got it to work too. So to conclude, just like Hasrat said, create the directory using the dialog button. Sketchware Pro supports multi-user setups correctly.

**Comment by HehehBoiii78** [comment]
How does someone close this issue? Also, @JavkhlanK, that's not plainly wrong. I am using a Samsung tablet using OneUI Core, and it doesn't work for me. I try to import the project, it shows me the dialog that is visible in the picture.
![Screenshot_20240320-230533_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/b80bb7b8-8075-4478-8556-0e88c9208db2)
No matter if I click on "Don't copy" or "Copy" and try to compile the project, it always says the "Missing directory detected" (the dialog's picture is given in the post) and **even if I click on the Create button in the "Missing directory detected" dialog, it ALWAYS gives the error "Failed to create directory/directories"! It is very hard for me to screenshot the error message that says it can't create the folder, because it is a Toast message and not a dialog, but I will still try that.**

**Comment by hasrat-ali** [comment]
you can record a video.

**Comment by JavkhlanK** [comment]
I meant "plainly wrong" as in it having worked for both me and Hasrat. I used a Google APIs emulator image, Hasrat probably not a Samsung device. Looks like Samsung messed up in their implementation.

Anyway when you're already recording your screen, please make sure to show the entire process failing, so e.g. the Local library dialog, as well as the entire compile error message.

**Comment by hasrat-ali** [comment]
Bro, if you still getting those errors, then just simply goto `Local Library manager` and unselect that library,  reselect again.

**Comment by HehehBoiii78** [comment]
Will try that, anyway, here is the video of the problem.

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/5c3dfbfd-e3d1-4cbe-b3dc-567e887c6a90

**Comment by HehehBoiii78** [comment]
I apologise for being late, my network wasn't working 💢

**Comment by HehehBoiii78** [comment]
> Bro, if you still getting those errors, then just simply goto `Local Library manager` and unselect that library, reselect again.

Thanks for this solution. That fixed my problem. Also, can you answer why does that issue occur in the first place? Why do we have to reselect it anyway?

**Comment by JavkhlanK** [comment]
Can you show what's inside the Local library's folder? (at /Internal storage/.sketchware/libs/local_libs/ btw)

**Comment by HehehBoiii78** [comment]
Alright. Here's what you asked.
![Screenshot_20240321-001433_My Files](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/5a89d48d-5bde-4c62-aa25-cc7ca740a211)
![Screenshot_20240321-001440_My Files](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/0d71ed0a-e4da-44fb-b5a1-b9c716046186)
![Screenshot_20240321-001450_My Files](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/f7c60b82-ce35-4e7d-ad90-b0d9ae55670f)
![Screenshot_20240321-001458_My Files](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/8fc0dc27-a1ee-4058-b49c-2bc62d76bed0)

**Comment by JavkhlanK** [comment]
Thanks. What a weird issue.

**Comment by PranavPurwar** [comment]
the stuff we save in `.sketchware/data/<project_id>/local_library` uses absolute path, rather than relative paths. so if a person on multiuser device extracts that project, it will always look for libraries in user space 1 which is restricted
