### ISSUE TITLE
The tooltip for the More options icon says "Save project" instead

### ISSUE THREAD

**Issue by HehehBoiii78** [Sketchware-Pro/Sketchware-Pro#1108]
This is a minor issue. I just noticed that while using the Material 3 version of Sketchware Pro, that if you hover over the "More" icon, it shows "Save project" instead.
To understand this much better, see the video below.

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/06750993-1966-4325-804a-c8ccaccce36e

Just one enhancement that I suggest gets fixed, nothing else.

**Comment by hasrat-ali** [comment]
Fixed with 8be3fc1
