### ISSUE TITLE
Add Cloud Firestore to Component List

### ISSUE THREAD

**Issue by rexfernandezluciano** [Sketchware-Pro/Sketchware-Pro#1110]
**Is your feature request related to a problem? Please describe.**
Since, Real-time database is too much cost and have limited simultaneous connection to 100, it's different when Firestore comes. There's no simultaneous connection limitations. There's only limitations for read and write operations.

**Describe the solution you'd like**
Adding Firestore will be good solution to Real-time database. Since adding Cloud Firestore manually in Sketchware Pro is not possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by githubconect** [comment]
😍

**Comment by hasrat-ali** [comment]
There won't be any more built-in Components, Blocks or Widgets, Use Custom Components, Blocks, etc. instead.

**Comment by rexfernandezluciano** [comment]
When adding using custom component, it needs to all Firebase libraries be updated. If it's not, the application will crashed and not find any component registered in the manifest specially "FirebaseFirestoreComponentRegistrar".
