### ISSUE TITLE
variable problem

### ISSUE THREAD

**Issue by ziarlock** [Sketchware-Pro/Sketchware-Pro#1111]
**Describe the bug**
I need to create a variable with underscore(_), but I can’t do this, although according to Java rules it can be done

**Expected behavior**
fix please

**Screenshots**
![Screenshot_20240322_052140_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/155832575/8168264c-29c7-41cb-ad13-a2254efa2bf4)

 Sketchware Pro-related info:
 - Sketchware Pro version: 6.4.0 rc04, rc05

**Comment by JavkhlanK** [comment]
I'm 100 % this is the same in vanilla Sketchware. It's probably like that to not have name conflicts with e.g. MoreBlock parameters or some Blocks' code (even though `this.…` could've been used instead). I'd not classify this as a bug, just don't use variables with such a name. That's not even a good coding style in Java.
