### ISSUE TITLE
Lottie error message

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1112]
**Describe the bug**
When using the newest sketchware pro test build under "actions" I get an error when trying to build a project with a lottie.

**To Reproduce**
1. Use lottie
...

**Error**
/storage/emulated/0/.sketchware/mysc/660/app/src/main/res/layout/maa.xml:27: error: attribute lottie_autoPlay (aka com.the.tilemaster.scheduler:lottie_autoPlay) not found.
/storage/emulated/0/.sketchware/mysc/660/app/src/main/res/layout/maa.xml:27: error: attribute lottie_fileName (aka com.the.tilemaster.scheduler:lottie_fileName) not found.
/storage/emulated/0/.sketchware/mysc/660/app/src/main/res/layout/maa.xml:27: error: attribute lottie_loop (aka com.the.tilemaster.scheduler:lottie_loop) not found.
error: failed linking file resources.

**Comment by guhg** [comment]
I don't think it could be the code because it was working before I updated to the latest snapshot. The issue isn't present in the latest beta release under releases.

**Comment by hasrat-ali** [comment]
> I don't think it could be the code because it was working before I updated to the latest snapshot. The issue isn't present in the latest beta release under releases.

 I don't think without more information anyone can help you. You didn't even provide which version you're using.

**Comment by hasrat-ali** [comment]
I got it working with v6.4.0-SNAPSHOT-33bb215-minApi21
