### ISSUE TITLE
Update all dependency and components to latest version

### ISSUE THREAD

**Issue by Earnchamp** [Sketchware-Pro/Sketchware-Pro#1115]
Please update all dependency and components to latest version 

And also add firebase crashlytics component as today i tried to add and initialize but error came Firebase crashlytics component not found even after creating a new component and added it

java.lang.RuntimeException: Unable to start activity Componentinfo(com.app.crashtest/ com.app.crashtest.MainActivity):

java.lang.NullPointerException: FirebaseCrashlytics component is not present.

at

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)

at

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)

at

android.app.servertransaction.LaunchActivityltem.execute(L aunchActivityltem.java:109)

at

android.app.servertransaction. Transaction Executor.execute Callbacks (TransactionExecutor.java:135)

at

android.app.servertransaction. TransactionExecutor.execute( Transaction Executor.java:95)

at android.app.ActivityThreadSH.handleMessage(ActivityThread.java:2345)

at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce (Looper.java:233) at android.os.Looper.loop(Looper.java:344)

at

android.app.ActivityThread.main(ActivityThread.java:8212) at java.lang.reflect.Method.invoke(Native Method)

at

com.android.internal.os.RuntimeInitSMethodAndArgsCaller.run(RuntimeInit.java:584)

at

com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034 )

Caused by: java.lang.NullPointerException:

FirebaseCrashlytics component is not present.

at

com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:216)

at

com.app.crashtest.MainActivity.initializeLogic(MainActivity.ja va:309)

**Comment by JavkhlanK** [comment]
1. Use Issue templates, don't create free-form issues unless you have experience or exactly know what you're doing
2. This is definitely a duplicate
3. This isn't a general-purpose Sketchware Pro project help platform, it's for bugs and feature requests.
