### ISSUE TITLE
Listview crash

### ISSUE THREAD

**Issue by DivyBajpai** [Sketchware-Pro/Sketchware-Pro#1116]
**Description of the bug**
Hey there I'm already on sketchware updated version but whenever I try to open BindCustomView of listview or recycleview my sketchware application gets crash can someone help me with a solution.

Device and Sketchware Pro-related info:
 - Device: Realme 
 - OS:  Android 13
 - Sketchware Pro version: 6.4.0-rc05-minApi26]

**Additional context**

**Comment by hasrat-ali** [comment]
Can you provide more information including stack trace (if any).
