### ISSUE TITLE
Cancel button does not work

### ISSUE THREAD

**Issue by TanTai97o** [Sketchware-Pro/Sketchware-Pro#1117]
**Describe the bug**

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107351062/f4187748-7708-4a9b-8a2a-abfcaf291a49

Device and Sketchware Pro-related info:
 - Device: SamSungA51 
 - OS: Android 13
 - Sketchware Pro version: v6.4.0-SNAPSHOT-7be66bf-minApi26

**Comment by hasrat-ali** [comment]
Fixed with 896d9fd
