### ISSUE TITLE
Vibration Issue on Android 14 HyperOS 1.0.5.0

### ISSUE THREAD

**Issue by InfiSoftApps** [Sketchware-Pro/Sketchware-Pro#1121]
Vibration on tap has been implemented on various screens of my app. It was working fine on all devices.
Recently, I got an update to Xiaomi Hyper OS 1.0.5.0 and post which, the vibration is not getting triggered on my phone.
Device: Redmi Note 13 5G (India)

Tried, re installing the app. but no luck.

Tried creating new dummy app on latest SK release version, but issue is still same. All functionalities OnClick work except the Vibration.

Is this a Sketchware Pro bug?

**Comment by InfiSoftApps** [comment]
The issue lyes with the OS side. 
This issue may be closed.

**Comment by JavkhlanK** [comment]
Issue creators can close their issues too btw
