### ISSUE TITLE
The Nightly version download link is no longer active

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1132]
I can't download Nightly version and it shows like this:

Error 404 – Not Found
GitHub produced an error for the download of artifact #1430568981.

Usually this means that the artifact has expired (>90 days).

Check on GitHub: https://github.com/Sketchware-Pro/Sketchware-Pro/suites/22952838960/artifacts/1430568981

**Comment by hasrat-ali** [comment]
Try now there's newer builds [here](https://github.com/Sketchware-Pro/Sketchware-Pro/actions)
