### ISSUE TITLE
Combine some settings.

### ISSUE THREAD

**Issue by remaker17** [Sketchware-Pro/Sketchware-Pro#1136]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I would like you to combine "System Settings" and "Developer Tools" into one.

**Describe alternatives you've considered**
No idea.

**Additional context**
No additional context.

**Comment by hasrat-ali** [comment]
Why, both are very different.

**Comment by remaker17** [comment]
> Why, both are very different.

But, System Settings's screen almost empty.

**Comment by hasrat-ali** [comment]
It doesn't mean that they should be combined.

**Comment by hasrat-ali** [comment]
Maybe some 'Mod settings' should be moved to SystemSettings
