### ISSUE TITLE
Material Switch makes app blank

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1137]
**Describe the bug**
When you use Material a switch and build the app, after you open the app, the screen is just blank
**To Reproduce**
1. Convert switch to com.google.android.material.materialswitch.MaterialSwitch;
2. Use latest android.jar
3. Use Material Components Library
4. Have Material Theming XMLs from Material Theme Builder
...

**Expected behavior**
Material Switch should work correctly and show up

**Screenshots**

https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/78f77830-aa21-453a-af27-307f00117a6d

Device and Sketchware Pro-related info:
 - Device: Galaxy Tab S8
 - OS: Android 13, One UI 6.1
 - Sketchware Pro version: Latest Snapshot as of writing this

**Additional context**
If the switch is not set as com.google.android.material.materialswitch.MaterialSwitch then the app shows the switch correctly just without the material you theme but when I try to get the modern switch (MaterialSwitch), the app is just blank, no objects will show

**Comment by ilyassesalama** [comment]
I think the app is not blank, but it crashed. However, it seems like Android doesn't show you the logs and just stays in the form of a blank screen. Use Sketchware Pro's logcat reader to see what's the reason behind that issue even though the reason is obvious.

**Comment by guhg** [comment]
How do you get the logcat reader to work?

**Comment by guhg** [comment]
> I think the app is not blank, but it crashed. However, it seems like Android doesn't show you the logs and just stays in the form of a blank screen. Use Sketchware Pro's logcat reader to see what's the reason behind that issue even though the reason is obvious.

I have never been able to get the logcat reader to work. I keep the screen open and launch the app and it never saves any logs. Is there something I am doing wrong.

**Comment by ilyassesalama** [comment]
I think you need to root your device.

**Comment by guhg** [comment]
Oh I can't do that lol

**Comment by guhg** [comment]
But what do you think the reason is? Why doesn't Sketchware support the newer switch and is there any way to implement it? I was able to get a customized `androidx.appcompat.widget.SwitchCompat` to look similar to a material switch but not fully.

**Comment by guhg** [comment]
I just have always really wanted to simply implement a modern material switch legitimately 
![Screenshot_20240528_160000_Sketchware Pro](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/b6f92385-81d2-489f-8adf-4171a3f13bd3)

**Comment by remaker17** [comment]
I managed to get the logs:
```
Caused by: java.lang.NoSuchMethodError: No virtual method setEnforceSwitchWidth(Z)V in class Lcom/google/android/material/materialswitch/MaterialSwitch; or its super classes (declaration of 'com.google.android.material.materialswitch.MaterialSwitch' appears in /data/app/~~f7vkZRl8k4ZfsOm6vEcEbg==/com.my.newproject2-zA7wR6dq2Rot7vk-cKSiLw==/base.apk!classes52.dex)
	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:118)
	at com.google.android.material.materialswitch.MaterialSwitch.<init>(MaterialSwitch.java:79)
	... 30 more
```

**Comment by remaker17** [comment]
I was able to run the application with MaterialSwitch:
- Download these artifacts and enable them:
  `androidx.activity:activity:1.9.0`
  `androidx.appcompat:appcompat:1.6.1`
  `org.jetbrains.kotlin:kotlin-stdlib:2.0.0`
  `com.google.android.material:material:1.13.0-alpha02`

- Exclude next built-in libraries:
  `material-1.6.1`
  `appcompat-1.4.0`

- Use `android.jar` from Android SDK 34.
- Convert `Switch` -> `com.google.android.material.materialswitch.MaterialSwitch`

That's all, now you can compile the application and see the result!
![Screenshot_20240529-080108.jpg](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/95296093/2e078492-cb80-40fd-a904-bde0536ffd6d)

**Comment by guhg** [comment]
> I was able to run the application with MaterialSwitch:
> 
> * Make sure that you're using latest version of Sketchware Pro or SNAPSHOT.
> * Download these artifacts and enable them:
>   `androidx.activity:activity:1.9.0`
>   `androidx.appcompat:appcompat:1.6.1`
>   `org.jetbrains.kotlin:kotlin-stdlib:2.0.0`
>   `com.google.android.material:material:1.13.0-alpha02`
> * Exclude next built-in libraries:
>   `appcompat-1.4.0`
>   `material-1.6.1`
> * Use `android.jar` from Android SDK 34.
> * Convert `Switch` to `com.google.android.material.materialswitch.MaterialSwitch`
> 
> That's all, now you can compile the application and see the result!
> 
> UPD: You must use `Material3` theme.
> 
> ![Screenshot.jpg](https://private-user-images.githubusercontent.com/95296093/334614057-2e078492-cb80-40fd-a904-bde0536ffd6d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDY0NjgsIm5iZiI6MTcxNjk0NjE2OCwicGF0aCI6Ii85NTI5NjA5My8zMzQ2MTQwNTctMmUwNzg0OTItY2I4MC00MGZkLWE5MDQtYmRlMDUzNmZmZDZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAxMjkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NmUyMjFlYTk3YmFlNmQyOTc3ODdkOTgzMDUxNWFjYzQ1OTMyYmZhYTE3NDg2MWMyYmIxYjVjNWMwYzdkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JomZkmb27u9YdzI2yvs8b2A04yQ3gsxR8FNmZBBx22Q)

Dude THANK YOU SO MUCH. I'm serious, I've been trying this for so long. How did you figure it out? You're just way smarter than me lol. I feel like I did those same things (excluding those libraries and stuff) but I guess I got the wrong versions

**Comment by remaker17** [comment]
I think you can close this issue now.

**Comment by guhg** [comment]
> I think you can close this issue now.

Teach me your ways. What's your email??
