### ISSUE TITLE
Several Dependencies receive error when importing

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1138]
When I try to download the androidx.appcompat:appcompat:1.7.0 library in Sketchware Pro, I get the errors shown in the screenshot. I've tried several other newer libraries and they get errors too, including androidx.core:core:1.15.0-alpha01.
![Screenshot_20240716_204126_Sketchware Pro](https://github.com/user-attachments/assets/4346ba70-a8b5-41ef-8439-0ecce8656d43)

**Comment by khaled-0** [comment]
This seems probably a library issue,
I'm getting the same thing an Android Studio
Reverted back to 1.6.1 for now

**Comment by guhg** [comment]
> This seems probably a library issue, I'm getting the same thing an Android Studio Reverted back to 1.6.1 for now

Yeah. Still happens in latest snapshot as well. You sure it can't be fixed? Not a problem with the dependency resolver? 
![Screenshot_20240716_204126_Sketchware Pro](https://github.com/user-attachments/assets/90aa1843-e216-4574-a84f-ce45988d9a3b)

**Comment by guhg** [comment]
I get an error trying to import several other newer libraries as well. Including androidx.biometric:biometric:1.4.0-alpha01

**Comment by guhg** [comment]
I get an error trying to import androidx.core:core:1.15.0-alpha01 as well. I've tested trying to dependency resolve 30 libraries and 14 out of those 30 got errors.

**Comment by khaled-0** [comment]
those all probably depends on some gradle 8.4 features 
hence they're breaking on older versions.
Shit google

**Comment by guhg** [comment]
> those all probably depends on some gradle 8.4 features hence they're breaking on older versions. Shit google

Man. We have to fix it somehow 😭. Talk to the guy that made the dependency resolver.

**Comment by hasrat-ali** [comment]
Fixed with 23750b8

**Comment by guhg** [comment]
> Fixed with [23750b8](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/23750b82a802afe9191d55c4f4a4bf6860216e4f)

Great job man, thanks! Very much appreciated
