### ISSUE TITLE
When App Crashes, Debug Screen no longer shows with error

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1140]
If my app crashes, Debug activity doesn't come up anymore so I don't know what the error message is. And I can't use logcat because I don't have root.

**Comment by JavkhlanK** [comment]
FYI: You can use a logcat reader without root access or a computer if you're on Android 11 or higher. Try one of those logcat apps on Google Play, or use Shizuku and Termux to access the system binary directly.

**Comment by guhg** [comment]
Okay I check it out. Why doesn't the DebugActivity show anymore when there's a crash though? Can it be fixed?

**Comment by ilyassesalama** [comment]
It was never there by default. You can create a new activity with that name then It'll be called automatically when a crash happens.

**Comment by guhg** [comment]
Well back in the past I specifically remember it would always show the
crash log after a crash. It just doesn't do that anymore.

**Comment by guhg** [comment]
It used to show a dialog with the full crash log that you could then copy, but now when an app crashes, it just shows a blank screen.

**Comment by JavkhlanK** [comment]
Whenever apps don't show the stack trace like that, going to the home screen, opening Recents, opening the app again from there, and combos of that often help, at least for me. Maybe try that.

This seems hard to fix, and the issue of the dialog not showing has been there forever. Newer Android versions probably introduced limits which made the chance of that happening much higher.

**Comment by guhg** [comment]
> Whenever apps don't show the stack trace like that, going to the home screen, opening Recents, opening the app again from there, and combos of that often help, at least for me. Maybe try that.
> 
> This seems hard to fix, and the issue of the dialog not showing has been there forever. Newer Android versions probably introduced limits which made the chance of that happening much higher.

Yeah, that's what I started doing months back but now that I updated to Android 14, the error message rarely shows up. It's like a 5% chance that I'll get to see the error message. Most of the time, the app will just freeze up or crash now without any error message. There has to be some way to fix it. Error messages used to be extremely helpful.

**Comment by JavkhlanK** [comment]
You can't just copy-paste code freely while ignoring the license.

**Comment by khaled-0** [comment]
Maybe it's time we update/fix the default crash handler.
This code below works for my app every time,
I'll try to port it to SKPro if I get an upvote

```
class ApplicationClass : Application() {
    override fun onCreate() {
        super.onCreate()
        Thread.setDefaultUncaughtExceptionHandler { _: Thread?, throwable: Throwable? ->
            val intent = Intent(applicationContext, MainActivity::class.java)
            intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
            intent.putExtra("stacktrace", Log.getStackTraceString(throwable))
            startActivity(intent)
            Process.killProcess(Process.myPid())
            exitProcess(1)
        }
    }
}
```

In MainActivity 
```
//Any crash logs sent via DefaultUncaughtExceptionHandler
        intent.getStringExtra("stacktrace")?.let { eventLog("Application Crashed", it) }

        LocalBroadcastManager.getInstance(this).registerReceiver(
            eventLogBroadcastReceiver,
            IntentFilter("eventLog")
        )
```

**Comment by guhg** [comment]
> Maybe it's time we update/fix the default crash handler. This code below works for my app every time, I'll try to port it to SKPro if I get an upvote
> 
> ```
> class ApplicationClass : Application() {
>     override fun onCreate() {
>         super.onCreate()
>         Thread.setDefaultUncaughtExceptionHandler { _: Thread?, throwable: Throwable? ->
>             val intent = Intent(applicationContext, MainActivity::class.java)
>             intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
>             intent.putExtra("stacktrace", Log.getStackTraceString(throwable))
>             startActivity(intent)
>             Process.killProcess(Process.myPid())
>             exitProcess(1)
>         }
>     }
> }
> ```
> 
> In MainActivity
> 
> ```
> //Any crash logs sent via DefaultUncaughtExceptionHandler
>         intent.getStringExtra("stacktrace")?.let { eventLog("Application Crashed", it) }
> 
>         LocalBroadcastManager.getInstance(this).registerReceiver(
>             eventLogBroadcastReceiver,
>             IntentFilter("eventLog")
>         )
> ```

Yes fix it! Do it!

**Comment by khaled-0** [comment]
@guhg Please test with https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/9328652398

**Comment by guhg** [comment]
> @guhg Please test with https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/9328652398

I tried it! Works wonders!
