### ISSUE TITLE
Ability to change Compile SDK Version

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1142]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when certain things don't work because the compile SDK version is set to 28. There needs to be a way to change it to 33 at least.

**Describe the solution you'd like**
Ability to customize compile SDK version or simply just update the compile SDK version to 33

**Describe alternatives you've considered**
I've tried editing the build.gradle but sketchware overwrites it

**Additional context**
Don't think so

**Comment by hasrat-ali** [comment]
Well, since `Sketchware` Pro isn't using `Gradle` so it's don't benifit at all.
And you can change it after exporting you project to `Android Studio`
