### ISSUE TITLE
You can't close out of the Dependency Dialogue

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1146]
**Describe the bug**
Please give us a clear and concise description of what the bug is.

**To Reproduce**
1. Open the Dependency Dialog
2. Try to close out of the dialog
3. Notice that it's impossible to close out of the dialogue unless you have a Dependency to add in the text field
...

**Expected behavior**
You should be able to close the dialog (Otherwise, you're stuck lol)

**Media Proof**
https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/69f1213e-4b84-446c-a81f-04607cd9bf1b

Device and Sketchware Pro-related info:
 - Device: Galaxy Tab S8
 - OS: Android 14, One UI 6
 - Sketchware Pro version tested: v6.4.0-SNAPSHOT-5f9740d-minApi26

**Comment by ilyassesalama** [comment]
This has been fixed in the material-redesign branch.

**Comment by hasrat-ali** [comment]
Why not closed then?

**Comment by ilyassesalama** [comment]
> Why not closed then?

Because it still hasn't been fixed in the main branch.

**Comment by hasrat-ali** [comment]
Ohh, sorry then
