### ISSUE TITLE
Add Shizuku Support

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1150]
I thought it would be really cool to have more advanced features by having support for Shizuku. For example, using Shizuku for the Logs (Logcat Reader) section in Sketchware Pro.

**Comment by 0verflowSec** [comment]
Cool..

**Comment by PranavPurwar** [comment]
> I thought it would be really cool to have more advanced features by having support for Shizuku. For example, using Shizuku for the Logs (Logcat Reader) section in Sketchware Pro.

Logcat reader does not need root nor shizuku.

**Comment by guhg** [comment]
> > I thought it would be really cool to have more advanced features by having support for Shizuku. For example, using Shizuku for the Logs (Logcat Reader) section in Sketchware Pro.
> 
> Logcat reader does not need root nor shizuku.

Hmmm well I can never get logcat reader to work. Nothing ever shows up in it.
