### ISSUE TITLE
Widgets injection

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#1151]
**Describe the bug**
After injecting `tools:replace="android:id"` to a button, Click Listener action code is still there so we should use replace blocks again.

**Expected behavior**
Click Listener should be deleted after injecting.

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Poco F3]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: v6.4.0-SNAPSHOT-927e466-minApi26

**Comment by JavkhlanK** [comment]
> Sketchware Pro version: latest

Please **never** say that. Specify the exact version from the Program information screen instead.

**Comment by JavkhlanK** [comment]
> Why do you care about a specific version when it has existed since that feature was introduced?

You made some fixes to handling `tools:remove="android:id"`, that's why. Regardless of that, it still is good to know to be able to deterministically reproduce issues.

**Comment by HanzoDev1375** [comment]
توم عین مهدی ترنس کسخل بچسب به اسکچ

**Comment by AmirSinaRZ** [comment]
> توم عین مهدی ترنس کسخل بچسب به اسکچ
اولا مگه چشه ؟ من امکانات دیگه ای ندارم اسکچم ی کامپایلر دیگه مگه مهمه آدم چطوری برنامه هاشو میسازه؟ 
دوما تو چرا اینقدر دنبال ما کسخلا راه میفتی بزار ما کسخلا کارمون بکنیم تو گیت هاب اسکچ چیکار می‌کنی ؟

**Comment by HanzoDev1375** [comment]
@JavkhlanK This person made me make fun of you and make you and your friends angry with me. This person and his friends are extremely bad people. Please block them. He used to create programs with painstaking decompiling and called  He was recording himself

**Comment by PranavPurwar** [comment]
> > > توم عین مهدی ترنس کسخل بچسب به اسکچ
> > 
> > 
> > اولا مگه چشه ؟ من امکانات دیگه ای ندارم اسکچم ی کامپایلر دیگه مگه مهمه آدم چطوری برنامه هاشو میسازه؟ دوما تو چرا اینقدر دنبال ما کسخلا راه میفتی بزار ما کسخلا کارمون بکنیم تو گیت هاب اسکچ چیکار می‌کنی ؟
> 
> وقتی مغز نداری نصب کردن android ide و گردل خیلی سخته نه اومدی بلوک میچینی مشکل از اسکچ نیست مشکل از نادانی افرادی چون مهدی دوجنسه شوق دوجنسه و تو هستند که اسم خودتون رو گذاشتید برنامه نویس برنامه نویس های واقعی من و @JavkhlanK و @hasrat-ali هستیم و اینم بدون تو یک احمقی امیر سینا @AmirSinaRZ

mind your language.

**Comment by HanzoDev1375** [comment]
> > > > توم عین مهدی ترنس کسخل بچسب به اسکچ
> > > 
> > > 
> > > اولا مگه چشه ؟ من امکانات دیگه ای ندارم اسکچم ی کامپایلر دیگه مگه مهمه آدم چطوری برنامه هاشو میسازه؟ دوما تو چرا اینقدر دنبال ما کسخلا راه میفتی بزار ما کسخلا کارمون بکنیم تو گیت هاب اسکچ چیکار می‌کنی ؟
> > 
> > 
> > وقتی مغز نداری نصب کردن android ide و گردل خیلی سخته نه اومدی بلوک میچینی مشکل از اسکچ نیست مشکل از نادانی افرادی چون مهدی دوجنسه شوق دوجنسه و تو هستند که اسم خودتون رو گذاشتید برنامه نویس برنامه نویس های واقعی من و @JavkhlanK و @hasrat-ali هستیم و اینم بدون تو یک احمقی امیر سینا @AmirSinaRZ
> 
> mind your language.

This person is different. You can insult the dead and the living. He is not a good person

**Comment by AmirSinaRZ** [comment]
باشه

**Comment by nargess58** [comment]
> @JavkhlanK This person made me make fun of you and make you and your friends angry with me. This person and his friends are extremely bad people. Please block them. He used to create programs with painstaking decompiling and called He was recording himself


This is GitHub and issues page idiot.
