### ISSUE TITLE
Grade Files Incredibly Outdated

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1154]
So, I'm just wondering.... Are the gradle files even used by Sketchware Pro because they are super outdated. Even the compile sdk version is only 28. This poses a problem when exporting the project as an android studio zip because then ```Android IDE``` and ```Android Studio``` find the app to be incredibly outdated.

**Comment by PranavPurwar** [comment]
Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.

**Comment by guhg** [comment]
> Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.

Yeah that's why they need to be updated.

**Comment by PranavPurwar** [comment]
> > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> 
> Yeah that's why they need to be updated.

If they're not used/maintained there's no point in uodating them.

**Comment by guhg** [comment]
> > > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> > 
> > 
> > Yeah that's why they need to be updated.
> 
> If they're not used/maintained there's no point in uodating them.

Yes they are. I used to export my projects to android studio all the time. Now it gives a bunch of outdated errors. The process would be a lot easier if the gradle files were updated in the first place.

**Comment by HanzoDev1375** [comment]
بمون تا اپدیت کنند برات

**Comment by AsimJib** [comment]
> > > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> > 
> > 
> > Yeah that's why they need to be updated.
> 
> If they're not used/maintained there's no point in uodating them.

It's gradually getting harder to use Sketchware Pro for development. If these things keep going, no wonder that Sketchware Pro will need to be placed in Trash Bin soon.

**Comment by remaker17** [comment]
> > > > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> > > 
> > > 
> > > Yeah that's why they need to be updated.
> > 
> > If they're not used/maintained there's no point in uodating them.
> 
> It's gradually getting harder to use Sketchware Pro for development. If these things keep going, no wonder that Sketchware Pro will need to be placed in Trash Bin soon. Then what's the point of Skpro developers are still in active development?

No one forces you to use Sketchware Pro.

**Comment by AsimJib** [comment]
> > > > > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> > > > 
> > > > 
> > > > Yeah that's why they need to be updated.
> > > 
> > > 
> > > If they're not used/maintained there's no point in uodating them.
> > 
> > 
> > It's gradually getting harder to use Sketchware Pro for development. If these things keep going, no wonder that Sketchware Pro will need to be placed in Trash Bin soon. Then what's the point of Skpro developers are still in active development?
> 
> No one forces you to use Sketchware Pro.

I've been using it since years now. Loved the hassle free development. SKPro has it's different fanbase!

So, suddenly leaving it might not be possible, but looking at the lots of issues, yes, I do really want to leave it after a point of time not far away. Thanks.

**Comment by PranavPurwar** [comment]
> > > > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> > > 
> > > 
> > > Yeah that's why they need to be updated.
> > 
> > 
> > If they're not used/maintained there's no point in uodating them.
> 
> It's gradually getting harder to use Sketchware Pro for development. If these things keep going, no wonder that Sketchware Pro will need to be placed in Trash Bin soon. Then what's the point of Skpro developers are still in active development?

The Sketchware Pro modders aren't paid in any way, you can't really just force the responsibility of active development on them. At the very least, they are working on it out of their own passion and time. If you're so inclined to criticize them, why don't you make a pull request yourself rather than trash talking about it?

**Comment by AsimJib** [comment]
> > > > > Neither sketchware nor sketchware pro use gradle for building projects. We have a custom build system. Gradle files were used for exporting apps to android studio but they have not been updated ever since original sketchware got discontinued. Thus the generated gradle files are outdated.
> > > > 
> > > > 
> > > > Yeah that's why they need to be updated.
> > > 
> > > 
> > > If they're not used/maintained there's no point in uodating them.
> > 
> > 
> > It's gradually getting harder to use Sketchware Pro for development. If these things keep going, no wonder that Sketchware Pro will need to be placed in Trash Bin soon. Then what's the point of Skpro developers are still in active development?
> 
> The Sketchware Pro modders aren't paid in any way, you can't really just force the responsibility of active development on them. At the very least, they are working on it out of their own passion and time. If you're so inclined to criticize them, why don't you make a pull request yourself rather than trash talking about it?

Hello Pranav, thanks for replying. Neither I'm criticizing them, nor I have an intension to do so. I just asked what is the problem, and I guess you're one of them who are facing the same problem too, if you're an SKPro user. If the issue does not solve, it's fine for me since I'm an cross platform developer. Yet, I love using SKPro and I wish it to be better over the time. That's all I meant to say all over my conversation.
