### ISSUE TITLE
Certain Areas of ```Material Redesign``` still use old Switches

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#1155]
In certain settings pages, there are some outdated components in the ```material redesign``` version of Sketchware Pro. It would be good to update these to stay consistent.

Old Switches... Etc ↓
![Screenshot_20240604_181147_Sketchware Ultra](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/624e1581-600c-4758-ad09-417b731d9735)
![Screenshot_20240604_181156_Sketchware Ultra](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/41343639/562f0dd1-fb28-49a4-90ee-077deff092c3)

**Comment by ilyassesalama** [comment]
These screens specifically are being redesigned by @remaker17. Please do not open issues about screens that are still in the old design since the redesigned version isn't done yet.
