### ISSUE TITLE
Error in my Sketchware Project

### ISSUE THREAD

**Issue by EXTAZY1488** [Sketchware-Pro/Sketchware-Pro#1163]
Error: /storage/emulated/0/.sketchware/mysc/601/app/src/main/AndroidManifest.xml:4: error: unexpected element <queries> found in <manifest>

How to fix?

**Comment by EXTAZY1488** [comment]
> Error:
> 
> /storage/emulated/0/.sketchware/mysc/601/app/src/main/AndroidManifest.xml:4: error: unexpected element <queries> found in <manifest>.
>
> 
> How to fix?

**Comment by JavkhlanK** [comment]
This isn't a general-purpose forum for help with Sketchware (Pro) projects. It's only for tracking bugs, feature requests, and other stuff directly related to the app.
