### ISSUE TITLE
Failed parsing overlays

### ISSUE THREAD

**Issue by Jeke26** [Sketchware-Pro/Sketchware-Pro#1170]
![Screenshot_20240616_210016](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/121435159/f2c9b18d-2814-4a96-ad77-39ff1019db74)
**Describe the bug**
Please give us a clear and concise description of what the bug is.

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 10]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by JavkhlanK** [comment]
Why ignore the bug report template?
