### ISSUE TITLE
Notification in Android 12+

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1172]
Hi! I know there are lots of reports regarding the notifications issue in Android 12+ devices. But, I'm still requesting the Sketchware Pro team, please provide a solution. Humble request, please consider the issue.

**Comment by hasrat-ali** [comment]
There's some improvement/changes in android starting android 12. So consider reading developer guide instead. Here's some links below...!

[Android 12 Behaviour Changes](https://developer.android.com/about/versions/12/behavior-changes-12)

[Notification Overview](https://developer.android.com/develop/ui/views/notifications)

[Notification Permission](https://developer.android.com/develop/ui/views/notifications/notification-permission)
