### ISSUE TITLE
Projects with libraries produce an SWB file without any libraries

### ISSUE THREAD

**Issue by HehehBoiii78** [Sketchware-Pro/Sketchware-Pro#1173]
**Describe the bug**
This is a fatal flaw. Any project that uses a number of local libraries always produces an SWB file that doesn't have any of the local libraries (regardless of the option set during the creation of the SWB file), leaving the project unusable or dysfunctional. Even the dialog in the image below doesn't appear in the other devices when they try to restore the project.

**To Reproduce**
1. Make any project with local libraries
2. Try to make an SWB file of that project even with all checkboxes checked
3. Restore the file on another device that doesn't have the local libraries.

**Expected behavior**
I expected the SWB file to contain all the selected libraries for that project and when another device without those libraries restores the project, the dialog in the image below appears and when they click on the "COPY" button, the libraries that the SWB file contains get transferred to the other device.

**Device and Sketchware Pro-related info:**
 - Device: Happens on any device
 - OS: Android 12
 - Sketchware Pro version: v6.4.0-SNAPSHOT-5fe6468-minApi26

**Additional context**
I tried uploading my project in the form of an SWB file I made (with the Sketchware Pro version listed above, though this seems to happen with any "material-redesign" branch version) on a hosting website. It failed miserably, because the people who tried to use my project complained that there are no libraries present at all and even the dialog in the image below didn't appear on their devices. I couldn't fix this in any way.
I tried to make an SWB file with version 6.4.0-rc05, and it produced the correct SWB file (though my project broke because of missing features in that old version)! The SWB file didn't have the issue of no libraries stored. I tried the same thing with slightly older versions from the material-redesign branch, and they produced the same results, and that signifies an issue with the material-redesign versions.
Please fix this bug as soon as possible.

**Image**
![github.jpg](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/163304670/fd9b9139-f3d5-412e-9ec6-853c644b3251)

**Comment by hasrat-ali** [comment]
Hey, can you try with [this build](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/11339561239)

**Comment by HehehBoiii78** [comment]
@hasrat-ali Can't test that out yet. I tried to, but there are a few bugs preventing me from doing so.
1. I can't use a custom android.jar file (I've recently opened another issue about it)
2. Sketchware Pro crashes when trying to download the Material Components for Android library (I'll open an issue for this soon if someone hasn't opened one already).
With these bugs, I can't reproduce the original environment to test if SWB exporting works properly now. Though I'll believe it'll work this time.

**Comment by mizanmia8557-lang** [comment]
7. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/ReferActivity.java (at line 276)
	startActivity(new Intent(ReferActivity.this, ReferListActivity.class)); Animatoo.animateSwipeLeft(ReferActivity.this);
	                                                                        ^^^^^^^^
Animatoo cannot be resolved
----------
----------
8. ERROR in /storage/emulated/0/.sketchware/data/609/files/java/FCMService.java (at line 55)
	Intent intent = new Intent(this, MainActivity.class);
	                                 ^^^^^^^^^^^^
MainActivity cannot be resolved to a type
----------
9. ERROR in /storage/emulated/0/.sketchware/data/609/files/java/FCMService.java (at line 61)
	.setSmallIcon(R.drawable.app_icon)
	              ^
R cannot be resolved to a variable
----------
9 problems (9 errors)

**Comment by mizanmia8557-lang** [comment]
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/LoginActivity.java (at line 359)
	startActivity(new Intent(LoginActivity.this, CountryActivity.class)); Animatoo.animateSwipeLeft(LoginActivity.this);
	                                                                      ^^^^^^^^
Animatoo cannot be resolved
----------
2. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/LoginActivity.java (at line 1040)
	DeviceName.init(this);
	^^^^^^^^^^
DeviceName cannot be resolved
----------
3. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/LoginActivity.java (at line 1042)
	device_name = DeviceName.getDeviceName();
	              ^^^^^^^^^^
DeviceName cannot be resolved
----------
----------
4. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/HomeActivity.java (at line 1031)
	startActivity(new Intent(HomeActivity.this, SpinnerActivity.class)); Animatoo.animateSwipeLeft(HomeActivity.this);
	                                                                     ^^^^^^^^
Animatoo cannot be resolved
----------
5. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/HomeActivity.java (at line 2495)
	startActivity(new Intent(HomeActivity.this, SpinnerActivity.class)); Animatoo.animateSwipeLeft(HomeActivity.this);
	                                                                     ^^^^^^^^
Animatoo cannot be resolved
----------
----------
6. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/HistoryActivity.java (at line 138)
	startActivity(new Intent(HistoryActivity.this, WithdrawHisActivity.class)); Animatoo.animateSlideLeft(HistoryActivity.this);
	                                                                            ^^^^^^^^
Animatoo cannot be resolved
----------
----------
7. ERROR in /storage/emulated/0/.sketchware/mysc/609/app/src/main/java/com/RHgroup/DailyIcome/ReferActivity.java (at line 276)
	startActivity(new Intent(ReferActivity.this, ReferListActivity.class)); Animatoo.animateSwipeLeft(ReferActivity.this);
	                                                                        ^^^^^^^^
Animatoo cannot be resolved
----------
----------
8. ERROR in /storage/emulated/0/.sketchware/data/609/files/java/FCMService.java (at line 55)
	Intent intent = new Intent(this, MainActivity.class);
	                                 ^^^^^^^^^^^^
MainActivity cannot be resolved to a type
----------
9. ERROR in /storage/emulated/0/.sketchware/data/609/files/java/FCMService.java (at line 61)
	.setSmallIcon(R.drawable.app_icon)
	              ^
R cannot be resolved to a variable
----------
9 problems (9 errors)
