### ISSUE TITLE
whats this

### ISSUE THREAD

**Issue by potat0boy** [Sketchware-Pro/Sketchware-Pro#1176]
listview1.setAdapter(new Listview1Adapter(msg));
	                         ^^^^^^^^^^^^^^^^
Listview1Adapter cannot be resolved to a type

this happens when i use this block
![Screenshot_2024_0629_013223](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/90828116/fb6b1bb5-bb9f-4947-aa17-0591aa0acfc0)

**Comment by elfilibusterismo** [comment]
You need to select a customView first in views property before using that block

![Screenshot_20240629-100107](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/113604229/b10e9221-04d4-4b8f-9669-0b86a08c39f5)

**Comment by potat0boy** [comment]
> You need to select a customView first in views property before using that block
> 
> ![Screenshot_20240629-100107](https://private-user-images.githubusercontent.com/113604229/344359660-b10e9221-04d4-4b8f-9669-0b86a08c39f5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzMwNjAsIm5iZiI6MTcxOTY3Mjc2MCwicGF0aCI6Ii8xMTM2MDQyMjkvMzQ0MzU5NjYwLWIxMGU5MjIxLTA0ZDQtNGI4Zi05NjY5LTBiODZhMDhjMzlmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxNDUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzQ1MTgzOWRiYzFkOWZkYjM3YmJlMGViOTY3ZjYyNDI0OTgzYzkxMDQ5ZjVkZTgyNzdmODk1Y2MyYjc2OWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yDZW1O0oSmJWptkvuVPv0HJwsqHzTk3RazKmZs1MZE0)

Thanks!
