### ISSUE TITLE
Dexing library

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#1187]
**Describe the bug**
Failed to dexing library.

**To Reproduce**
Dependency : ```ir.tapsell.plus:tapsell-plus-sdk-android:2.2.6```

**Screenshots**
![Screenshot_2024-07-02-20-04-16-233_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/116455534/70935f65-a888-4409-8279-d22c053b65fa)
![Screenshot_2024-07-02-20-04-10-039_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/116455534/03de5ab9-2898-46cc-be6a-f44700047ac4)

Device and Sketchware Pro-related info:
 - Device: [Poco F3]
 - OS: [Android 13]
 - Sketchware Pro version: [v6.4.0-SNAPSHOT-5fe6468-minApi26]

**Comment by JavkhlanK** [comment]
Fixed after commit 10a7408, get the currently latest nightly build.
