### ISSUE TITLE
Target API 34 needed.

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1193]
App must target Android 14 (API level 34) or higher

We've detected that your app is targeting an old version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.

From 31 August 2024, if your target API level is not within one year of the latest Android release, you won't be able to update your app.

**Comment by PranavPurwar** [comment]
Go to project config and update targetSdk to 34

**Comment by subhash16** [comment]
Currently using Version v6.4.0-SNAPSHOT-f85522d-minApi26

**Comment by subhash16** [comment]
> Go to project config and update targetSdk to 34

I am currently using Currently using Version v6.4.0-SNAPSHOT- f85522d -minApi26
Will it work or I need to download other version 
If need other version then give link

**Comment by PranavPurwar** [comment]
It will work on any version of Sketchware Pro.

**Comment by subhash16** [comment]
> It will work on any version of Sketchware Pro.

The default android.jar was upgraded to SDK version 33, r02 (Android 13) (6e4ecfa)

**Comment by subhash16** [comment]
( f85522d )

**Comment by subhash16** [comment]
> > It will work on any version of Sketchware Pro.
> 
> The default android.jar was upgraded to SDK version 33, r02 (Android 13) ([6e4ecfa](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/6e4ecfa25a9efab0f55db9c73dea1aefbc034871))

After that it's not updated

**Comment by subhash16** [comment]
Latest android.jar not updated

**Comment by subhash16** [comment]
> Go to project config and update targetSdk to 34

Without updating the sketchware app to latest Android jar 34, if we set target sdk 34 is there problem occurs?

**Comment by PranavPurwar** [comment]
I just told you to go ahead and try it. Have you tried it yet?

**Comment by subhash16** [comment]
> I just told you to go ahead and try it. Have you tried it yet?

Yes tried No issues till now.I am asking if latest Android jar is not available on sketchware if I set forcefully 34 ,Do you think No problem will occur?

**Comment by PranavPurwar** [comment]
> > I just told you to go ahead and try it. Have you tried it yet?
> 
> Yes tried No issues till now.I am asking if latest Android jar is not available on sketchware if I set forcefully 34 ,Do you think No problem will occur?

Target SDK is different from compile sdk. You can set update target sdk anytime.

**Comment by subhash16** [comment]
> > > I just told you to go ahead and try it. Have you tried it yet?
> > 
> > 
> > Yes tried No issues till now.I am asking if latest Android jar is not available on sketchware if I set forcefully 34 ,Do you think No problem will occur?
> 
> Target SDK is different from compile sdk. You can set update target sdk anytime.

Thank you sir.

**Comment by hasrat-ali** [comment]
![Screenshot_2024-07-06-00-22-18-499_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/42956453/b6e44860-568b-4abc-b8d2-046b5631256b)
If you want to use latest `android.jar`, download it and put the full path here.

**Comment by subhash16** [comment]
> ![Screenshot_2024-07-06-00-22-18-499_com sketchware remod](https://private-user-images.githubusercontent.com/42956453/346206151-b6e44860-568b-4abc-b8d2-046b5631256b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjc3NTYsIm5iZiI6MTcyMDI2NzQ1NiwicGF0aCI6Ii80Mjk1NjQ1My8zNDYyMDYxNTEtYjZlNDQ4NjAtNTY4Yi00YWJjLWI4ZDItMDQ2YjU2MzEyNTZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDEyMDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjQ5ZWQ5NmY0YTdhNjQ5ZGE2MmUyMTA0NThjMjBmMTk5MTUzOGZlN2IxMjliODEyMGEyOTM2Y2I5YmRlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MaiWenKiUuP7ESVE4TU7-Guypeb5k_kGTau1dWAY0VQ) If you want to use latest `android.jar`, download it and put the full path here.

Sir where can I find latest jar
