### ISSUE TITLE
Buggy "Cancel build?" dialog

### ISSUE THREAD

**Issue by HehehBoiii78** [Sketchware-Pro/Sketchware-Pro#1204]
**Describe the bug**
The "Cancel build?" dialog that appears when you start to build a project then click on the Back button, is abnormally functional with multiple bugs. The abnormalities are present in different variants. The first variant can be found in the builds of Sketchware Pro from the material-redesign branch that used the pure M3 dialog (see first image) without changing it to what it is in the newer builds (see second image). The second variant can be found in the newer builds of Sketchware that have moved on from the pure M3 dialog design (also see second image). The third variant can be found in the newest snapshots of Sketchware Pro (see third image). All variants have issues.

**Issues**
Variant 1
1. The dialog can be dismissed (that shouldn't be allowed)!

Variant 2
1. The dialog can be dismissed.
2. The buttons of the dialog do work, but they do not close the dialog at all. You need to click out of the dialog to close it.

Variant 3
1. The dialog can be dismissed.

**Expected behavior**
Variant 1
1. The dialog shouldn't allow the user to dismiss itself.
2. If the Stop building button is selected, the build dialog should re-appear and show the progress of the cancellation process.
3. If the Continue building button is selected, the build dialog should re-appear and continue the build.

Variant 2
1. The dialog shouldn't allow the user to dismiss itself.
2. The buttons of the dialog should close the "Cancel build?" dialog before starting to do their function.
3. If the Stop building button is selected, the build dialog should re-appear and show the progress of the cancellation process.
4. If the Continue building button is selected, the build dialog should re-appear and continue the build.

Variant 3
1. The dialog shouldn't allow the user to dismiss itself.
2. If the Stop building button is selected, the build dialog should re-appear and show the progress of the cancellation process, similar to how it is in the "Latest Stable" versions of Sketchware Pro.
3. If the Continue building button is selected, the build dialog should re-appear and continue the build.

**Images**
Variant 1
![Screenshot_20240714-133247_Sketchware Pro.jpg](https://github.com/user-attachments/assets/a9f1255a-c872-450f-b87c-eca3a73a1289)

Variant 2
![Screenshot_20240714-132331_Sketchware Pro.jpg](https://github.com/user-attachments/assets/f497e77c-c823-4758-9fb6-7b010d23c00f)

Variant 3
![Screenshot_20240725-173551_Sketchware Pro.jpg](https://github.com/user-attachments/assets/841c5682-ecdb-4904-9227-ec919e16619f)

**Sketchware Pro-related info:**
Variant 1
- Sketchware Pro version:
v6.4.0-SNAPSHOT-7591e71-minApi26

Variant 2
- Sketchware Pro version:
v6.4.0-SNAPSHOT-bad2a20-minApi26

Variant 3
- Sketchware Pro version:
v6.4.0-SNAPSHOT-d48652e-minApi26

**Additional context**
In the Latest Stable and Latest Beta versions of Sketchware (basically the builds of Sketchware Pro not from the material-redesign branch), the build cancelling confirmation dialog doesn't show at all. Instead, it starts cancelling the build immediately without confirmation. This behavior is not good—unintentional back button clicks can anger a person really bad. The dialog itself helps a lot, it just needs to be fixed so that it does its function properly.

**Comment by ilyassesalama** [comment]
Thanks for your report, this bug has been fixed with commit [b7eac383d](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/b7eac383d3f0814181002b23889efdb0fb3edd50)
