### ISSUE TITLE
Image Add Not Working.

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1212]
**Describe the bug**
When I add images in ImageManager the images is not saved 

**To Reproduce**
1)Create a project 
2) Tap write side 3 dots
3) tap on Image
4) tap on Plus icon 
5) Choose Image
6) Save (Not saving)

**Expected behavior**
Should be save on image manager 

**Screenshots**
![Screenshot_20240726-023352~2](https://github.com/user-attachments/assets/1d22cb58-ef24-47fb-a1c2-535a86351611)

Device and Sketchware Pro-related info:
 - Device: [e.g. Motorola G54,G64,Poco M2pro,Redmi Note 10 pro]
 - OS: [e.g. Android 13,14]
 - Sketchware Pro version:Version v6.4.0-SNAPSHOT-d48652e-minApi26

**Additional context**
Please Fix ..

**Comment by subhash16** [comment]
Thank you Sir Can I use now the latest snapshot

**Comment by hasrat-ali** [comment]
Yes

**Comment by subhash16** [comment]
Material redesign merged with main , original design not available
