### ISSUE TITLE
Minimum SDK, Target SDK

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1214]
When I make a new project its minimum SDK sets to 21 and Target SDK sets to 28 which is outdated now.
Everytime I have to  manually change the target sdk 34.

**Describe the solution you'd like**
Please do something to minimum SDK 24 and target sdk version 34 which will set automatically when the project first time create.

![Screenshot_20240730-015742](https://github.com/user-attachments/assets/1c88a446-df0f-4183-ad10-98b83e27d60d)
v6.4.0-SNAPSHOT- 3458625 -minApi26

**Comment by oramirezd** [comment]
I am think about that is some restrictive and bad.I am think about if you would developme te​ with other minimium or target version SDK its add manually.

**Comment by ilyassesalama** [comment]
Thanks for the suggestion, this has been changed now.

**Comment by subhash16** [comment]
> Thanks for the suggestion, this has been changed now.

Thank you Sir,
But I also recommend to change the minimum SDK version to 24.
please Sir .
