### ISSUE TITLE
Some activities not following current selected theme from preferences

### ISSUE THREAD

**Issue by remaker17** [Sketchware-Pro/Sketchware-Pro#1222]
**Describe the bug**
See title.

**To Reproduce**
My phone is on dark theme rn.
1. Select light theme on preferences.
2. Open settings.
3. Open event manager.
4. See result.

**Expected behavior**
Every activity must follow current selected theme.

**Screenshots**
![1.jpg](https://github.com/user-attachments/assets/3971ecc1-46f1-4133-886c-eff4fc165291)
![2.jpg](https://github.com/user-attachments/assets/9ebc155b-f821-4e4a-b136-92ef9d1f94cd)

Device and Sketchware Pro-related info:
 - Device: Doesn't matter.
 - OS: Android 11
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3125311-minApi21]

**Additional context**
~~Trindadev's themes implementation so weird.~~
Only activities that extends `android.app.Activity` doesn't follow selected theme.

**Comment by hasrat-ali** [comment]
A theme manager would be better in `BaseAppCompatActivity`

**Comment by remaker17** [comment]
> A theme manager would be better in `BaseAppCompatActivity`

> Only activities that extends `android.app.Activity` doesn't follow selected theme.
