### ISSUE TITLE
Restore project "Cancel & Select Button" not visible clearly 

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1223]
**Describe the bug**
Restore project "Cancel & Select Button" not visible clearly 

**Screenshots**
![Screenshot_20240812-142129~2](https://github.com/user-attachments/assets/be522c78-37b0-44ff-9c54-c7fe262119ef)

Device and Sketchware Pro-related info:

Device: All
OS: All
Sketchware Pro version: v6.4.0-SNAPSHOT- 135ad63 -minApi26

**Comment by trindadedev13** [comment]
update sketchware

**Comment by subhash16** [comment]
Yes ,its now Solved
