### ISSUE TITLE
Edit Image not working in ImageManager

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1238]
**Describe the bug**
Edit Image not working in ImageManager like 
1)Edit the Image Name.
2)Add to my collection 

**To Reproduce**
GOTO Configuration>Image>Tap on a image

**Expected behavior**
Image name edit & add to collection should work.

**Screenshots**
![Screenshot_20240902-031338~3](https://github.com/user-attachments/assets/fd4f7c52-d56d-4351-b926-5f775a336498)

Device and Sketchware Pro-related info:
 - Device: All
 - OS: All
 - Sketchware Pro version: v6.4.0-SNAPSHOT- 9c80150 -minApi26

**Comment by subhash16** [comment]
No It's not working till now .I have texted.
v6.4.0-SNAPSHOT- 1a2fd68 -minApi26

**Comment by subhash16** [comment]
Please look into this issue

**Comment by hasrat-ali** [comment]
Is that feature was available in any previous version?

**Comment by subhash16** [comment]
> Is that feature was available in any previous version?

Yes but I couldn't remember the version

**Comment by subhash16** [comment]
> > Is that feature was available in any previous version?
> 
> Yes but I couldn't remember the version

Sorry for that I told yes but I can't remember it that it was working on any version or not.

**Comment by hasrat-ali** [comment]
As far as I know, it was never there.

**Comment by JavkhlanK** [comment]
This never worked, no.
