### ISSUE TITLE
Automatic Edge-to-Edge Support in Sketchware Pro Made Applications Needed

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1240]
**Description:**  
Currently, when enabling the `EdgeToEdge.enable(this);` feature in apps built with Sketchware Pro, toolbars and navigation drawers overlap with the status bar, instead of properly adapting to edge-to-edge layouts. This causes visual inconsistencies and obstructs critical UI elements.

**Expected Behavior:**  
Sketchware Pro should automatically support edge-to-edge layouts without requiring additional configurations, ensuring that toolbars and navigation drawers do not overlap the status bar.

**Actual Behavior:**  
Enabling `EdgeToEdge();` in apps built using SW Pro leads to toolbar and drawer overlap with the status bar, instead of adapting correctly to the edge-to-edge layout.

**Request:**  
Please update Sketchware Pro to automatically handle edge-to-edge layouts, ensuring UI elements align correctly without overlapping the status bar.

---

**Comment by Yamenher** [comment]
Bruh just use windows insets, it's not a sketchware pro bug and you must hadle that yourself, read docs about that to learn more

**Comment by hasrat-ali** [comment]
Well, you should do it yourself. So...
