### ISSUE TITLE
Proguard & R8

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1241]
Add option to only use Proguard & R8 when signing APK or AAB.

**Comment by PranavPurwar** [comment]
> Add option to only use Proguard & R8 when signing APK or AAB.

If you're working on your app, why not just "disable" Code Shrinking for that time? You only need to build signed APKs/AABs once in a while. So it doesn't really make sense to keep it always on and asking for this "option".

**Comment by RoyTheReal** [comment]
@PranavPurwar AAB export still doesn't work for me. Gives error. I made bug report a long time ago.

**Comment by AnBui2004** [comment]
@PranavPurwar I ask this to make it more convenient and avoid the time consuming of turning it on or off and having to rebuild.

**Comment by PranavPurwar** [comment]
> @PranavPurwar I ask this to make it more convenient and avoid the time consuming of turning it on or off and having to rebuild.

You only have to build release APKs once a month or so. I don't know how this is a real problem. You can just enable and disable builds there. Moreover people usually wanna check that their configuration is correct and doesn't crash the app, which takes a few iterations. For which, this would make it quite difficult.
