### ISSUE TITLE
Html Webview not working on latest android sdk

### ISSUE THREAD

**Issue by Omnicron-Hydra** [Sketchware-Pro/Sketchware-Pro#1245]
When **building** on min sdk 21 target 33, html webview doesn't seem to work, but when i change or revert it back to min sdk 21 target sdk 28, Then everthing starts working perfectly

And this mostimes, trigger play protect when building on sdk 21 - 28
Is there a solution to this bug?

**Comment by hasrat-ali** [comment]
There is no problem in webview.

There is a problem in apk signing. You should use `targetSdk 28` until signing will be fixed.
