### ISSUE TITLE
Lots of Warning - Deprecated Code

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1246]
3. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 22)
	View _view = _toast.getView();
	                    ^^^^^^^^^
The method getView() from the type Toast is deprecated
----------
4. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 53)
	View _view = _toast.getView();
	                    ^^^^^^^^^
The method getView() from the type Toast is deprecated
----------
5. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 126)
	NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
	^^^^^^^^^^^
The type NetworkInfo is deprecated
----------
6. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 126)
	NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
	                                                      ^^^^^^^^^^^^^^^^^^^^^^
The method getActiveNetworkInfo() from the type ConnectivityManager is deprecated
----------
7. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 127)
	return _activeNetworkInfo != null && _activeNetworkInfo.isConnected();
	                                                        ^^^^^^^^^^^^^
The method isConnected() from the type NetworkInfo is deprecated
----------
8. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 148)
	_inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0);
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method toggleSoftInput(int, int) from the type InputMethodManager is deprecated
----------
9. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 153)
	_inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method toggleSoftInput(int, int) from the type InputMethodManager is deprecated
----------
10. WARNING in /storage/emulated/0/.sketchware/mysc/602/app/src/main/java/com/my/newproject2/SketchwareUtil.java (at line 153)
	_inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
	                                                       ^^^^^^^^^^^
The field InputMethodManager.SHOW_FORCED is deprecated
----------
10 problems (2 errors, 8 warnings)

**Comment by JavkhlanK** [comment]
Duplicate of #804. You should know that before you open an issue, you should check for duplicates first.

**Comment by subhash16** [comment]
Sir Sorry for the duplicate,But that was already closed
