### ISSUE TITLE
Give more flexibility when editing views

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1249]
Please consider adding the option to exclude certain attributes from views. For instance, `android:textColor` is mandatory in a Button, but I prefer not to include `android:textColor` in the button as it disrupts the automatic Material 3 theming. Currently, the only way to remove it is by using an XML command block, which removes all android:textColor properties and leaves a space in the XML code. It would be more convenient for the user to have the option to exclude any built-in values when editing a view (Or just make them all custom editable and deletable like in the `appcompat` section). So then we can just add our own in the inject section. This would be very useful as we can already do this with `appcompat` objects.

**Comment by hasrat-ali** [comment]
You can always remove **any attribute** using `tools:replace="..."`.
For example: `tools:replace="android:textColor"`
