### ISSUE TITLE
Trying to implement Edge to Edge support (Please help)

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1251]
Trying to implement Edge to Edge support (Please help)
I have successfully implemented edge-to-edge support in my app, and it works perfectly on Android 14. However, after upgrading to Android 15 beta, I encountered an issue where the app draws under the status bar. This behavior is confusing since it functions correctly on Android 14 with edge-to-edge enabled. Interestingly, on Android 15, if I quickly switch the app to landscape mode and then return to portrait, the issue resolves, and the app no longer draws under the status bar.

Video displaying the issue: https://drive.google.com/file/d/15x5XqIMA4XYWHr0zwouH3H6WNSQrP0bz/view?usp=drivesdk

Below is the code that works fine on Android 14:

```
EdgeToEdge.enable(this);
WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.linear7), (v, insets) -> {
int topInset = insets.getInsets(WindowInsetsCompat.Type.statusBars()).top;
v.setPadding(0, topInset, 0, 0);
return WindowInsetsCompat.CONSUMED;
});
ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.actionbar), (v, insets) -> {
int topInset = insets.getInsets(WindowInsetsCompat.Type.statusBars()).top;
v.setPadding(0, topInset, 0, 0);
return WindowInsetsCompat.CONSUMED;
});
ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.linear1), (v, insets) -> {
int topInset = insets.getInsets(WindowInsetsCompat.Type.statusBars()).top;
v.setPadding(0, topInset, 0, 0);
return WindowInsetsCompat.CONSUMED;
});
```
I'm hoping someone can shed light on this issue. I don't know why it's not working properly on android 15.

**Comment by RoyTheReal** [comment]
@JavkhlanK Could you possibly help? Idk what's wrong. I know Android 15 enforces edge to edge now but my code was working on older versions

**Comment by JavkhlanK** [comment]
no

**Comment by RoyTheReal** [comment]
:(
