### ISSUE TITLE
Kotlin & Jetpack Compose

### ISSUE THREAD

**Issue by Jompschz** [Sketchware-Pro/Sketchware-Pro#1257]
Is there a possibility that Sketchware could implement the Kotlin language in the future, and also JC for interface development?

**Comment by trindadedev13** [comment]
> Is there a possibility that Sketchware could implement the Kotlin language in the future, and also JC for interface development?

As far as I know, Sketchware already has Kotlin, and I find it difficult for anyone to add Jetpack Compose, as it is completely different.

**Comment by hasrat-ali** [comment]
We already have support for Kotlin, but unfortunately, Jetpack Compose is not possible for now.
