### ISSUE TITLE
Request for Direct AndroidManifest.xml Editing Feature in Sketchware

### ISSUE THREAD

**Issue by Ars-king** [Sketchware-Pro/Sketchware-Pro#1263]
Subject: Request for AndroidManifest.xml Direct Modification Feature in Sketchware for Custom App Development

Dear Sketchware Pro Development Team,

I hope this message finds you well. I am a dedicated user of Sketchware and have been working on several projects such as Home applications, Assistant apps, and Plugin apps, which often require modifications to the AndroidManifest.xml file.

However, currently, there is no direct way to edit the AndroidManifest.xml file within Sketchware, which significantly limits my ability to customize app components as required for specific projects. For example, when trying to add a line like:

`<category android:name="android.intent.category.DEFAULT" />
`
to the intent filter, it either gets placed outside the built-in intent filter structure or leads to placement issues when inserted through the app components section. This makes it difficult to achieve the desired functionality for custom apps.

My feature request:

1. Please consider adding a direct AndroidManifest.xml editor within Sketchware, allowing developers to modify or add components freely.

2. Alternatively, introduce a "Manifest Manager" that allows us to choose from predefined app types such as:

Plugin app

Home app

Assistant app

Regular app

Based on the selection, the required intent filters and manifest configurations would be automatically generated. This would greatly improve workflow efficiency and enable developers to create more complex and customized applications without running into intent filter or placement issues.

Thank you for considering this feature request. I believe this enhancement would significantly expand Sketchware's capabilities and provide developers like myself with more flexibility when building diverse types of applications.

Best regards,
ARS

**Comment by JavkhlanK** [comment]
Use the feature request template next time.

There already exists a Manifest Manager to do similar things.

There also are XML Command Blocks which let you edit the entire file in an incremental way, so that changes made by using Sketchware Pro features like adding new Blocks, Components, etc. don't conflict with the made changes.  
[Here's tutorials on using those Blocks in the Discord server](https://discord.com/channels/790686719753846785/797801500276424724/798164544375619625)

There won't be a feature to select from "predefined app types" because those app types don't exist. The manifest is way more variable than that, and such categories wouldn't make sense.

**Comment by Ars-king** [comment]
![Screenshot_20240924-110703](https://github.com/user-attachments/assets/24389ce7-72a8-49e1-bc81-e667ca360d99)
![Uploading Screenshot_20240924-110719.png…]()

Sir JavkhlanK

Thank you for your response. I appreciate the clarification regarding the existing features.

However, I would like to bring to your attention an error I encountered while working on my project. I have attached two screenshots for your reference. The error message is as follows:

`/storage/emulated/0/.sketchware/mysc/1024/app/src/main/AndroidManifest.xml:121: error: unexpected element <intent-filter> found in <manifest><application>.`

This issue seems to arise when trying to add an <intent-filter> in the AndroidManifest.xml, which indicates that the structure may not be handling certain elements correctly.

I would appreciate any guidance or solutions you could provide regarding this error.

Thank you for your assistance!

Best regards,
ARS

**Comment by JavkhlanK** [comment]
1. please stop using chatgpt to make your comments more formal, they only waste your and my time
2. use an XML Command Block then. follow the tutorial I already linked earlier.

**Comment by Ars-king** [comment]
Sorry sir, actually I use sketchware version v6.4.0-rc05-miniApi26 and I didn't get the inbuilt command bolck, so I requested you to improve. And yes I am banglai, and my english is bad, so I took the support of AI to clarify my problem. Now using command block no problem, thank you
