### ISSUE TITLE
Question real quick

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1265]
I need to know because I am thinking about buying a device. Does sketchware pro run well on Dimensity chipsets like the MediaTek Dimensity 9300 Plus?

**Comment by RoyTheReal** [comment]
@JavkhlanK Please?

**Comment by RofrancoD** [comment]
Me funciona bien con el mediatek 8300 ultra y G90T

**Comment by JavkhlanK** [comment]
why shouldn't it? if every program had to be adjusted to every CPU, that'd be a terrible world. it's the other way around, mostly
