### ISSUE TITLE
Error In FirebaseDB Component Listeners

### ISSUE THREAD

**Issue by EncodingLion** [Sketchware-Pro/Sketchware-Pro#1269]
**Did you notice that adding Firebase DB component, automatically adding these listeners in java file:**

- onChildAdded
- onChildChanged
- onChildDeleted
- onCanceled

`Even we didn't toggle them, they automatically added`

 ```Please help!, I need solution of that problem urgently.
These Listeners need to add only when we toggle it as **ON** .```

**Comment by JavkhlanK** [comment]
not an error, also use issue templates
