### ISSUE TITLE
Activity selection indicator missing

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1273]
After Activity selection, there is no indicator in which activity I'm in. It's helpful when I have many activities in my project and I need to check codes in various activities. This help us keep track and quickly change activities quickly.

![Screenshot_20241005-154434](https://github.com/user-attachments/assets/e0a9a083-31d2-4a29-bfc4-885f36536ea4)
![Screenshot_20241005-154439](https://github.com/user-attachments/assets/7fb49736-ba2d-4444-a462-8b6ca54fe2a8)

**Comment by hasrat-ali** [comment]
You can see below 

![IMG_20241005_190132](https://github.com/user-attachments/assets/f890be1a-72e8-4be4-81cb-9b3be1207bf4)

**Comment by AsimJib** [comment]
Yes, I want like this. But it's not showing. This is the version I'm using.
![Uploading Screenshot_20241005-190542.jpg…]()

**Comment by AsimJib** [comment]
Yes, I want like this. But it's not showing. This is the version I'm using.

![Screenshot_20241005-190542](https://github.com/user-attachments/assets/7c402869-f2ce-4d21-9821-765ff73b2af1)

**Comment by AsimJib** [comment]
Thanks for implementing this feature. 😊
