### ISSUE TITLE
Compiler SDK Update

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1274]
Currently Sketchware Pro uses compiler SDK 28 . Please take a look if it's possible to upgrade the SDK to 33 or higher.

**Comment by RoyTheReal** [comment]
Yes

**Comment by AsimJib** [comment]
Thanks for implementing this feature. 🫡

**Comment by RoyTheReal** [comment]
So, Sketchware Pro now compiles apps at API 33?

**Comment by RoyTheReal** [comment]
> On 34.

So, what does this change/help?
