### ISSUE TITLE
Why Sketchware Pro can not use the library "android.support.*"?

### ISSUE THREAD

**Issue by oramirezd** [Sketchware-Pro/Sketchware-Pro#1276]
I am always ask why Sketchware Pro not allow to choose between the library "android.support.*" and "androidx" .Just allow to use the library "androidx" . Please,reconsidering this choice in Sketchware Pro.

**Comment by trindadedev13** [comment]
why would you want to use android.support instead of androidx which is newer?

**Comment by JavkhlanK** [comment]
Because that library is deprecated, old as hell, not supported, and a pain in the ass to work with in 2024. Let's not make Sketchware Pro's build process *even more complicated*.

People should move away from the old support libraries, still supporting / even adding support **back** is not the way to go.

**Comment by oramirezd** [comment]
@trindadedev13 Because many projects still use this library along with the "android.support.desing.*" library whose source code is found on github and when it comes to adapting it or making the corresponding change to "androidx" to recompile with Sketchware Pro it is relatively annoying,difficoult.
In addition, it would also allow the developer who uses Sketchware Pro to be able to choose between the two libraries and not just the one that is offered as something obligatory to use.

**Comment by trindadedev13** [comment]
@oramirezd I have never seen any project (created in sketchware) that uses android support

**Comment by oramirezd** [comment]
@trindadedev13 Mabbe some library *.jar download for use how to external library its compiled with this library becouse the original code source use this library "android.support.*" and for that when activate the fuction "App Compat" for use the library "adroidx", compile fine but when start the apk not work fine.

**Comment by oramirezd** [comment]
@trindadedev13 The oficial version of Sketchware(com.besome.sketch) use the library "android.support.*" when activare the choice "App Compat" but not allow to choose use the library "androidx".Download and see that.

**Comment by oramirezd** [comment]
@trindadedev13 But any way, How many project in Github appear using still this library "android.support.*' and when try to compile with Sketchware Pro its to make the change first (work so hard) for compile fine becouse this IDE for android not use this library? 
Think about this.

**Comment by oramirezd** [comment]
@JavkhlanK 
**Because that library is deprecated, old as hell, not supported, and a pain in the ass to work with in 2024. Let's not make Sketchware Pro's build process even more complicated .

People should move away from the old support libraries, still supporting / even adding support back is not the way to go._ ** 


Even that library its deprecated, old as hell, and a pain in the ass to work with 2024... 

I am think about its work any way for to Sketchware Pro can allow to use, or can choose betwin this library "android.support.*" and "androidx" when activate the "App Compat" for to allow the development to use the library want to use how all the IDE for Android.

The development of any IDE how this Sketchware Pro for Android must work so hard for build a good IDE able to compile any project even if it is using old compilation methods to make it the IDE for Android (in this case Sketchware Pro) widely accepted by everyone, preferred because it allows the developer to choose how to do it, choose the tools to use without having to be forced to use the one they come predefined by this application.

**Comment by JavkhlanK** [comment]
No, simply no. You don't know how painful that would be. It'd also be pointless since almost no one needs that (as it should be).

In any way, if you *really* do need the old support libraries, [there is a way](https://docs.sketchware.pro/builtinlib).

(And this will not be worked on)

**Comment by oramirezd** [comment]
@JavkhlanK I conected to this link but in that site web not appear that info how you say.

**Comment by oramirezd** [comment]
@JavkhlanK Well.Yes, I do not really do not the idea but the oficial Sketchware(com.besome.sketch) use this library "android.support.*" and compile fine.Get the programing and resolve this problems.I say, if you want.

**Comment by JavkhlanK** [comment]
It doesn't in version 3.10.0. A version released more than **4 years ago**. Sketchware Pro is still updated unlike Sketchware.
