### ISSUE TITLE
Upgrade Build Gradle

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1277]
Recent changes on Sketchware Pro are awesome. I just loved these changes.

I have another feature request now. Please consider looking at it if you can upgrade the build Gradle from 7.4.2 to latest version or at least 8.2+?

**Comment by ilyassesalama** [comment]
Sketchware Pro does not use Gradle. The gradle version you see when you export your project's source code is just a hardcoded value.

**Comment by AsimJib** [comment]
Got it. Thanks.
