### ISSUE TITLE
Make Material 3 default in Sketchware Pro applications

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#1278]
I kindly request that you consider updating the **default styles.xml** file and other relevant configurations to ensure that applications are set to use Material 3 components by default. At present, manually replacing these components is suboptimal, and an issue arises where the toolbar text color remains white, even after switching to Material 3. According to Material 3 design guidelines, the toolbar (or action bar) should display black text. Adjusting the default settings would not only align with these guidelines but also provide a more seamless and consistent implementation experience for us developers that use Sketchware Pro.

**Comment by subhash16** [comment]
Yes Good Idea
