### ISSUE TITLE
Multiple Activities in Selected state

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1280]
1. When there are many activities in a project, multiple activities are marked with red border as in active activity state. I have tested with with a project containing 38 activities and I get 3 activities marked as selected with red border.

2. If you switch to custom activity toggle from the views, after selecting a custom view, it automatically switches the toggle to the main views pretending you are in the main view section.

I guess these should be helpful to understand what I'm trying to say. If any clarifications needed, please let me know. I would be glad to see these things fixed. Thanks.

**Comment by JavkhlanK** [comment]
Use the provided bug report template please. It exists for a reason.
