### ISSUE TITLE
In the "Direct Code Editor" need to show the line number.

### ISSUE THREAD

**Issue by oramirezd** [Sketchware-Pro/Sketchware-Pro#1285]
Y es, in this "Direct Code Editor" window need to show the number line how to all programing window editor.

**Comment by oramirezd** [comment]
This is the facebook link of one my ask about: https://www.facebook.com/groups/sketchwarepro/permalink/1683160019093770/?app=fbl

![](https://i.imgur.com/RVrkk0h.jpeg)

**Comment by oramirezd** [comment]
How this number line:

![](https://i.imgur.com/Tp2C5H5.jpeg)

**Comment by JavkhlanK** [comment]
this screen already was removed for various reasons

and for the next times, ***please use Issue templates***, they exist for a reason. otherwise your Issues may be closed.
