### ISSUE TITLE
How to compile file *.aidll?

### ISSUE THREAD

**Issue by oramirezd** [Sketchware-Pro/Sketchware-Pro#1286]
Y es.I would to know how I can compile this file *.aidll to contein many code source from github with Sketchware Pro.

**Comment by hasrat-ali** [comment]
Well, since **Sketchware (Pro)** isn't using **Gradle** it's not possible, atleast for now.

**Comment by oramirezd** [comment]
@hasrat-ali How to do that with Sketchware Pro?

**Comment by hasrat-ali** [comment]
Idk

**Comment by oramirezd** [comment]
@hasrat-ali Whats the mean, this? I do not understan.

_Sent from my Moto G Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by oramirezd** [comment]
@hasrat-ali Whats the mean "ldk".?

_Sent from my Moto G Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by oramirezd** [comment]
@hasrat-ali Whats the mean "ldk".?

_Sent from my Moto G Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
