### ISSUE TITLE
Custom View Text Color

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1301]
Text color for custom views in dark mode does not change. Please fix.

![Screenshot_20241018-234828](https://github.com/user-attachments/assets/7e9b7fb6-cb49-4f95-9342-874208050ec6)

**Comment by hasrat-ali** [comment]
Can you tell the exact version of your current Sketchware Pro.

**Comment by ilyassesalama** [comment]
This is because `xw` class changes the color of that text programmatically. That class needs to be decompiled to fix this issue.

**Comment by AsimJib** [comment]
> Can you tell the exact version of your current Sketchware Pro.

![Screenshot_20241020-073054](https://github.com/user-attachments/assets/1fb49be6-12bb-4a3d-853c-79282d712645)

**Comment by trindadedev13** [comment]
this can be closed

**Comment by AsimJib** [comment]
> this can be closed

Yes, Thanks for the fix.
