### ISSUE TITLE
Stuck at the beginning after install

### ISSUE THREAD

**Issue by yusufquteb** [Sketchware-Pro/Sketchware-Pro#1302]
When i download new sketchware pro from your telegram channel, after installing and opening it take time to load projects the crash
This happens every time

My device is samsung a23
Android 14
My working version is Pro_v6.4.0-SNAPSHOT-ab33cc8-minApi26.apk , newly versions are crashing

**Comment by ilyassesalama** [comment]
A crash log is necessary. We can't know what's going on without it.

**Comment by hasrat-ali** [comment]
You are using older build. Try [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/12097874141).

**Comment by yusufquteb** [comment]
It is awesome..it toke 2 minutes only to open.
Can it be faster?

**Comment by hasrat-ali** [comment]
> A crash log is necessary. We can't know what's going on without it.

This

**Comment by yusufquteb** [comment]
There's no crash ..it's lagging but no it became faster.
You do great things.
Thank you 🌷
When you will publish direct code editor?
I need it to edit xml and java files
