### ISSUE TITLE
[MINOR ISSUE] Component name validation button only works once

### ISSUE THREAD

**Issue by Hamilthon** [Sketchware-Pro/Sketchware-Pro#1307]
**Describe the bug**
Whenever choosing a component in the component menu, when prompted to name it, the "enter" button only works once, which means that if your field is emptynor incorrect you have to close the prompt and the component list menu and try again.

**To Reproduce**
1. Get into a project
2. Go to the component tab
3. Click on the "+" to add components
4. Click on whatever object you want
5. Enter either an incorrect name or a blank field and press enter
6. Enter a valid name and try to press enter
...

**Expected behavior**
The prompt should let you try infinitely until you enter a proper name and validate

**Screenshots**
Here is a video demonstrating the issue :
https://streamable.com/ifz5ek

Device and Sketchware Pro-related info:
 - Device: Oppo A53
 - OS: Android 12
 - Sketchware Pro version: v6.4.0-rc05-minApi26

**Comment by hasrat-ali** [comment]
This bug is already fixed with 41607633c48aa35a3e3219f2f090e26c083adf89.
