### ISSUE TITLE
What's the utilility the code to appear in the end of all project of Sketchware and how to modify by the same app?

### ISSUE THREAD

**Issue by oramirezd** [Sketchware-Pro/Sketchware-Pro#1321]
I am ask  What's   the utility of this code that appears to the end of each project(and I am think about to can erase) of Sketchware and how implement it inside of project?How to can modify this code? Why say "@Deprecated", in Spanish I think to mean " Despreciado":

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import android.util.SparseBooleanArray;
import android.util.TypedValue;
import android.view.View;
import android.widget.ListView;

@Deprecated
	public void showMessage(String _s) {
		
	}
	
	@Deprecated
	public int getLocationX(View _v) {
		int _location[] = new int[2];
		_v.getLocationInWindow(_location);
		return _location[0];
	}
	
	@Deprecated
	public int getLocationY(View _v) {
		int _location[] = new int[2];
		_v.getLocationInWindow(_location);
		return _location[1];
	}
	
	@Deprecated
	public int getRandom(int _min, int _max) {
		Random random = new Random();
		return random.nextInt(_max - _min + 1) + _min;
	}
	
	@Deprecated
	public ArrayList<Double> getCheckedItemPositionsToArray(ListView _list) {
		ArrayList<Double> _result = new ArrayList<Double>();
		SparseBooleanArray _arr = _list.getCheckedItemPositions();
		for (int _iIdx = 0; _iIdx < _arr.size(); _iIdx++) {
			if (_arr.valueAt(_iIdx))
			_result.add((double)_arr.keyAt(_iIdx));
		}
		return _result;
	}
	
	@Deprecated
	public float getDip(int _input) {
		return TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, _input, getResources().getDisplayMetrics());
	}
	
	@Deprecated
	public int getDisplayWidthPixels() {
		return getResources().getDisplayMetrics().widthPixels;
	}
	
	@Deprecated
	public int getDisplayHeightPixels() {
		return getResources().getDisplayMetrics().heightPixels;
	}
}

_Sent from my Moto G Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hasrat-ali** [comment]
Enable this option to remove those deprecated codes

![Screenshot_2024-10-25-23-07-49-539_com sketchware remod-edit](https://github.com/user-attachments/assets/65c467be-6e43-4a60-8392-70a436434be9)

**Comment by oramirezd** [comment]
@hasrat-ali Yes, I know that.But I would to know the utilily and how to impmement into the project.?

_Sent from my Moto G Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
