### ISSUE TITLE
How can  compile Kotlin class with Sketchware Pro?

### ISSUE THREAD

**Issue by oramirezd** [Sketchware-Pro/Sketchware-Pro#1322]
I would want to know how to compile Kotling class with Sketchware Pro download from https://github.com/Sketchware-Pro/Sketchware-Pro/releases/download/v6.4.0-rc05/Sketchware.Pro.v6.4.0-rc05-minApi21.apk.  or  https://t.me/c/1642886773/3708.    When I try to created manually to say in my cuarrent Android phone 7.1.1 to " the action need Android +8".In my phone not compile that class but know the class with the icon. I installed  in other phone with Android +8 but not compile that Kotlin class becouse I do not know how to activate other choice for can compile.

_Sent from my Moto G Play using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hasrat-ali** [comment]
`minApi21` isn't able to compile `kotlin` classes.
You have to use `minApi26` variant with android 8+ os
