### ISSUE TITLE
Crashing compiled app

### ISSUE THREAD

**Issue by redowan178** [Sketchware-Pro/Sketchware-Pro#1324]
at com.vpn.ai.SketchLogger.startLogging(SketchLogger.java:80)
	at com.vpn.ai.SketchLogger$2.run(SketchLogger.java:68)

**Comment by hasrat-ali** [comment]
Can you show all `stack traces`?

**Comment by redowan178** [comment]
i Didn't get all stack trace

**Comment by vimalanandathero9-cyber** [comment]
> ```
> at com.vpn.ai.SketchLogger.startLogging(SketchLogger.java:80)
> at com.vpn.ai.SketchLogger$2.run(SketchLogger.java:68)
> ```

at com.vpn.ai.SketchLogger.startLogging(SketchLogger.java:80)
at com.vpn.ai.SketchLogger$2.run(SketchLogger.java:68)

**Comment by baitemirmutzapaazov1234-oss** [comment]
com.newsylvazzpanel.SketchLogger.startLogging(SketchLogger.java:54)

**Comment by baitemirmutzapaazov1234-oss** [comment]
https://t.me/ffpanelki/301

**Comment by baitemirmutzapaazov1234-oss** [comment]
Ти

Ьуьутките
