### ISSUE TITLE
Bug string.xml

### ISSUE THREAD

**Issue by innerloka** [Sketchware-Pro/Sketchware-Pro#1325]
**Describe the bug**
I found a new bug in the latest Sketchware nightly, where an error message for string.xml appears. Is there any way to fix it right away? I hope the modder can fix this bug soon.

Screenshoots
![Screenshot_20241026_224820](https://github.com/user-attachments/assets/98738b77-76d4-4bf9-a506-bcc3adbdf359)

Device and Sketchware Pro-related info:
 - Device: iQOO Z7
 - OS: Android 14
 - Sketchware Pro version: v6.4.0-SNAPSHOT-5f82376-minApi26

**Comment by hasrat-ali** [comment]
You can just delete that file, then create it with some string resources

**Comment by AsimJib** [comment]
You can simply delete that file or just add `<string name="app_name" translatable="true">YOUR_APP_NAME</string>` inside `<resources>`. That's all.

**Comment by innerloka** [comment]
Thank

**Comment by subhash16** [comment]
What happened if I delete the file?

**Comment by subhash16** [comment]
Same problem occurred again and again

**Comment by AsimJib** [comment]
> Same problem occurred again and again 

You must be doing something wrong. Try deleting the file.
