### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by laymintu** [Sketchware-Pro/Sketchware-Pro#1330]
**Describe the bug**
Resources Editor should have default!

**Expected behavior**
Don't automatically create them string.xml and colors.xml , let the users create it manually

**Screenshots**
![Screenshot_2024-10-27-17-05-30-767_com.sketchware.remod.jpg](https://github.com/user-attachments/assets/1d7570ec-ff4b-4857-8ea4-d4c9ad45674e)

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 13 Pro]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Comment by hasrat-ali** [comment]
duplicate of #1341
