### ISSUE TITLE
Trying to add a custom android.jar file won't work

### ISSUE THREAD

**Issue by HehehBoiii78** [Sketchware-Pro/Sketchware-Pro#1336]
**Description of the bug**
When I try to add a custom android.jar file in the "Build Settings" dialog, and press "Save", it doesn't work. When I reopen the "Build Settings" dialog, the custom android.jar text field resets to being empty. Because of this, I can't properly utilize Material 3 components.

**To Reproduce**
1. Open a project
2. Click on the "Configure" button next to the "Run" button
3. Click on "Build Settings"
4. Specify a path to a custom android.jar file
5. Click on Save
6. Reopen the "Build Settings" dialog
• Notice that the "Custom android.jar" text field resets to being empty.

**Expected behavior**
I expected the path to get saved for use in my project.

**Android and Sketchware Pro versions**
 - OS: Android 14, OneUI Core 6.1
 - Sketchware Pro version: v6.4.0-SNAPSHOT-5f82376-minApi26

**Additional context**
I am using the latest Nightly version of Sketchware Pro as of October 28th 2024, 12:04 AM.

**Comment by CarlosCMD** [comment]
Did you include the full path (e.g. /storage/emulated/0/Path/To/android.jar)?

**Comment by HehehBoiii78** [comment]
> Did you include the full path (e.g. /storage/emulated/0/Path/To/android.jar)?

@CarlosCMD Yes, I have even done it before with older versions of Sketchware Pro.

**Comment by HehehBoiii78** [comment]
> Did you include the full path (e.g. /storage/emulated/0/Path/To/android.jar)?

@CarlosCMD Yes, I have even done it before with older versions of Sketchware Pro.

**Comment by RoyTheReal** [comment]
Yes, I have this issue too. It doesn't save what you input into the dialog.
