### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by KrishnaVyshak** [Sketchware-Pro/Sketchware-Pro#134]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

```

**Comment by JavkhlanK** [comment]
interesting, it doesn't tell why it failed.

**Comment by ilyassesalama** [comment]
Make sure you have the latest changes from the repo, some typos prevented a successful build before.

**Comment by AlucardTN** [comment]
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 31s
> ```

you're missing some jar files, which is the sketchware dex, use mt manager to convert dex to jar and use them in android studio to build a modded sketchware pro

**Comment by KrishnaVyshak** [comment]
K, let me try...

**Comment by ilyassesalama** [comment]
This thread will be closed after 3 days if there are no new updates.
