### ISSUE TITLE
Strings.xml error generated wrong xml type

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1341]
**Describe the bug**
/storage/emulated/0/.sketchware/data/603/files/resource/values/strings.xml:0: error: xml parser error: no element found.
/storage/emulated/0/.sketchware/data/603/files/resource/values/strings.xml: error: file failed to compile.

**To Reproduce**
When comile the app

**Expected behavior**

**Screenshots**
![Screenshot_20241030-210429](https://github.com/user-attachments/assets/b1f55b27-b0ad-4d2a-afdb-fbfde2b73852)

Device and Sketchware Pro-related info:
 - Device: [All]
 - OS: [All]
 - Sketchware Pro version: [v6.4.0-SNAPSHOT-7633197-minApi26]

![1000051464](https://github.com/user-attachments/assets/45687084-3feb-4683-b7e7-69aebb51a008)

**Comment by AsimJib** [comment]
Duplicate bug report. This is not even a bug actually. Why depend on the generated file format? Edit the file and add as per your requirement.

Complete file format looks like :

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name" translatable="true">YOUR_APP_NAME</string>
</resources>`

**Comment by subhash16** [comment]
> Duplicate bug report. This is not even a bug actually. Why depend on the generated file format? Edit the file and add as per your requirement.
> 
> Complete file format looks like :
> 
> `<?xml version="1.0" encoding="utf-8"?> <resources> <string name="app_name" translatable="true">YOUR_APP_NAME</string> </resources>`

You even don't know which one is bug

**Comment by AsimJib** [comment]
It's your incapability that you don't know how to edit that tag and use it. It's working perfectly for all. Why not for you??

**Comment by subhash16** [comment]
> It's your incapability that you don't know how to edit that tag and use it. It's working perfectly for all. Why not for you??

I know that's why I mentioned

**Comment by elfilibusterismo** [comment]
Fixed in https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1348

**Comment by subhash16** [comment]
Thank you and @AsimJib is your in capability Provoled.

**Comment by AsimJib** [comment]
> Thank you and @AsimJib is your in capability Provoled.

I didn't mean to say that. I just tried to tell you that you must try and not just complain every time.
