### ISSUE TITLE
"queries" is causing my app to stop working. 

### ISSUE THREAD

**Issue by abrihamdemisse** [Sketchware-Pro/Sketchware-Pro#1344]
As the title says:

My app stoped working saying "'my app name' has stopped" working after running it with version:
`v6.4.0-SNAPSHOT-92102d7-minApi26`
The difference in the manifest is just the "queries" tag added by sketchware pro by default,  and I couldn't figure out why it is being added,  other projects don't have it. 

What can I do pls help me guys?

**Comment by AsimJib** [comment]
Here is an example app manifest below. Where do you see the queries tag added automatically??
`
<manifest
	xmlns:android="http://schemas.android.com/apk/res/android"
	package="com.my.newproject28">
	<application
		android:allowBackup="true"
		android:icon="@drawable/app_icon"
		android:label="@string/app_name"
		android:name=".SketchApplication"
		android:requestLegacyExternalStorage="true"
		android:usesCleartextTraffic="true"
		android:theme="@style/AppTheme">
		<activity
			android:name=".MainActivity"
			android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout"
			android:hardwareAccelerated="true"
			android:supportsPictureInPicture="true"
			android:screenOrientation="portrait"
			android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity
			android:name=".DebugActivity"
			android:screenOrientation="portrait" />
		<uses-library
			android:name="org.apache.http.legacy"
			android:required="false" />
	</application>
</manifest>
`

**Comment by elfilibusterismo** [comment]
> Here is an example app manifest below. Where do you see the queries tag added automatically??
> 
> `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.my.newproject28"> <application android:allowBackup="true" android:icon="@drawable/app_icon" android:label="@string/app_name" android:name=".SketchApplication" android:requestLegacyExternalStorage="true" android:usesCleartextTraffic="true" android:theme="@style/AppTheme"> <activity android:name=".MainActivity" android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout" android:hardwareAccelerated="true" android:supportsPictureInPicture="true" android:screenOrientation="portrait" android:exported="true"> <intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity> <activity android:name=".DebugActivity" android:screenOrientation="portrait" /> <uses-library android:name="org.apache.http.legacy" android:required="false" /> </application> </manifest>`

Am I supposed to see queries tag in here? I don't see nothing

**Comment by abrihamdemisse** [comment]
> > Here is an example app manifest below. Where do you see the queries tag added automatically??
> > `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.my.newproject28"> <application android:allowBackup="true" android:icon="@drawable/app_icon" android:label="@string/app_name" android:name=".SketchApplication" android:requestLegacyExternalStorage="true" android:usesCleartextTraffic="true" android:theme="@style/AppTheme"> <activity android:name=".MainActivity" android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout" android:hardwareAccelerated="true" android:supportsPictureInPicture="true" android:screenOrientation="portrait" android:exported="true"> <intent-filter> <action android:name="android.intent.action.MAIN" /> <category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity> <activity android:name=".DebugActivity" android:screenOrientation="portrait" /> <uses-library android:name="org.apache.http.legacy" android:required="false" /> </application> </manifest>`
> 
> Am I supposed to see queries tag in here? I don't see nothing

![Screenshot_20241101-191027_Sketchware Pro](https://github.com/user-attachments/assets/83a7b8fe-67c2-4b25-bff1-b80e5385ede6)

below permissions and above application tag

**Comment by abrihamdemisse** [comment]
> I see!
> 
> These queries are added to ensure that the app can check for browsers or services that support HTTPS links and Custom Tabs, improving web interaction without violating Android's visibility requirements.
> 
> This is likely not the reason for your app to stop responding.

That is only the difference when I run it with different version

**Comment by hasrat-ali** [comment]
Can  you send that project reproduce the issue
