### ISSUE TITLE
Material Widgets (like Sketchware FU)

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1349]
**Material Widget Support*
Material You is a great way of making the app UI beautiful. But Sketchware Pro doesn't have this feature. Please Implement it if anyone can

**Comment by laymintu** [comment]
I want to download **Sketchware Fu** give me the link plz

**Comment by StudioAsInc** [comment]
> I want to download **Sketchware Fu** give me the link plz

https://t.me/sketchwarefu/2

**Comment by ilyassesalama** [comment]
Screenshots would help. No one is going to install another version of Sketchware just to understand what you're talking about.

**Comment by trindadedev13** [comment]
> Screenshots would help. No one is going to install another version of Sketchware just to understand what you're talking about.

Sketchware FU have More Material Widgets, like MaterialSwitch, material chip etc....
Sketchware FU have some colors system in colors palette
sketchware fu have option to enable dynamic colors
and more things related with material 3/you

**Comment by ilyassesalama** [comment]
> > Screenshots would help. No one is going to install another version of Sketchware just to understand what you're talking about.
> 
> Sketchware FU have More Material Widgets, like MaterialSwitch, material chip etc.... Sketchware FU have some colors system in colors palette sketchware fu have option to enable dynamic colors and more things related with material 3/you

Why can't the modder who worked on that version contribute to this project instead?

**Comment by trindadedev13** [comment]
> > > Screenshots would help. No one is going to install another version of Sketchware just to understand what you're talking about.
> > 
> > 
> > Sketchware FU have More Material Widgets, like MaterialSwitch, material chip etc.... Sketchware FU have some colors system in colors palette sketchware fu have option to enable dynamic colors and more things related with material 3/you
> 
> Why can't the modder who worked on that version contribute to this project instead?

we will never know my dear

**Comment by PranavPurwar** [comment]
No need to add more views. We already have support for it.
![Screenshot_20241110-113604_Sketchware Pro](https://github.com/user-attachments/assets/5883c0d6-31c2-45ad-8490-608952e125f4)

**Comment by trindadedev13** [comment]
@PranavPurwar 
It's not the same thing, but anyway, now we have the Widget Maker, so it is not so necessary to add new Views

**Comment by StudioAsInc** [comment]
> @PranavPurwar It's not the same thing, but anyway, now we have the Widget Maker, so it is not so necessary to add new Views

Switches like Sketchware have it self
