### ISSUE TITLE
Auto save custom blocks through restore

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1351]
Sometime other people share me. their pro.
Ject and date contains a custo

**Comment by waelchateur** [comment]
i guess this could be if they fix the backup logic since backup didnt save block type so this will bring nothing to user so saving Custom blocks from projects isnt a good idea unless they update the swb backup logic

**Comment by ilyassesalama** [comment]
Isn't this already existing?

**Comment by trindadedev13** [comment]
use this:
![Screenshot_20241128-220824](https://github.com/user-attachments/assets/4989e4f3-4ac1-4c60-a323-b9514892c570)
