### ISSUE TITLE
Edit More Block

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1354]
Please provide a way to edit existing more blocks. I need some more blocks to edit in future updates. I found that there is no way to edit existing more block. So I need to delete and add a new modified version of more block again from scratch.

I request you to add a way to edit existing more blocks.

**Comment by ilyassesalama** [comment]
This idea has been circulating for years now, but there are a lot of things that need to be taken into consideration before doing such a thing to maintain the stability of projects.

**Comment by hasrat-ali** [comment]
You can just copy your blocks to collection then create new moreblock .
