### ISSUE TITLE
No works block menager

### ISSUE THREAD

**Issue by JoroslavDev** [Sketchware-Pro/Sketchware-Pro#1378]
**Describe the bug**
Please give us a clear and concise description of what the bug is.

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: Honor 20 lite
 - OS: Android 9
 - Sketchware Pro version: 6.3.0

https://github.com/user-attachments/assets/76b9325c-4d15-4ee2-a746-a12e9dff66b3

**Additional context**
No works block menager

**Comment by trindadedev13** [comment]
can you try latest build and try again?

**Comment by trindadedev13** [comment]
update your sketchware
