### ISSUE TITLE
Switch saving issue

### ISSUE THREAD

**Issue by AsimJib** [Sketchware-Pro/Sketchware-Pro#1388]
![Screenshot_20241116-141758](https://github.com/user-attachments/assets/c19d32c4-4922-40b5-924b-8844f8d0424a)
These switches does not stay at on position after re-open Sketchware Pro.

**Comment by Mustiy0** [comment]
Fixed
 @trindadedev13 can you close it?

**Comment by trindadedev13** [comment]
fixed with https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1432.
