### ISSUE TITLE
Duplicate custom activity

### ISSUE THREAD

**Issue by laymintu** [Sketchware-Pro/Sketchware-Pro#1392]
![IMG_20241119_100217_785.jpg](https://github.com/user-attachments/assets/b85e304f-5927-4fcf-9fdd-d08737f681a0)

![IMG_20241119_100217_543.jpg](https://github.com/user-attachments/assets/cf33031e-e2a6-4848-872b-6c6421802829)

**Comment by hasrat-ali** [comment]
How we can reproduce it?
