### ISSUE TITLE
Slow down on RUN project 

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1397]
**Describe the bug**
When I build a project its slow down the process on Deleting temporary files 

**Screenshots**
![Screenshot_20241120-125302~2](https://github.com/user-attachments/assets/46dfcb09-07bd-4d3e-ad6c-bad682c33694)

Device and Sketchware Pro-related info:
 - Device: [e.g. All]
 - OS: [e.g. All]
 - Sketchware Pro version: [ v6.4.0-SNAPSHOT- 9e1cf20 -minApi26 ]

**Additional context**
v6.4.0-SNAPSHOT- 620db06 -minApi26
This version working fine on same project 
After this version problem occurred.

**Comment by laymintu** [comment]
Same before but **use the latest version **

**Comment by subhash16** [comment]
> Same before but **use the latest version **

Tested on that version 9e1cf20

**Comment by elfilibusterismo** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1426
