### ISSUE TITLE
Need Backup & Restore Support for Java & Kotlin Files 

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1404]
sometimes i design code here to use as shorcuts.

so we need to manually copy paste this for other apps everytime.
please make a backup restore support for this 
like "collection"

![Screenshot_20241121-175402.png](https://github.com/user-attachments/assets/6d5493a9-d675-4233-b398-4eac9a68f93a)

**Comment by Bobur-777** [comment]
Why you need this option?

**Comment by araafroyall** [comment]
i makes long codes in java class and use them as shorcuts for different activities and apps .

so i need this

**Comment by Bobur-777** [comment]
> i makes long codes in java class and use them as shorcuts for different activities and apps .
> 
> so i need this 
I don't know it is useful or not, but you can mske your classes as library 🙃

**Comment by araafroyall** [comment]
i dont know how to make them as library. i uses only classes. 
and it will be useful for me .

Lets see example here , i need this in many app so i need backup option



```java 
package Cleaner.Royall;

import android.app.Activity;
import android.content.Context;
import android.content.DialogInterface;
import android.widget.Toast;
import android.widget.TextView;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.View;
import android.content.SharedPreferences;

public class SketchwareUtil {

    public static void showMessage(Context _context, String _s) {
        Toast.makeText(_context, _s, Toast.LENGTH_SHORT).show();
    }


    public static void Dialog(Activity a, String title, String msg) {
    new AlertDialog.Builder(a)
        .setTitle(title).setMessage(msg)
        .setIcon(title.equals("𝗜𝗻𝗳𝗼𝗿𝗺𝗮𝘁𝗶𝗼𝗻") ? R.drawable.information :
                 title.equals("𝗦𝘂𝗰𝗲𝘀𝘀") ? R.drawable.check :
                 title.equals("𝗘𝗿𝗿𝗼𝗿") ? R.drawable.icon_1 : android.R.drawable.ic_dialog_alert)
        .setPositiveButton("OK", (d, w) -> {}).show();
    }
    

    public static void Error(Activity activity, TextView result) {
     if (result != null) {
        String resultText = result.getText().toString();

        if (resultText.contains("Permission denied")) {
            Dialog(activity, "𝗘𝗿𝗿𝗼𝗿", "Root Permission Denied");

        } else if (resultText.contains("notfounded")) {
            Dialog(activity, "𝗘𝗿𝗿𝗼𝗿", "Internal Error, Please Contact Developer to Resolve this issue");

        } else {
            try {
                String command = "su";
                Runtime.getRuntime().exec(command);

                if (resultText.contains("araafroyall")) {
                    Dialog(activity, "𝗘𝗿𝗿𝗼𝗿", "Something issue in Premium\nOr Trial Expired\n\nActivate Premium to Use App");
                } else {
                    Dialog(activity, "𝗘𝗿𝗿𝗼𝗿", "Something went Wrong");
                }
            } catch (Exception e) {
                Dialog(activity, "𝗘𝗿𝗿𝗼𝗿", "Root Access Not Found or Hidden");
            }
        }

        result.setText(" ");
     }
    }
    
    
    
    public static void ViewIcon(TextView view, Context context, int iconResId) {
    view.setCompoundDrawablesWithIntrinsicBounds(context.getResources().getDrawable(iconResId), null, null, null);
    }
   
    
    
    public static void RequirePremium(Activity a) {
    new AlertDialog.Builder(a)
        .setTitle("𝐑𝐞𝐪𝐮𝐢𝐫𝐞 𝐏𝐫𝐞𝐦𝐢𝐮𝐦").setMessage("This is a Premium feature \nPurchase Premium to use ").setIcon(R.drawable.crown)
        .setPositiveButton("🛸 Get Premium", (d, w) -> a.startActivity(new Intent(a, PremiumActivity.class)))
        .setNegativeButton("Cancel", (d, w) -> {}).show();
    }
    
    
    public static void Themer(View targetView, SharedPreferences preferences) {
        int color = getValidColor(preferences.getString("colorcode", ""));
        int radius = getValidRadius(preferences.getString("radius", ""));
        targetView.setBackground(new GradientDrawable() {
            public GradientDrawable getIns(int r, int c) {
                setCornerRadius(r);
                setColor(c);
                return this;
            }
        }.getIns(radius, color));
    }

    private static int getValidColor(String colorCode) {
        try { return colorCode.startsWith("#") && (colorCode.length() == 7 || colorCode.length() == 9) ? Color.parseColor(colorCode) : 0xFFE8F5E9; }
        catch (Exception e) { return 0xFFE8F5E9; }
    }

    private static int getValidRadius(String radiusString) {
        try { return Integer.parseInt(radiusString); }
        catch (Exception e) { return 15; }
    }
    
    
    public static void showCustomDialog(Activity a, String t, String m, int i, boolean c, Runnable ok) {
     new AlertDialog.Builder(a).setTitle(t).setMessage(m).setIcon(i).setCancelable(c)
        .setPositiveButton("OK", (d, w) -> { if (ok != null) ok.run(); }).show();
    }
    
    public static void displayDialog(Activity a, String t, String m, int i, boolean c, Runnable ok, Runnable cancel) {
     new AlertDialog.Builder(a).setTitle(t).setMessage(m).setIcon(i).setCancelable(c)
        .setPositiveButton("OK", (d, w) -> { if (ok != null) ok.run(); })
        .setNegativeButton("Cancel", (d, w) -> { if (cancel != null) cancel.run(); }).show();
    }
    
    public static void TitleIcon(android.app.Activity activity, int drawableRes, String titleText, String subtitleText) {
     try {
        android.app.ActionBar ab = activity.getActionBar();
        if (ab != null) {
            ab.setDisplayShowHomeEnabled(true);
            ab.setIcon(drawableRes);
            ab.setDisplayShowTitleEnabled(false);
            
            TextView customTitle = new TextView(activity);
            customTitle.setText(titleText);
            customTitle.setTextSize(20);
            ab.setCustomView(customTitle);
            ab.setDisplayShowCustomEnabled(true);
            if (subtitleText != null) {
                ab.setSubtitle(subtitleText);
            } else {
                ab.setSubtitle(null);
            }
        }
     } catch (Exception e) {
        // ignore silently
     }
    }
    
}

```

**Comment by Bobur-777** [comment]
> i dont know how to make them as library. i uses only classes. 
> and it will be useful for me .
> 
> Lets see example here , i need this in many app so i need backup option
> 
> 
> 
> ```java 
> package com.my.newproject2;
> 
> import android.content.Context;
> import android.util.Base64;
> import java.io.BufferedReader;
> import java.io.InputStreamReader;
> import java.nio.charset.StandardCharsets;
> import javax.crypto.Cipher;
> import javax.crypto.SecretKey;
> import javax.crypto.spec.SecretKeySpec;
> import javax.crypto.spec.IvParameterSpec;
> 
> public class AssetsPro {
> 
>     private static final String DEFAULT_KEY = "XXXXXXXXX";
>     public static final String ENCRYPT = "encrypt", DECRYPT = "decrypt";
> 
>     public static String getValue(Context context, String fileName, String mode) {
>         try {
>             if (fileName.startsWith("/")) {
>                 fileName = fileName.substring(1);
>             }
> 
>             BufferedReader reader = new BufferedReader(new InputStreamReader(context.getAssets().open(fileName)));
>             StringBuilder content = new StringBuilder();
>             String line;
>             while ((line = reader.readLine()) != null) content.append(line).append("\n");
>             return "SECURE".equals(mode) ? decryptData(content.toString().trim(), DEFAULT_KEY) : content.toString().trim();
>         } catch (Exception e) {
>             return "notfounded";
>         }
>     }
> 
>     private static String decryptData(String encryptedData, String key) {
>         try {
>             if (encryptedData.startsWith("$IV")) {
>                 encryptedData = encryptedData.substring(3);
>                 byte[] combined = Base64.decode(encryptedData, Base64.DEFAULT);
>                 byte[] ivBytes = java.util.Arrays.copyOfRange(combined, 0, 16);
>                 byte[] encryptedBytes = java.util.Arrays.copyOfRange(combined, 16, combined.length);
> 
>                 Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
>                 cipher.init(Cipher.DECRYPT_MODE, genKey(key), new IvParameterSpec(ivBytes));
> 
>                 byte[] decryptedBytes = cipher.doFinal(encryptedBytes);
>                 return new String(decryptedBytes, StandardCharsets.UTF_8);
>             } else {
>                 Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
>                 cipher.init(Cipher.DECRYPT_MODE, genKey(key));
>                 return new String(cipher.doFinal(Base64.decode(encryptedData, Base64.DEFAULT)), StandardCharsets.UTF_8);
>             }
>         } catch (Exception e) {
>             return "notfounded";
>         }
>     }
> 
>     public static void WithIv(android.app.Activity act, String inp, String key, String txtId, String action, Runnable onComplete, Runnable onError) {
>         try {
>             Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
>             if (ENCRYPT.equals(action)) {
>                 byte[] ivBytes = new byte[16];
>                 new java.security.SecureRandom().nextBytes(ivBytes);
>                 cipher.init(Cipher.ENCRYPT_MODE, genKey(key), new IvParameterSpec(ivBytes));
>                 byte[] encryptedBytes = cipher.doFinal(inp.getBytes(StandardCharsets.UTF_8));
> 
>                 byte[] combined = new byte[ivBytes.length + encryptedBytes.length];
>                 System.arraycopy(ivBytes, 0, combined, 0, ivBytes.length);
>                 System.arraycopy(encryptedBytes, 0, combined, ivBytes.length, encryptedBytes.length);
> 
>                 updTxt(act, txtId, "$IV" + Base64.encodeToString(combined, Base64.DEFAULT));
>             } else if (DECRYPT.equals(action)) {
>                 if (inp.startsWith("$IV")) {
>                     byte[] combined = Base64.decode(inp.substring(3), Base64.DEFAULT);
>                     byte[] ivBytes = java.util.Arrays.copyOfRange(combined, 0, 16);
>                     byte[] encryptedBytes = java.util.Arrays.copyOfRange(combined, 16, combined.length);
> 
>                     cipher.init(Cipher.DECRYPT_MODE, genKey(key), new IvParameterSpec(ivBytes));
>                     byte[] decryptedBytes = cipher.doFinal(encryptedBytes);
>                     updTxt(act, txtId, new String(decryptedBytes, StandardCharsets.UTF_8));
>                 } else updTxt(act, txtId, "notfounded");
>             }
>             if (onComplete != null) act.runOnUiThread(onComplete);
>         } catch (Exception e) {
>             updTxt(act, txtId, "notfounded");
>             if (onError != null) act.runOnUiThread(onError);
>         }
>     }
> 
>     public static void WithNoIv(android.app.Activity act, String inp, String key, String txtId, String action, Runnable onComplete, Runnable onError) {
>         try {
>             Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
>             cipher.init(ENCRYPT.equals(action) ? Cipher.ENCRYPT_MODE : Cipher.DECRYPT_MODE, genKey(key));
>             byte[] processedBytes = cipher.doFinal(ENCRYPT.equals(action) ? inp.getBytes(StandardCharsets.UTF_8) : Base64.decode(inp, Base64.DEFAULT));
>             updTxt(act, txtId, ENCRYPT.equals(action) ? Base64.encodeToString(processedBytes, Base64.DEFAULT) : new String(processedBytes, StandardCharsets.UTF_8));
> 
>             if (onComplete != null) act.runOnUiThread(onComplete);
>         } catch (Exception e) {
>             updTxt(act, txtId, "notfounded");
>             if (onError != null) act.runOnUiThread(onError);
>         }
>     }
> 
>     private static void updTxt(android.app.Activity act, String txtId, String txt) {
>         act.runOnUiThread(() -> {
>             android.widget.TextView textView = act.findViewById(act.getResources().getIdentifier(txtId, "id", act.getPackageName()));
>             if (textView != null) textView.setText(txt);
>         });
>     }
> 
>     private static SecretKey genKey(String pwd) throws Exception {
>         return new SecretKeySpec(java.security.MessageDigest.getInstance("SHA-256").digest(pwd.getBytes(StandardCharsets.UTF_8)), "AES");
>     }
> }
> ```
> 
> 
> 

Or just create one folder and add your classes them for example /Downloads/My classes/ so you can easily find and import

**Comment by araafroyall** [comment]
i can't make folder. i makes classes directly in app so i need backup option .

why you not understanding

**Comment by Bobur-777** [comment]
> i can't make folder. i makes classes directly in app so i need backup option .
> 
> why you not understanding 

I understand

**Comment by elfilibusterismo** [comment]
Seems not necessary you can do this instead
https://github.com/user-attachments/assets/35465c6c-2c38-4878-83b5-972cf3c42c20
