### ISSUE TITLE
Need widget color back 

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1405]
Widgets was better and faster to use in stable versions 

on nightly version or material design it has only one color.

please give us back that color

![Screenshot_20241121-180226.png](https://github.com/user-attachments/assets/a85bdf84-eb9b-4433-9a1e-642d9daaad8e)

![Screenshot_20241121-180022.png](https://github.com/user-attachments/assets/2e586657-6ee8-4a35-a6e4-217ea0f71035)

**Comment by laymintu** [comment]
Its nice bro no need to change

**Comment by ilyassesalama** [comment]
Just get used to it. You'll find it better if your phone supports Material You.

**Comment by araafroyall** [comment]
> Just get used to it. You'll find it better if your phone supports Material You.

i know its better but having colored one will speed up widget selection . hope you understand

**Comment by ilyassesalama** [comment]
> i know its better but having colored one will speed up widget selection . hope you understand
To be honest, I agree with you with this one. But I don't think we'll do that.

**Comment by araafroyall** [comment]
i think you need to talk to different contributors about this.

widget color is too important for me for speedily selection
