### ISSUE TITLE
Need Shorcuts for Widget Selection

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1407]
sometime we have hundreds of widgets like textview or buttons 

and we need to select one so it is very time consuming to find and select particular one.

we need such feature which sort the list by button, if there is need to textview than sort by textview 

we need here (see screenshot)

![Screenshot_20241121-182626.png](https://github.com/user-attachments/assets/9cf038a8-9f2e-4e68-9734-445df2376c60)

**Comment by laymintu** [comment]
Search feature??

**Comment by araafroyall** [comment]
> Search feature??

yes its may be a search or sortby feature

**Comment by Mustiy0** [comment]
Added in #1428
@trindadedev13 sorry for the pings.
