### ISSUE TITLE
App Stuck on 'Deleting Temporary Files' in Latest Sketchware Nightly Version

### ISSUE THREAD

**Issue by sketchlibpro** [Sketchware-Pro/Sketchware-Pro#1414]
**Describe the bug**
When running a project in the latest Sketchware Pro Nightly version, the process gets stuck on "Deleting temporary files" and does not proceed further. This issue only occurs in the latest version, while the previous version from a week ago works fine.

**To Reproduce**

1. Open Sketchware Pro and update to the latest Nightly version.

2. Open any project.

3. Run the project.

4. Notice that the process stucks at "Deleting temporary files" and does not continue.

**Expected behavior**
The project should successfully pass the "Deleting temporary files" step and execute normally.

**Screenshots**
![Screenshot_20241122_233049_Sketchware Pro](https://github.com/user-attachments/assets/800c04c9-72a3-44ee-abb8-af01d0087174)

**Device and Sketchware Pro-related info:**
** - Device:** Samsung Galaxy A14 5G
** - OS:** Android 14
 **- Sketchware Pro version:** v6.4.0-SNAPSHOT-39196eb-minApi26

**Additional context**
This issue is a major blocker as it prevents projects from running entirely. It appears to be specific to the latest Nightly version, as the version released last week works without any problems. Addressing this should be a high priority.

**Comment by YUGGI200** [comment]
In addition, this bug works only with big projects, and smaller projects with 2-3 activities and libs can't reproduce this bug


you'll need big projects to reproduce, and 7 people until now reported this in telegram

i have 2 big projects from different people which can help to reproduce this bug, anyone wants to reproduce it can dm me on telegram @yuggi200

**Comment by laymintu** [comment]
> **Describe the bug**
> When running a project in the latest Sketchware Pro Nightly version, the process gets stuck on "Deleting temporary files" and does not proceed further. This issue only occurs in the latest version, while the previous version from a week ago works fine.
> 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open Sketchware Pro and update to the latest Nightly version.
> 
> 2. Open any project.
> 
> 3. Run the project.
> 
> 4. Notice that the process stucks at "Deleting temporary files" and does not continue.
> 
> 
> 
> 
> **Expected behavior**
> The project should successfully pass the "Deleting temporary files" step and execute normally.
> 
> 
> **Screenshots**
> ![Screenshot_20241122_233049_Sketchware Pro](https://github.com/user-attachments/assets/800c04c9-72a3-44ee-abb8-af01d0087174)
> 
> 
> **Device and Sketchware Pro-related info:**
> ** - Device:** Samsung Galaxy A14 5G
> ** - OS:** Android 14
>  **- Sketchware Pro version:** v6.4.0-SNAPSHOT-39196eb-minApi26
> 
> **Additional context**
> This issue is a major blocker as it prevents projects from running entirely. It appears to be specific to the latest Nightly version, as the version released last week works without any problems. Addressing this should be a high priority.
> 

Same 😑

**Comment by laymintu** [comment]
Same 🙂

**Comment by PranavPurwar** [comment]
Please share any one of such projects where this issue occurs for testing.

**Comment by sketchlibpro** [comment]
I've noticed that Sketchware is able to run the projects for which it generates the source code without getting stuck. However, for projects where it cannot generate the source code, they get stuck on 'deleting temporary files' and fail to run. I believe this information will help in fixing the issue

**Comment by laymintu** [comment]
> Please share any one of such projects where this issue occurs for testing.

You can download a big project on sketchub and test it,
Please fix it, **we can't wait an hour to build apk**

**Comment by subhash16** [comment]
#1397

**Comment by elfilibusterismo** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/pull/1426
