### ISSUE TITLE
Need built-in java class Manager

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1417]
i don't require these two in my project by default.

i think there should be an option to manage , remove , modify or edit this 

![IMG_20241123_082156_576.jpg](https://github.com/user-attachments/assets/04e9fa3f-ff01-468d-a273-10b8b64890e5)

**Comment by araafroyall** [comment]
I have found a way to remove this .🙂

**Comment by trindadedev13** [comment]
FileUtil is only added if you use something related to files

**Comment by laymintu** [comment]
> I have found a way to remove this .🙂

You can remove it by MT manager

**Comment by elfilibusterismo** [comment]
See https://github.com/Sketchware-Pro/Sketchware-Pro/pull/961

**Comment by araafroyall** [comment]
>  FileUtil is only added if you use something related to files

you need to think twice. 

i dont add any of that components. still they added.

also if i need a tost than it will add full sketchutil which is never required.

**Comment by araafroyall** [comment]
> > I have found a way to remove this .🙂
> 
> You can remove it by MT manager 

no. i need option within sketchware pro

**Comment by araafroyall** [comment]
> See https://github.com/Sketchware-Pro/Sketchware-Pro/pull/961


we need to remove. as we dont use if any of their components than it auto imbeded and causing 20 kb app to 40 kb .

**Comment by elfilibusterismo** [comment]
> > See #961
> 
> we need to remove. as we dont use if any of their components than it auto imbeded and causing 20 kb app to 40 kb .

Did you even read the comments?

**Comment by araafroyall** [comment]
> > > See #961
> > 
> > we need to remove. as we dont use if any of their components than it auto imbeded and causing 20 kb app to 40 kb .
> 
> Did you even read the comments?

have you checked twice. if even any respected component block not added still it including that fileutil.java

**Comment by araafroyall** [comment]
ok no problem. i still can remove or edit them . i have a method or idea for this
