### ISSUE TITLE
Appcompat cause parsing error

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1419]
**Describe the bug**
When turned on appcompat and RUN the project cause below ss error 

**Screenshots**
![Screenshot_20241123-150303](https://github.com/user-attachments/assets/097e5c05-6a9c-4fd5-a22d-0fee4aa1eeee)

Device and Sketchware Pro-related info:
 - Device: [e.g. All]
 - OS: [e.g. All]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT- d9cbc47 -minApi26]

**Comment by trindadedev13** [comment]
can you try latest and tell me?

**Comment by subhash16** [comment]
Ok Sir I will check soon

**Comment by subhash16** [comment]
App build successfully but crash when open the app

**Comment by subhash16** [comment]
After this version 620db06 Appcompat creating problems
