### ISSUE TITLE
Stucked on "Deleting temporarily files..."

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1429]
**Describe the bug**
After installing the leatest debug from workflows, when I run my project (compile) it stucked at "Deleting temporarily files..." always. But when I use old workflows apk of Sketchware or use the official basic version of Sketchware it works. I waited more that 10 minutes but still stucked.

**Overall**
New workflows release of Sketchware Pro stucked at "Deleting temp. Files..."

**Comment by PranavPurwar** [comment]
fixed with #1426
