### ISSUE TITLE
'Sketchware" like material switch and others

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1430]
**What I want**
![IMG_20241125_010349_087](https://github.com/user-attachments/assets/d5590e3e-f0f3-4320-b889-b8940d552ff7)

On the image you can see the switch of Sketchware Pro... I want this type of switch and other materials things like Sketchware on Sketchware pro

**Comment by waelchateur** [comment]
easy since creat custom widgets featue added to sk we can now create our own : try this 

com.google.android.material.materialswitch.MaterialSwitch

**Comment by elfilibusterismo** [comment]
Use create custom widget
