### ISSUE TITLE
Avoid Timer-Caused Crashes

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1433]
I recommend adding this code before `runOnUiThread(new Runnable() {` to avoid errors when Activity is null after being destroyed or for some reason:

         if (getActivity() == null) {
                try {
                    _timer.cancel();
                } catch (Exception _err) {
                
                }
                return;
            }

**Comment by hasrat-ali** [comment]
You can make custom block for that. No need to make it built-in
