### ISSUE TITLE
⚠️ App crashes when app compact is on

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1439]
# 🚨 App Crash Issue 🚨

Hey there! 👋

I'm facing a **problem** with the app I made using Sketchware Pro. The app crashes every time I open it.

## 🛠️ Bug Faced On/Tested On 🛠️
- `v6.4.0-SNAPSHOT-4de627c-minApi26`
- `v6.4.0-SNAPSHOT-b02fe61-minApi26`

## 💡 When Does This Occur? 💡
When **App Compact and Design** is ON

## 🔍 When It Does Not Occur? 🔍
When I turn off the **App Compact and Design**

## 🎥 Example Video 🎥
Check out this [example video (RAW/uncut)](https://streamable.com/hpnmbc). Note: Hold the video to play on 2x (sorry for the long video, I couldn't edit it).

Thank you so much for looking into this! 🙏

**Comment by StudioAsInc** [comment]
@PranavPurwar Fix it

**Comment by subhash16** [comment]
Duplicate issue see #1419

**Comment by StudioAsInc** [comment]
> Duplicate issue see #1419 

Is it fixed, or you are telling me to wait.??

**Comment by subhash16** [comment]
> > Duplicate issue see #1419
> 
> Is it fixed, or you are telling me to wait.??

Not fixed till now

**Comment by JelLee11** [comment]
So it's still not fix? I really like the newest nightly version but this is a huge problem

**Comment by StudioAsInc** [comment]
> > Duplicate issue see #1419
> 
> No, this is a different issue.

You are my personal fev... contributor, I always use your version. **of Sketchware Pro**

**Comment by hasrat-ali** [comment]
I removed those commit that are responsible for this. Try newer build.

**Comment by StudioAsInc** [comment]
> I removed those commit that are responsible for this. Try newer build.

**Is your newer build** or anyone's newer build?

**Comment by trindadedev13** [comment]
> > I removed those commit that are responsible for this. Try newer build.
> 
> **Is your newer build** or anyone's newer build?

If you download the only build available on Github or Nightly website, it will be available, or on telegram, download the latest apk.
