### ISSUE TITLE
Update Firebase codes

### ISSUE THREAD

**Issue by laymintu** [Sketchware-Pro/Sketchware-Pro#1442]
There were no errors when I used older versions, but when I updated tonight, I encountered many errors related to **Firebase**. Please fix it

(This is a screenshot)
l![Screenshot_2024-11-28-07-27-34-542_pro.sketchware.jpg](https://github.com/user-attachments/assets/31084f1c-bc9a-4fa7-8599-607ccb334fb4)

**Comment by laymintu** [comment]
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 38)
	import com.google.firebase.iid.FirebaseInstanceId;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import com.google.firebase.iid.FirebaseInstanceId cannot be resolved
----------
2. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 39)
	import com.google.firebase.iid.InstanceIdResult;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import com.google.firebase.iid.InstanceIdResult cannot be resolved
----------
3. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 147)
	fcm_onCompleteListener = new OnCompleteListener<InstanceIdResult>() {
	                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type new OnCompleteListener<InstanceIdResult>(){} must implement the inherited abstract method OnCompleteListener<InstanceIdResult>.onComplete(Task<InstanceIdResult>)
----------
4. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 147)
	fcm_onCompleteListener = new OnCompleteListener<InstanceIdResult>() {
	                                                ^^^^^^^^^^^^^^^^
InstanceIdResult cannot be resolved to a type
----------
5. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 149)
	public void onComplete(Task<InstanceIdResult> task) {
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Name clash: The method onComplete(Task<InstanceIdResult>) of type new OnCompleteListener<InstanceIdResult>(){} has the same erasure as onComplete(Task<TResult>) of type OnCompleteListener<TResult> but does not override it
----------
6. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 149)
	public void onComplete(Task<InstanceIdResult> task) {
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method onComplete(Task<InstanceIdResult>) of type new OnCompleteListener<InstanceIdResult>(){} must override or implement a supertype method
----------
7. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/MainActivity.java (at line 149)
	public void onComplete(Task<InstanceIdResult> task) {
	                            ^^^^^^^^^^^^^^^^
InstanceIdResult cannot be resolved to a type
----------
----------
8. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 47)
	import com.google.firebase.iid.FirebaseInstanceId;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import com.google.firebase.iid.FirebaseInstanceId cannot be resolved
----------
9. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 48)
	import com.google.firebase.iid.InstanceIdResult;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import com.google.firebase.iid.InstanceIdResult cannot be resolved
----------
10. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 381)
	fcm_onCompleteListener = new OnCompleteListener<InstanceIdResult>() {
	                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type new OnCompleteListener<InstanceIdResult>(){} must implement the inherited abstract method OnCompleteListener<InstanceIdResult>.onComplete(Task<InstanceIdResult>)
----------
11. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 381)
	fcm_onCompleteListener = new OnCompleteListener<InstanceIdResult>() {
	                                                ^^^^^^^^^^^^^^^^
InstanceIdResult cannot be resolved to a type
----------
12. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 383)
	public void onComplete(Task<InstanceIdResult> task) {
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Name clash: The method onComplete(Task<InstanceIdResult>) of type new OnCompleteListener<InstanceIdResult>(){} has the same erasure as onComplete(Task<TResult>) of type OnCompleteListener<TResult> but does not override it
----------
13. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 383)
	public void onComplete(Task<InstanceIdResult> task) {
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method onComplete(Task<InstanceIdResult>) of type new OnCompleteListener<InstanceIdResult>(){} must override or implement a supertype method
----------
14. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 383)
	public void onComplete(Task<InstanceIdResult> task) {
	                            ^^^^^^^^^^^^^^^^
InstanceIdResult cannot be resolved to a type
----------
15. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 722)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
16. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 722)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
17. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 1520)
	binding.cardview1.setRadius((float)30);
	^^^^^^^
binding cannot be resolved
----------
18. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/HomeActivity.java (at line 1521)
	binding.cardview1.setCardElevation((float)0);
	^^^^^^^
binding cannot be resolved
----------
----------
19. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/BookInfoActivity.java (at line 360)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
20. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/BookInfoActivity.java (at line 360)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
----------
21. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/SeemoreActivity.java (at line 140)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
22. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/SeemoreActivity.java (at line 140)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
----------
23. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/BestCollectionsActivity.java (at line 238)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
24. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/BestCollectionsActivity.java (at line 238)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
----------
25. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/SearchActivity.java (at line 179)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
26. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/SearchActivity.java (at line 179)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
----------
27. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/CollectionbooksActivity.java (at line 113)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
28. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/CollectionbooksActivity.java (at line 113)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
----------
29. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/ReviewsActivity.java (at line 101)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
30. ERROR in /storage/emulated/0/.sketchware/mysc/653/app/src/main/java/digital/online/books/ReviewsActivity.java (at line 101)
	androidx.swiperefreshlayout.widget.CircularProgressDrawable iTicon = new androidx.swiperefreshlayout.widget.CircularProgressDrawable(getApplicationContext());
	                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
androidx.swiperefreshlayout cannot be resolved to a type
----------
----------
31. ERROR in /storage/emulated/0/.sketchware/data/653/files/java/FCMService.java (at line 96)
	.bigLargeIcon(null));
	 ^^^^^^^^^^^^
The method bigLargeIcon(Bitmap) is ambiguous for the type NotificationCompat.BigPictureStyle
----------
31 problems (31 errors)

**Comment by hasrat-ali** [comment]
I removed those commit that are responsible for this. Try newer build.

**Comment by laymintu** [comment]
> I removed those commit that are responsible for this. Try newer build.

Thank for very much 🥳
