### ISSUE TITLE
Need ChatGPT Implimentation

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1445]
hi. sometimes we need java , kotlin or other codes from chatGPT it takes time to go to chatGPT everytime for the code. 

please make an option which contains basic chatgpt acessciable from configuration window 
so we can get the codes without leaving Sketchware pro.

**Comment by laymintu** [comment]
If you can't  or don't have time to open ChatGPT then **stop Coding ****
**Happy coding **
