### ISSUE TITLE
Need More Block Extended Support

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1446]
Hi. when creating more block it accessible only in working activity. so we need to create everytime more block in different Activities.

using java class , please make an option to create "Global More Block" which can be accessed from all activity and usable in all activities 

hope you understand

**Comment by hasrat-ali** [comment]
You can just add it to collection the  import it in different activities

**Comment by araafroyall** [comment]
> You can just add it to collection the  import it in different activities 

but it will use same amount of code and storage again and again on importing to different activities
