### ISSUE TITLE
Need More Runner in Blocks

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1448]
Hi. for example using `if else` block we can run only 2 custom commands .

we need multiple runners support for blocks 

for example
```java
if (condition1) {
    // Code for condition1
} else if (condition2) {
    // Code for condition2
} else if (condition3) {
    // Code for condition3
} else if (condition4) {
    // Code for condition4
}
```

hope you understand 

even we can't make it from block manager or can't create such block for now.

but it is very important feature , please make this for us

If you make such multiple runners in blocks , it will be useful for making multi purpose blocks 

This is basic example of conditional block, 
we need multiple runners for different blocks or we need option to make such blocks from block manager

**Comment by araafroyall** [comment]
or like this , `for conditional`


```java
if (condition1) {
    // Code for condition1
} else if (condition2) {
    // Code for condition2
} else if (condition3) {
    // Code for condition3
} else if (condition4) {
    // Code for condition4
} else if (condition5) {
    // Code for condition5
} else {
    // Default case
}
```

**Comment by laymintu** [comment]
How about this? You can try yourself 😁 😉!
They even can't fix bugs but you are asking such a feature 🥵😅

https://github.com/user-attachments/assets/abda1386-d9e0-44a1-a170-f742f5fb793f

**Comment by araafroyall** [comment]
> 
> How about this? You can try yourself 😁 😉!
> They even can't fix bugs but you are asking such a feature 🥵😅
> 
> https://github.com/user-attachments/assets/abda1386-d9e0-44a1-a170-f742f5fb793f
> 
> 

i just showed them example.

i need this mechanism for different types of blocks. 

even in more blocks i need multiple runners

**Comment by ilyassesalama** [comment]
I don't this is possible using blocks.

**Comment by araafroyall** [comment]
Its possible , but it will require high amount of work
