### ISSUE TITLE
Need Blocks & Projects Store Manager

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1449]
It seems you making project store using sketchub.in 

we need Block store too 

also i have suggestion why you should not use github as repository provider for project store 
if you own sketchub.in than no problem

but i suggest use github repo to store and update project as well as make block store 
and allow all user so we can upload our project and blocks in that

if you deciding to make project or block store using github repo than tell me , i will maintain that repo for sketchware pro 
just you impliment such feature to use blocks & projects from github repo 
i will maintain that repo myself and allow particular user acess for their project and blocks just like `LsPosed` people doing

hope u understand 

For example `LsPosed` is using similar concept

**Comment by araafroyall** [comment]
now the developers using github API for detecting contributors.
i am suggesting same , please use github repo for modules and blocks store

**Comment by PranavPurwar** [comment]
> It seems you making project store using sketchub.in
> 
> we need Block store too
> 
> also i have suggestion why you should not use github as repository provider for project store if you own sketchub.in than no problem
> 
> but i suggest use github repo to store and update project as well as make block store and allow all user so we can upload our project and blocks in that
> 
> if you deciding to make project or block store using github repo than tell me , i will maintain that repo for sketchware pro just you impliment such feature to use blocks & projects from github repo i will maintain that repo myself and allow particular user acess for their project and blocks just like `LsPosed` people doing
> 
> hope u understand
> 
> For example `LsPosed` is using similar concept

If you own a Sketchub account, you can upload and update your own projects. LSPosed doesn't use this concept. Users must not be forced to use a different service with entirely different purpose for something as simple as project/block store.

**Comment by araafroyall** [comment]
where is block store ? have you seen ?

**Comment by PranavPurwar** [comment]
With a block store, more and more people would simply "copy and paste" stuff expecting it to work out of the box. Hence, I do not see a need for a "Block Store". You're free to provide valid usecases for it though
