### ISSUE TITLE
Project Crashing problem

### ISSUE THREAD

**Issue by Apkmodifire** [Sketchware-Pro/Sketchware-Pro#1451]
https://github.com/user-attachments/assets/82939084-8b5d-4c6d-b90c-868c7e325a03

#e89348d

v6.4.0-SNAPSHOT-e89348d-minApi26
I TRY RUN MY PROJECT RUN SUCCESSFULLY COMPLETED 
AND THAN TRY OPEN MY PROJECT IT'S CRASH

And when I try this, Version v6.4.0-SNAPSHOT-cfae6a0-minApi26  no error or crash

**Comment by JelLee11** [comment]
It  was dew to turning on the AppCompat. It was still not fix to this point and this matter is duplicated... I think this is was your facing with

**Comment by hasrat-ali** [comment]
You are using older build. Try [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/12097874141).
