### ISSUE TITLE
APK/AAB building still fails

### ISSUE THREAD

**Issue by AnBui2004** [Sketchware-Pro/Sketchware-Pro#1452]
Device: Redmi Turbo 3.
OS: HyperOS 1.0.17.0.
Android version: 14.
Sketchware version: v6.4.0-SNAPSHOT-a42fdf2-minApi26

![Screenshot_2024-11-29-17-05-51-036_pro sketchware](https://github.com/user-attachments/assets/b27f7311-c9df-490e-9205-b33e62a3d5cc)
![Screenshot_2024-11-29-17-05-54-743_pro sketchware](https://github.com/user-attachments/assets/d79b6132-df9c-4720-b4fa-a095fe87b90a)

**Comment by Edward-NewGate-KOC** [comment]
Could you share a project that has this issue? Or let us know how to reproduce it in a new one ?
It seems no one else is facing this problem

**Comment by AnBui2004** [comment]
I found the cause of the problem, that is these blocks are empty. In previous versions Sketchware would automatically ignore if it was empty but in the latest Nightly version it does not.

![InShot_20241130_111011397](https://github.com/user-attachments/assets/313593cf-3f86-4051-8dcb-e54847b76c8e)

**Comment by PranavPurwar** [comment]
Yes, I even warned @elfilibusterismo that his changes will cause issues on old projects but he just ignored me. His changes [here](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/217cb5ba4c0046e306f45f91f3f18f5b5dca0efd#diff-5f95fa74b4a32a00a76996742116dbc5903829711a39e3e274c3bcbc43260d28R68) introduced this irregular new behaviour

**Comment by elfilibusterismo** [comment]
> Yes, I even warned @elfilibusterismo that his changes will cause issues on old projects but he just ignored me. His changes [here](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/217cb5ba4c0046e306f45f91f3f18f5b5dca0efd#diff-5f95fa74b4a32a00a76996742116dbc5903829711a39e3e274c3bcbc43260d28R68) introduced this irregular new behaviour

What do you mean? If I didn't remove that the next block won't generate , you return it as an empty

**Comment by PranavPurwar** [comment]
what next block?

**Comment by elfilibusterismo** [comment]
> what next block?

See this https://t.me/sketchwarepro/203595/284162
