### ISSUE TITLE
⚠️ LAYOUT Designer issue in Sketchware Pro (nightly)

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1460]
Drag and drop the problem in Sketchware nightly.

### Example video
https://github.com/user-attachments/assets/644c1442-cb32-4e77-8580-a56956543cf2

Faced this on/tested on
Many devices, all the nightly versions.

**Comment by laymintu** [comment]
Its 2000 years ago, 


As for me, i deleted all and put again or
Saved it and deleted and then put again 🥵

**Comment by StudioAsInc** [comment]
> Its 2000 years ago, 
> 
> 
> As for me, i deleted all and put again or
> Saved it and deleted and then put again 🥵

STILL It's a bug 🐛

**Comment by RoyTheReal** [comment]
Yeah it's still a bug. I've reported this same bug previously
