### ISSUE TITLE
Need "Duplicate Project" Maker

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1468]
hi sometime we need to test the things out . to prevent our original project from corrupt.

please make a duplicate option.

also if you can , make a merge option to merge all changes from duplicate project to original. if test sucess.

hope you understand

**Comment by hasrat-ali** [comment]
You can backup your project and restore it again.

**Comment by araafroyall** [comment]
this was not suggested method 🙁
