### ISSUE TITLE
Need `.sh` Editing Support in Assets 

### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1471]
Hi. it seems only `.txt` files can be edited inside assets in code editor , and other files opening in external app.

sometime we need to write shell scripts `.sh`

please make these format files should be edited inside assets.

or you can make an option to edit anyfile type by viewing it as textview in Assets without leaving Sketchware pro.

Please its very urgent for me. make this

**Comment by AyushVivek** [comment]
Yes I also want this feature
