### ISSUE TITLE
Using just Released nightly version #93264b7 the app icon error


### ISSUE THREAD

**Issue by araafroyall** [Sketchware-Pro/Sketchware-Pro#1480]
i restore old swb file. 

```java
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/filsa/SketchUi/MainActivity.java (at line 1206)
	icon.setImageResource(R.drawable.app_icon);
	                                 ^^^^^^^^
app_icon cannot be resolved or is not a field
----------
1 problem (1 error)
```

**Comment by Mustiy0** [comment]
New icon path is
`R.mipmap.ic_launcher`

**Comment by araafroyall** [comment]
> New icon path is
> `R.mipmap.ic_launcher`


but i restored old swb file . how can i acess now

**Comment by Mustiy0** [comment]
Wdym? Just edit the code

**Comment by araafroyall** [comment]
which code. i downloaded swb from sketchub

**Comment by Mustiy0** [comment]
Bro, just go to main activity line 1206 and change 
`icon.setImageResource(R.drawable.app_icon); `
To
`icon.setImageResource(R.mipmap.ic_launcher);`

**Comment by araafroyall** [comment]
how can i edit mainactivity java class
