### ISSUE TITLE
Need SearchBar on the image selector dialog of Sketchware.

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1488]
### The problem
I have a huge list of images that I use into my project. Every time I add an image, I have to scroll to the last of the list, which is huge.

### What I want?
● Show newer added images at the top.
● SearchBar to search images with name.

### Extra feat. request
● Images with .xml extension should work directly as we add normal .png & .jpg images.

**Comment by araafroyall** [comment]
i already submitted #1474
