### ISSUE TITLE
Used custom block overlaped

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1494]
**Describe the bug**
Used custom block overlaped

**To Reproduce**
Open any project>Configuration>Custom blocks

**Screenshots**
![Screenshot_20241210-143306](https://github.com/user-attachments/assets/0d0dfd36-abe6-44c0-bec8-73490e892911)

Device and Sketchware Pro-related info:
 - Device: [e.g. All]
 - OS: [e.g. All]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT- f197226 -minApi26]

**Comment by Edward-NewGate-KOC** [comment]
Fixed in [a5e360d](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/a5e360da95eedb4667ad19ff9d92192b709263f5)

**Comment by subhash16** [comment]
@Edward-NewGate-KOC you didn't give it as Bug tag
