### ISSUE TITLE
Deprecated Api

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#1496]
![Screenshot_20241211-010229~2](https://github.com/user-attachments/assets/5825aa2f-be7c-4bfc-a1ad-4b98419b25dc)

**Comment by hasrat-ali** [comment]
Since those classes are used in libraries, so I don't think you can do anything.

**Comment by subhash16** [comment]
> Since those classes are used in libraries, so I don't think you can do anything.

So what can i do now. Is there any problem will happen?

**Comment by hasrat-ali** [comment]
You can ignore this afaik.

**Comment by subhash16** [comment]
Please fix this issue
