### ISSUE TITLE
Allow code editing

### ISSUE THREAD

**Issue by yyy33** [Sketchware-Pro/Sketchware-Pro#1497]
**Is your feature request related to a problem? Please describe.**
NO.

**Describe the solution you'd like**
Add a code editing mode that allows to choose whether to edit the code directly or use graphical programming. And the graphical programming mode can be converted to code editing mode, but the code editing mode cannot be converted to graphical editing mode.

**Describe alternatives you've considered**
No.

**Additional context**
![Screenshot_20241211-124905](https://github.com/user-attachments/assets/15136d0a-1b67-48ea-bb3e-013e597c38ca)

**Comment by elfilibusterismo** [comment]
Use Java/Kotlin Manager
