### ISSUE TITLE
الترجمه ومنح صلاحيات الوصول للاندرويد في التطبيقات

### ISSUE THREAD

**Issue by 01154767907** [Sketchware-Pro/Sketchware-Pro#1506]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 01154767907** [comment]
اريد أن أضيف صلاحيات الوصول لي ملفات الاندرويد و ترجمة البرنامج

**Comment by subhash16** [comment]
You uneducated people.If you have any problem then tell in English.Fuck you.

**Comment by trindadedev13** [comment]
Fill out the issue template, and use English.
