### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by redowan178** [Sketchware-Pro/Sketchware-Pro#1521]
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/909/app/src/main/java/com/redo/ahmed/SketchLogger.java (at line 68)
	Context context = SketchAplication.getContext();
	                  ^^^^^^^^^^^^^^^^
SketchAplication cannot be resolved
----------
1 problem (1 error)

**Comment by StudioAsInc** [comment]
Why it occurs?

**Comment by redowan178** [comment]
I just changed the "Application class name" from the project configuration

**Comment by elfilibusterismo** [comment]
Not our problem.

When changing application class name, ensure that the application class exists in java/kotlin manager

**Comment by Gabrielsynapse** [comment]
Não entendi
