### ISSUE TITLE
💥Crashing while exporting (.aab)

### ISSUE THREAD

**Issue by StudioAsInc** [Sketchware-Pro/Sketchware-Pro#1531]
I previously reported this bug; however, due to a lack of response from contributors, I had to resubmit it.

# Previous report
**ID:** #1510
**Link:** https://github.com/Sketchware-Pro/Sketchware-Pro/issues/1510

@hasrat-ali @ilyassesalama

**Comment by hasrat-ali** [comment]
Pls don't do like this. They will fix it when they get time for it.
