### ISSUE TITLE
font delete,last font not be deleted

### ISSUE THREAD

**Issue by nalcwap** [Sketchware-Pro/Sketchware-Pro#1532]
**Describe the bug**
if you try delete last font font not be removed from list of fonts if one remains

**To Reproduce**
1. Step 1 addone font then when saved try delete from font manager,you will fail delete save that font
2. Step 2
3. Step 3
...

**Expected behavior**
expected no fonts in list of fonts when save delete the font ,see video if you not understand 

**Screenshots**

https://github.com/user-attachments/assets/69bb349e-49e0-40ce-ad5e-537f8e076d30

Device and Sketchware Pro-related info:
 - lg v480
 - android 5.02
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

**Comment by Edward-NewGate-KOC** [comment]
Fixed in : Commit fcd3bf4
