### ISSUE TITLE
Unable to build this project in Android Studio. Tons of errors

### ISSUE THREAD

**Issue by khaled-0** [Sketchware-Pro/Sketchware-Pro#157]
Look at those
![image](https://user-images.githubusercontent.com/74397286/124292878-dff68b80-db77-11eb-8f9f-78af1703d31e.png)
![image](https://user-images.githubusercontent.com/74397286/124292939-edac1100-db77-11eb-832b-1417746b6a3f.png)
![image](https://user-images.githubusercontent.com/74397286/124292971-f997d300-db77-11eb-95d4-ab9d0b667a9b.png)

Downloaded the repo and tried to build, nothing works , everything's error wth. 
what to do , does anyone have any idea?
has anyone built it successfully?

I've tried with Java7 and 8 , results are same.

**Comment by JavkhlanK** [comment]
You'll have to get stub classes or DEX files converted to .jar files from a recent Sketchware Pro APK as dependencies. Put them then into /app/libs/

**Comment by khaled-0** [comment]
you can't run sketchware pro from android studio sadly
many classes have hardcoded resource ids and building an app will re-generate integer ids for them
