### ISSUE TITLE
Popup in the design activity when

### ISSUE THREAD

**Issue by hosni-fraj** [Sketchware-Pro/Sketchware-Pro#164]
HMM.... check the title

**Comment by JavkhlanK** [comment]
not opening useless issues on GitHub and rather suggesting it on Discord when

**Comment by hosni-fraj** [comment]
We already discussed about this in Discord server.

**Comment by JavkhlanK** [comment]
I just realized that a PopupMenu has already been added to DesignActivity. Didn't you check the file before opening a new issue?

**Comment by hosni-fraj** [comment]
Sorry
