### ISSUE TITLE
Sketchware Compile problems

### ISSUE THREAD

**Issue by joyful-cambion** [Sketchware-Pro/Sketchware-Pro#210]
Hello, 
I am currently using sketchware (6.4.0 beta-3 public) and when I'm compiling an app using sketchware I get this error log:

[/data/user/0/com.sketchware.remod/files/libs/libs/savedstate-1.0.0/res/values/values.xml:3: error: Found tag id where item is expected, , /data/user/0/com.sketchware.remod/files/libs/libs/lifecycle-viewmodel-2.0.0/res/values/values.xml:3: error: Found tag id where item is expected, , /data/user/0/com.sketchware.remod/files/libs/libs/lifecycle-runtime-2.0.0/res/values/values.xml:3: error: Found tag id where item is expected, ]

This can be fixed by changing build settings to AAPT2 and the app will compile with no issues, but after I install the app it won't open and it'll crash immediately.

**Comment by JavkhlanK** [comment]
What libraries does the project use? And more importantly, what's the reason the app crashed for?

**Comment by joyful-cambion** [comment]
@JavkhlanK Sorry I just started using tha app, I am using the default libraries I haven't changed any libraries whatsoever, and the app crashes for no reason it doesn't even open when you click to launch it it shows a message "App keeps stopping" app info / close app and that's it

**Comment by JavkhlanK** [comment]
Hm, that reminds me of v6.4.0 Public Beta 1's DEX merge issues. Could you upload the built APK here? You might have to rename the file from .apk to .zip

**Comment by joyful-cambion** [comment]
@JavkhlanK  Broo, it's funny I think I know where the issue is I just had to backup my app and do a clean install, and it just worked now with no issues I think this is because I installed the app on top of old version. Sorry for disturbing 😅

**Comment by JavkhlanK** [comment]
okay lol then

**Comment by joyful-cambion** [comment]
Nevermind I know where the problem is because it happened again, It happens when I enable "app compact library" so anytime I add a drawer or FAB it happens again
