### ISSUE TITLE
Admob error

### ISSUE THREAD

**Issue by HARDIK1221** [Sketchware-Pro/Sketchware-Pro#245]
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/699/app/src/main/java/com/my/newproject15/MainActivity.java (at line 85)
	adview1.loadAd(new AdRequest.Builder().addTestDevice("79A19AF25CE083C24DE7CBD569CD1E38")
	                                       ^^^^^^^^^^^^^
The method addTestDevice(String) is undefined for the type AdRequest.Builder
----------

**Comment by JavkhlanK** [comment]
AdViews are still not working, please wait for the next beta version.
