### ISSUE TITLE
Can't download a library

### ISSUE THREAD

**Issue by CrLn-66** [Sketchware-Pro/Sketchware-Pro#246]
![Screenshot_20211001_110724](https://user-images.githubusercontent.com/78108570/135560405-06ec51a0-d9bc-4bcd-b8af-24c7291c1252.jpg)

I am trying to download library but it always say "Download failed, No network"

**Comment by Bhavy-Ukani** [comment]
Add custom repository url

**Comment by CrLn-66** [comment]
How?

**Comment by Bhavy-Ukani** [comment]
> How?
#### You can add repository urls in this repositories.json file
Path 👇👇
`/.sketchware/libs/repositories.json`

**Comment by CrLn-66** [comment]
I entered a new repo url "http://repo.maven.apache.org/maven2/"
but nothing happened i tried to download different library still the same.

![Screenshot_20211001_152004](https://user-images.githubusercontent.com/78108570/135581199-76737944-c6e7-4d0e-afb3-96f99f7b98d2.jpg)

**Comment by khaled-0** [comment]
Close this when
