### ISSUE TITLE
Can't export Source Code to Android Studio - Bug

### ISSUE THREAD

**Issue by ReduxFlakes** [Sketchware-Pro/Sketchware-Pro#250]
While trying to export my app to Android Studio project I got a message saying "An error ocurred!" and then some Java error. Down below I put my device info and video for proof. Hope this get fixed in the next re.

**Device**
Samsung J6
Android 10

**Video**

https://user-images.githubusercontent.com/87225951/136457964-bac6578a-e06f-4141-b5eb-e942fad15c14.mp4

**Comment by JavkhlanK** [comment]
This is a known issue, but for now, keep creating the mentioned directories (look carefully at the error message for them) and trying to export your project. This bug will be fixed with the next beta version.

**Comment by JavkhlanK** [comment]
v6.4.0-rc01 contains a fix for this issue.
