### ISSUE TITLE
When I add a webview to Sketchware beta 6, there is an error while building the app

### ISSUE THREAD

**Issue by debendronath** [Sketchware-Pro/Sketchware-Pro#252]
When I add a webview to Sketchware beta 6, there is an error while building the app.

Error log
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 158)
	}
});
	^^^^
Syntax error on tokens, delete these tokens
----------
2. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 161)
	wb.setWebViewClient(new WebViewClient() {
	                                        ^
Syntax error, insert "}" to complete ClassBody
----------
3. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 161)
	wb.setWebViewClient(new WebViewClient() {
	                                        ^
Syntax error, insert ")" to complete Expression
----------
4. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 161)
	wb.setWebViewClient(new WebViewClient() {
	                                        ^
Syntax error, insert ";" to complete Statement
----------
5. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 161)
	wb.setWebViewClient(new WebViewClient() {
	                                        ^
Syntax error, insert "}" to complete MethodBody
----------
6. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 163)
	public void onPageStarted(WebView _param1, String _param2, Bitmap _param3) {
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method onPageStarted(WebView, String, Bitmap) of type BrowserActivity must override or implement a supertype method
----------
7. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 167)
	super.onPageStarted(_param1, _param2, _param3);
	      ^^^^^^^^^^^^^
The method onPageStarted(WebView, String, Bitmap) is undefined for the type AppCompatActivity
----------
8. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 171)
	public void onPageFinished(WebView _param1, String _param2) {
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method onPageFinished(WebView, String) of type BrowserActivity must override or implement a supertype method
----------
9. ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/com/debendronathmanik/gresults/BrowserActivity.java (at line 176)
	}
});
	^^^^^
Syntax error on tokens, delete these tokens
----------
9 problems (9 errors)
![Screenshot_2021-10-10-02-07-14-987_com sketchware remod](https://user-images.githubusercontent.com/92230560/136672545-a79aa4fd-2563-4ffe-b526-cbf27053733d.jpg)

**Comment by abdogamerpro** [comment]
I think it's a know issue, same here.

**Comment by JavkhlanK** [comment]
Hi, that's a currently known issue of Sketchware Pro v6.4.0 Beta 6. It will be fixed with the next beta version, so stay tuned for that.

**Comment by hasrat-ali** [comment]
If it is fixed why not closed?

**Comment by JavkhlanK** [comment]
I wanted to keep it open until the beta version that fixes that bug gets released.

**Comment by JavkhlanK** [comment]
Sketchware Pro v6.4.0-rc01 should have fixed this issue.

**Comment by Masum12111** [comment]
storage/emulated/0/.sketchware/mysc/619/app/src/main/java/com/topup/app/EditProfileActivity.java (at line 221)

**Comment by Masum12111** [comment]
storage/emulated/0/.sketchware/mysc/619/app/src/main/java/com/topup/app/EditProfileActivity.java (at line 221)

**Comment by Masum12111** [comment]
storage/emulated/0/.sketchware/mysc/619/app/src/main/java/com/t
