### ISSUE TITLE
NullPointerException error when creating aab

### ISSUE THREAD

**Issue by likhwa** [Sketchware-Pro/Sketchware-Pro#258]
Hi guys, I'm getting an error when I try to create an aab file. I initially thought the error was in my app, but from the message below it seems like an error in Sketchware Pro's ExportProjectActivity. You can have a look at the error message in the screenshot below:

![Screenshot_20211016-014754_Sketchware Pro](https://user-images.githubusercontent.com/42215238/137565525-31a76a2c-057c-4bb7-a7ae-1def5939b5c0.jpg)

**Comment by JavkhlanK** [comment]
What Sketchware Pro version did you use?

**Comment by JavkhlanK** [comment]
It looks like that error's coming from some More Block. Does just running the project with Sketchware Pro work?

**Comment by likhwa** [comment]
Just tried and it does not. Gives the following error

Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

**Comment by hasrat-ali** [comment]
Did you used any your own block menu type `%z` or `%s.[new type]` or anything similar to this.

**Comment by likhwa** [comment]
No. I used the vanilla(original) Sketchware and it doesn't allow own blocks.
