### ISSUE TITLE
Admob Reward Ad Error

### ISSUE THREAD

**Issue by manhtetthar** [Sketchware-Pro/Sketchware-Pro#267]
i used sketchware 6.4.1 Sketchware studio to create my project and it perfectly run without any error and showing ad. so i want to export to aab bundle then i run my project on Sketchware 6.4.0 beta 6 (this version) and got following errors. please help me 

![Screenshot_20211031-030224](https://user-images.githubusercontent.com/55823972/139557730-3cf53cbc-fd81-4fcf-81d8-9945b2efc6f9.png)

**Comment by PranavPurwar** [comment]
In short, you need to reimplement those ads. We had recently updated the built in admob library, which needs a whole new set of codes to work. You can find those new blocks in the components section of swpro.

**Comment by JavkhlanK** [comment]
Note: The Blocks/code associated with the RewardedVideoAd Component haven't been updated yet

**Comment by PranavPurwar** [comment]
then check if admob is enabled or not

**Comment by JavkhlanK** [comment]
It obviously is, just the Component & Blocks' code is outdated and not working for the updated built-in library version.

**Comment by PranavPurwar** [comment]
if it's enabled then the admob library should already be added for scanning in ecj. also no one has ever reported this behaviour before and we haven't edited that part so it's most likely some misconfiguration

**Comment by manhtetthar** [comment]
> It obviously is, just the Component & Blocks' code is outdated and not working for the updated built-in library version.

i am not using reward ad bocks.  i was using this method
https://sketchwareworld.blogspot.com/2019/11/admob-rewarded-video-ads-in-sketchware.html?m=1

**Comment by manhtetthar** [comment]
> then check if admob is enabled or not

admob is enabled

**Comment by JavkhlanK** [comment]
> > It obviously is, just the Component & Blocks' code is outdated and not working for the updated built-in library version.
> 
> i am not using reward ad bocks.  i was using this method
> https://sketchwareworld.blogspot.com/2019/11/admob-rewarded-video-ads-in-sketchware.html?m=1

You've used an outdated method to get rewarded video ads then. Look at [the official AdMob documentation](https://developers.google.com/admob/android/rewarded) to find out what to use with Sketchware Pro v6.4.0
