### ISSUE TITLE
Changing screen orientation of project doesn't work

### ISSUE THREAD

**Issue by PranavPurwar** [Sketchware-Pro/Sketchware-Pro#275]
i set the orientation to "both" and when checked in manifest, it was still portrait
Fix this until next beta or big nub

**Comment by khaled-0** [comment]
Check your ```AndroidManifest``` injections 
Idk ketchware injects portrait automatically

**Comment by PranavPurwar** [comment]
![Screenshot_2021-11-25-13-21-20](https://user-images.githubusercontent.com/75154889/143401214-4a27f736-9019-40d3-b718-f38a60233e01.png)
![Screenshot_2021-11-25-13-22-08](https://user-images.githubusercontent.com/75154889/143401241-e66db4ae-99f1-470d-a7bc-cee095b951a5.png)
there is no screenOrientation attribute in my android manifest injection

**Comment by JavkhlanK** [comment]
With what method did you set the Activity's orientation to both?

**Comment by PranavPurwar** [comment]
here
![Uploading Screenshot_2021-11-25-13-25-29.png…]()

**Comment by PranavPurwar** [comment]
here
![Screenshot_2021-11-25-13-25-29](https://user-images.githubusercontent.com/75154889/143401748-2e24df0a-0009-43b6-9a36-14a54aa1f3f3.png)

**Comment by JavkhlanK** [comment]
> Fix this until next beta or big nub 
Also, please note that rule 4 from the Discord server also applies here.

**Comment by PranavPurwar** [comment]
but im not on discord server, so how do i know that ?

**Comment by JavkhlanK** [comment]
Whoops, sorry for not leaving this issue left unanswered. Back to the issue.
Looking at vanilla Sketchware's behavior, it's doing the same thing. Also, looking [the official documentation for the `<activity>` tag](https://developer.android.com/guide/topics/manifest/activity-element#screen) inside an AndroidManifest.xml file, you'll find out that the attribute not being set or having the value of `"unspecified"` will match what "both" means in Sketchware's context, so this is the expected behavior.

**Comment by JavkhlanK** [comment]
> but im not on discord server, so how do i know that ?

There's a [code of conduct](https://github.com/Sketchware-Pro/Sketchware-Pro/blob/main/CODE_OF_CONDUCT.md) that must be followed by everyone collaborating here. Please make sure to read it thoroughly.

**Comment by PranavPurwar** [comment]
I DIDN'T SET THAT TO BOTH, I SET THAT TO ONLY LANDSCAPE. YOU N**

**Comment by JavkhlanK** [comment]
Are you sure about that? The issue's description and your latest screenshot both show "both" as chosen option.
Also as last warning, please keep this place friendly and free of inappropriate language, or else, there will be some consequences.

**Comment by PranavPurwar** [comment]
i added "both" later

**Comment by PranavPurwar** [comment]
because landscape was not working

**Comment by JavkhlanK** [comment]
Unfortunately, I can't reproduce your issue. For me, all options set in the Activity's properties work. Could you please tell what Sketchware Pro version you used when you got that issue?

**Comment by PranavPurwar** [comment]
6.4.0 beta 6

**Comment by JavkhlanK** [comment]
I unfortunately couldn't reproduce your issue with that version either.

**Comment by khaled-0** [comment]
It happens randomly sometimes

**Comment by PranavPurwar** [comment]
then fix it

**Comment by PranavPurwar** [comment]
ix it or else re-open thid issue
