### ISSUE TITLE
BottomNavigation Missing Event Listener Code

### ISSUE THREAD

**Issue by khaled-0** [Sketchware-Pro/Sketchware-Pro#282]
bottomnavigation onitemselected listener 
Code miss it show
//No listener code

There's also some other missing listeners i don't remember.
_Originally posted by @Htet04 in https://github.com/Sketchware-Pro/Sketchware-Pro/issues/249#issuecomment-987818786_

**Comment by hasrat-ali** [comment]
ok, this problem was already fixed just wait for the next beta or stable release.

**Comment by khaled-0** [comment]
I'll close this but i suggest you kindly go over all the events and blocks to see if there's anything else missing. Because i remember this bug in searchView too.

**Comment by JavkhlanK** [comment]
The SearchView Event bug got fixed recently too.
