### ISSUE TITLE
[Suggestion] Only latest changelog blue

### ISSUE THREAD

**Issue by DerGoogler** [Sketchware-Pro/Sketchware-Pro#290]
#### Example:
![Screenshot_20211225000421](https://user-images.githubusercontent.com/54764558/147373943-e673f556-d79e-4d2b-bc5b-be2720483f3e.png)
> Only photo is edited
    
What do you think? 🤔

**Comment by JavkhlanK** [comment]
Not a too bad idea, not gonna lie.

**Comment by ilyassesalama** [comment]
Isn't that the expected behavior. If not, that's a bug then.

**Comment by DerGoogler** [comment]
> Isn't that the expected behavior. If not, that's a bug then.

Read the quote below the picture

**Comment by PranavPurwar** [comment]
how is it a bug

**Comment by DerGoogler** [comment]
> how is it a bug

I don' know
