### ISSUE TITLE
Can Not add button Navigation in Sketchware pro 6.4.0 -rc01 .Please Fix it.Thank

### ISSUE THREAD

**Issue by MoeLaMin545** [Sketchware-Pro/Sketchware-Pro#292]
![Screenshot_20211225_182752_com.sketchware.remod.jpg](https://user-images.githubusercontent.com/96643430/147384422-3815b4d5-fdd7-4857-9841-815bab9a27ec.jpg)![Screenshot_20211225_182741_com.sketchware.remod.jpg](https://user-images.githubusercontent.com/96643430/147384424-9ad632ee-a322-4063-a309-b7d56a670ce6.jpg)![Screenshot_20211225_182802_com.sketchware.remod.jpg](https://user-images.githubusercontent.com/96643430/147384429-f7321069-c79e-4ef6-a1e7-1eb8c1983ade.jpg)![Screenshot_20211225_174404_com.sketchware.remod.jpg](https://user-images.githubusercontent.com/96643430/147384452-772cc911-2018-4ec3-8002-3380e38a250d.jpg)

**Comment by JavkhlanK** [comment]
Whoops. Will be fixed with v6.4.0-rc02!

**Comment by JavkhlanK** [comment]
Quick update on that bug: We've already fixed it, it's only waiting to be released.

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
