### ISSUE TITLE
cannot clear compile logs in v6.4.0-rc01 

### ISSUE THREAD

**Issue by PranavPurwar** [Sketchware-Pro/Sketchware-Pro#295]

**Comment by JavkhlanK** [comment]
Oh right, that's a regression from Beta 6. Will get added to the options menu.

**Comment by khaled-0** [comment]
idk why would you want that, bot oke,
jbk will surely add it back,
definitely, piola

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
