### ISSUE TITLE
RewardedVideoAd doesn't depend on AdMob being enabled and has outdated code

### ISSUE THREAD

**Issue by satyamtiwari2001** [Sketchware-Pro/Sketchware-Pro#297]
Plz fix Admob Rewarded Ads error in Next Update

**Comment by JavkhlanK** [comment]
What's 6.4.0_fix2? That doesn't sound like an official Sketchware Pro version.

**Comment by satyamtiwari2001** [comment]
> What's 6.4.0_fix2? That doesn't sound like an official Sketchware Pro version. 

I mean 6.4.0 test build version

**Comment by JavkhlanK** [comment]
What exact v6.4.0 test version are you talking about? What exact AdMob issue are you talking about? Please provide more details.

**Comment by satyamtiwari2001** [comment]
![Screenshot_20211229-225542.png](https://user-images.githubusercontent.com/72878449/147688031-ddfbeac3-d391-4ceb-a8c8-6ef712022f95.png)
I am using latest version of sketchware pro v6.4.0 While complie the project which contain Admob Rewarded Ads component it give this Error
![Screenshot_20211229-225813.png](https://user-images.githubusercontent.com/72878449/147688193-faea317d-92c1-4b75-92aa-e505ed55562c.png)

**Comment by JavkhlanK** [comment]
You will need the AdMob built-in library enabled for that Component to work.

**Comment by satyamtiwari2001** [comment]
So how i enabled it plz tell me many sketchware user getting this error not able to fix 😧

**Comment by JavkhlanK** [comment]
Open your project in Sketchware Pro, open the drawer there, select Library at the top and open AdMob there, then go through the setup of enabling AdMob, then you should be done. Try to compile your project again afterwards.

**Comment by JavkhlanK** [comment]
Apparently, that Component doesn't require the built-in AdMob library being enabled for the project, so that should get fixed.

**Comment by satyamtiwari2001** [comment]
It already Selected and there is error let me show you ![Screenshot_20211229-230854.png](https://user-images.githubusercontent.com/72878449/147689088-e22f7224-ddaf-443d-a26f-4967278819c1.png)
It's enable
![Screenshot_20211229-231016.png](https://user-images.githubusercontent.com/72878449/147689114-be2e0acd-e46f-4e2e-9b10-a7da26bf4eca.png)

**Comment by JavkhlanK** [comment]
Ah, so the Component's code is outdated too. Thanks for reporting that issue; we'll try to fix it.

**Comment by satyamtiwari2001** [comment]
Thx for the help every sketchware developer happy for this
