### ISSUE TITLE
bug: App crashing on startup without Storage access

### ISSUE THREAD

**Issue by tfun037** [Sketchware-Pro/Sketchware-Pro#298]
![Screenshot_20211230-142843](https://user-images.githubusercontent.com/59114113/147737203-c0adc332-c005-498c-8e58-daa9601fa776.png)
This app is not open

**Comment by JavkhlanK** [comment]
That's a currently known issue of Sketchware Pro v6.4.0-rc01. It got fixed with 707cb84a6e20304d1bcc33374241bd97a7c7db39 already, but that fix will come with v6.4.0-rc02.

There's a simple fix for that though: Grant Sketchware Pro Storage permissions manually from Settings, then it shouldn't crash.

**Comment by JavkhlanK** [comment]
Keeping this open until v6.4.0-rc02 comes out.

**Comment by conh727** [comment]
The team of contributors will be able to solve software problems in the application

**Comment by gamazinplayz** [comment]
After giving permission still crashing

**Comment by JavkhlanK** [comment]
> After giving permission still crashing

Could you upload the error message that shows up here?

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
