### ISSUE TITLE
Internet not working in sketchware pro compiled app

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#299]
my project can't use internet which is compiled with this app but original sketchware allow

**Comment by JavkhlanK** [comment]
Could you provide more details on that? What do you mean by internet, what does the project do?

**Comment by TechnicalStudioDevelopers** [comment]
> Could you provide more details on that? What do you mean by internet, what does the project do?

I mean i am very old user of sketchware and i am developing a app from 1 year it has about 29 activities (screens) i used several components of firebase and this full app which i created is completely done now but i want to compile it with sketchware pro (lastest) but when i compiled it with sketchware pro so everything is working perfectly but my app can't use data network so i think my internet not working but internet is working perfectly but app can't use any data and when i run(compile) it with sketchware (original) so my app can uses data but not in sketchware pro please solve this issue

**Comment by JavkhlanK** [comment]
What do you **exactly** mean by internet usage? Is it just Firebase? If so, please make sure to reconfigure your project's Firebase settings: Reopen the Firebase Library settings and replace your old Project ID with the full URL of the Database; an example is provided in Sketchware Pro itself. You can find the full Database URL by opening the Firebase Console and opening the Realtime Database tab, then you'll find a text with `https://` somewhere, copy that and enter the same text without the `https://` in the front and without the last `/`.

**Comment by TechnicalStudioDevelopers** [comment]
> What do you **exactly** mean by internet usage? Is it just Firebase? If so, please make sure to reconfigure your project's Firebase settings: Reopen the Firebase Library settings and replace your old Project ID with the full URL of the Database; an example is provided in Sketchware Pro itself. You can find the full Database URL by opening the Firebase Console and opening the Realtime Database tab, then you'll find a text with `https://` somewhere, copy that and enter the same text without the `https://` in the front and without the last `/`.

I am all know it suppose if this is my firebase key problem so a component (Request network) which load a response is also not working i am my app fully can't use network after compiled by sk pro

**Comment by JavkhlanK** [comment]
Did you change any advanced settings in Sketchware Pro, like the Build Setting which stops adding http-legacy-28.dex to the app? That could be a reason why your project's not working anymore.

Also, could you please check that earlier mentioned Firebase setting? If that was**n't** the cause of your project's Firebase Components failing, then we'd have a major Sketchware Pro to look into.

**Comment by TechnicalStudioDevelopers** [comment]
> Did you change any advanced settings in Sketchware Pro, like the Build Setting which stops adding http-legacy-28.dex to the app? That could be a reason why your project's not working anymore.
> 
> Also, could you please check that earlier mentioned Firebase setting? If that was**n't** the cause of your project's Firebase Components failing, then we'd have a major Sketchware Pro to look into.

If i am making any mistake please compile my this app in sketchware and sketchware pro 
First in sketchware pro then sketchware then share result
Link of swb - https://dl.dropbox.com/s/cxndp3nd16d12yp/tsd%20v1.2%20%28com.tsd.html%2C%201%29%202021-12-30t193425.swb?dl=0

**Comment by JavkhlanK** [comment]
Thanks, I got your SWB. I'll remove the download link, as it contains your project, so hopefully it doesn't get into the wrong hands.

**Comment by JavkhlanK** [comment]
I found an invalid Firebase configuration in that SWB. Please replace `technical-studio-develop-…` with something that ends with `.com` or `.io`, I've explained previously how you can get the full Database URL.

**Comment by TechnicalStudioDevelopers** [comment]
> 

but when i compile with original sketchware so its works perfectly

**Comment by JavkhlanK** [comment]
That's a change made by Sketchware Pro to allow projects with newer Firebase Database URLs that don't end with `.firebaseio.com`. Some databases are in the US, some in Asia, that's why some projects with those server URLs don't work on Sketchware anymore.

**Comment by TechnicalStudioDevelopers** [comment]
> I found an invalid Firebase configuration in that SWB. Please replace `technical-studio-develop-…` with something that ends with `.com` or `.io`, I've explained previously how you can get the full Database URL.

if there is firebase mistake then why network response component not working

**Comment by JavkhlanK** [comment]
> > I found an invalid Firebase configuration in that SWB. Please replace `technical-studio-develop-…` with something that ends with `.com` or `.io`, I've explained previously how you can get the full Database URL.
> 
> if there is firebase mistake then why network response component not working

I haven't found any (to me) known misconfiguration in your project yet, so could you please try it out again after fixing the Firebase part?

**Comment by TechnicalStudioDevelopers** [comment]
> > > I found an invalid Firebase configuration in that SWB. Please replace `technical-studio-develop-…` with something that ends with `.com` or `.io`, I've explained previously how you can get the full Database URL.
> > 
> > 
> > if there is firebase mistake then why network response component not working
> 
> I haven't found any (to me) known misconfiguration in your project yet, so could you please try it out again after fixing the Firebase part?

remember that other internet components are also no working and have you tried my app in original sketchware

**Comment by JavkhlanK** [comment]
I haven't, as it's pretty slow lol

**Comment by TechnicalStudioDevelopers** [comment]
> I haven't, as it's pretty slow lol

oh bro sorry i just readed about full url is needed in sketchware pro thanks you for help
