### ISSUE TITLE
/* Failed to resolve Custom Block's code: java.util.UnknownFormatConversionException: Conversion = 'm' */
}

### ISSUE THREAD

**Issue by 2439905184** [Sketchware-Pro/Sketchware-Pro#302]
I have a small problem with custom block function.
how to use variable in custom block。
![Screenshot_20220103-110456.jpg](https://user-images.githubusercontent.com/29478722/147897177-fd1a4c30-8821-4cb7-93d2-e74bd43598c2.jpg)

**Comment by hasrat-ali** [comment]
You have to use `%s` as block format argument.
