### ISSUE TITLE
Keyboard is not showing in source Code

### ISSUE THREAD

**Issue by venkyram-jio** [Sketchware-Pro/Sketchware-Pro#303]
Please add the keyboard to edit code![Screenshot_2022-01-07-14-00-23-47.jpg](https://user-images.githubusercontent.com/60128898/148515244-16e295cb-a8f5-466d-a51c-d1e22364111d.jpg)

**Comment by JavkhlanK** [comment]
That's a read-only viewer of the Event's source code. You can't really change code there, as changes won't and can't be saved.

**Comment by venkyram-jio** [comment]
> That's a read-only viewer of the Event's source code. You can't really change code there, as changes won't and can't be saved.

Ok. Thanks for the information.
But where I can change the code. If I want to change.

**Comment by JavkhlanK** [comment]
If you want to edit the Activity's full source code, you have to either use Java Command Blocks or copy the Activity's code & add that to a new file with the same name in Java Manager. Both ways are replacements for the recently removed Direct Source Code Editor.
