### ISSUE TITLE
Pro guard rules error

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#304]
![Screenshot_2022-01-07-19-26-08-134_com tsd html](https://user-images.githubusercontent.com/96680248/148554020-abc39ff9-2a9b-463c-8fea-336640519eb7.jpg)
Hello sketchware pro team i am currently facing a problem with proguard rules when i enable proguard rules and sign my apk so it doesn't load anything and shows a toast message as in image how can i fix it😭😭

**Comment by JavkhlanK** [comment]
Can you show your ProGuard rules? Just that screenshot is not really helpful in diagnosing the issue. A list of used Local libraries in your project would also be helpful.

**Comment by TechnicalStudioDevelopers** [comment]
![Uploading Screenshot_2022-01-07-20-25-50-053_com.sketchware.remod.jpg…]()

**Comment by TechnicalStudioDevelopers** [comment]
![Screenshot_2022-01-07-20-25-50-053_com sketchware remod](https://user-images.githubusercontent.com/96680248/148561895-c178868c-d053-4f7c-ba75-3f2627cdd721.jpg)

**Comment by TechnicalStudioDevelopers** [comment]
I used the following 
  Library manager:-
    App compact
    Firebase
    Admob
 Extra permissions : no extra permission
Stringfog : no

**Comment by JavkhlanK** [comment]
Looks like you forgot to exclude repackaging / obfuscation of some important class(es). Gson is throwing that error, by the way. Did you add Gson as Local library?

**Comment by TechnicalStudioDevelopers** [comment]
> Looks like you forgot to exclude repackaging / obfuscation of some important class(es). Gson is throwing that error, by the way. Did you add Gson as Local library?

I can i fix it please tell me

**Comment by Insight-deviler** [comment]
Refer this gist for proguard rules
[Common proguard rules](https://gist.github.com/jemshit/767ab25a9670eb0083bafa65f8d786bb)
The ones that is default in sketchware won't work for many library

**Comment by TechnicalStudioDevelopers** [comment]
I have added 
-keepattributes Signature
in proguard rules not working but what can i do please give mea direct solution

**Comment by TechnicalStudioDevelopers** [comment]
> Refer this gist for proguard rules [Common proguard rules](https://gist.github.com/jemshit/767ab25a9670eb0083bafa65f8d786bb) The ones that is default in sketchware won't work for many library

Done bro issue is fixed with rules
-ignorewarnings
-dontwarn
-dontnote
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep public class android.webkit.JavascriptInterface {}

Thanks a lot to @JavkhlanK  and @Insight-deviler

**Comment by TechnicalStudioDevelopers** [comment]
> Refer this gist for proguard rules [Common proguard rules](https://gist.github.com/jemshit/767ab25a9670eb0083bafa65f8d786bb) The ones that is default in sketchware won't work for many library

Done bro issue is fixed with rules
-ignorewarnings
-dontwarn
-dontnote
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep public class android.webkit.JavascriptInterface {}

Thanks a lot to @JavkhlanK  and @Insight-deviler
