### ISSUE TITLE
Can't sign APK file on the newest beta version

### ISSUE THREAD

**Issue by theblackdna** [Sketchware-Pro/Sketchware-Pro#306]
When signing an application, the compilation works normally but after it ends and the compiler's dialog closes, no application was signed and only the progress bar is shown. How to fix this?

**Comment by JavkhlanK** [comment]
By progress bar you mean the loading animation after the APK building dialog closes, right?

Could you upload debug.txt here? It's a logging file and could say what went wrong. Steps to get it:
 - First, open Sketchware Pro and try to run any project normally
 - Then, try to export a signed APK from the project again
 - And finally, upload /Internal storage/.sketchware/debug.txt here. The GitHub web interface contains an option to uploa
