### ISSUE TITLE
IntersticialAd Callback error: on a null object reference.

### ISSUE THREAD

**Issue by franciscowilton** [Sketchware-Pro/Sketchware-Pro#308]
When using the blocks from InterstitialAd  of the latest version of sketchware pro an error is returned right when starting the activity.

![Screenshot_20220115-013816_WhatsAppBot](https://user-images.githubusercontent.com/60080154/149609339-aebc5dc6-7db5-4611-a120-93d5b5655425.png)

**Comment by JavkhlanK** [comment]
That block to enable fullscreen content callbacks can only be used after the ad has been loaded, so you must place it in the onAdLoaded Event.

I think there should be a quick check in the Block's code though, one which shows a toast message in case of the ad not having been loaded yet.

**Comment by franciscowilton** [comment]
Oh, that must be it, I called it in OnCreate, thanks again.

**Comment by JavkhlanK** [comment]
Keeping this opened until projects don't crash anymore.

**Comment by JavkhlanK** [comment]
Revision 91c3d83f1f5f4d374dad4f1087801c63fed93698 fixes this, keeping open again until v6.4.0-rc02 gets released.

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
