### ISSUE TITLE
Sketchware Pro 6.4.0-rc01 crashes whenever I try to import a new sound file

### ISSUE THREAD

**Issue by Laxan3000** [Sketchware-Pro/Sketchware-Pro#311]
When I tried to replace an .aac file to a compressed .mp3, the app started to crash and not accepted any sort of sound file anymore. I even tried uninstalling and reinstalling the app to be sure I've cleared it's data, but nothing. The issue is just the same

Sound importing errors:
![sconosciuto-2.png](https://user-images.githubusercontent.com/58862419/150675930-582d1e09-5f1a-4979-8f52-9c46e31a6562.png)
![sconosciuto-1.png](https://user-images.githubusercontent.com/58862419/150675897-077dbaae-9030-4744-85fa-bef3b42b30e9.png)

**Comment by JavkhlanK** [comment]
Ah, right. Welcome to another episode of storage issues on newer Android versions!

So the main problem is that vanilla Sketchware used old mechanics to get the picked files' path, but on newer Android versions, that's not possible anymore (and throws errors in apps, providing no backwards compatibility (maybe cause Sketchware's method was not written well?)). It's essentially the same issue you get when using the FilePicker Component in Sketchware or Sketchware Pro projects.

To fix that issue, we'd have to modify that activity of Sketchware in Sketchware Pro, which is not in focus, at least by me. Still, thanks for reporting, as we can now keep track of that bug in the GitHub repository.

**Comment by Laxan3000** [comment]
> Ah, right. Welcome to another episode of storage issues on newer Android versions!
> 
> So the main problem is that vanilla Sketchware used old mechanics to get the picked files' path, but on newer Android versions, that's not possible anymore (and throws errors in apps, providing no backwards compatibility (maybe cause Sketchware's method was not written well?)). It's essentially the same issue you get when using the FilePicker Component in Sketchware or Sketchware Pro projects.
> 
> To fix that issue, we'd have to modify that activity of Sketchware in Sketchware Pro, which is not in focus, at least by me. Still, thanks for reporting, as we can now keep track of that bug in the GitHub repository.

Indeed, I noticed it only happens if /Download/ is the destination folder

**Comment by JavkhlanK** [comment]
This should now have finally been fixed. Could you please try it out? It worked for me on Android 5 (AVD), Android 8.1 (AVD), and Android 12 (One UI 4.1).
