### ISSUE TITLE
Proguard rules 

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#312]
Dear sketchware pro team,
I am facing a new problem again i used proguard to protect my apk from hacker attack but when i see how my app is protected and how is code obfuscated but when i de compiled my apk using a online website but when i getted a result that my apk code is not obfuscated perfectly only id's of wedgets,variables,more block naked replaced only but i thinked that i am making a mistake but what?
So, i de compiled spck editor (html editor on play store) so the results is shocking that spck code editor codes is heavily obfuscated
while sketchware pro compile app only replaced with variables,more block,or id of wedgets while spck code editor is replaced everything when we get a textview from its id sketchware obfuscate the code like

`private textview a`

An example of sketchware obfuscated code so you can understand my matter

`	aa.setTarget(imageview1);
		aa.setPropertyName("scaleX");
		aa.setFloatValues((float)(5), (float)(1));
		aa.setDuration((int)(2000));
		aa.setRepeatMode(ValueAnimator.REVERSE);
		aa.setRepeatCount((int)(0));
		aa.setInterpolator(new LinearInterpolator());
		animation.start();
		ab.setTarget(imageview1);
		ab.setPropertyName("scaleY");
		ab.setFloatValues((float)(5), (float)(1));
		ab.setDuration((int)(2000));
		ab.setRepeatMode(ValueAnimator.REVERSE);
		ab.setRepeatCount((int)(0));
	ab.setInterpolator(new LinearInterpolator());
		ab.start();
		a.edit().putString("currentVersion", "1.2.0").commit();
		a.edit().putString("version", "1.2").commit();
		a.edit().putString("developerUID", "KU7Nn0QHl4cB75AFWiGJxmsVZoo1").commit();
`

spck code editor obfuscated code be like

`package a.a.a.a; 
2	 
3	import android.os.Binder; 
4	import android.os.Bundle; 
5	import android.os.IBinder; 
6	import android.os.IInterface; 
7	import android.os.Parcel; 
8	 
9	public interface a extends IInterface { 
10	   void a(int var1, Bundle var2); 
11	 
12	   public abstract static class a extends Binder implements a.a.a.a.a { 
13	      public a() { 
14	         this.attachInterface(this, "android.support.v4.os.IResultReceiver"); 
15	      } 
16	 
17	      public static a.a.a.a.a a(IBinder var0) { 
18	         if (var0 == null) { 
19	            return null; 
20	         } else { 
21	            IInterface var1 = var0.queryLocalInterface("android.support.v4.os.IResultReceiver"); 
22	            return (a.a.a.a.a)(var1 != null && var1 instanceof a.a.a.a.a ? (a.a.a.a.a)var1 : new a.a.a.a.a.a.a(var0)); 
23	         } 
24	      } 
25	 
26	      public IBinder asBinder() { 
27	         return this; 
28	      } 
29	 
30	      public boolean onTransact(int var1, Parcel var2, Parcel var3, int var4) { 
31	         if (var1 != 1) { 
32	            if (var1 != 1598968902) { 
33	               return super.onTransact(var1, var2, var3, var4); 
34	            } else { 
35	               var3.writeString("android.support.v4.os.IResultReceiver"); 
36	               return true; 
37	            } 
38	         } else { 
39	            var2.enforceInterface("android.support.v4.os.IResultReceiver"); 
40	            int var5 = var2.readInt(); 
41	            Bundle var6; 
42	            if (var2.readInt() != 0) { 
43	               var6 = (Bundle)Bundle.CREATOR.createFromParcel(var2); 
44	            } else { 
45	               var6 = null; 
46	            } 
47	 
48	            this.a(var5, var6); 
49	            return true; 
50	         } 
51	      } 
52	 
53	      private static class a implements a.a.a.a.a { 
54	         private IBinder a; 
55	 
56	         a(IBinder var1) { 
57	            this.a = var1; 
58	         } 
59	 
60	         public IBinder asBinder() { 
61	            return this.a; 
62	         } 
63	      } 
64	   } 
65	} 
66	 
`

hope that you will help me.my sketchware proguard rules 

`-ignorewarnings
-dontwarn
-dontnote
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep public class android.webkit.JavascriptInterface {}
`

please i need more better code security like spck

**Comment by JavkhlanK** [comment]
You need to know that obfuscation does not mean security. It makes harder to read code, but people with dedication will still be able to modify the app.

Now to the example, I don't see much of a difference except for the repackaged classes of that Editor app. You looked at some abstract interface code, which will always look complicated in code form, whether it's obfuscated or not. Anyway, maybe you want to repackage your app's classes (which results in class names like `a.a.a.a` from that Editor app), [click here to read more about that](https://www.guardsquare.com/manual/configuration/examples#repackaging).

**Comment by TechnicalStudioDevelopers** [comment]
I mean that can i obfuscate my app like below code using sketchware pro?

`40 int var5 = var2.readInt(); 41 Bundle var6; 42 if (var2.readInt() != 0) { 43 var6 = (Bundle)Bundle.CREATOR.createFromParcel(var2); 44 } else { 45 var6 = null; 46 } 47 48 this.a(var5, var6); 49 return true; 50 } 51 } 52 53 private static class a implements a.a.a.a.a { 54 private IBinder a; 55 56 a(IBinder var1) { 57 this.a = var1; 58 } 59 60 public IBinder asBinder() { 61 return this.a; 62 } 63 } 64 } 65 } 66`

**Comment by JavkhlanK** [comment]
If you're talking about the `a.a.a.a` classes, yes. You can find extra ProGuard rules to get similar behavior in the link of my previous comment.

**Comment by TechnicalStudioDevelopers** [comment]
can you share me link when your shared when i was talking about gson problem i lost the linl plz

**Comment by JavkhlanK** [comment]
Are you talking about [this GitHub issue](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/304#issuecomment-1007877624)?

**Comment by TechnicalStudioDevelopers** [comment]
> You need to know that obfuscation does not mean security. It makes harder to read code, but people with dedication will still be able to modify the app.
> 
> Now to the example, I don't see much of a difference except for the repackaged classes of that Editor app. You looked at some abstract interface code, which will always look complicated in code form, whether it's obfuscated or not. Anyway, maybe you want to repackage your app's classes (which results in class names like `a.a.a.a` from that Editor app), [click here to read more about that](https://www.guardsquare.com/manual/configuration/examples#repackaging).

This website rules or sketchware pro rules are same?

**Comment by TechnicalStudioDevelopers** [comment]
bro can you tell me how can i obfuscate my app with sketchware with more better obfuscated code

**Comment by JavkhlanK** [comment]
The webpage I linked to earlier should have enough info on that.
