### ISSUE TITLE
Major issues in rc01

### ISSUE THREAD

**Issue by jackw2022** [Sketchware-Pro/Sketchware-Pro#315]
Hello Devs,

in sketchware version 6.3.0 fix 1, YouTube player, viewpager + fragments, navigation bar buttons used to work fine
In rc01 version they are not working
Please fix these issues and thank you very much

**Comment by JavkhlanK** [comment]
Yeah, they have some major issues. Do you have any details on the YouTube Player Component issue? For example, is your project crashing, or not even compiling, and if any of these, could you please upload the entire error message here?

**Comment by jackw2022** [comment]
> Yeah, they have some major issues. Do you have any details on the YouTube Player Component issue? For example, is your project crashing, or not even compiling, and if any of these, could you please upload the entire error message here?
