### ISSUE TITLE
Major Issues in Sketchware Version 6.4.0 rc01

### ISSUE THREAD

**Issue by jackw2022** [Sketchware-Pro/Sketchware-Pro#317]
NOTE: CLOSED PREVIOUS ISSUE BY MISTAKE. SORRY !

Hello Devs,

in sketchware version 6.3.0 fix 1, YouTube player, viewpager + fragments, navigation bar buttons used to work fine
In rc01 version they are not working
Please fix these issues and thank you very much.
------------------------------------------------

-----------
DESCRIPTION:
-----------

- 1) YouTube player : it FC when opening the exported apk.

- 2) Navigation button bar : 

------------
✓ Java Code with the issue: 
--------------------------------------------------------------------------------------------------------
linear2 = findViewById(R.id.linear2);
		bottomnavigation1 = findViewById(R.id.bottomnavigation1);
		linear3 = findViewById(R.id.linear3);
		linear4 = findViewById(R.id.linear4);
		
		bottomnavigation1.setOnItemSelectedListener(new NavigationBarView.OnItemSelectedListener() {
			@Override
			public boolean onNavigationItemSelected(MenuItem item) {
				final int _itemId = item.getItemId();
				if (_itemId == 0) {
					linear2.setVisibility(View.VISIBLE);
				}
				if (_itemId == 1) {
					linear3.setVisibility(View.VISIBLE);
				}
				if (_itemId == 2) {
					linear4.setVisibility(View.VISIBLE);
				}
				return true;
			}
		});
	}

----------------------------------------------------
----------------------------------------------------

----------
Error Log:
----------------------------------------------------
1. ERROR in /storage/emulated/0/.sketchware/mysc/759/app/src/main/java/com/my/newproject32/MainActivity.java (at line 74)
	bottomnavigation1.setOnItemSelectedListener(new NavigationBarView.OnItemSelectedListener() {
	                  ^^^^^^^^^^^^^^^^^^^^^^^^^
The method setOnItemSelectedListener(NavigationBarView.OnItemSelectedListener) in the type NavigationBarView is not applicable for the arguments (new OnItemSelectedListener(){})

2. ERROR in /storage/emulated/0/.sketchware/mysc/759/app/src/main/java/com/my/newproject32/MainActivity.java (at line 74)
	bottomnavigation1.setOnItemSelectedListener(new NavigationBarView.OnItemSelectedListener() {
	                                                ^^^^^^^^^^^^^^^^^
NavigationBarView cannot be resolved to a type

3. ERROR in /storage/emulated/0/.sketchware/mysc/759/app/src/main/java/com/my/newproject32/MainActivity.java (at line 76)
	public boolean onNavigationItemSelected(MenuItem item) {
	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method onNavigationItemSelected(MenuItem) of type new OnItemSelectedListener(){} must override or implement a supertype method

3 problems (3 errors)
----------------------------------------------------

**Comment by JavkhlanK** [comment]
Thanks for a detailed report!

The BottomNavigationView issue at least is a known bug of Sketchware Pro v6.4.0-rc01, but not the YouTube Player Component.
Could you please clarify what you meant with 'it FC when opening the exported APK'?

**Comment by jackw2022** [comment]
Hi,
Thanks for your reply
I mean by "FC" The app crashes when i open it
It does not give any details about the error
I imported the library from 6.3.0 fix1 but the same problem.

**Comment by JavkhlanK** [comment]
Could you share the crashing APK here? But first, please try exporting a signed APK of that project & see if that APK is crashing just like the APK built regularly with Sketchware Pro. If it isn't, then it's one of the known bugs of v6.4.0-rc01, and just tell that the signed APK works here.

**Comment by JavkhlanK** [comment]
Moving tracking of the YouTube Player View issue to #401.
