### ISSUE TITLE
Update Latest Material, core libraries

### ISSUE THREAD

**Issue by kannano** [Sketchware-Pro/Sketchware-Pro#320]
In earlier version of sketchware material library version 1.3 has been used but for now material 1.0.0 version is being used. Pls do update the material libraries and dependent libraries to latest version

**Comment by JavkhlanK** [comment]
The folder names used internally in Sketchware Pro don't necessarily represent the versions of the library, so it using `material-1.0.0` doesn't mean that it's at version 1.0.0. Sketchware Pro v6.4.0-rc01 has the MDC library of version 1.5.0-beta01 built-in.

**Comment by JavkhlanK** [comment]
To verify that, open the Sketchware Pro APK and open the file at /assets/libs/libs.zip, then navigate to material-1.0.0 and open classes.jar there. A file inside META-INF/ tells the library's version.
