### ISSUE TITLE
Error showing source code for custom views

### ISSUE THREAD

**Issue by brunodavi** [Sketchware-Pro/Sketchware-Pro#323]
When I go to `custom_view` > `settings_button` > `Show source code` it shows an error when viewing the `.xml`

> Not sure if it could be because I restored the project from a backup (.swb)

<details>
<summary>Screenshots</summary>

![sketchware_select_custom_view_aaa.jpg](https://user-images.githubusercontent.com/48166556/152654019-09d0f7cb-2fd0-42ff-a851-ce28da3d9906.jpg)

![sketchware_click_show_source_code.jpg](https://user-images.githubusercontent.com/48166556/152654143-88cbfbae-fae4-48a7-be80-06481d934096.jpg)

![sketchware_error_show_source_code.jpg](https://user-images.githubusercontent.com/48166556/152654179-a399452b-ca32-4be9-9613-6bc35cf85dec.jpg)

> Here's a sequence of what happens

</details>

**Comment by JavkhlanK** [comment]
Thanks for the report! Was able to reproduce, might try to fix before v6.4.0-rc02's release.

**Comment by JavkhlanK** [comment]
Fixed by #327.

**Comment by JavkhlanK** [comment]
Wait, I'll keep this issue open until v6.4.0-rc02 gets released.

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
