### ISSUE TITLE
Add a option remove `Attribute` on `Widgets`

### ISSUE THREAD

**Issue by brunodavi** [Sketchware-Pro/Sketchware-Pro#324]
I would like a way to visually create new widgets

<details>
<summary>Examples</summary>

![sketchware_source_keyboard_view.jpg](https://user-images.githubusercontent.com/48166556/152654993-436ec8a0-5b36-4244-8852-5c9669499811.jpg)

> I would like a way to remove this part of `LinearLayout` without having to manually create this in resources

```xml
<android.inputmethodservice.KeyboardView
 android:id="@+id/keyboard_view"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:orientation="horizontal"
 android:keyPreviewLayout="@layout/popup"
 android:layout_alignParentBottom="true" />
```

> And also a way to remove attributes or a null widget
> to be able to create something like this

```xml
<android.inputmethodservice.KeyboardView
 android:id="@+id/keyboard_view"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"

 android:keyPreviewLayout="@layout/popup"
 android:layout_alignParentBottom="true" />
```

> Not sure if this changes anything, maybe a way to add a closing tag

```xml
<android.inputmethodservice.KeyboardView
 android:id="@+id/keyboard_view"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"

 android:keyPreviewLayout="@layout/popup"
 android:layout_alignParentBottom="true">
</android.inputmethodservice.KeyboardView>
```

> I think it would be interesting for the custom view to be in `layout` na opção resources

</details>

**Comment by JavkhlanK** [comment]
So, a View with a mandatory convert option value, that'd probably be very helpful.

**Comment by JavkhlanK** [comment]
So now there's the option to not have the `android:orientation="…"` property in the generated XML code. Would that be enough for your purposes, @brunodavi?

**Comment by brunodavi** [comment]
Yes, but there would also be another feature I would like, if you haven't posted it yet I'll send it anytime

**Comment by brunodavi** [comment]
And thank you very much for adding this feature
