### ISSUE TITLE
fix: Not working `<queries>` tag in AndroidManifest.xml

### ISSUE THREAD

**Issue by JamzApps** [Sketchware-Pro/Sketchware-Pro#329]
Cant add queries code in manifest for speech to text in android 11(mandatory or will not work).
<queries>
   <intent>
     <action android:name="android.speech.RecognitionService" />
   </intent>
</queries>

**Comment by khaled-0** [comment]
That's a gradle dependent feature.
And seeing as how sketchware doesn't use gradle, it'll be interesting to see how this might be tackled.

**Comment by JamzApps** [comment]
Thats the last bug i need to ditch my android 10 phone, so hopefully sooner than later. Cus its on its last crack...
But i noticed 3.4.2 in build.gradle with settings.gradle foldrler.

**Comment by tyron12233** [comment]
This can be solved by updating the aapt2 Sketchware Pro uses. The queries tag has been introduced on android 11 and i'm assuming Sketchware Pro uses aapt2 from android 9

**Comment by arab-ware** [comment]
> This can be solved by updating the aapt2 Sketchware Pro uses. The queries tag has been introduced on android 11 and i'm assuming Sketchware Pro uses aapt2 from android 9

Where could we get the latest aapt2 so?

**Comment by JavkhlanK** [comment]
the most efficient way would be compiling from source, and I had plans to do that already. I'd also upload necessary patches to the source & hashes to check the built binary & verify it.

**Comment by JavkhlanK** [comment]
Alright I managed to fix that bug. Turns out that it was a mistake by me, the distributed APK didn't have the same aapt2 files as this repository. Sorry!

**Comment by JavkhlanK** [comment]
Keeping this opened as well until v6.4.0-rc02 gets released.

**Comment by JamzApps** [comment]
Sweet, now i can use I my new phone, thanks man!

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
