### ISSUE TITLE
Error onesignal

### ISSUE THREAD

**Issue by MohammedAlherk** [Sketchware-Pro/Sketchware-Pro#331]
the method getpermissionsubscriptionstate() is undefined for the type onesignal
----------
1. ERROR 
The method getPermissionSubscriptionState() is undefined for the type OneSignal
----------
2. ERROR 
The method getEnabled() is undefined for the type OSPermissionState
----------
3. ERROR
The method getSubscribed() is undefined for the type OSSubscriptionState
----------
4. ERROR
The method getUserSubscriptionSetting() is undefined for the type OSSubscriptionState
----------
5. ERROR 
The method startInit(MainActivity) is undefined for the type OneSignal
----------
6. ERROR
OSInFocusDisplayOption cannot be resolved or is not a field
----------
7. ERROR 
The method setSubscription(boolean) is undefined for the type OneSignal
----------
8. ERROR 
The method setSubscription(boolean) is undefined for the type OneSignal
----------
9. ERROR
The method getPermissionSubscriptionState() is undefined for the type OneSignal
----------
10. ERROR
The method getEnabled() is undefined for the type OSPermissionState
----------
11. ERROR
The method getSubscribed() is undefined for the type OSSubscriptionState
----------
12. ERROR
The method getUserSubscriptionSetting() is undefined for the type OSSubscriptionState
----------
12 problems (12 errors)

**Comment by JavkhlanK** [comment]
Something happened to the built-in OneSignal version since v6.3.0 fix1 and I don't wanna bother with it, so I'll revert the library to the version in v6.3.0 fix1.

To fix your issue, please use v6.3.0 fix1 or don't use OneSignal in your project, sorry.

**Comment by MohammedAlherk** [comment]
thank you

**Comment by JavkhlanK** [comment]
This issue should've been fixed with 183e1eb330b4cfcc0f744aebfd6a0220f9df5808. Please wait for v6.4.0-rc02 and test building your project again. If it fails, please tell here. Thanks!

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
