### ISSUE TITLE
Remove the Shared Block button in the More Blocks list

### ISSUE THREAD

**Issue by NiceSapien** [Sketchware-Pro/Sketchware-Pro#332]
Shared block button doesn't work and i think it should be removed

**Comment by hasrat-ali** [comment]
It has already been removed.

**Comment by NiceSapien** [comment]
> It has already been removed.

Bro am on latest beta
Or is it removed in Private Beta?

**Comment by hasrat-ali** [comment]
Which version are you using?

**Comment by NiceSapien** [comment]
Idk it's latest beta

**Comment by JavkhlanK** [comment]
"latest beta" doesn't tell which version it is. Share the name you can see in Program information instead.

**Comment by NiceSapien** [comment]
It is v6.4.0-rc01

**Comment by JavkhlanK** [comment]
Could you show a screenshot of the screen where you think it should be removed from Sketchware Pro?

**Comment by NiceSapien** [comment]
Here u go @JavkhlanK :
![Screenshot_20220228-185105_Sketchware Pro.jpg](https://user-images.githubusercontent.com/71333407/155990339-8a003317-8f27-4d49-b0f1-df3ffff1d9b7.jpg)

**Comment by hasrat-ali** [comment]
Kinda not easy to remove but....!

**Comment by NiceSapien** [comment]
Ok👍

**Comment by JavkhlanK** [comment]
Alright, thanks! That would require some lower-level patches, and we'll see what we can do.

**Comment by hasrat-ali** [comment]
Fixed with 6.4.0.rc2

**Comment by NiceSapien** [comment]
Nice
