### ISSUE TITLE
Custom event listener doesn't show up in proper way

### ISSUE THREAD

**Issue by kannano** [Sketchware-Pro/Sketchware-Pro#341]
I have written a event listener using Event  Listener in developer options but the codes which I wrote partially get shown in the Java class whenever I try restarting the app it shows different codes in middle of listener codes. Also yes I know that this issue has been fixed as it is mentioned in changelog & please make sure it is rid out from app. Thanks n please solve this bug

**Comment by kannano** [comment]
![Uploading Screenshot_2022-03-08-13-16-24-042_com.sketchware.remod.jpg…]()

**Comment by kannano** [comment]
![Screenshot_2022-03-08-13-16-18-323_com sketchware remod](https://user-images.githubusercontent.com/47701056/157278204-5400f5b1-3459-428b-8579-381b0a6370b7.jpg)
![Screenshot_2022-03-08-13-17-25-155_com sketchware remod](https://user-images.githubusercontent.com/47701056/157278222-398ceb45-fadf-4f22-91a1-0806c9cfdbfd.jpg)

**Comment by kannano** [comment]
![Screenshot_2022-03-08-13-16-24-042_com sketchware remod](https://user-images.githubusercontent.com/47701056/157278373-0d3f5e88-72a3-4483-ae8b-8217b566c0a0.jpg)

**Comment by JavkhlanK** [comment]
Could you show the code that got generated? Looks like it's missing a brace or bracket close.

**Comment by waelchateur** [comment]
%i    ????   what is i

**Comment by waelchateur** [comment]
@kannano try to make it independent Method

i guess it is interfering with the initialise method

**Comment by kannano** [comment]
@waelchateur I tried that too but not helped

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
