### ISSUE TITLE
Remove SketchwareUtil & SketchApplication Classes

### ISSUE THREAD

**Issue by kimoandroid** [Sketchware-Pro/Sketchware-Pro#343]
hello, can you please remove these two files from sketchware SketchwareUtil & SketchApplication
because i tried too much to remove them but failed

**Comment by waelchateur** [comment]
rather than removing them why not updating them with Saf and replacing the deprecated codes and of cource updating file blocks to support newer sdk

**Comment by JavkhlanK** [comment]
I think this is more generally a feature that allows not generating files like SketchApplication.java, not just removing FileUtil.java.

**Comment by kimoandroid** [comment]
Yes, there is a feature in sketchware that generate these files, that's why I told modders to remove them

**Comment by Arashvscode** [comment]
> 

You can rename classes and add them in Java Manager

**Comment by MomoQ1** [comment]
> hello, can you please remove these two files from sketchware SketchwareUtil & SketchApplication because i tried too much to remove them but failed

I can do that .

**Comment by JavkhlanK** [comment]
why did you remove your suggestion?

**Comment by kimoandroid** [comment]
> why did you remove your suggestion?


I Think the suggestion is not affective on Sketchware Pro.

**Comment by JavkhlanK** [comment]
Okay then. Still no need to edit title & body to (incompletely) remove your suggestion though.

But that's not important though, just leave things as they are now.
