### ISSUE TITLE
TODO: Add instructions on custom moreblock type

### ISSUE THREAD

**Issue by khaled-0** [Sketchware-Pro/Sketchware-Pro#346]
Just so we don't forget about this before next release.

It doesn't seem necessary to me, because we already have a way for it.
(`moreblockName[type|typeName]` or `moreblockName[type|typeName|typeCode]` )

_Originally posted by @hasrat-ali in https://github.com/Sketchware-Pro/Sketchware-Pro/issues/220#issuecomment-944908703_

**Comment by JavkhlanK** [comment]
Can we keep issue trackers of things not yet in releases opened until they are live in one?

**Comment by khaled-0** [comment]
Closing this as new release contains the fix
