### ISSUE TITLE
Proguard On Latest Release  ( RC test ) .

### ISSUE THREAD

**Issue by arab-ware** [Sketchware-Pro/Sketchware-Pro#347]
It crashes sketchware pro with no debug dialog showing up hmmmmm

**Comment by kimoandroid** [comment]
same problem

**Comment by JavkhlanK** [comment]
@arab-ware, @kimoandroid, can you tell which Android versions your device run? I don't have any issues running it on my Android 12 device.

**Comment by kimoandroid** [comment]
> @arab-ware, @kimoandroid, can you tell which Android versions your device run? I don't have any issues running it on my Android 12 device.

I have Android 11 
CPU: Helio G95
Ram: 8 GB

**Comment by arab-ware** [comment]
> @arab-ware, @kimoandroid, can you tell which Android versions your device run? I don't have any issues running it on my Android 12 device.

Android 11
1.5GB
32 bit device
Samsung a10s

**Comment by JavkhlanK** [comment]
Since v6.4.0-rc04-minApi26 supports Kotlin again and it at least doesn't crash anymore, I guess this issue was fixed.
