### ISSUE TITLE
Import error with proguard

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#350]
Sketchware import is not working when used pro guard .Sorry for bad English

**Comment by hasrat-ali** [comment]
Providing stack trace/log would be very helpful.

**Comment by TechnicalStudioDevelopers** [comment]
I am using JavascriptInterface in app but after using pro guard it is not working please help🥺

**Comment by JavkhlanK** [comment]
Can you clarify 'not working'? Sounds like you forgot to exclude that JavaScriptInterface from obfuscation with ProGuard.

**Comment by TechnicalStudioDevelopers** [comment]
-ignorewarnings
-dontwarn
-dontnote
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes JavascriptInterface 
-dontwarn sun.misc.**
-keep public class android.webkit.JavascriptInterface {}
-keep public class com.mopub.**
-keepclassmembers class fqcn.of.javascript.interface.for.webview { public *; }
-repackageclasses ''
-allowaccessmodification

**Comment by TechnicalStudioDevelopers** [comment]
> -ignorewarnings -dontwarn -dontnote -keepattributes Signature -keepattributes _Annotation_ -keepattributes JavascriptInterface -dontwarn sun.misc.** -keep public class android.webkit.JavascriptInterface {} -keep public class com.mopub.** -keepclassmembers class fqcn.of.javascript.interface.for.webview { public *; } -repackageclasses '' -allowaccessmodification

My pro guard rules

**Comment by JavkhlanK** [comment]
Still, what exactly do you mean by 'not working'? Can't help out when you don't even know what's wrong.
