### ISSUE TITLE
Help me fix build error

### ISSUE THREAD

**Issue by Kayzen873** [Sketchware-Pro/Sketchware-Pro#351]
----------
1. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/MainActivity.java (at line 84)
	linear1.setBackgroundDrawable(getResources().getDrawable(R.drawable.bg_1));
	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
2. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/MainActivity.java (at line 84)
	linear1.setBackgroundDrawable(getResources().getDrawable(R.drawable.bg_1));
	                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getDrawable(int) from the type Resources is deprecated
----------
3. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/MainActivity.java (at line 142)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setSystemUiVisibility(int) from the type View is deprecated
----------
4. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/MainActivity.java (at line 142)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LAYOUT_STABLE is deprecated
----------
5. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/MainActivity.java (at line 142)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN is deprecated
----------
----------
6. ERROR in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 135)
	private  cd;
	         ^^
Syntax error, insert "Identifier (" to complete MethodHeaderName
----------
7. ERROR in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 135)
	private  cd;
	         ^^
Syntax error, insert ")" to complete MethodDeclaration
----------
8. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 219)
	new CyberTask11().execute(getIntent().getStringExtra("u"));
	                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method execute(String...) from the type AsyncTask<String,Integer,String> is deprecated
----------
9. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 283)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setSystemUiVisibility(int) from the type View is deprecated
----------
10. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 283)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
	                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR is deprecated
----------
11. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 289)
	Window w = this.getWindow();	w.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);	w.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
	                            	                                        ^^^^^^^^^^^^^^^^^^^^^^^
The field WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS is deprecated
----------
12. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 656)
	private class CyberTask11 extends AsyncTask<String, Integer, String> {
	              ^^^^^^^^^^^
The constructor AsyncTask<String,Integer,String>() is deprecated
----------
13. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 656)
	private class CyberTask11 extends AsyncTask<String, Integer, String> {
	                                  ^^^^^^^^^
The type AsyncTask<String,Integer,String> is deprecated
----------
14. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 660)
	super.onPreExecute();
	      ^^^^^^^^^^^^^^
The method onPreExecute() from the type AsyncTask<String,Integer,String> is deprecated
----------
15. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 704)
	publishProgress((int)Math.round(sumCount*100 / size));
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method publishProgress(Integer...) from the type AsyncTask<String,Integer,String> is deprecated
----------
16. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 724)
	super.onProgressUpdate(values);
	      ^^^^^^^^^^^^^^^^^^^^^^^^
The method onProgressUpdate(Integer...) from the type AsyncTask<String,Integer,String> is deprecated
----------
17. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 734)
	d.execute();
	  ^^^^^^^^^
The method execute(Void...) from the type AsyncTask<Void,Integer,Integer> is deprecated
----------
18. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 741)
	private class Decompress extends AsyncTask<Void, Integer, Integer> { 
	                                 ^^^^^^^^^
The type AsyncTask<Void,Integer,Integer> is deprecated
----------
19. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 750)
	super();		
	^^^^^^^^
The constructor AsyncTask<Void,Integer,Integer>() is deprecated
----------
20. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/InjectActivity.java (at line 784)
	publishProgress((int)count);
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method publishProgress(Integer...) from the type AsyncTask<Void,Integer,Integer> is deprecated
----------
----------
21. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/FileUtil.java (at line 232)
	return Environment.getExternalStorageDirectory().getAbsolutePath();
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getExternalStorageDirectory() from the type Environment is deprecated
----------
22. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/FileUtil.java (at line 240)
	return Environment.getExternalStoragePublicDirectory(type).getAbsolutePath();
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getExternalStoragePublicDirectory(String) from the type Environment is deprecated
----------
23. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/FileUtil.java (at line 252)
	path = Environment.getExternalStorageDirectory() + "/" + split[1];
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getExternalStorageDirectory() from the type Environment is deprecated
----------
24. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/FileUtil.java (at line 305)
	final String column = MediaStore.Images.Media.DATA;
	                                              ^^^^
The field MediaStore.MediaColumns.DATA is deprecated
----------
----------
25. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 22)
	View _view = _toast.getView();
	                    ^^^^^^^^^
The method getView() from the type Toast is deprecated
----------
26. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 31)
	_view.setBackgroundDrawable(_gradientDrawable);
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
27. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 53)
	View _view = _toast.getView();
	                    ^^^^^^^^^
The method getView() from the type Toast is deprecated
----------
28. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 64)
	_view.setBackgroundDrawable(_gradientDrawable);
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
29. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 126)
	NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
	^^^^^^^^^^^
The type NetworkInfo is deprecated
----------
30. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 126)
	NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
	                                                      ^^^^^^^^^^^^^^^^^^^^^^
The method getActiveNetworkInfo() from the type ConnectivityManager is deprecated
----------
31. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 127)
	return _activeNetworkInfo != null && _activeNetworkInfo.isConnected();
	                                                        ^^^^^^^^^^^^^
The method isConnected() from the type NetworkInfo is deprecated
----------
32. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 148)
	_inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0);
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method toggleSoftInput(int, int) from the type InputMethodManager is deprecated
----------
33. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/SketchwareUtil.java (at line 153)
	_inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method toggleSoftInput(int, int) from the type InputMethodManager is deprecated
----------
----------
34. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 574)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setSystemUiVisibility(int) from the type View is deprecated
----------
35. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 574)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LAYOUT_STABLE is deprecated
----------
36. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 574)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN is deprecated
----------
37. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 578)
	w.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
	                                        ^^^^^^^^^^^^^^^^^^^^^^^
The field WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS is deprecated
----------
38. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 585)
	_drawer_top.setBackgroundDrawable(getResources().getDrawable(R.drawable.T_shape));
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
39. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 585)
	_drawer_top.setBackgroundDrawable(getResources().getDrawable(R.drawable.T_shape));
	                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getDrawable(int) from the type Resources is deprecated
----------
40. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 589)
	_drawer_bottom.setBackgroundDrawable(getResources().getDrawable(R.drawable.B_shape));
	               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
41. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 589)
	_drawer_bottom.setBackgroundDrawable(getResources().getDrawable(R.drawable.B_shape));
	                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getDrawable(int) from the type Resources is deprecated
----------
42. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 788)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setSystemUiVisibility(int) from the type View is deprecated
----------
43. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 788)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
	                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_HIDE_NAVIGATION is deprecated
----------
44. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 788)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
	                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY is deprecated
----------
45. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 794)
	Window w = this.getWindow();	w.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);	w.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
	                            	                                        ^^^^^^^^^^^^^^^^^^^^^^^
The field WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS is deprecated
----------
46. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 824)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setSystemUiVisibility(int) from the type View is deprecated
----------
47. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/HomeActivity.java (at line 824)
	getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
	                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR is deprecated
----------
----------
48. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/ReportActivity.java (at line 67)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setSystemUiVisibility(int) from the type View is deprecated
----------
49. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/ReportActivity.java (at line 67)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LAYOUT_STABLE is deprecated
----------
50. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/ReportActivity.java (at line 67)
	getWindow().getDecorView().setSystemUiVisibility( View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
	                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The field View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN is deprecated
----------
51. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/ReportActivity.java (at line 71)
	w.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
	                                        ^^^^^^^^^^^^^^^^^^^^^^^
The field WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS is deprecated
----------
----------
52. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 101)
	new CyberTask11().execute("https://github.com/IkuzaDev/Update/blob/main/map.zip?raw=true");
	                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method execute(String...) from the type AsyncTask<String,Integer,String> is deprecated
----------
53. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 187)
	private class CyberTask11 extends AsyncTask<String, Integer, String> {
	              ^^^^^^^^^^^
The constructor AsyncTask<String,Integer,String>() is deprecated
----------
54. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 187)
	private class CyberTask11 extends AsyncTask<String, Integer, String> {
	                                  ^^^^^^^^^
The type AsyncTask<String,Integer,String> is deprecated
----------
55. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 191)
	super.onPreExecute();
	      ^^^^^^^^^^^^^^
The method onPreExecute() from the type AsyncTask<String,Integer,String> is deprecated
----------
56. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 235)
	publishProgress((int)Math.round(sumCount*100 / size));
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method publishProgress(Integer...) from the type AsyncTask<String,Integer,String> is deprecated
----------
57. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 255)
	super.onProgressUpdate(values);
	      ^^^^^^^^^^^^^^^^^^^^^^^^
The method onProgressUpdate(Integer...) from the type AsyncTask<String,Integer,String> is deprecated
----------
58. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 265)
	d.execute();
	  ^^^^^^^^^
The method execute(Void...) from the type AsyncTask<Void,Integer,Integer> is deprecated
----------
59. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 272)
	private class Decompress extends AsyncTask<Void, Integer, Integer> { 
	                                 ^^^^^^^^^
The type AsyncTask<Void,Integer,Integer> is deprecated
----------
60. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 281)
	super();		
	^^^^^^^^
The constructor AsyncTask<Void,Integer,Integer>() is deprecated
----------
61. WARNING in /storage/emulated/0/.sketchware/mysc/719/app/src/main/java/com/ikuza/Dx/DroneActivity.java (at line 315)
	publishProgress((int)count);
	^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method publishProgress(Integer...) from the type AsyncTask<Void,Integer,Integer> is deprecated
----------
61 problems (2 errors, 59 warnings)

**Comment by JavkhlanK** [comment]
Looks like your project's missing a Custom Component. Can't tell much more from just the compile error message though.

**Comment by DarkLight2377** [comment]
bro just re install the whole sk pro
