### ISSUE TITLE
New version 

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#357]
Hello, I have a request when the new version will be released

**Comment by JavkhlanK** [comment]
We can't tell. v6.4.0-rc02 will get released when we feel like it's ready.

**Comment by Arashvscode** [comment]
> 

Thank you. Can you add the (var) keyword?

**Comment by JavkhlanK** [comment]
That's a Java 11 feature, which the current Java compiler doesn't support yet. Might upgrade ecj to support it though.
