### ISSUE TITLE
Bug: Duplicated variables

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#358]
![Screenshot_۲۰۲۲۰۴۱۵-۱۱۵۹۲۱_Sketchware Pro](https://user-images.githubusercontent.com/101287880/163539662-67635605-a60a-4627-aa7d-52d1eb2b1c8f.jpg)

#bug

**Comment by JavkhlanK** [comment]
Not just a bug of SrcViewerActivity, but the actual generated code. @hasrat-ali, have you seen this already?

**Comment by hasrat-ali** [comment]
> Not just a bug of SrcViewerActivity, but the actual generated code. @hasrat-ali, have you seen this already?

Yeah,  i already seen. Need to fix that.
Will do it soon.

**Comment by Arashvscode** [comment]
Fixed tnks
