### ISSUE TITLE
Bug sing apk File 

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#359]
![Screenshot_۲۰۲۲۰۴۱۶-۰۰۱۷۵۰_Sketchware Pro](https://user-images.githubusercontent.com/101287880/163625537-1135c258-a3d8-4e42-a3f0-9006baa73c50.jpg)

#bug
Failed resolution of: Lcom/android/apksig/util/-$$Lambda$RunnablesExecutor$re6B2STec8sDn1AlZ-GKl1gwEfY;

Hi, I created an empty project with D8 and run it, I got this error

**Comment by JavkhlanK** [comment]
Can you reproduce that issue and then upload /Internal storage/.sketchware/debug.txt here?

**Comment by Arashvscode** [comment]
> Can you reproduce that issue and then upload /Internal storage/.sketchware/debug.txt here?

[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/8498220/debug.txt)

**Comment by JavkhlanK** [comment]
Thanks. Was able to reproduce using GitHub Actions-built APKs.

**Comment by Arashvscode** [comment]
Fixed tnk @JavkhlanK  and @hasrat-ali  ❤

**Comment by JavkhlanK** [comment]
Got fixed with the latest GitHub Actions-built APK(s).

**Comment by Arashvscode** [comment]
> 

Tnks lol
