### ISSUE TITLE
Bug padding

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#364]
![Screenshot_۲۰۲۲۰۴۲۲-۱۲۲۷۱۴_Sketchware Pro](https://user-images.githubusercontent.com/101287880/164644403-93fd5ec2-32bd-40dc-8a09-ffbc57e07886.jpg)

When I want to add a padding to an object, the normal length is 8, while here it shows 0

**Comment by JavkhlanK** [comment]
That doesn't look like you're editing the View's padding, instead, its margin.
