### ISSUE TITLE
Problem with localboardcastManager when creating aab

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#365]
![Screenshot_2022-03-01-12-40-32-93_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/164648580-01f1078e-873f-42dd-8702-ff0eb17ad2cf.jpg)
![Screenshot_2022-03-01-14-26-55-71_29df9931ef74bdd19fed97f571053f20](https://user-images.githubusercontent.com/88816748/164648650-fcfb4ddb-55bc-41ec-9929-2bb9ff99d809.jpg)

Problem with localboardcastManager when creating aab

**Comment by JavkhlanK** [comment]
Thanks for reminding me! The DEX file of localbroadcastmanager in dexs.zip actually doesn't contain the classes of it currently, and I think it's best to regenerate all DEX files from their classes.jar just to be sure.

**Comment by JavkhlanK** [comment]
Fixed by commit a4ed84cd5eaf87a56b0b98642e3ee2bb2fb714ed. Keeping this Issue open until v6.4.0-rc02, the first version containing that fix, gets released.

**Comment by JavkhlanK** [comment]
Fixed with [v6.4.0-rc02](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc02).
