### ISSUE TITLE
Bug not show block 

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#367]
![Screenshot_۲۰۲۲۰۴۲۲-۱۵۴۲۲۸_Sketchware Pro](https://user-images.githubusercontent.com/101287880/164703939-6f84c9a3-51e4-4a84-9c6e-f2e0839650e3.jpg)
Hi not show block if else

**Comment by hasrat-ali** [comment]
Ok, i faced this issue with only ASD blocks for now.

**Comment by hasrat-ali** [comment]
@JavkhlanK how it can be Vanilla Sketcheware Bug?

**Comment by JavkhlanK** [comment]
Try creating an if Block with a lot of other Blocks in it, or use the add source directly Block and paste in a lot of code. The same happens on vanilla Sketchware too, AFAIK.

**Comment by hasrat-ali** [comment]
Nothing happened.
![Screenshot_2022-04-22-18-14-21-25](https://user-images.githubusercontent.com/42956453/164716867-44d0eca5-1650-48dd-9b8c-bca794c5d23f.jpg)

**Comment by hasrat-ali** [comment]
Now in SK pro (latest CI build)
![Uploading Screenshot_2022-04-22-18-16-28-74.jpg…]()

**Comment by Arashvscode** [comment]
> 

Hiding for me lol

**Comment by Arashvscode** [comment]
> ![Screenshot_۲۰۲۲۰۴۲۲-۱۵۴۲۲۸_Sketchware Pro](https://user-images.githubusercontent.com/101287880/164703939-6f84c9a3-51e4-4a84-9c6e-f2e0839650e3.jpg) Hi not show block if else

This error may be due to overuse of the if & else block because I tried several other projects but did not encounter this bug
But you try to fix this bug and let me tell you that when I try to enter Logic Editor, my mobile screen gets dark for 2 minutes and my mobile phone waits for an error.

**Comment by JavkhlanK** [comment]
Weird. I definitely remember vanilla Sketchware doing the same for at least very large inputs in ASDs though.

**Comment by Arashvscode** [comment]
> 

Can you fix this bug?

**Comment by Arashvscode** [comment]
@JavkhlanK  are you fixed bug?

**Comment by JavkhlanK** [comment]
If this Issue's still open and I haven't commented anything, what do you think?

**Comment by Arashvscode** [comment]
> If this Issue's still open and I haven't commented anything, what do you think?

Null += yam yam

**Comment by Arashvscode** [comment]
![Screenshot_۲۰۲۲۰۵۰۸-۱۱۱۷۱۳_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167285245-1eff6c9e-bc00-4317-91ef-b189e1f4e659.jpg)

The problem of missing blocks has been fixed

**Comment by Arashvscode** [comment]
My bro plz add tag fixed  And close this Issues
