### ISSUE TITLE
Fix screen size error on all mobile phones

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#373]
Hello, please add a new feature that displays the same application size on all mobile phones
On some phones, apps made with sk pro are either too small or too large Some of the buttons even disappear on different mobile phones

**Comment by JavkhlanK** [comment]
That happens when you use fixed layout widths / heights, such as 400 dp. Use a combination of match_parent, wrap_content, and the gravity property instead.
