### ISSUE TITLE
Error writing code in direct source and so on

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#375]
https://user-images.githubusercontent.com/101287880/166000399-d6968cbb-ca4e-4df9-84aa-6be666ec9c12.mp4

![Screenshot_۲۰۲۲۰۴۲۹-۲۲۴۳۳۶_Sketchware Pro](https://user-images.githubusercontent.com/101287880/166000606-a72c70c7-0e4b-40f1-8928-5baf5f5710e0.jpg)

When I try to type code, the program gets an error and jumps. Watch the video and photo to understand more

**Comment by JavkhlanK** [comment]
Seems to be caused by commit 8e952747e8cedcab51ac4a284a879d883b54d977.

**Comment by Arashvscode** [comment]
> Seems to be caused by commit [8e95274](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/8e952747e8cedcab51ac4a284a879d883b54d977).I do not know maybe from @hasrat-ali Ask for his latest action lol

**Comment by hasrat-ali** [comment]
> Seems to be caused by commit [8e95274](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/8e952747e8cedcab51ac4a284a879d883b54d977).

Oh no. I had not thought about this.
@JavkhlanK can you update `LogicEditorActivity`? because I don't have my computer for now.

**Comment by Arashvscode** [comment]
> 

in is bad

**Comment by JavkhlanK** [comment]
> > Seems to be caused by commit [8e95274](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/8e952747e8cedcab51ac4a284a879d883b54d977).
> 
> Oh no. I had not thought about this.
> @JavkhlanK can you update `LogicEditorActivity`? because I don't have my computer for now.

Was about to do that, yeah.

**Comment by JavkhlanK** [comment]
Commit 78a54e3dac0c7fdb0c6b7932044d6b157f01e354 fixed that.
