### ISSUE TITLE
Update to latest version of ECJ

### ISSUE THREAD

**Issue by m-anshuman2166** [Sketchware-Pro/Sketchware-Pro#376]
I see library used is very old, could anyone update it to latest ?

New versions offer a lot of customization and features

https://mvnrepository.com/artifact/org.eclipse.jdt/ecj/3.29.0

**Comment by Arashvscode** [comment]
> I see library used is very old, could anyone update it to latest ?
> 
> New versions offer a lot of customization and features
> 
> https://mvnrepository.com/artifact/org.eclipse.jdt/ecj/3.29.0
I have tried before, it does not work well in my project

**Comment by JavkhlanK** [comment]
Duplicate of #363.
