### ISSUE TITLE
AddComponentActivity not disabling Add button after pressing

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#377]
![Screenshot_۲۰۲۲۰۵۰۱-۱۹۳۴۳۵_Sketchware Pro](https://user-images.githubusercontent.com/101287880/166163949-b9984277-aae2-48b6-9805-a419081ab86f.jpg)

The program sometimes creates duplicate components due to low speed

**Comment by JavkhlanK** [comment]
Was able to reproduce by quickly tapping Add in ComponentAddActivity.

In the meantime, don't press that button more than once.

**Comment by Arashvscode** [comment]
> 

I push once this happens one in a million
