### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#378]
![Screenshot_۲۰۲۲۰۵۰۲-۱۷۲۱۴۱_ZArchiver Pro](https://user-images.githubusercontent.com/101287880/166236604-6a64ffb9-6034-4c66-b5a2-38cb33c58363.jpg)
Project libraries are not fully backed up. In this project, 8 libraries have been used, but 2 libraries have been backed up.

**Comment by JavkhlanK** [comment]
Were all of those 8 libraries selected in Local library Manager? Just backed up a project of mine, and it had all libraries that were enabled (so selected in Local library Manager).

**Comment by JavkhlanK** [comment]
Was using Sketchware Pro v6.4.0-SNAPSHOT-1655251 without AAB support btw.

**Comment by Arashvscode** [comment]
> Was using Sketchware Pro v6.4.0-SNAPSHOT-1655251 without AAB support btw.
Yes I enabled all libraries and library backups

**Comment by khaled-0** [comment]
dead??

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
