### ISSUE TITLE
Sketchware project to Android Studio 

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#380]
I am trying to convert my .swb project into an Android Studio project it keeps processing but nothing happenes. I am using Sketchware latest version. My device is Android v8.1.0

**Comment by JavkhlanK** [comment]
To confirm, did you use Sketchware Pro v6.4.0-rc01 or v6.4.0-rc01-kt?

**Comment by PrakharDoneria** [comment]
Sketchware Pro vv6.4.0-rc01

**Comment by JavkhlanK** [comment]
I think I made a change related to that after v6.4.0-rc01.

Can you try using this snapshot APK from the repository and see if it seems to do nothing too?
The APK with AAB output is for Android 8 and newer devices, but contains support for exporting AABs.
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/2323078959

**Comment by JavkhlanK** [comment]
To clarify, I meant the artifacts generated by that workflow.

**Comment by PrakharDoneria** [comment]
Thank you its fine now
