### ISSUE TITLE
OneSignal Component 

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#381]
Their is no block for OneSignal push-notification and you also not put OneSignal SDK into your app. Can you suggest what to do?

**Comment by JavkhlanK** [comment]
Most I can offer you is to look for OneSignal Custom Blocks somewhere online. We shouldn't really build even more Blocks into Sketchware Pro itself, so I don't think they should be added, only as Custom Blocks.

**Comment by PrakharDoneria** [comment]
Thanks for the help
