### ISSUE TITLE
Java compilation error

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#382]
![Screenshot_۲۰۲۲۰۵۰۸-۰۹۵۷۵۶_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167283209-c2bf58ce-5b74-4e9c-9c15-9d6e09bbdae0.jpg)
I created a simple project and ran the program. While compiling Java, these strange numbers appeared to me. 
I downloaded the latest action available

**Comment by hasrat-ali** [comment]
For me too.

[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/8646383/debug.txt)

**Comment by Arashvscode** [comment]
> For me too.
> 
> [debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/8646383/debug.txt)

Ok my bro 
[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/8646386/debug.txt)

See

**Comment by Arashvscode** [comment]
![Screenshot_۲۰۲۲۰۵۰۸-۱۵۰۵۴۵_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167292319-dbd6f895-9763-4d1d-bf81-04cb71de511a.jpg)

Tnks my bro fixed bug @JavkhlanK  @hasrat-ali
