### ISSUE TITLE
Romved size text

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#385]
![Screenshot_۲۰۲۲۰۵۰۸-۱۷۱۶۰۲_Sketchware Pro](https://user-images.githubusercontent.com/101287880/167296824-b63d0200-8d56-4633-8781-4a5a787b7dcd.jpg)
Please delete the text size selection because it has the ability to make the text smaller and larger in the sora editor
I suggest leaving the search mode and the day and night mode is github and Dracula theme

**Comment by JavkhlanK** [comment]
Why should a feature be removed?

**Comment by Arashvscode** [comment]
> Why should a feature be removed?

Sora Editor has the ability to zoom in by hand, so the text gets bigger and smaller, well, there is no need for text size
Try adding search because you really need to find the error code

**Comment by JavkhlanK** [comment]
What's wrong with being able to set the text size to a specific value? Since the feature doesn't obstruct any other, it shouldn't be removed.

**Comment by Arashvscode** [comment]
> 


https://user-images.githubusercontent.com/101287880/167305049-43096af8-47a3-4329-b9e7-2c352c8269e8.mp4
Watch this video and you will realize that choosing the text size for sora editor is a meaningless thing

**Comment by Arashvscode** [comment]
> > 
> 
> Watch this video and you will realize that choosing the text size for sora editor is a meaningless thing


Uploading 20220508_204131.mp4…

**Comment by Arashvscode** [comment]
https://user-images.githubusercontent.com/101287880/167305276-e6a15cb2-0f5d-4699-a999-aacc72cdeab0.mp4

**Comment by JavkhlanK** [comment]
I know there's pinch-to-zoom in sora-editor. It doesn't provide setting the exact font size though, and that might be used by some.

**Comment by Arashvscode** [comment]
> I know there's pinch-to-zoom in sora-editor. It doesn't provide setting the exact font size though, and that might be used by some.
OK, so add the search feature

**Comment by JavkhlanK** [comment]
Working (that counts in tested) Pull requests are always welcome.

**Comment by Arashvscode** [comment]
> Working (that counts in tested) Pull requests are always welcome.
😂
I'm afraid to add and close my Pull😂

**Comment by khaled-0** [comment]
Not a real issue
