### ISSUE TITLE
Unknown error!

### ISSUE THREAD

**Issue by subompaul** [Sketchware-Pro/Sketchware-Pro#387]
![Screenshot_2022-05-11-12-33-40-812_com sketchware remod](https://user-images.githubusercontent.com/99627749/167792203-3f097787-03f5-43ce-8eed-92b75ae84ee3.jpg)
How to solve this error!

**Comment by Arashvscode** [comment]
This action may be repeated from the library. Please ask your questions in Discord

**Comment by JavkhlanK** [comment]
You can find more details on that in /Internal storage/.sketchware/debug.txt. Currently, that's happening most likely cause you have Local libraries enabled, which already are included by e.g. enabling AppCompat. If you want to fix that problem quickly, open the Local library causing that issue's classes.jar file as ZIP archive and remove the duplicate file, e.g. some file in /META-INF/.

**Comment by subompaul** [comment]
> You can find more details on that in /Internal storage/.sketchware/debug.txt. Currently, that's happening most likely cause you have Local libraries enabled, which already are included by e.g. enabling AppCompat. If you want to fix that problem quickly, open the Local library causing that issue's classes.jar file as ZIP archive and remove the duplicate file, e.g. some file in /META-INF/.

I did not understand 😅 can you please give your telegram.😄😄😄

**Comment by JavkhlanK** [comment]
I'm @jkhon0 on Telegram.

**Comment by subompaul** [comment]
> I'm @jkhon0 on Telegram.

There is no @jkhon0 there is @jkhon is it yours?🙂

**Comment by JavkhlanK** [comment]
Wait, right, my username there's @jkhon actually.

**Comment by subompaul** [comment]
> Wait, right, my username there's @jkhon actually.


After I tried reinstalling all the libraries 3 times, then I clicked run button then It showed 441 errors.

Then I found out that...
I have updated sketchware and the 3rd party components that I have used where not there.....I imported the components again **then it is working**!

thank you for helping!
