### ISSUE TITLE
Dont run apk file

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#391]
![Screenshot_۲۰۲۲۰۵۱۴-۰۱۵۷۵۹_Sketchware Pro](https://user-images.githubusercontent.com/101287880/168391994-304aac80-98e0-4a0f-ae03-4a080d9f20e0.jpg)
[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/8691434/debug.txt)

**Comment by JavkhlanK** [comment]
Looking at debug.txt, /Internal storage/.sketchware/local_libs/language-base_V_0.5.4/classes.jar doesn't exist. Fix your Local library configuration, for example by deleting /Internal storage/.sketchware/data/1329/local_library and afterwards enabling needed Local libraries again.
