### ISSUE TITLE
Timer dublicates

### ISSUE THREAD

**Issue by yusufquteb** [Sketchware-Pro/Sketchware-Pro#392]
![Screenshot_20220515-003331_Sketchware Pro](https://user-images.githubusercontent.com/65425995/168450346-60612d61-e1b8-4c1b-aa9d-4a6e72f860ac.jpg)
![Screenshot_20220515-003208_Sketchware Pro](https://user-images.githubusercontent.com/65425995/168450354-ee0091ba-bb57-4e73-a498-e85dbc716bcc.jpg)
![Screenshot_20220515-003155_Sketchware Pro](https://user-images.githubusercontent.com/65425995/168450357-3c23436e-f7f4-4625-9768-41acd2d8d634.jpg)

**Comment by JavkhlanK** [comment]
We're aware of that issue. It has already been fixed with 2bb7b2a9cf355273ed5813670d2fe1fb8ae81274, and it's only waiting to be released.

**Comment by yusufquteb** [comment]
Thank you for fast reply

**Comment by JavkhlanK** [comment]
Keeping open until v6.4.0-rc03 gets released.

**Comment by JavkhlanK** [comment]
v6.4.0-rc03 was just released, and the bug doesn't occur there anymore.
