### ISSUE TITLE
Duplicate Firebase database error

### ISSUE THREAD

**Issue by tfun037** [Sketchware-Pro/Sketchware-Pro#396]
![Screenshot_20220515-174025](https://user-images.githubusercontent.com/59114113/168472278-91ee0a8d-1d67-4eaa-81cf-0183e0d56912.png)
![Screenshot_20220515-174136](https://user-images.githubusercontent.com/59114113/168472290-112c01a7-4c17-41da-9945-4a947047d7f9.png)
Dublicate Firebase Database

**Comment by JavkhlanK** [comment]
Duplicate of #392.

**Comment by tfun037** [comment]
How to fix in temporary

**Comment by JavkhlanK** [comment]
Either revert to v6.4.0-rc01, or try removing duplicate fields with Command Blocks.
