### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#398]
![Screenshot_۲۰۲۲۰۵۱۵-۲۲۴۰۰۰_Sketchware Pro](https://user-images.githubusercontent.com/101287880/168487707-37bd9493-48de-4379-b63c-bb310c150709.jpg)
I downloaded the latest action, and when I run the program, it always shows me a message to create a res folder in the local libraries, while in previous versions this message was never displayed to me.

**Comment by khaled-0** [comment]
And how is this a bug?
It's literally on the message that what's going on

**Comment by JavkhlanK** [comment]
@khaled-0, look at the path, it's about built-in libraries. That's not supposed to happen, though one could achieve that by using a Developer Tools option.

Can you try clearing the app cache, and if that doesn't work, the app data?

**Comment by Arashvscode** [comment]
> 
This is strange for local libraries

**Comment by khaled-0** [comment]
So for some reason it expects built in libraries in data/data/...cache/libs/libs/
Manually copying all built in libs there fixes the issue.
But it shouldn't do that in the first place

**Comment by JavkhlanK** [comment]
Some? That's intended, see commit ebbc8f4af6ba5746319948520e021e8696907163. I'm sure it's also extracting built-in libraries to that location, since it worked on my device. I'm guessing this is another bug similar to the older …/res not found bug, where the ZIP file wasn't fully readable by some devices.

**Comment by khaled-0** [comment]
Wait no, so for some reason it doesn't try to extract the libs after first time

**Comment by JavkhlanK** [comment]
They aren't getting copied over to the cache directory, but instead, getting extracted there.

Since deleting those files isn't fatal and Sketchware Pro can extract them again on its own, using the cache directory is better, for example for users who want to quickly make some storage space free.

**Comment by khaled-0** [comment]
![Screenshot_20220516-221735403](https://user-images.githubusercontent.com/74397286/168638109-2ae73b7d-ad67-4e78-9731-2de2f04b4051.jpg)
Resulting in this.
But it doesn't show the following dialog anymore for me.

**Comment by JavkhlanK** [comment]
wait bruh lol

**Comment by JavkhlanK** [comment]
Weird, they did for me after I deleted the entire libs folder in the files directory.

**Comment by JavkhlanK** [comment]
Should have been fixed with 6bc31f7e8d97a896bd1fcff0a0883864837e94d0.

**Comment by khaled-0** [comment]
Even tho it's marked as fixed and it works 
I still couldn't replicate the same dialog anymore
It only showed once randomly in my testings.
Meh I hope it's the same issue and got fixed

**Comment by Arashvscode** [comment]
Tnks jbk0
