### ISSUE TITLE
Trustlook 

### ISSUE THREAD

**Issue by Hihellhhhhh** [Sketchware-Pro/Sketchware-Pro#403]
Hey Developers sketchware contains trustlook please remove it or can't publish in any platform please 
![Screenshot_2022-05-17-13-36-46-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87873993/168762371-74eb41f9-f8c0-4fab-a922-c77f096e1a64.jpg)

**Comment by Hihellhhhhh** [comment]
![Screenshot_2022-05-17-13-36-46-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87873993/168761967-f31f1678-eee5-43c4-a65e-bd08d992f1f9.jpg)
Not Only Trustlook Nano Virus Also 
Please Fix

**Comment by khaled-0** [comment]
Sketchware pro is not going to be published in any platform

**Comment by JavkhlanK** [comment]
Trustlook and NANO-Antivirus are most likely the names of the security vendors that reported Sketchware Pro as suspicious.

I couldn't find anything about the Riskware.… report, so I'm guessing it's just a false-positive. The other one about DebugKey can be explained simply, official Sketchware Pro releases get signed with testkey, a well-known public key with well-known private key. Since all Sketchware Pro versions were shipped signed with it, I didn't wanna change that.

**Comment by JavkhlanK** [comment]
Also just like @khaled-0 said, Sketchware Pro won't ever be distributed on e.g. Google Play. Doing that goes too far for the "modding for the community" philosophy in my opinion.

**Comment by Hihellhhhhh** [comment]
> Sketchware pro is not going to be published in any platform

I am not able to publish my application when signing from sketchware

**Comment by Hihellhhhhh** [comment]
> Also just like @khaled-0 said, Sketchware Pro won't ever be distributed on e.g. Google Play. Doing that goes too far for the "modding for the community" philosophy in my opinion.

It is containing just this 2 virus and my application is repeatedly rejected
So how to fix it

**Comment by khaled-0** [comment]
> > Also just like @khaled-0 said, Sketchware Pro won't ever be distributed on e.g. Google Play. Doing that goes too far for the "modding for the community" philosophy in my opinion.
> 
> It is containing just this 2 virus and my application is repeatedly rejected So how to fix it???????

People successfully published apps made with sketchware pro before (I myself personally did too).
So I don't know what platform you're using and why it thinks that the apps has virus. 
And we most likely can't possibly fix it.

**Comment by Hihellhhhhh** [comment]
> > > Also just like @khaled-0 said, Sketchware Pro won't ever be distributed on e.g. Google Play. Doing that goes too far for the "modding for the community" philosophy in my opinion.
> > 
> > 
> > It is containing just this 2 virus and my application is repeatedly rejected So how to fix it???????
> 
> People successfully published apps made with sketchware pro before (I myself personally did too). So I don't know what platform you're using and why it thinks that the apps has virus. And we most likely can't possibly fix it.

Sir can u please give me ur discord id or telegram I'd i need to contact u regarding my application u please tell me what's wrong there why it's telling that it has virus....

**Comment by JavkhlanK** [comment]
Was that APK analysis of your project or of Sketchware Pro itself? If it's your project, you have some weird code or libraries in use (except for the DebugKey detection).

Please also note that currently you have to sign exported AAB or APK files with another app such as apk-signer from Google Play to have valid signatures.

Another thing to note is that the APK in …/mysc/bin/ shouldn't be uploaded to Google Play. Export a (signed) APK instead.

**Comment by khaled-0** [comment]
Also probably invalid
