### ISSUE TITLE
App crash (rc03)

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#408]
App crash when click "show last compile error" with large errors (with 800-1200 errors)

**Comment by JavkhlanK** [comment]
fix your project's warnings / errors lmao

**Comment by khaled-0** [comment]
Btw I've seen 1900+ errors in a 5k+ line of class and it didn't even lag

**Comment by JavkhlanK** [comment]
Keeping open until v6.4.0-rc05 gets released.
