### ISSUE TITLE
Crash while importing firebase settings from another project.

### ISSUE THREAD

**Issue by JeremiahJacob261** [Sketchware-Pro/Sketchware-Pro#414]
Sketchware pro crashes while trying to "**_Import firebase information from other projects_**"
Please review my checks...

**Comment by JavkhlanK** [comment]
Did you get any error message or do you have a stack trace?

**Comment by JeremiahJacob261** [comment]
It was a stack Trace..

**Comment by JavkhlanK** [comment]
Well, can you share it with us or not? Without it, the report is basically useless.

**Comment by khaled-0** [comment]
Just don't import from other projects
Import from json.

It's a vanilla sw bug and the classes aren't decompiled yet ant kinda messy after decompiling
