### ISSUE TITLE
Firebase RTDB not working with the current version

### ISSUE THREAD

**Issue by LuckyDev256** [Sketchware-Pro/Sketchware-Pro#416]
I have tried with several projects but always failing to put map keys and values to firebase real time database.  
When I use SKETCHWARE 6.3.0 FIX1, it works on well but this version too has issues with filePicker component which has not been solved for a long time.

**Comment by JavkhlanK** [comment]
When upgrading to Sketchware Pro v6.4.0, you'll have to reconfigure projects using Firebase. As the updated strings in Library Settings say, you must replace the Project ID with the full database URL, as some new Databases can't be used in vanilla Sketchware and Sketchware Pro v6.3.0 fix1 and earlier's system.

Get the full database URL from the [Firebase Console](https://console.firebase.google.com), then remove the leading `https://` and `/` at the end to get an URL like this: `whatever-default-rtdb.asia-southeast1.firebasedatabase.app`. Then replace the current Project ID with that.

Even simpler would be to use Sketchware Pro v6.4.0-rc03 (or newer) and just import data from google-services.json (downloaded from Firebase Console).
