### ISSUE TITLE
issue : crash on block import from block manager menu

### ISSUE THREAD

**Issue by bloom11** [Sketchware-Pro/Sketchware-Pro#417]
hi there is an issue in the block loading menu from the dev option . The app often crash at the same  point when trying to create a new block collection "pallette" from the  menu while when direcly copying the new blocks file in the folder and replacing my previous blocks file it work perfectly. It work but it mean that you have to replace your block every time.
Knowing the importance of the debug report in order to solve the issue i search for a debug trace but unfortunately there  was none. There was no bug line added to the debug file when the app crash this way. But it was indeeed very easy to reproduce. Also an other little info to help , it seem that the app after every  crash, automatically bring a pop windows explaining that something went wrong and give the option to kill the app with a shut down button on the lower rigth corner of the pop up.

**Comment by JavkhlanK** [comment]
Could you please share the JSON file you're trying to import? And for clarification, could you also please make e.g. a screen recording of that issue?

**Comment by bloom11** [comment]
ok I will try to reproduce the issue  as soon as possible

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
