### ISSUE TITLE
Error not executing collections

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#422]
![Screenshot_20220528-005206_Sketchware Pro](https://user-images.githubusercontent.com/101287880/170784577-b4fae820-a04e-4a4e-8da7-b5fd8418f7fc.jpg)

https://user-images.githubusercontent.com/101287880/170784590-eda27eed-8182-4a24-9f11-8911e8a252d6.mp4

When I click on the collections, the program gets an error and jumps

**Comment by hasrat-ali** [comment]
Keep this open until new release published.

**Comment by Arashvscode** [comment]
Thanks for fixing bug

**Comment by JavkhlanK** [comment]
> Keep this open until new release published.

No need for that in this case, as that should happen only if the bug was in a released version, such as v6.4.0-rc03.
