### ISSUE TITLE
Speech to Text not working on Android 11 ERROR_INSUFFICIENT_PERMISSIONS

### ISSUE THREAD

**Issue by JamzApps** [Sketchware-Pro/Sketchware-Pro#425]
Getting ERROR_INSUFFICIENT_PERMISSIONS when using Speech to Text on android 11. Was working in rc01....

**Comment by JavkhlanK** [comment]
Resolved via https://t.me/sketchwarepro/180614.

**Comment by JamzApps** [comment]
forgot to add use legacy true
