### ISSUE TITLE
[BUG] Application simply crash when "Aligning APK"

### ISSUE THREAD

**Issue by codeszsoft** [Sketchware-Pro/Sketchware-Pro#428]
I have a problems when building my application using the latest version of "RELEASED" sketchware pro. The app automatically crashed at the "Aligning APK" message shown. How to fix this kind of stuff?, i passed the java compiling proccess so i thought if it was not my fault. I need your help please

**Comment by JavkhlanK** [comment]
Duplicate of #404.

You can try the workaround in #413 if you want to keep using v6.4.0-rc03.
