### ISSUE TITLE
Codeview issue

### ISSUE THREAD

**Issue by TechnicalStudioDevelopers** [Sketchware-Pro/Sketchware-Pro#429]
As there is some changes in code preview which is very smooth but Hold the cursor and see the error
![Screenshot_2022-06-01-08-16-20-547_com sketchware remod](https://user-images.githubusercontent.com/96680248/171317531-7cc431bc-9d1b-414f-af0e-35a2544e0b45.jpg)
When we hold the cursor and code doesn't zoom and it create error

**Comment by JavkhlanK** [comment]
Doesn't look like a Sketchware Pro bug to me, but a bug nonetheless.

**Comment by Rosemoe** [comment]
Solution: In the latest editor(0.11.4 about half month ago), obtain Magnifier object and magnifier.setWithinEditorForcibly(true);

**Comment by Rosemoe** [comment]
> Bug code editor

You can make one on your own if you are able to.
 **Intelligent you**
