### ISSUE TITLE
issus: Java code editor_ui bug_ bad erase action and movement 

### ISSUE THREAD

**Issue by bloom11** [Sketchware-Pro/Sketchware-Pro#430]
hi, there is an issu in the Java code editor. 
It happened at various moment and is replicable. When moved with the erase key of the keyboard the cursor doesn't erase the line before but instead goes at some random line above in the code file while the zoom action is still active. 

The movement to bring the cursor from one line to an other can also be  a bit complicated with the cursor no going at the expected line visible in the zoom bubble but instead staying where it was before or randomly choosing a line. 

Tips : a temporary solution is to use the option open with external editor which work perfectly 

https://user-images.githubusercontent.com/55237521/171340036-4a32450e-ce07-486f-b0f4-7055e329aa2e.mp4

**Comment by JavkhlanK** [comment]
Yeah, we've seen that bug even in v6.3.0 fix1. It seems to depend on which keyboard app (IME) was used, but anyway, it's definitely a bug of the code editor library in use in Sketchware Pro.

Which Sketchware Pro version did you use?

**Comment by Arashvscode** [comment]
Oh yes, I'm notifying this extension to the editor code builder

**Comment by Arashvscode** [comment]
> 

I saw this bug in version 0.9.0 I thought the manufacturer fixed it

If not, use version 0.8.4 because it is not much different from previous versions. In fact, the most stable version of the editor code is this version.

**Comment by JavkhlanK** [comment]
I don't think that bug's severity outweighs the improvements of the latest library version. AFAIK, using Gboard should work fine on all Sketchware Pro versions.

**Comment by Arashvscode** [comment]
It works well for me. I have a Samsung keyboard and a keyboard that I made myself

**Comment by Arashvscode** [comment]
https://user-images.githubusercontent.com/101287880/171407505-691f6c66-7409-4ca8-aad7-553e87135aa1.mp4

see in video

**Comment by bloom11** [comment]
I'm using the last compiled version which has the modifications implemented for the issue which was making impossible to erase global variable onecz created they were not appearing in the  variable menu.
version.installed :
v6.4.0-SNAPSHOT-ed42440 with AAB support 150

**Comment by JavkhlanK** [comment]
@bloom11, please look for duplicates first before reporting a bug. Your issue's being tracked in #419.

**Comment by bloom11** [comment]
> 



> @bloom11, please look for duplicates first before reporting a bug. Your issue's being tracked in #419.

No problem, ^^ you miss understood my word, I was answering the question

@JavkhlanK JavkhlanK commented 2 days ago
Yeah, we've seen that bug even in v6.3.0 fix1. It seems to depend on which keyboard app (IME) was used, but anyway, it's definitely a bug of the code editor library in use in Sketchware Pro.

Which Sketchware Pro version did you use?

**Comment by JavkhlanK** [comment]
Oh, sorry about that. I should've read your comment more thoroughly.

Could you then please see if you get the same issue while editing code in Java Manager?

**Comment by Rosemoe** [comment]
I'll try to adapt for the IME in next editor release.

**Comment by JavkhlanK** [comment]
can you try again using the latest nightly build? i'm pretty sure this has been fixed already
