### ISSUE TITLE
bug : issus in settings menu / impossible to exit the menu 

### ISSUE THREAD

**Issue by bloom11** [Sketchware-Pro/Sketchware-Pro#435]
hi i'm reporting a bug :
impossible to exit the settings menu  accessible only from the welcom page of sketchware pro app when outside of project. 

I'm using a debug versio' share to correct the bug of the global variable impossible to erase : 
version.installed :
v6.4.0-SNAPSHOT-ed42440 with AAB support 150

![Screenshot_20220603-131818_Sketchware Pro](https://user-images.githubusercontent.com/55237521/171844254-3bd6b412-99ad-4dd4-9e77-75465aeb79c3.jpg)

https://user-images.githubusercontent.com/55237521/171844301-6b45007d-fd31-4060-bd5a-1a5415948aa5.mp4

**Comment by anthony-china** [comment]
I just wanted to talk about this problem, but there was feedback.
