### ISSUE TITLE
Dont start App

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#437]
https://user-images.githubusercontent.com/101287880/171994222-41d03d8f-0bef-43c2-b714-f3b7b93a7daf.mp4

 The result of the last action tested is as follows: Version name of the output capability of aab output
The result is as follows: the program does not run

**Comment by JavkhlanK** [comment]
Could you tell what exact version you used? Something like v6.4.0-SNAPSHOT-3c60985c with AAB support would be appreciated.

**Comment by Arashvscode** [comment]
> 

Yes, I used the same version of the latest new action

**Comment by Arashvscode** [comment]
![Screenshot_20220604-143125_Samsung Internet](https://user-images.githubusercontent.com/101287880/171994586-644bcc03-d536-4184-8a68-b2edf8ed0dbd.jpg)

I always use the same version

**Comment by JavkhlanK** [comment]
By version I'm talking about the SNAPSHOT-<...> part before with/without AAB support. Your "latest" version might actually not be the latest one anymore.

**Comment by Arashvscode** [comment]
> 

I sent you a screenshot, you can see

**Comment by Arashvscode** [comment]
@hasrat-ali  my bro bug fixed?

**Comment by hasrat-ali** [comment]
> @hasrat-ali my bro bug fixed?
Yes

**Comment by Arashvscode** [comment]
> > @hasrat-ali my bro bug fixed?
> > Yes

Tnks
