### ISSUE TITLE
All images deleted in data folder

### ISSUE THREAD

**Issue by JamzApps** [Sketchware-Pro/Sketchware-Pro#439]
App deleted all my images in xmls so i had to replace them all. It deleted all images in my data folder. This was my biggest app too, so it took all day to add them again.

**Comment by khaled-0** [comment]
Also looks more like user fault
Close because not reproducible and dead?

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
