### ISSUE TITLE
Each time you enter the software, a prompt pops up!

### ISSUE THREAD

**Issue by anthony-china** [Sketchware-Pro/Sketchware-Pro#448]
![Screenshot_20220610_144251_com sketchware remod](https://user-images.githubusercontent.com/38490701/173006543-3466225f-0611-4d76-9b34-8db02ec3ae88.jpg)
You don't have to pop it up every time.For me, I have OCD. Every time I re-enter the software, strings XML is uncomfortable! Hope it can be removed! Load once and pop up.

**Comment by JavkhlanK** [comment]
It's just a toast, can't you ignore it? It's been that way in Sketchware Pro v6.3.0 fix1 and vanilla Sketchware.

**Comment by anthony-china** [comment]
This is just a suggestion
