### ISSUE TITLE
Analyzing crash logs every day！

### ISSUE THREAD

**Issue by taogeaidd** [Sketchware-Pro/Sketchware-Pro#451]

**Comment by taogeaidd** [comment]
![Screenshot_2022-06-13-03-47-36-86.jpg](https://user-images.githubusercontent.com/105388617/173254144-66bc6738-6980-4f68-9c7b-0acd21495cb9.jpg)![Screenshot_2022-06-13-03-49-45-71.jpg](https://user-images.githubusercontent.com/105388617/173254150-27a1cd6f-12bc-492e-8f5e-f6f09cf7522d.jpg)

**Comment by JavkhlanK** [comment]
Could you please clarify what you mean?

**Comment by khaled-0** [comment]
Invalid
Close when
