### ISSUE TITLE
Admob not work

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#452]
Admob's bug is well compiled, but as soon as the program arrives, it will be jumped and click on the application several times, even even the activity of the debug is not displayed

**Comment by JavkhlanK** [comment]
Could you at least show what errors you're getting?

**Comment by Arashvscode** [comment]
> 

An unspecified error does not even enter the program

**Comment by JavkhlanK** [comment]
Well, I couldn't reproduce the error on a project using interstitial ads.

**Comment by hasrat-ali** [comment]
@Arashvscode are you talking about actual `AdmobActivity`?

**Comment by Arashvscode** [comment]
Fixed
