### ISSUE TITLE
Menu items block not working

### ISSUE THREAD

**Issue by App-Developer-Ayush** [Sketchware-Pro/Sketchware-Pro#456]
When I want to create a menu in Toolbar with the events onCreateOptionsMenu and onOptionsItemSelected , I got an error. Here's the error:- 
----------
1. ERROR in /storage/emulated/0/.sketchware/mysc/630/app/src/main/java/com/my/newproject8/MainActivity.java (at line 68)
	menu.add(0, "Hello");
	     ^^^
The method add(int) in the type Menu is not applicable for the arguments (int, String)
----------
2. ERROR in /storage/emulated/0/.sketchware/mysc/630/app/src/main/java/com/my/newproject8/MainActivity.java (at line 69)
	menu.add(1, "Hello 2");
	     ^^^
The method add(int) in the type Menu is not applicable for the arguments (int, String)
----------
2 problems (2 errors)
![Screenshot_2022-06-15-12-40-58-675_com sketchware remod](https://user-images.githubusercontent.com/105949684/173765856-ac43cf84-3ec5-4f3b-9156-c6874e0ea01b.jpg)

**Comment by hasrat-ali** [comment]
did you use custom blocks?

**Comment by hasrat-ali** [comment]
Ok, i reproduced it.

**Comment by App-Developer-Ayush** [comment]
> did you use custom blocks?

Yes, I used the built-in custom block that the event onCreateOptionsMenu has.

**Comment by App-Developer-Ayush** [comment]
Please give a solution to fix this error

**Comment by hasrat-ali** [comment]
Create/use custom blocks or asd(s)

**Comment by App-Developer-Ayush** [comment]
> Create/use custom blocks or asd(s)

Okay, but please fix this error in next update.

**Comment by hasrat-ali** [comment]
Fixed with new release [v6.4.0-rc04](https://github.com/Sketchware-Pro/Sketchware-Pro/tree/refs/tags/v6.4.0-rc04)
