### ISSUE TITLE
This is in original sketchware problem, Keyboard always open after creating more block

### ISSUE THREAD

**Issue by JamzApps** [Sketchware-Pro/Sketchware-Pro#476]
They keyboard always pops back open after more block is created, a little annoying.

**Comment by JavkhlanK** [comment]
Just for clarification, when you create a More Block by pressing the FAB in DesignActivity or the Create button in LogicEditorActivity?

**Comment by Arashvscode** [comment]
This man is right, it's really annoying

**Comment by JamzApps** [comment]
> Just for clarification, when you create a More Block by pressing the FAB in DesignActivity or the Create button in LogicEditorActivity?
in Logic, maybe you could close keyboard before you create more block.

**Comment by JavkhlanK** [comment]
> > Just for clarification, when you create a More Block by pressing the FAB in DesignActivity or the Create button in LogicEditorActivity?
> 
> in Logic, maybe you could close keyboard before you create more block.

Alright, thanks.

Was able to reproduce, even in vanilla Sketchware.

**Comment by JamzApps** [comment]
> > > Just for clarification, when you create a More Block by pressing the FAB in DesignActivity or the Create button in LogicEditorActivity?
> > 
> > 
> > in Logic, maybe you could close keyboard before you create more block.
> 
> Alright, thanks.
> 
> Was able to reproduce, even in vanilla Sketchware.


yeah i should have said its an original problem, with original sketchware not a mod fault, its also on import block in logic

**Comment by JavkhlanK** [comment]
Fixed with commit cf09a6362c96726625da9f264c34d3cb5b927185.
