### ISSUE TITLE
Build Crush

### ISSUE THREAD

**Issue by denzkie2003** [Sketchware-Pro/Sketchware-Pro#477]
Sketchware Pro app keep crushing when building an apk.

**Comment by JavkhlanK** [comment]
Did you use Sketchware Pro v6.4.0-rc03? If yes, that sounds like the issue already reported in #404.

**Comment by denzkie2003** [comment]
Oh yes! sorry but I was hoping if it's fix?

**Comment by JavkhlanK** [comment]
See in #404, it was already fixed and the bugfix just needs to be released.

**Comment by JavkhlanK** [comment]
Link to Issue #404 if you're not viewing this thread in the GitHub webpage: https://github.com/Sketchware-Pro/Sketchware-Pro/issues/404

**Comment by denzkie2003** [comment]
Thanks, I'll check it out.
