### ISSUE TITLE
Ad mob not work

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#490]
https://user-images.githubusercontent.com/101287880/177123099-9fb24bc4-f0e1-4588-a89c-fa6c16f3b2da.mp4

Hi @JavkhlanK  & @hasrat-ali  admob not work plz fixed tnks

**Comment by rexllc** [comment]
It's same with mine. No fixes yet applied to this.

**Comment by JavkhlanK** [comment]
Keeping opened until the next version, v6.4.0-rc05, gets released.

**Comment by JavkhlanK** [comment]
Can you please leave it opened? We'll close it when v6.4.0-rc05 gets released.

**Comment by Arashvscode** [comment]
> 

Oh ok sorry 
![Screenshot_20220712-232010_Sketchware Pro](https://user-images.githubusercontent.com/101287880/178571778-b0905ed7-c595-4acb-973a-7fae57b22f0b.jpg)


Fixed bug in showing

**Comment by Ade-Firmansyah** [comment]
Give me link 👉

**Comment by JavkhlanK** [comment]
> Give me link 👉

It hasn't been released yet. Wait for v6.4.0-rc05's release.

**Comment by OECAPPS** [comment]
> 

When will u release it

**Comment by JavkhlanK** [comment]
When it's ready. Right now there's a major bug which has to be fixed first.

**Comment by OECAPPS** [comment]
and how long will that be

**Comment by JavkhlanK** [comment]
Great timing you had, lol. Commit f371eca5c91628eb34f16d4300de5c1008ed1720 should have fixed that bug. I'll prepare v6.4.0-rc05's release soon.

**Comment by OECAPPS** [comment]
Very good update
