### ISSUE TITLE
Viewpager error while setting tabcount

### ISSUE THREAD

**Issue by Insight-deviler** [Sketchware-Pro/Sketchware-Pro#492]
In the latest test build 4, while using viewpager, new error popping up which is not available in the older versions of the sk pro
The block used:
Viewpager setFragmetAdapter TabCount
Error showed
ERROR in /storage/emulated/0/.sketchware/mysc/601/app/src/main/java/sa/in/viewActivity.java (at line 84)
	5.setTabCount( );
	^^
Syntax error, insert "AssignmentOperator Expression" to complete Assignment
----------
[Error screenshot](https://www.dropbox.com/s/dmevrpdxcy06kob/screenshot_20220707-182243_sketchware%20pro.jpg?dl=0)

**Comment by JavkhlanK** [comment]
Yeah, I was thinking so too. Glad to see that Block finally work again.

**Comment by Insight-deviler** [comment]
Thanks bro for the help
