### ISSUE TITLE
Error in Exporting AAB file and App

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#498]
I made a keystore using [APK Signer](https://play.google.com/store/apps/details?id=com.haibison.apksigner) and was using Sketchware.Pro.v6.4.0-rc04-minApi26 version so that I can use Ad Mob, but got error at last
![Screenshot_20220711-194628](https://user-images.githubusercontent.com/92568876/178287172-856de570-9aa5-4cd1-a70a-e64bd1cecccf.png)
Also when I executed project normally (RUN button) my app crashes 
![Screenshot_20220711-194844](https://user-images.githubusercontent.com/92568876/178287323-05946d3e-a3c3-49db-9194-7330ce07e04f.png)

Also ad shows Test Ad instead of Real Ads in application maybe that's a APK singing issue

**Comment by JavkhlanK** [comment]
First issue: Yeah, it's probably a restriction of the signing library Sketchware Pro uses. Not sure how to fix that, but as workaround, try exporting an unsigned APK or AAB, and then sign the output using a 3rd party tool like apk-signer from Google Play.

Second issue: Does your project use the YouTube Player View? If yes, that's also a known issue, which also don't fully understand why. When exported, things magically work again. It's weird.

Third: You have to export projects for them to use the real ad ID. That's because AdMob can and will suspend accounts when you as developer watch real ads using the production ad unit ID.

**Comment by AdesonBezerra** [comment]
I was using test version 01 and was compiling AAB, when I migrated to new version it was not compiling

**Comment by AdesonBezerra** [comment]
![Screenshot_20220716-093251_Sketchware Pro](https://user-images.githubusercontent.com/106257193/179355446-d7e70169-8543-4b7f-9ecd-a8a194168d6b.png)
![Screenshot_20220716-093208_Sketchware Pro](https://user-images.githubusercontent.com/106257193/179355448-7a65b1e6-2e81-496d-99e9-a32d073d75c6.png)
![Screenshot_20220716-094344_Chrome](https://user-images.githubusercontent.com/106257193/179355449-28a14aa2-d590-4fc7-b8eb-94bb500600c7.png)

**Comment by AdesonBezerra** [comment]
it is generating the defective AAB

**Comment by AdesonBezerra** [comment]
I also verified that I succeed in exporting AAB without signing

![Screenshot_20220716-103218_Sketchware Pro](https://user-images.githubusercontent.com/106257193/179357147-2ed65843-9d61-4e94-b192-faf75f92b269.png)

**Comment by JavkhlanK** [comment]
Wow, okay. Thanks for reporting! I'd say Spongy Castle classes taken from Sketchware should be replaced with a Gradle dependency, that'd fix the issues that come from the dex2jar version I used to create .class/.jar files out of .dex files.

**Comment by JavkhlanK** [comment]
I'm not sure if we'll ever get signing with key stores made with tools other than Sketchware Pro to work though.

**Comment by AdesonBezerra** [comment]
if i create a signature key in Sketchware Pro can i get it? in the old version I was using a key that I created in apk-signer and it worked, I will try to create one in Sketchware Pro in this new version to see if it works

**Comment by JavkhlanK** [comment]
I advise you to export unsigned files and later sign them with a tool like apk-signer from Google Play, as I found out that key stores generated by and usable by Sketchware Pro currently are not "secure enough" for Google Play. (SHA1withRSA only, apparently, but SHA-1 hashing was sorta broken already)

**Comment by ayyoubmoqine** [comment]
✅✅

**Comment by AdesonBezerra** [comment]
What confuses me is that, in the test version rc01 it was working, I was able to sign, with the new versions no, this has nothing to do with PayStore

**Comment by JavkhlanK** [comment]
That makes sense as Sketchware Pro was fully ported to Android Studio / Gradle + Android Gradle Plugin after v6.4.0-rc01. There seemingly still are a few issues though, as you can see here.

**Comment by AdesonBezerra** [comment]
cool, so let's wait for the next updates

**Comment by JavkhlanK** [comment]
This should have been fixed with commit 32828fe1892630aa3c9d2676d05ce928c0876640.

**Comment by AdesonBezerra** [comment]
Since it's compiling and signing I believe this problem has been resolved

**Comment by JavkhlanK** [comment]
Thanks for testing it out!

**Comment by subhash16** [comment]
> Since it's compiling and signing I believe this problem has been resolved

Then close this issue
