### ISSUE TITLE
Code Editor Bug (Sora-Editor)

### ISSUE THREAD

**Issue by BanDroid** [Sketchware-Pro/Sketchware-Pro#502]
Demonstration video:
[]()https://drive.google.com/file/d/1N57CjbBE29n9O-40ZnYG6R_xmmlEEgeX/view?usp=drivesdk

Describe the bug:
Sora editor implementation in sketchware doesn't work well in my device, typing anything will create a new line instead of writing to the file. Please look up at the Sora-editor group, Rosemoe explained the bugs there.

Also, i'm using version test build 04-minApi-26 (latest release) and also tested on the debug github actions build, and still got the problem.

**Comment by JavkhlanK** [comment]
This was confirmed by Raival in the Discord server. What exact phone did you use?

**Comment by BanDroid** [comment]
![Screenshot_2022-07-21-18-07-17-108_com.android.settings.jpg](https://user-images.githubusercontent.com/68449470/180199696-dbc3cc75-2bea-4ced-aa7c-cbaddf53dac6.jpg)

**Comment by JavkhlanK** [comment]
Thanks!

**Comment by Arashvscode** [comment]
> ![Screenshot_2022-07-21-18-07-17-108_com.android.settings.jpg](https://user-images.githubusercontent.com/68449470/180199696-dbc3cc75-2bea-4ced-aa7c-cbaddf53dac6.jpg)


Try to use another keyboard. I also use Google keyboard and I have the same problem

**Comment by Raival-e** [comment]
This bug has been fixed in v0.15.1 of Sora Editor

**Comment by JavkhlanK** [comment]
Could any of you please try using the latest snapshot build and see if the bug's still occurring?

**Comment by BanDroid** [comment]
> Could any of you please try using the latest snapshot build and see if the bug's still occurring?

Yes i will, and i will close this issue my self after testing it, thanks

**Comment by JavkhlanK** [comment]
Please don't close it if you found out it was fixed, just let us know so that we can mark it as fixed, and close when v6.4.0-rc05 gets released.

**Comment by BanDroid** [comment]
Ok, thanks for telling me that

**Comment by BanDroid** [comment]
It is fixed, thanks.

**Comment by JavkhlanK** [comment]
Great, thanks @Rosemoe!

**Comment by JavkhlanK** [comment]
> Please don't close it if you found out it was fixed, just let us know so that **we can mark it as fixed, and close when v6.4.0-rc05 gets released**.
