### ISSUE TITLE
Request Network Error

### ISSUE THREAD

**Issue by SLSTunnel** [Sketchware-Pro/Sketchware-Pro#504]
When making an online app it won't work even when you connect and using a fast internet connection.

**Comment by JavkhlanK** [comment]
Could you give some more details of your issue? For example, showing how and what exactly you're doing with RequestNetwork would help significantly.

**Comment by subhash16** [comment]
Close this issue, it's working fine

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
