### ISSUE TITLE
Message when executing the app created with sketchware rc4

### ISSUE THREAD

**Issue by Yeused** [Sketchware-Pro/Sketchware-Pro#505]
Hello, good evening, I have the following problem, when I compile my application with sketchware rc04, after a few seconds of executing the already installed app it gives me the following error, I have tried compiling an empty app, I execute it and even so I get the message thank you

java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
	at android.widget.Toast$TN.<init>(Toast.java:390)
	at android.widget.Toast.<init>(Toast.java:114)
	at android.widget.Toast.makeText(Toast.java:277)
	at android.widget.Toast.makeText(Toast.java:267)
	at com.yeused.pruebasrapidas.SketchwareUtil.showMessage(SketchwareUtil.java:157)
	at com.yeused.pruebasrapidas.SketchLogger$1.run(SketchLogger.java:48)

**Comment by JavkhlanK** [comment]
Hi, thanks for reporting. That bug was already fixed with commit eca95dd307773b3971986328ba9697640733c1ba.

**Comment by YUGGI200** [comment]
Not fixed yet

**Comment by JavkhlanK** [comment]
> Not fixed yet

I think you mean that v6.4.0-rc05 has not been released yet. This Issue will stay open until it gets released. This bug has already been fixed though, just use a snapshot build to test it out.

**Comment by YUGGI200** [comment]
I can't understand this technical language / word "snapshot test" but I BELIEVE YOU
