### ISSUE TITLE
Admob error 

### ISSUE THREAD

**Issue by Anaknimam** [Sketchware-Pro/Sketchware-Pro#510]
![Screenshot_20220724_081744](https://user-images.githubusercontent.com/108710261/180627036-75eb5124-0bcf-47ae-8af8-5966a659c390.jpg)
![Screenshot_20220724_081750](https://user-images.githubusercontent.com/108710261/180627037-aca153e2-1e55-4dd2-b324-881169bcee8b.jpg)
![Screenshot_20220724_081805](https://user-images.githubusercontent.com/108710261/180627039-579ea5f1-7c08-402a-8da8-6429cf046617.jpg)
![Screenshot_20220724_081818](https://user-images.githubusercontent.com/108710261/180627041-016e058e-3c76-4ebe-aeaf-29cd036316e9.jpg)
 When I click the admob the screen will turn black and then it show the error

**Comment by hasrat-ali** [comment]
This issue is already fixed. Wait for next update.

**Comment by hasrat-ali** [comment]
And this issue is already tracked here. #490
