### ISSUE TITLE
Need help .my app

### ISSUE THREAD

**Issue by Kayr123** [Sketchware-Pro/Sketchware-Pro#518]
So i have this textview it's supposed to be (MYANMAR) i have a list view in other activities when i select something it print it in this text view 
I used ... activity put extra key ... On item selected ....

So when first activity created ( main page ) i put (text view set text . Activity get extra key ) 

THE problem is when the activity is started  i didn't choose a server yet so activity extra key is empty ..

Question : how to keep original text view the when i select something from list it will print it there 

Here is a video https://user-images.githubusercontent.com/109683667/181241524-c0d5a7c7-c66f-43f3-8512-ab7d9f59f30b.mp4

**Comment by JavkhlanK** [comment]
This repository and Issues section are for Sketchware Pro bugs or questions about it specifically only.
