### ISSUE TITLE
Multiplication of view events

### ISSUE THREAD

**Issue by AdesonBezerra** [Sketchware-Pro/Sketchware-Pro#523]
![Screenshot_20220731-165826_Sketchware Pro](https://user-images.githubusercontent.com/106257193/182047747-154d2e53-5295-4b2a-84c3-62ef20fdfeb2.png)

**Comment by JavkhlanK** [comment]
Probably related to commit d809a615ae19534b4b4dcbbe5ae47db11b4d74db. Will have to investigate.
