### ISSUE TITLE
Old textview codes are not working 

### ISSUE THREAD

**Issue by LilMpesa** [Sketchware-Pro/Sketchware-Pro#524]
**Some codes seem to be not properly put**

**Comment by JavkhlanK** [comment]
Can you tell more about what exactly the problem is? Some screenshots or at least steps to reproduce your issue would be helpful.

**Comment by LilMpesa** [comment]
Hi, I turned on this issue because codes embedded in the app are not
properly put and lack the common java coding type.
they return to be true thus they are wrongly formatted and they won't do
anything in the app i.e

BELOW IMAGE
the common code is *getBackground* "does not work"
Else supposed to be *getDrawable "*works like charm"
PROOF VIDEO

*https://drive.google.com/file/d/13m8IogC9mforr1KWCnq9_l1WPqH_3wBi/view?usp=drivesdk
<https://drive.google.com/file/d/13m8IogC9mforr1KWCnq9_l1WPqH_3wBi/view?usp=drivesdk>*
.

I can join your repo soon because I won't be online all the time,because I
School.
.
I can be the* [SKETCHWARE BUG BOUNTY FIXER]*
😪✌️

**Comment by JavkhlanK** [comment]
You'll have to use the Block specifically for the ImageView for it to work. It looks like this:

![setColorFilter example](https://user-images.githubusercontent.com/40118124/182243137-f48af97f-4f23-421f-948e-d196cf642538.png)

**Comment by JavkhlanK** [comment]
Also, how's that related to TextView?

**Comment by LilMpesa** [comment]
Human error ❗ mistook it with imageview.
But thanks I got your help on what I sought
