### ISSUE TITLE
Accerometer support

### ISSUE THREAD

**Issue by oong819** [Sketchware-Pro/Sketchware-Pro#525]
add support for accerometer
currently Sketchware Pro only support gyroscope, which is not supported on all device

**Comment by nonzzzz** [comment]
Gyroscope not supported by all devices? You're wrong.

**Comment by oong819** [comment]
the Sketchware app itself say Gyroscope not supported on all device

also read Android documents: https://developer.android.com/guide/topics/sensors/sensors_motion

**Comment by nonzzzz** [comment]
> the Sketchware app itself say Gyroscope not supported on all device
> 
> also read Android documents: https://developer.android.com/guide/topics/sensors/sensors_motion

The Sketchware says: 
_Your device does not support this hardware. This component may not function properly._
This does not mean that it is not supported by **all** devices.

**Comment by oong819** [comment]
i said not all device support gyroscope, not all device dont support gyroscope

**Comment by JavkhlanK** [comment]
Feel free to create a Custom Component, but there won't be any more new built-in Components in Sketchware Pro.

**Comment by oong819** [comment]
> Feel free to create a Custom Component, but there won't be any more new built-in Components in Sketchware Pro.

I dont know how to create a accelerometer  component, also dont see any tutorial

**Comment by JavkhlanK** [comment]
In the official Discord server there's tutorials for creating Custom Components by Main modder Mike: https://discord.com/channels/790686719753846785/797801500276424724/800831248007954444
