### ISSUE TITLE
Old library

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#526]
![Screenshot_20220802-155401_Sketchware Pro](https://user-images.githubusercontent.com/101287880/182363477-2a763938-4df5-406a-b5e0-888ef816d8d1.jpg)

Hello, please update the libraries to the latest version, thanks

**Comment by AdesonBezerra** [comment]
Also update the FirebaseDatabase

**Comment by JavkhlanK** [comment]
Duplicate of #469.
