### ISSUE TITLE
Error deleting projects

### ISSUE THREAD

**Issue by AdesonBezerra** [Sketchware-Pro/Sketchware-Pro#527]
I'm using this version, and when I delete projects the error.
![Screenshot_20220803-225851_Sketchware Pro](https://user-images.githubusercontent.com/106257193/182746792-14c30fca-1824-4015-b356-e20d379c17ff.png)

**Comment by JavkhlanK** [comment]
Try using the latest snapshot build, it should have fixed that bug.
