### ISSUE TITLE
Please reply

### ISSUE THREAD

**Issue by 1999ali1999** [Sketchware-Pro/Sketchware-Pro#534]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by 1999ali1999** [comment]
Welcome I want to know if sketchware is the latest version of java or the old version 8 +. We want more and more additions and improvements as well because it is a really great and almost complete application

**Comment by JavkhlanK** [comment]
Why couldn't you have found out yourself by downloading & testing the app?
