### ISSUE TITLE
Project, Blocks, Components randomly deleting

### ISSUE THREAD

**Issue by 1tsMeMario** [Sketchware-Pro/Sketchware-Pro#536]
Every so often while im working on a project, ill close sketchware and open it back up to find all my projects, blocks, and components deleted. i check the .sketchware folder but they are gone for good each time

**Comment by JavkhlanK** [comment]
This is the first time I'm hearing of this, and never got to reproduce that. All I can advise to frequently do is backing up your projects, Custom Components/Blocks/etc. as Sketchware Pro v6.4.0 still is unstable.

**Comment by AdesonBezerra** [comment]
When I enter an event and start editing the blocks, randomly they stack up the wrong way or get deleted, and it happens randomly, not every time,

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details like screen recordings or steps to reproduce. Without them, tracking this issue is useless as it can't be fixed.
