### ISSUE TITLE
Proguard error

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#542]
With regards and respect, the result of your last github action test regarding ProGuard running in Java 11 is as follows. The program works well with ProGuard, but it doesn't run. Test it yourself if you need it. Do you prefer a heavy and professional project or here?  Tell me to send you the error

Tnks sir

**Comment by Arashvscode** [comment]
> 

Yes tesing

**Comment by Arashvscode** [comment]
The blocks are extracted, but we face this error when importing


![IMG_20220819_191137_287](https://user-images.githubusercontent.com/101287880/185644067-e1c417bd-0bf3-40b7-b83c-339f28a2fc8f.jpg)

**Comment by JavkhlanK** [comment]
> With regards and respect, the result of your last github action test regarding ProGuard running in Java 11 is as follows. The program works well with ProGuard, but it doesn't run. Test it yourself if you need it. Do you prefer a heavy and professional project or here? Tell me to send you the error
> 
> Tnks sir

Yeah, the error message would definitely be needed.

**Comment by JavkhlanK** [comment]
> The blocks are extracted, but we face this error when importing
> 
> ![IMG_20220819_191137_287](https://user-images.githubusercontent.com/101287880/185644067-e1c417bd-0bf3-40b7-b83c-339f28a2fc8f.jpg)

Read the error message. A Custom Block has an invalid or no associated block palette. Anyway, it's not related to the initial issue of this GitHub Issue, why did you report/ask here?

**Comment by Arashvscode** [comment]
[Erro.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/9383657/Erro.txt)
[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/9383661/debug.txt)


See in file

**Comment by JavkhlanK** [comment]
You added Gson as Local library (again!), but didn't include its ProGuard rules. I'm not sure what exactly's missing, but this is not a Sketchware Pro bug.

**Comment by Arashvscode** [comment]
> 

This is not possible. I don't have this library at all in local libraries

**Comment by JavkhlanK** [comment]
Line 2652 in debug.txt says otherwise.

**Comment by Arashvscode** [comment]
> Line 2652 in debug.txt says otherwise.
Yes, I realized that I deleted it, but still the same error as before

**Comment by Arashvscode** [comment]
Fixed

**Comment by JavkhlanK** [comment]
Alright, good.
