### ISSUE TITLE
error when changing the property

### ISSUE THREAD

**Issue by AiceGate** [Sketchware-Pro/Sketchware-Pro#543]
Android 11
Sketchware Pro v6.4.0 test build 04

https://user-images.githubusercontent.com/99378880/185554329-39f7ec13-4a97-44f1-95e7-764eb3280a52.mp4

**Comment by JavkhlanK** [comment]
Could you please show the entire error message? Simply copy & pasting it here would work too, by the way.

**Comment by AiceGate** [comment]
![image](https://user-images.githubusercontent.com/99378880/185683509-c940b50a-b979-4d5a-8f70-fb0104bb4f12.png)

the error can't be copied :(

**Comment by JavkhlanK** [comment]
Can you show it in a screen recording or screenshots then?

**Comment by AiceGate** [comment]
https://user-images.githubusercontent.com/99378880/185686506-3cfcc6fa-ade5-445a-a3b3-66206566e385.mp4

**Comment by JavkhlanK** [comment]
Thanks!

**Comment by AiceGate** [comment]
https://user-images.githubusercontent.com/99378880/185686506-3cfcc6fa-ade5-445a-a3b3-66206566e385.mp4

**Comment by AiceGate** [comment]
I should be the one to say thank you.

**Comment by AiceGate** [comment]
sorry for my mistake. it turns out that this error occurs because the developer mode is on on my cellphone.
Forgive me.

**Comment by JavkhlanK** [comment]
I'm not really sure how having Developer mode on could do that, but alright, as long as your problem's solved, I'm fine with that.
