### ISSUE TITLE
MoreBlock after import not working 

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#555]
![IMG_20220828_173835](https://user-images.githubusercontent.com/88816748/187072345-94a42bbe-e262-48eb-a053-9f17deef7570.jpg)
![Screenshot_2022-08-28-17-38-05-40_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187072354-7194b466-01c2-4807-8ed3-2f3ab5bf57be.jpg)
![IMG_20220828_173923](https://user-images.githubusercontent.com/88816748/187072359-d1bae72b-9863-48e3-96ae-cb1a27e878a3.jpg)

Moreblock  after import  parameters not working

**Comment by JavkhlanK** [comment]
#555 🔔🔔🔔

anyway, what Sketchware Pro version did you use? Please make sure to include that in all reports.

**Comment by AndroXStudiO** [comment]
I am using last build version
from github

**Comment by JavkhlanK** [comment]
Thanks, I'll look into that.

**Comment by JavkhlanK** [comment]
Fixed with commit f7eccbb303e8b634286f0c2b701b2f861a301211: fix: Don't remove More Block parameters when importing from Collections. Thanks for reporting!
