### ISSUE TITLE
Command block not working 

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#556]
i am trying to change getContext().getApplicationContext() to getActivity()

but Only for this codes command block not working. but if i want to change any other codes then its working. i dnt know why i am facing this issue. any other better option instead Command block?

here my example :

![IMG_20220830_103443](https://user-images.githubusercontent.com/88816748/187350082-c7ada652-abcc-4b7a-9e81-fe751ed0bad7.jpg)
![IMG_20220830_103042](https://user-images.githubusercontent.com/88816748/187350100-f1ea5008-c5b9-4ac8-9169-de421f6dfd19.jpg)

**Comment by JavkhlanK** [comment]
Can you show your whole Command Block? By the way, you can save that single Block, and create a clean screenshot of just the Block when in Collections > Block.

**Comment by AndroXStudiO** [comment]
how to show full block?
LogicEditor page not zoom-able.

anyway see this pic 
![Screenshot_2022-08-30-19-22-11-17_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187448587-45e96b2a-26cf-4060-af3b-8bf79fd1a329.jpg)

**Comment by AndroXStudiO** [comment]
![Screenshot_2022-08-30-19-25-40-93_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187449033-30714f89-135e-4ecc-a655-d54400d09d81.jpg)


already i have tried > find-replace
>replace
>find replace all


i means all options.

**Comment by JavkhlanK** [comment]
Found the fix! Since `find-replace` and the other 2 similar commands use regular expressions, you must escape special characters like `(` with `\`. This Block works:

![bro](https://user-images.githubusercontent.com/40118124/187452158-be8e6a55-91ff-4414-83c9-b8d03e5b1161.png)

By the way, this is intended behavior. Even v6.3.0 fix1 does this.

**Comment by JavkhlanK** [comment]
@AndroXStudiO did it work? If yes, please tell, so I can "close" this question Issue.

**Comment by AndroXStudiO** [comment]
let me check

**Comment by AndroXStudiO** [comment]
YES. now WORKING with >fine-replace-all
and using escape special characters like \(\)\
