### ISSUE TITLE
SketchLogger Error With Custom Application Class

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#558]
i got this error when i am using Custom Application Class

![Screenshot_2022-08-31-14-13-42-70_530cacab4ad0eed970d4085057c2e61d](https://user-images.githubusercontent.com/88816748/187628764-8c353d35-d2d5-41a4-bc19-42f1ede116d6.jpg)

maybe that issue occurred for this line 

![IMG_20220831_141330](https://user-images.githubusercontent.com/88816748/187629182-5f436461-983f-4148-9b08-21016034c8b9.jpg)

**Comment by AndroXStudiO** [comment]
when i used Custom Application Class its not change with sketchLogger class......see that screenshort. 
after changed SketchApplication to my custom, but its still available at SketchLogger.

sorry for my bad English 🙂

**Comment by JavkhlanK** [comment]
I feel like it should be expected that things are gonna stop working when you do that, and that the user's advanced enough to fix those issues on their own if they change the application class name. Anyway, show your custom application class, looks like it's returning `null` in `getContext()` which obviously breaks the toast.

**Comment by AndroXStudiO** [comment]
See my CUSTOM Application class


![Screenshot_2022-08-31-14-37-22-72_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187636381-eae5a5bf-a30f-45c1-bfe4-6de4c3f91c49.jpg)
![Screenshot_2022-08-31-14-37-28-35_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187636511-ee5cc784-18c1-43ef-af82-26e28a729072.jpg)
![Screenshot_2022-08-31-14-37-34-22_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187636582-8760e8dd-b69f-4a5f-a3ca-cb1030a5822b.jpg)

**Comment by JavkhlanK** [comment]
Seems fine. Maybe you changed SketchLogger to not work anymore then. Can you show it, maybe as file this time?

**Comment by AndroXStudiO** [comment]
![Screenshot_2022-08-31-14-45-56-69_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/88816748/187637666-8674d455-8934-44f5-b119-4f2a3380ebd1.jpg)

**Comment by AndroXStudiO** [comment]
"Maybe you changed SketchLogger to not work anymore then. Can you show it, maybe as file this time?"------------ i'm not understood this line

**Comment by JavkhlanK** [comment]
How did that file even compile? You used a different application class that's not `SketchApplication`.

**Comment by AndroXStudiO** [comment]
then what is my problem and how to solve it?

**Comment by JavkhlanK** [comment]
Try replacing all `SketchApplication` references in SketchLogger.java with your custom application class' name.

**Comment by AndroXStudiO** [comment]
SketchAplication class still available after used own application file.

![Screenshot_2022-08-31-14-53-00-18_9bde489fb18d43e8729607528f1e9d52](https://user-images.githubusercontent.com/88816748/187639289-d8dc6ad9-4bc8-4556-b581-b2fd8c8ef46c.jpg)

**Comment by AndroXStudiO** [comment]
already i have converted all SketchApplication codes with my custom application

**Comment by JavkhlanK** [comment]
Alright I think that's why it compiled. Still try changing SketchLogger though, that should fix your problem,

**Comment by JavkhlanK** [comment]
Upcoming bugfix will not generate SketchApplication.java when a custom application class is in use, and replace uses of SketchApplication in generated files like SketchLogger with the custom application class. Automatically adding methods like `getContext()` to custom application classes won't happen though, at least not for now.

**Comment by AndroXStudiO** [comment]
then how to change SketchLogger?

using JavaManager i have to write my own SketchLogger?

**Comment by JavkhlanK** [comment]
Using Java Manager, yes. Just copy the file that got generated.

**Comment by AndroXStudiO** [comment]
Using Java Manager and Own SketchLogger class...its fix my issue ❤️ for now.

**Comment by JavkhlanK** [comment]
Should have been implemented with commit 09a45b7bf4b296260b3f87805e4baa75afb15396.
