### ISSUE TITLE
New Issue with Last-Build version from Github

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#561]
![Screenshot_2022-08-31-16-07-17-15_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/187654519-0c2f6f46-0178-4f9c-9b5f-dbbada4393e3.jpg)

**Comment by JavkhlanK** [comment]
Was fixed with commit 3b334d3b7bb5697e0b2814105dffbb11f6eb835c (revert: Rename method in a.a.a.Lx back to obfuscated name).
