### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by MuhammadKalimullahkhan** [Sketchware-Pro/Sketchware-Pro#566]
When ever I try to add an admob banner or interstitial ads ID the app crashes.

**Comment by JavkhlanK** [comment]
Duplicate of #490. This is a known issue of v6.4.0-rc04 as mentioned in the release notes, and will be fixed with v6.4.0-rc05.

**Comment by MuhammadKalimullahkhan** [comment]
Ok, thank you sir
