### ISSUE TITLE
No way to remove build-in imports like CodeView / LottieAnimation

### ISSUE THREAD

**Issue by Maks-gaming** [Sketchware-Pro/Sketchware-Pro#571]
There is no way for users to remove built-in component imports in case they need to supply their own with the same class name. This issue is likely to be of great importance to users.

Maybe it is high-priority issue?

**Comment by JavkhlanK** [comment]
Don't Java Command Blocks work?

**Comment by Maks-gaming** [comment]
> Don't Java Command Blocks work?

No, if i'll add for example custom codeview lib with the same classname, then a class conflict error will appear

**Comment by Maks-gaming** [comment]
Conflict with built-in codeview, but its not used
![Screenshot_20220907-085148_Sketchware Pro.jpg](https://user-images.githubusercontent.com/77161824/188798968-ab0e2e6b-bad5-41f7-88e5-86b4320d0dd8.jpg)

**Comment by Maks-gaming** [comment]
nvm, found it, but still dont understand how to use it

**Comment by JavkhlanK** [comment]
There are tutorials on Command Blocks in our Discord server in channel #tips-n-tricks.
