### ISSUE TITLE
Custom Typed More Block Restoring Bug

### ISSUE THREAD

**Issue by arab-ware** [Sketchware-Pro/Sketchware-Pro#574]
Hello there devs !
When I restore a custom more block from saved collection like listString more block it broke the name and that cause java build error .....
I am using the latest sketchware pro 04 rc !

![Screenshot_20220907-230211_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968266-f0b25486-51f6-467a-9b1a-ade29ede9afb.jpg)
![Screenshot_20220907-230213_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968271-5855342f-33a8-4ffd-9a30-0d7ab5987690.jpg)
![Screenshot_20220907-230215_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968274-44400047-e47f-48c2-aa27-4d28776f7ace.jpg)
![Screenshot_20220907-230216_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968276-6ede03ec-181d-4805-9eb8-9a44e56d7d94.jpg)
![Screenshot_20220907-230222_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968279-d4380360-bf91-45f8-ac11-6caf8c285d2a.jpg)
![Screenshot_20220907-230235_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968281-83e866ca-6100-44d1-8e13-64c5020c4f45.jpg)
![Screenshot_20220907-230237_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968283-35191656-f973-44cb-8678-4d8b4b36cbde.jpg)
![Screenshot_20220907-230433_Sketchware Pro](https://user-images.githubusercontent.com/80012174/188968286-a7b71dc1-8cd4-4742-8a21-16ff9cf04ee6.jpg)

**Comment by JavkhlanK** [comment]
This bug only occurs on More Blocks with a return type that contains a space, such as List String, and not e.g. int.

**Comment by JavkhlanK** [comment]
Fixed with commit c454b1a6edf10844d226e0708f92c3ca34805abf.
