### ISSUE TITLE
REQUEST TO ADMINS

### ISSUE THREAD

**Issue by MoeeLaaMinn** [Sketchware-Pro/Sketchware-Pro#576]
-PLEASE ADD FUNCTION LAYOUT WIDTH & HEIGHT 
android:layout_width="fill_parent"
android:layout_height="fill_parent"
-PLEASE RE-ADD DIRECT SOURCECODE EDITOR
-PLEASE CHANG LINEAR LAYOUT TO CONSTANT LAYOUT.

**Comment by JavkhlanK** [comment]
1. Why are you screaming?
2. fill_parent essentially is match_parent, just with a different name. Look it up, it's even deprecated now, and you should instead use match_parent.
3. The Direct Source Code Editor was removed for a reason. You should use Command Blocks instead, or to edit Java files more freely, create replacements in Java Manager with the same filename. For more details, [see this explanation in the Discord server](https://discord.com/channels/790686719753846785/790749749522464779/908817727878201424).
4. You can't just change a layout type to another and expect all projects using it to work again.
