### ISSUE TITLE
Xml Comment Block Not Work

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#577]
The test result of the last available action, min api version 26, the xml comment block does not work

Tesing in version

https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3029520409

**Comment by JavkhlanK** [comment]
Was able to reproduce, thanks for reporting.

**Comment by Arashvscode** [comment]
Fixed bug???
@JavkhlanK

**Comment by AdesonBezerra** [comment]
It's not working on mine either, neither XML nor Java

**Comment by AdesonBezerra** [comment]
Command Blocks not working

**Comment by JavkhlanK** [comment]
Fixed with commit 85297e180abeb244e79fb6ff4384f2de7ea0119c. This run's APK has the fix included: https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3161563843
