### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Parenthesice** [Sketchware-Pro/Sketchware-Pro#581]
After using the advanced (more) feature for editing a widget there is a crash report

**Comment by ilyassesalama** [comment]
What do you mean by "advanced (more) feature"? Can you take a screenshot of the error or steps to reproduce the crash?

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
