### ISSUE TITLE
Error while using old Projects on new sketchware

### ISSUE THREAD

**Issue by jithinpkflash** [Sketchware-Pro/Sketchware-Pro#582]
I m using sketchware pro 6.3.0 fix 1
But Everytime i try to update to new version. Its not working with my existing projects.
I have a big project it wont work.
am attaching the ss below
![IMG_20220917_215244_550](https://user-images.githubusercontent.com/67454799/190866846-1b4d0527-dbbd-4243-80fb-77731ed67a30.jpg)

**Comment by JavkhlanK** [comment]
This is a known issue in v6.4.0-rc04, and already was fixed. Wait for v6.4.0-rc05's release or use an earlier version, like v6.4.0-rc03.

**Comment by subhash16** [comment]
When will release rc5

**Comment by JavkhlanK** [comment]
There are no fixed release dates, it'll be released when we feel like it is ready. And that's not soon, at least until current Logic Editor bugs are fixed.
