### ISSUE TITLE
Wrongly stacked blocks in the block editor

### ISSUE THREAD

**Issue by AdesonBezerra** [Sketchware-Pro/Sketchware-Pro#583]
When I enter an event and start editing the blocks, randomly they stack up the wrong way or get deleted, and it happens randomly, not every time, 

This happens when I drag a block, either from the palette or when I copy code that is already there

This bug is bad to reproduce because it doesn't appear every time, it appears randomly, but I'll try to take a print.

Just happened to me in the onBindCustomView event 

I also verified that when using the if block only this happens, but when using the filled if it does not I also verified that when using the if block only this happens, but when using the filled if it does not 

I'm using the Commit 348d9bf version

**Comment by AdesonBezerra** [comment]
![Screenshot_20220918-122601_WhatsApp](https://user-images.githubusercontent.com/106257193/190914930-80ccd555-2fdb-49c8-b80a-e5a4c1317665.png)
![Screenshot_20220918-122556_WhatsApp](https://user-images.githubusercontent.com/106257193/190914933-dcb3a781-54ca-40d6-9d32-b66bb86c65ca.png)

**Comment by IslanBrazil** [comment]
pt-BR: Mano, por favor, na próxima vez tu coloca títulos em inglês.
en: Bro, please, next time you put titles in English.

**Comment by JavkhlanK** [comment]
Could you try to screen record while that's happening and share that here?

**Comment by AdesonBezerra** [comment]
It usually happens when we copy the blocks, and drag several times, that is, when we are working on that eventIt usually happens when we copy the blocks, and drag several times, that is, when we are working on that event

**Comment by AdesonBezerra** [comment]
It usually happens when we copy the blocks, and drag several times, that is, when we are working on that event

**Comment by JavkhlanK** [comment]
Just like #611, I think I've fixed this bug recently. Can you try using a recent snapshot build to confirm it?
