### ISSUE TITLE
Update firebase version to 19.3.0

### ISSUE THREAD

**Issue by AdesonBezerra** [Sketchware-Pro/Sketchware-Pro#585]
With firebase version 19.3.0 we will be able to use increment values ​​to send data to the database easily and you can also use the write timestamp

This change takes no more than 3 lines of code and won't mess up old projects before this change.

In this way we will be able to use the methods:
ServerValue.TIMESTAMP
ServerValue.increment(0)

Example:
send.put("balance", ServerValue.increment(1));
send.put("timestamps", ServerValue.TIMESTAMP);
Db.path("users/uid).update(send);

import com.google.firebase.database.ServerValue;

Note: I already made the modification using the latest version and it worked without problems, follow the video of how I did it to edit the mod
https://drive.google.com/file/d/1PdvlJ_PlPtWpQwMGXjFlEXYXO5Iwp3N6/view

**Comment by JavkhlanK** [comment]
Updating from 19.0.0 to 19.3.0 might actually contain no backwards-incompatible changes, so that looks like a doable change!

**Comment by AdesonBezerra** [comment]
How cool, this update will help my group of friends a lot, I hope they update, none of my tests failed in relation to backwards compatibility.

**Comment by AdesonBezerra** [comment]
I'm waiting for this update because it is very important for my group of programmers.

**Comment by khaled-0** [comment]
bor just do it already
he's desperate

**Comment by JavkhlanK** [comment]
I'm busy right now, but when I can, I'll get to it.

**Comment by adesonob** [comment]
Please looking forward to this update.

**Comment by JavkhlanK** [comment]
Done. Could you please test the latest snapshot build with it out?
