### ISSUE TITLE
Object animator not working.

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#586]
Object animator not working like rotation.
When will release rc05.

**Comment by JavkhlanK** [comment]
Can you be more specific than just 'not working'? Any exact steps to reproduce, or what exact Block isn't doing what it says?

**Comment by subhash16** [comment]
Like set property rotation.

**Comment by JavkhlanK** [comment]
More details please, could you maybe send a screen recording or an SWB of the project where it's 'not working'?

**Comment by subhash16** [comment]
[Tiles.zip](https://github.com/Sketchware-Pro/Sketchware-Pro/files/10880231/Tiles.zip)

**Comment by subhash16** [comment]
No answer

**Comment by HAKANKOKCU** [comment]
did you put 1 to duration? duration should be miliseconds. seconds×1000

**Comment by subhash16** [comment]
> did you put 1 to duration? duration should be miliseconds. seconds×1000

I have provided swb

**Comment by JavkhlanK** [comment]
> I have provided swb

And that project works just fine. Even rotating a View, e.g. like this:  
![](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/40118124/449a62ea-078d-4d12-b48f-e493ebc7f976)

So, what exactly is your problem?

**Comment by HAKANKOKCU** [comment]
dont disable animator animations at developer options of your device

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.

**Comment by subhash16** [comment]
> dont disable animator animations at developer options of your device

Thank you for telling that that is the main thing that create the problem
