### ISSUE TITLE
Compress .mp3 when converting to .aab

### ISSUE THREAD

**Issue by yusufquteb** [Sketchware-Pro/Sketchware-Pro#596]
I have an application which have many mp3 files in asset
After converting to apk runs normally 
After converting to aab no sound plays

**Comment by JavkhlanK** [comment]
Which exact Sketchware Pro version did you use, e.g. v6.4.0-rc01?

**Comment by JavkhlanK** [comment]
Is there any specific error message you're getting in the app or something? Could you maybe share an AAB and APK of that project?

**Comment by yusufquteb** [comment]
> Is there any specific error message you're getting in the app or something? Could you maybe share an AAB and APK of that project?

No errors appears ,just no sounds plays
I searched the web
They say must add this line to 
build.gradle

aaptOptions{
noCompress "mp3"
}

I don't know how to share files here

**Comment by JavkhlanK** [comment]
Anything related to build.gradle isn't related to Sketchware and Sketchware Pro. They don't use Gradle to build projects.

What tool did you use to convert that AAB into a usable file? I feel like I once saw a report complaining about an AAB "bug" that should actually have been caused by the conversion app.

You could upload files to e.g. MediaFire and just paste the link in here.

**Comment by yusufquteb** [comment]
> Anything related to build.gradle isn't related to Sketchware and Sketchware Pro. They don't use Gradle to build projects.
> 
> What tool did you use to convert that AAB into a usable file? I feel like I once saw a report complaining about an AAB "bug" that should actually have been caused by the conversion app.
> 
> You could upload files to e.g. MediaFire and just paste the link in here.

I use sketchware rc04 to convert to aab

**Comment by JavkhlanK** [comment]
I meant the app you used to convert the AAB to e.g. an APK.

**Comment by yusufquteb** [comment]
> I meant the app you used to convert the AAB to e.g. an APK.

App bundle installer
Or
Apk Abb converter

**Comment by JavkhlanK** [comment]
Can you share the AAB file and output APK file so that I can have a look at them?

**Comment by yusufquteb** [comment]
> Can you share the AAB file and output APK file so that I can have a look at them?

Iam uploading right now

**Comment by yusufquteb** [comment]
> > Can you share the AAB file and output APK file so that I can have a look at them?
> 
> Iam uploading right now

Apk file

https://t.me/mynationdreams/10

Aab file

https://t.me/mynationdreams/11

**Comment by JavkhlanK** [comment]
Thanks, will look at them now.

**Comment by yusufquteb** [comment]
> Thanks, will look at them now.

Thank you bro🥰

**Comment by yusufquteb** [comment]
> Thanks, will look at them now.

This link in google play

https://play.google.com/store/apps/details?id=firstwords.mynationdreams

**Comment by JavkhlanK** [comment]
Just checked, and in the AAB those asset files are compressed somehow. Gonna investigate further.

**Comment by yusufquteb** [comment]
> Just checked, and in the AAB those asset files are compressed somehow. Gonna investigate further.

Tank you for helping 🌹

**Comment by shapun963** [comment]
you need to use             Config$Compression#addAllUncompressedGlob(extensions to not compress)
inorder to not compress it.

**Comment by yusufquteb** [comment]
> you need to use             Config$Compression#addAllUncompressedGlob(extensions to not compress) inorder to not compress it.

How?

**Comment by shapun963** [comment]
> > you need to use             Config$Compression#addAllUncompressedGlob(extensions to not compress) inorder to not compress it.
> 
> How?

You cant change on your end .It must be changed in sk pro.

**Comment by JavkhlanK** [comment]
> you need to use             Config$Compression#addAllUncompressedGlob(extensions to not compress) inorder to not compress it.

Thanks, I'll try to use that to add already not compressed files in the main module archive to the uncompressed list.

About 14 hours ago I found out that adding `--uncompressed` to the bundletool cmdline fixed the compression issue, and that the main module archive created by Sketchware Pro had asset files uncompressed. I couldn't share that here though, I fell asleep during my break lmao

**Comment by yusufquteb** [comment]
> > you need to use             Config$Compression#addAllUncompressedGlob(extensions to not compress) inorder to not compress it.
> 
> Thanks, I'll try to use that to add already not compressed files in the main module archive to the uncompressed list.
> 
> About 14 hours ago I found out that adding `--uncompressed` to the bundletool cmdline fixed the compression issue, and that the main module archive created by Sketchware Pro had asset files uncompressed. I couldn't share that here though, I fell asleep during my break lmao

Can you share it with me?
Can't move on  in my app

**Comment by JavkhlanK** [comment]
> > > you need to use             Config$Compression#addAllUncompressedGlob(extensions to not compress) inorder to not compress it.
> > 
> > 
> > Thanks, I'll try to use that to add already not compressed files in the main module archive to the uncompressed list.
> > About 14 hours ago I found out that adding `--uncompressed` to the bundletool cmdline fixed the compression issue, and that the main module archive created by Sketchware Pro had asset files uncompressed. I couldn't share that here though, I fell asleep during my break lmao
> 
> Can you share it with me? Can't move on in my app

No, please wait for the bug to be fixed properly.

**Comment by JavkhlanK** [comment]
That's nice. Thanks for mentioning the bundletool API, @shapun963!
