### ISSUE TITLE
Unknown error, the norm of not executing the outputted programs

### ISSUE THREAD

**Issue by Arashvscode** [Sketchware-Pro/Sketchware-Pro#598]
The result of the last test action, old projects compile well, but do not enter the program. It has been tested on several old projects, but the program does not run. Unknown error.
Using in version Min api 26 
https://github.com/Sketchware-Pro/Sketchware-Pro/suites/8457008997/artifacts/375345400

**Comment by PranavPurwar** [comment]
Disable proguard @Arashvscode

**Comment by JavkhlanK** [comment]
Can you give any more details, such as if any error message showed up? If not, maybe the project as SWB? I couldn't reproduce any "not running" issues with my test projects. ProGuard was enabled, by the way.

**Comment by PranavPurwar** [comment]
Idk mostly it is proguard that messes up with your code or just you cannot code properly

**Comment by Arashvscode** [comment]
> Disable proguard @Arashvscode

لThis feature is not active because the project is very old, maybe for 6 months ago

**Comment by Arashvscode** [comment]
> 

I explain very well. I compile the project well, then install it, but it does not enter the program. Not only this, but I also import several old projects, the same problem occurs. It does not even enter the debug activity. In very old versions of sk pro, this is the case.  do not fall

**Comment by Arashvscode** [comment]
https://t.me/ProTeam25/24
Using in project to test
Name vsm = vs oode Mobile
Size Swb File 74Mb

**Comment by PranavPurwar** [comment]
Your code causes crash. Not a SWPro bug

**Comment by JavkhlanK** [comment]
I couldn't get that to compile, and I'm not willing to fix those weird errors, especially on such a project full of weird unused classes and more. Without any stack trace / error message, I can't help.

**Comment by Arashvscode** [comment]
> 

This is just a very very simple project from me, so if you see my other projects, I don't think you are programming anymore!

**Comment by PranavPurwar** [comment]
"very simple, old, broken, copied from other sources, non-compilable, project", you are not the one to decide that, btw

**Comment by PranavPurwar** [comment]
anyways, not an swpro bug

**Comment by Arashvscode** [comment]
> 

Ok tnks

**Comment by Arashvscode** [comment]
@JavkhlanK  + @PranavPurwar  ples Try add jdk17

**Comment by JavkhlanK** [comment]
Forgot already what was discussed in #468? Stop still asking annoyingly about it like a child.
