### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by LilMpesa** [Sketchware-Pro/Sketchware-Pro#600]
sketchware app crashes when I somehow use the Java Command blocks, but not often😒

**Comment by JavkhlanK** [comment]
More details? Should we just guess what could be wrong or what?

Screenshots of used Blocks (the Block being shown fully!), and error message would be great, else this discussion will go nowhere.

**Comment by LilMpesa** [comment]
I'll update your error.......give me sometime for it to show up.....

closing with return 😌

**Comment by LilMpesa** [comment]
Your sora editor has problems ❗

![Screenshot_20221006-035730.png](https://user-images.githubusercontent.com/108099689/194228222-32442fc6-afd3-427f-88db-45e2ccece591.png)

**Comment by LilMpesa** [comment]
I'm forwarding to you so that you may forward to them😂 Sora affects your app code on its implementation......

@Arashvscode stop being annoying 😒

**Comment by JavkhlanK** [comment]
@LilMpesa next time please don't reopen an already closed Issue with a new comment unrelated to the comments earlier in that thread.

**Comment by JavkhlanK** [comment]
Should probably have been fixed with the upgrade to sora-editor v0.17.2.
