### ISSUE TITLE
About

### ISSUE THREAD

**Issue by Jeiel17** [Sketchware-Pro/Sketchware-Pro#604]
I was banned from the Discord server due to a bot that uploaded without my consent. Sorry. Please give me at least the current version of Sketchware pro.

```v6.4.0-rc04-minApi26```

**Comment by RealNethical** [comment]
lmao thats not even a issue and btw whats your discord username

**Comment by JavkhlanK** [comment]
This is an issue tracker for Sketchware Pro bugs. Please don't open issues for things like that in the future again.

**Comment by Jeiel17** [comment]
> lmao thats not even a issue and btw whats your discord username

Jetronix#7173

**Comment by Jeiel17** [comment]
> This is an issue tracker for Sketchware Pro bugs. Please don't open issues for things like that in the future again.

Yes. I am aware of this.

**Comment by Jeiel17** [comment]
```a.a.a.By: Failed to add /storage/emulated/0/.sketchware/libs/local_libs/CyberAlpha IOS Dialog/classes.jar
	at a.a.a.Dp.g(Dp.java:645)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1047)
	at a.a.a.MA.a(Unknown Source:11)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1152)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:895)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)```

**Comment by JavkhlanK** [comment]
The first line of that says `a.a.a.By: Failed to add /storage/emulated/0/.sketchware/libs/local_libs/CyberAlpha IOS Dialog/classes.jar` (though not visible in GitHub for some reason). Check if that mentioned file exists, if not, remove it as Local library dependency first.

By the way, you can use comment previews to avoid issues like the cut off text in the future. Just click on Preview right above the comment box and have a look before posting.

**Comment by JavkhlanK** [comment]
I couldn't unban you by the way, found no banned user with that tag.

**Comment by Jeiel17** [comment]
> The first line of that says `a.a.a.By: Failed to add /storage/emulated/0/.sketchware/libs/local_libs/CyberAlpha IOS Dialog/classes.jar` (though not visible in GitHub for some reason). Check if that mentioned file exists, if not, remove it as Local library dependency first.
> 
> By the way, you can use comment previews to avoid issues like the cut off text in the future. Just click on Preview right above the comment box and have a look before posting.

Not solved. I uncheck the checkbox plus Sketchware Pro check it again. I delete the element and Sketchware pro asks to create it mandatory.

**Comment by JavkhlanK** [comment]
If that's the case, write down all Local libraries you want enabled in your project, then delete /Internal storage/.sketchware/data/\<project ID\>/local_library, then enable all those you want in the project again.

**Comment by PranavPurwar** [comment]
not an swpro bug

**Comment by Jeiel17** [comment]
> If that's the case, write down all Local libraries you want enabled in your project, then delete /Internal storage/.sketchware/data/\<project ID\>/local_library, then enable all those you want in the project again.

Already did that. Sketchware pro still persists. I will wait for the next update to use it.

**Comment by Jeiel17** [comment]
> not an swpro bug

In fact it is. I create other projects and even if I deleted the element or unchecked Sketchware pro still persists in the element.

**Comment by JavkhlanK** [comment]
> > If that's the case, write down all Local libraries you want enabled in your project, then delete /Internal storage/.sketchware/data/<project ID>/local_library, then enable all those you want in the project again.
> 
> Already did that. Sketchware pro still persists. I will wait for the next update to use it.

I've fixed that with commit e965df5cf91ceae202cfec9d7c822c41103030d3. If you want to already test it out, use this snapshot build: https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3257262524  
If you don't know what to do with that, open the link, scroll down, and click on app-minApi21 or app-minApi26, depending on what Android version your device runs. MinApi26 is for Android 8 and above only.

**Comment by JavkhlanK** [comment]
Update: Use [this version] instead, the previous one can't open up Local library Manager.

[this version]: https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3259061210

**Comment by Jeiel17** [comment]
> Update: Use [this version] instead, the previous one can't open up Local library Manager.
> 
> [this version]: https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3259061210

Don't forget to unban on Discord please.

**Comment by JavkhlanK** [comment]
> I couldn't unban you by the way, found no banned user with that tag.
