### ISSUE TITLE
Weird Block Behavior

### ISSUE THREAD

**Issue by oong819** [Sketchware-Pro/Sketchware-Pro#611]
Cant really describe this but look at the screenshots

app version: sorry dont remember i download it from actions tab

but i have a download link form browser download history https://pipelines.actions.githubusercontent.com/serviceHosts/523ebe16-815d-4d58-b433-717bd98e7c9a/_apis/pipelines/1/runs/371/signedartifactscontent?artifactName=apk-minApi21-debug&urlExpires=2022-10-14T04%3A39%3A08.7236327Z&urlSigningMethod=HMACV2&urlSignature=qZAeNmcsA1uviXzhn%2F2o%2BfXgBeIEScp4%2Bnm%2Bk10bxEU%3D

this bug also happen in 6.4.0 rc4

sorry dont have enough storage to record a video

![Screenshot_20221014-144815](https://user-images.githubusercontent.com/76146430/195793607-085f9ae1-67b6-4dea-93d7-baa288da4b6d.png)
![Screenshot_20221014-144823](https://user-images.githubusercontent.com/76146430/195793631-e96c9724-d6c3-41ff-8474-75a7bdc7b6cd.png)
![Screenshot_20221014-144826](https://user-images.githubusercontent.com/76146430/195793652-f5d7d963-4e74-4dfb-b8ac-1cd9af1473c5.png)
![Screenshot_20221014-144832](https://user-images.githubusercontent.com/76146430/195793681-9bb1cbbe-d33c-4c7d-9158-4c946087943e.png)
![Screenshot_20221014-144846](https://user-images.githubusercontent.com/76146430/195793721-b29d03f3-7803-4ede-bd63-002ad7d592d3.png)
![Screenshot_20221014-144910](https://user-images.githubusercontent.com/76146430/195793911-259b5ca7-8a27-47f3-9e57-96dbd0679c5a.png)
![Screenshot_20221014-144916](https://user-images.githubusercontent.com/76146430/195793933-cc393b67-ba0d-4489-9b1e-07d99ed46d1b.png)

**Comment by JavkhlanK** [comment]
Can you share the project as SWB instead? I wasn't able to reproduce such Block bugs in my projects so far.

**Comment by oong819** [comment]
> Can you share the project as SWB instead? I wasn't able to reproduce such Block bugs in my projects so far.

robally 
ncdt hours 
m
y creen
 g8chding

**Comment by JavkhlanK** [comment]
what

**Comment by oong819** [comment]
> what

my screen glitching and im using soft keyboard

project file here (rename it from png to zip)
![Expluke](https://user-images.githubusercontent.com/76146430/195809137-cd5ebfcd-ac54-4e1e-8e20-e2164147e533.png)

**Comment by JavkhlanK** [comment]
Thanks, I'll look into that.

**Comment by JavkhlanK** [comment]
Wait, I can't really restore this. Can you use this option instead?

![Screenshot_20221014_202532_Sketchware Pro](https://user-images.githubusercontent.com/40118124/195915736-5c03009e-9024-47b1-ab32-5e66204fae66.png)

**Comment by oong819** [comment]
> Wait, I can't really restore this. Can you use this option instead?
> 
> ![Screenshot_20221014_202532_Sketchware Pro](https://user-images.githubusercontent.com/40118124/195915736-5c03009e-9024-47b1-ab32-5e66204fae66.png)

sorry deleted the app to save storage
but i compressed all the .sketchware folder after deleted unessessary things
![sketchware](https://user-images.githubusercontent.com/76146430/195966993-928d5969-0553-4429-a6f8-60b0b9084e40.png)
also how to enable proguard with out error? its no such method when proguarding class on compilation

**Comment by JavkhlanK** [comment]
I'll have a look again, thanks.

To the ProGuard issue, can you show the entire error message?

**Comment by oong819** [comment]
> I'll have a look again, thanks.
> 
> To the ProGuard issue, can you show the entire error message?

sorry i unintalled Sketchware Pro, will screenshot in future

**Comment by oong819** [comment]
> I'll have a look again, thanks.
> 
> To the ProGuard issue, can you show the entire error message?

ohno i lost my project its dont appesr i should not delete mysc folder

is it able to recover the project from those folder i sent?

**Comment by oong819** [comment]
> I'll have a look again, thanks.
> 
> To the ProGuard issue, can you show the entire error message?

java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/File;Ljava/nio/charset/Charset;)V in class Ljava/util/zip/ZipFile; or its super classes (declaration of 'java.util.zip.ZipFile' appears in /system/framework/core-libart.jar)
	at proguard.io.JarReader.read(JarReader.java:72)
	at proguard.io.DirectorySource.readFiles(DirectorySource.java:68)
	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54)
	at proguard.InputReader.readInput(InputReader.java:262)
	at proguard.InputReader.readInput(InputReader.java:230)
	at proguard.InputReader.readInput(InputReader.java:207)
	at proguard.InputReader.execute(InputReader.java:157)
	at proguard.ProGuard.readInput(ProGuard.java:310)
	at proguard.ProGuard.execute(ProGuard.java:113)
	at a.a.a.Dp.runProguard(Dp.java:973)
	at mod.hey.studios.project.proguard.ProguardHandler.start(ProguardHandler.java:216)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1052)
	at a.a.a.MA.a(Unknown Source)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by JavkhlanK** [comment]
> > I'll have a look again, thanks.
> > 
> > To the ProGuard issue, can you show the entire error message?
> 
> ohno i lost my project its dont appesr i should not delete mysc folder
> 
> is it able to recover the project from those folder i sent?

Yeah it's possible, no worries.

**Comment by JavkhlanK** [comment]
> > I'll have a look again, thanks.
> > 
> > To the ProGuard issue, can you show the entire error message?
> 
> java.lang.NoSuchMethodError: No direct method <init>(Ljava/io/File;Ljava/nio/charset/Charset;)V in class Ljava/util/zip/ZipFile; or its super classes (declaration of 'java.util.zip.ZipFile' appears in /system/framework/core-libart.jar)
> 	at proguard.io.JarReader.read(JarReader.java:72)
> 	at proguard.io.DirectorySource.readFiles(DirectorySource.java:68)
> 	at proguard.io.DirectorySource.pumpDataEntries(DirectorySource.java:54)
> 	at proguard.InputReader.readInput(InputReader.java:262)
> 	at proguard.InputReader.readInput(InputReader.java:230)
> 	at proguard.InputReader.readInput(InputReader.java:207)
> 	at proguard.InputReader.execute(InputReader.java:157)
> 	at proguard.ProGuard.readInput(ProGuard.java:310)
> 	at proguard.ProGuard.execute(ProGuard.java:113)
> 	at a.a.a.Dp.runProguard(Dp.java:973)
> 	at mod.hey.studios.project.proguard.ProguardHandler.start(ProguardHandler.java:216)
> 	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.b(DesignActivity.java:1052)
> 	at a.a.a.MA.a(Unknown Source)
> 	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:1176)
> 	at com.besome.sketch.design.DesignActivity$BuildAsyncTask.doInBackground(DesignActivity.java:928)
> 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 	at java.lang.Thread.run(Thread.java:818)
> 

This looks like what Pranav meant with a too new ProGuard version for minApi21 builds. Will fix soon, thanks for reporting!

**Comment by oong819** [comment]
crash in pic1 freeze in pic2

pic1
![Screenshot_20221018-194728](https://user-images.githubusercontent.com/76146430/196588752-8fc0e85a-6c7d-4f6b-b2dd-24dd89004358.png)
pic2
![Screenshot_20221018-194755](https://user-images.githubusercontent.com/76146430/196588783-cc452baf-4e81-4a55-a904-16bca81321f0.png)

**Comment by oong819** [comment]
this seems like just visual glitch, dont affect code

![Screenshot_20221023-125609](https://user-images.githubusercontent.com/76146430/197376528-39ee0b1b-5db9-4325-97f3-a5bdbe2b167e.png)
![Screenshot_20221023-125615](https://user-images.githubusercontent.com/76146430/197376533-0fbc1324-4fc6-46e2-95ab-774985d11485.png)
![Screenshot_20221023-125617](https://user-images.githubusercontent.com/76146430/197376535-9c890e7b-c55b-481d-a94e-f4792ece28ea.png)
![Screenshot_20221023-125620](https://user-images.githubusercontent.com/76146430/197376536-afcef68a-e09d-45ab-9170-64096f5c77f2.png)
![Screenshot_20221023-125644](https://user-images.githubusercontent.com/76146430/197376541-6e5456b5-f3cf-43c7-80c0-0ab86823e729.png)

**Comment by JavkhlanK** [comment]
I think I've fixed all those bugs recently, could you try using the latest snapshot build from [this link](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3357230966)?

**Comment by Arashvscode** [comment]
I tested the last action and it was fine, thanks

**Comment by oong819** [comment]
Yay finally

**Comment by oong819** [comment]
> I think I've fixed all those bugs recently, could you try using the latest snapshot build from [this link](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/3357230966)?

uhhh
![Screenshot_20221109-194523](https://user-images.githubusercontent.com/76146430/200834189-b87d4d70-6037-4550-8440-c7975f5e20ce.png)

version: Version v6.4.0-SNAPSHOT-d7fbf56-minApi21

**Comment by JavkhlanK** [comment]
That Event was probably corrupted by previous buggy snapshot builds. Try using the Reset option in the Events list.

**Comment by oong819** [comment]
> That Event was probably corrupted by previous buggy snapshot builds. Try using the Reset option in the Events list.

![Screenshot_20221109-230711](https://user-images.githubusercontent.com/76146430/200881425-eb6355a9-b4d9-45c3-8e01-da1486a8e741.png)
![Screenshot_20221109-230717](https://user-images.githubusercontent.com/76146430/200881474-b8b723b5-2085-4c50-9ad1-bd73358d1604.png)
![Screenshot_20221109-230824](https://user-images.githubusercontent.com/76146430/200881510-b6934c80-703b-4563-b2f0-358d8ea78e26.png)

amazing error code

**Comment by JavkhlanK** [comment]
Just reset it already, the Event is corrupted.

**Comment by oong819** [comment]
> Just reset it already, the Event is corrupted.

i copy the block to the collection and reset it before those screenshots

**Comment by JavkhlanK** [comment]
Don't do that, you'll just copy those corrupted Blocks to Collections.
