### ISSUE TITLE
Upload to google console

### ISSUE THREAD

**Issue by yusufquteb** [Sketchware-Pro/Sketchware-Pro#612]
When i upload to google console 
I receive this warning 

There is no deobfuscation file associated with this App Bundle. If you use obfuscated code (R8/proguard), uploading a deobfuscation file will make crashes and ANRs easier to analyse and debug. Using R8/proguard can help reduce app size

And i found after searching i need to add 

buildTypes {
        release {
            minifyEnabled true
            
        }
    }
How to add?

**Comment by JavkhlanK** [comment]
Make sure to enable generating debug files in ProGuard settings.

**Comment by yusufquteb** [comment]
Thank you bro 🌹
