### ISSUE TITLE
Crash and hang when place If then block

### ISSUE THREAD

**Issue by oong819** [Sketchware-Pro/Sketchware-Pro#615]
its freeze some seconds and crash in pic 1 scene
freeze in pic 2 scene

pic1
![Screenshot_20221018-194728](https://user-images.githubusercontent.com/76146430/196435178-ea0b1d23-e288-41a5-b372-3d414f6dd42f.png)

pic2
![Screenshot_20221018-194755](https://user-images.githubusercontent.com/76146430/196435251-981885fb-e54b-442d-beeb-93e176e46173.png)

app version: `` https://pipelines.actions.githubusercontent.com/serviceHosts/523ebe16-815d-4d58-b433-717bd98e7c9a/_apis/pipelines/1/runs/380/signedartifactscontent?artifactName=apk-minApi21-debug&urlExpires=2022-10-17T00%3A06%3A14.2780291Z&urlSigningMethod=HMACV2&urlSignature=l1lIWS3ZfNuqVaQD4HhsNJ%2BUoV8%2FbTHxa64QDm5ErDY%3D ``

**Comment by JavkhlanK** [comment]
Thanks for reporting! Let's track this in #611 though.

By the way, please use version names like shown in this screenshot, not download links of snapshot builds. Those become invalid after some time, and you can't easily guess the version name from the link.

![Screenshot_20221018_200104_Sketchware Pro.png](https://user-images.githubusercontent.com/40118124/196509829-f6ce2052-ecc6-4def-b432-e46c77bb4cc2.png)
