### ISSUE TITLE
You need to update firebase urgently as we can't download from firebase and can you add a gradle setting?

### ISSUE THREAD

**Issue by mesflit** [Sketchware-Pro/Sketchware-Pro#627]
You need to update firebase urgently as we can't download from firebase and can you add a gradle setting?

**Comment by JavkhlanK** [comment]
Please stop spamming and creating new Issues.

Both of your requests are duplicates.  
Firebase one: #469  
Gradle one: #479, though implementing Gradle will be a PITA. Something like "gradle setting" isn't doable nicely, and isn't planned unless the build system gets changed to Gradle.
