### ISSUE TITLE
Audio files and OneSignal error

### ISSUE THREAD

**Issue by InfiSoftApps** [Sketchware-Pro/Sketchware-Pro#628]
![Screenshot_2022-11-05-13-59-11-017_com sketchware remod](https://user-images.githubusercontent.com/114339115/200111039-e54711e2-a724-4f36-87f8-e8838ad9608c.jpg)

My App doesn't compile in beta versions.
My App includes 2 audio files(bell.mp3, pop.mp3) and OneSignal. 
Both of them are giving error.

Attached screenshot of error log

**Comment by JavkhlanK** [comment]
Does the project compile in v6.3.0 fix1?

Also, could you send a screenshot of Sound Manager? Looks like those sounds don't exist at all.

**Comment by InfiSoftApps** [comment]
![Screenshot_2022-11-05-17-52-12-099_com sketchware remod](https://user-images.githubusercontent.com/114339115/200119612-6a349dd2-ec55-48bc-a827-28873f1a57db.jpg)

Yes bro, app compiled very well in 6.3.0 fix1.
Attached screenshot of sound manager with files available there

**Comment by JavkhlanK** [comment]
What Sketchware Pro v6.4.0 beta version did you use?

Also, maybe try removing and adding those Sounds again, that could help.

**Comment by InfiSoftApps** [comment]
I'm on the latest rc5. Had save issue with rc4 as well.

**Comment by JavkhlanK** [comment]
Are you really using v6.4.0-rc05? Please check, and if you really are, maybe try deleting the app's cache files. The built-in OneSignal library has in v6.4.0-rc05 the same files as in v6.3.0 fix1, so I can't imagine a project working in v6.3.0 fix1, but not in v6.4.0-rc05 because of OneSignal.

I couldn't reproduce that Sounds bug. Tried removing and re-adding Sounds in my test project, and also referencing it in code with `R.raw.soundname`. It worked all the time.

**Comment by InfiSoftApps** [comment]
https://user-images.githubusercontent.com/114339115/200132869-ca1c6825-3549-486e-8308-4635766fb645.mp4

Bro, I've noticed 1 thing. Even though i delete the audio file and re-add, I am able to play the file in AudioManager.
But once i go back from AudioManager and come back again, I'm unable to play the file.
Possibly SK is unable to detect the file.
Sending screen recording for more clarity.

**Comment by JavkhlanK** [comment]
Can you check if any file exists in /Internal storage/.sketchware/resources/sounds/617/?

**Comment by InfiSoftApps** [comment]
Even after adding the file into project, the folder didn't even exist.
I manually created the folder and it was done. 

Also about the OneSignal, i commented out the error giving codes and it's working fine now.

Thank you for your prompt support.
We may close this issue now.

**Comment by JavkhlanK** [comment]
Great it now works!
