### ISSUE TITLE
Android Manifest Manager 

### ISSUE THREAD

**Issue by adesonob** [Sketchware-Pro/Sketchware-Pro#630]
In Android Manifest Manager there is a function called All Activities, to add attributes to all activities, but when I put the attribute android:exported="true" It doesn't work as it should.

![Screenshot_20221105-173156_Sketchware Pro](https://user-images.githubusercontent.com/92691301/200140232-069a29e6-5ff6-4b1a-b642-2f6eff0120d3.png)

![Screenshot_20221105-173128_Sketchware Pro](https://user-images.githubusercontent.com/92691301/200140234-ea89d220-ee60-4a9f-b825-4112421da4f4.png)

**Comment by JavkhlanK** [comment]
That feature is a bit weird. It adds attributes only to activities added to the manager itself, so if you want that property to be added to GamingActivity, you'd have to add `gaming` as activity in AndroidManifest Manager.

**Comment by arab-ware** [comment]
Why don't just use command blocks
They work fine , simple and they also work for services and receivers tags (in case your app has them)

**Comment by adesonob** [comment]
ok, i'll do it

**Comment by subhash16** [comment]
On config just change 28 to 32 or 33 then check
Show source code
![Screenshot_2022-11-06-22-53-21-086_com sketchware remod](https://user-images.githubusercontent.com/37414496/200185345-5261f340-a00b-4139-96a4-fd2b984a61de.jpg)
![Screenshot_2022-11-06-22-53-42-864_com sketchware remod](https://user-images.githubusercontent.com/37414496/200185348-d92f85ac-0926-46f3-b5cc-03c6d2067b4c.jpg)

**Comment by subhash16** [comment]
So simple

**Comment by JavkhlanK** [comment]
I guess this question was answered.

**Comment by subhash16** [comment]
Thanks for closing
