### ISSUE TITLE
I can't export to app can some explain how to do it in test build

### ISSUE THREAD

**Issue by Lightshousegames** [Sketchware-Pro/Sketchware-Pro#636]

**Comment by JavkhlanK** [comment]
Use this option:  
![Screenshot_20220605-151931_Sketchware Pro.png](https://user-images.githubusercontent.com/40118124/201014280-c6208824-6d52-4bb5-9ab5-187beb91f307.png)

**Comment by Lightshousegames** [comment]
Me too it doesn't work I just use export to aab and install it using an app bundle installer

**Comment by JavkhlanK** [comment]
Can you clarify "doesn't work"?

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
