### ISSUE TITLE
FCM notifications aren't received on devices running on Android 12 and above

### ISSUE THREAD

**Issue by InfiSoftApps** [Sketchware-Pro/Sketchware-Pro#640]
My app has FCM integrated into app where I send push notifications from Firebase Web Console.
Those notifications are successfully received on devices running till Android 11 but not on the devices running above that.

Doing some Google search, i found out that possible cause of this is outdated SDK.
Is it the main cause?
If yes, please guide me to upgrade my app to lastest SDK.
If no, please guide me towards the possible solution.

**Comment by JavkhlanK** [comment]
Currently, that's pretty hard unless you upgrade the library files in libs.zip and dexs.zip in the Sketchware Pro APK. Otherwise, you could not use the built-in Cloud Messaging Component, and add the FCM library on your own in Local library Manager.

**Comment by PranavPurwar** [comment]
maybe its because of sketchware not adding NOTIFICATIONS permission

**Comment by InfiSoftApps** [comment]
Can you pls suggest what's the best solution i can apply?

If we need to add the library manually, what exact process should i follow..

**Comment by InfiSoftApps** [comment]
@JavkhlanK Sir,
Can you please guide me how can I proceed for the timebeing.!!

Thank You in advance

**Comment by JavkhlanK** [comment]
Like I mentioned above, you could try not using the built-in Cloud Messaging Component, and add the FCM library on your own in Local library Manager.

**Comment by InfiSoftApps** [comment]
I can add the Library manually but what concerns me is, how to initiate thr FCM manually?

If i use inbuilt component, it does all the menifest as well as initiation thing.

I would be glad if you could guide me setting up FCM manually.

**Comment by PranavPurwar** [comment]
Check FCM documentation

**Comment by InfiSoftApps** [comment]
@PranavPurwar brother, I checked the documentation.
But not sure how to implement those steps in SK.
That's where I'm stuck.

https://firebase.google.com/docs/cloud-messaging/android/client

**Comment by PranavPurwar** [comment]
Use Android Manifest manager and permission manager

**Comment by InfiSoftApps** [comment]
I'm familiar with Permission Manager.
I would be glad if you could just guide me step by step with Manifest Implementation.

**Comment by InfiSoftApps** [comment]
![Screenshot_2022-12-10-23-42-37-219_com sketchware remod](https://user-images.githubusercontent.com/114339115/206870873-2ddbc3e8-68a8-4e72-a519-4919de34dce7.jpg)


![Screenshot_2022-12-08-14-45-08-553_com sketchware remod](https://user-images.githubusercontent.com/114339115/206870875-8ec35cb7-8a9c-43de-bde8-f94893b8fe27.jpg)

I've included local Library of FCM but getting some error.
Can @PranavPurwar sir/ @JavkhlanK Sir please help me.

**Comment by JavkhlanK** [comment]
Stop mentioning people when asking for help, thanks.

**Comment by CloverClubWork** [comment]
Hello, can I have the JSoup Library please? I always searching it to use on Sketchware Pro but I could not. If you could please provide it. Thank you

**Comment by JavkhlanK** [comment]
To this Issue's question, you can exclude built-in FCM libraries and replace them with your own versions from Local library Manager for a while now. Just go to Library Manager, then Exclude built-in libraries.
