### ISSUE TITLE
App Crashed Due to Trimmed manifest codes

### ISSUE THREAD

**Issue by damylolae** [Sketchware-Pro/Sketchware-Pro#642]
When I add third party codes to Android manifest , app crashes in on app started , digging deep I found out that at build time , some of the codes are trimmed out , below screenshot shows manifest file viewed through apk editor contains 40+ lines of codes while sketchware pro is 118 lines. A fix will go a long way.

**Comment by damylolae** [comment]
![Uploading Screenshot_20221116-171845.png…]()

**Comment by damylolae** [comment]
![Screenshot_20221116-171845](https://user-images.githubusercontent.com/74447702/202239669-2f785b17-9d55-4f29-9976-bcf0bee55e67.png)

**Comment by JavkhlanK** [comment]
Just the length of a source file compared to a compiled, then disassembled file not matching doesn't mean that something got trimmed. Can you upload both the original AndroidManifest.xml **as file** and the decompiled AndroidManifest.xml also **as file** here?

**Comment by damylolae** [comment]
Alright,Noted

**Comment by damylolae** [comment]
[Uploading projectAndroidManifest.xml…]()

**Comment by JavkhlanK** [comment]
Be more patient until the file's fully uploaded before you press the Comment button.

**Comment by damylolae** [comment]
[projectAndroidManifest.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/10024105/projectAndroidManifest.txt)

**Comment by damylolae** [comment]
[ApkAndroidManifest.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/10024107/ApkAndroidManifest.txt)

**Comment by JavkhlanK** [comment]
Just checked, and they're the same tag-wise. The APK Editor one is just formatted differently.
