### ISSUE TITLE
StringFog Not working

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#649]
hello, 
i have problem with stringfog in heavy projects
when i'm using d8/java11 and **ProGuard**, stringfog not working
This only happens when ProGuard is on

**Comment by AmirSinaRZ** [comment]
After compiling when i'm checking classes all strings are visible

**Comment by JavkhlanK** [comment]
By not working, do you mean that it looks like it runs, but in the end doesn't obfuscate strings?

**Comment by AmirSinaRZ** [comment]
> By not working, do you mean that it looks like it runs, but in the end doesn't obfuscate strings?

No, it does not run at all

**Comment by JavkhlanK** [comment]
Does compiling stop or what? If it does, share a screenshot of the error message.

**Comment by AmirSinaRZ** [comment]
> Does compiling stop or what? If it does, share a screenshot of the error message.

If I set java version 1.8 stringfog working well but in java 11 project compiling well but without running stringfog and in dialog you can't see < stringfog is compiling>

**Comment by JavkhlanK** [comment]
I couldn't reproduce that. Turning on StringFog with Java 11 as target instead made d8 stop compiling.

**Comment by JavkhlanK** [comment]
Let's track that in #616 instead.
