### ISSUE TITLE
Text color missing 

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#652]
i have added text color to white #ffffff
but after run app showing black
![Screenshot_2022-11-22-18-17-36-17_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/203312109-43ad5e59-8d1a-4650-9fa0-27b4d7844dd2.jpg)

**Comment by JavkhlanK** [comment]
What are you talking about? There's not even `android:textColor` mentioned in that screenshot.
