### ISSUE TITLE
Add options to change widget/layout in XML file (like priority)

### ISSUE THREAD

**Issue by oong819** [Sketchware-Pro/Sketchware-Pro#664]
im making some animation with object animator

i dont jave time edit full layert(y=t

**Comment by JavkhlanK** [comment]
can you clarify this, I didn't get what you meant

**Comment by oong819** [comment]
> can you clarify this, I didn't get what you meant

![Screenshot_20221130-224044](https://user-images.githubusercontent.com/76146430/204842396-3a985f50-ca14-440c-b8b3-e83650ea1069.png)
i want a can be displayed over d

**Comment by JavkhlanK** [comment]
Add both LinearLayouts to another LinearLayout with ID e.g. root, then use this code to swap a and b:

```java
root.removeView(b);
root.addView(b, root.indexOfChild(a));
```

**Comment by oong819** [comment]
> Add both LinearLayouts to another LinearLayout with ID e.g. root, then use this code to swap a and b:
> 
> ```java
> root.removeView(b);
> root.addView(b, root.indexOfChild(a));
> ```

thx but i just realized that order in XML dont affect objectanimator overlap
