### ISSUE TITLE
Package error/ create key

### ISSUE THREAD

**Issue by mindxxxwarrior** [Sketchware-Pro/Sketchware-Pro#667]
After making a key it shows an error in the package while trying to install.. so ..Can't create new key in android 12 miui 13 version ..

**Comment by JavkhlanK** [comment]
Creating a key store and exporting a signed APK outputting a not installable APK are probably unrelated. Can you try exporting an APK and signing it with testkey, then installing it? That should fail too.

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
