### ISSUE TITLE
Trojan Virus

### ISSUE THREAD

**Issue by CloverClubWork** [Sketchware-Pro/Sketchware-Pro#675]
Good morning sir/ma'am. The newest version of Sketchware Pro, after installing it, my android detected it has a Trojan Virus and after creating some project, the project have a Trojan Virus too. This is my issue in my vivo. Please to remove this if not acceptable.

**Comment by oong819** [comment]
cam you try install an empty apk? (app that have minimal java code and xml)

**Comment by JavkhlanK** [comment]
See threads #637, #403 for more details.
