### ISSUE TITLE
Deleting the project in full storage

### ISSUE THREAD

**Issue by Parsa-GP** [Sketchware-Pro/Sketchware-Pro#680]
The project deletes itself when the storage is full.
(AND I LOST 4 PROJECT AND WASTED MY ENTIRE MONTH)

**Comment by PranavPurwar** [comment]
Its your file manager or system cleaner issue

**Comment by JavkhlanK** [comment]
I'm not aware of anything like that, only a warning that more free storage space should be needed to run projects normally.

Can you try to record that happening somehow?

**Comment by IMOitself** [comment]
I think you've used ES file explorer..
If you tried to clean your phone with it, it will delete the .sketchware folder.
It sees the folder as useless because it couldnt find the Sketchware app(com.besome.sketchware) specially when you are using Sketchware Pro (com.sketchware.remod).

**Comment by Parsa-GP** [comment]
> I think you've used ES file explorer.. If you tried to clean your phone with it, it will delete the .sketchware folder. It sees the folder as useless because it couldnt find the Sketchware app(com.besome.sketchware) specially when you are using Sketchware Pro (com.sketchware.remod).

Hello. Thank you for your advice.
Yes, apparently it was because of that program. Does x-plore have this problem or can I use x-plore?

**Comment by Parsa-GP** [comment]
oops...
