### ISSUE TITLE
Github Snapshot Version - problem

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#683]
i have download a Snapshot version today..and i got one bugs that should be fixed.
![IMG_20221228_011656](https://user-images.githubusercontent.com/88816748/209712669-63cad4ea-afca-4778-bbfd-25a7a1dff23a.jpg)
See in this screenshot. if i select any view from desgin layout (i mean from mobile screen that is our desgin screen) its working fine and selected view got like blue color....its fine.

but if i select any view from (i mentioned this in that screenshot named as 1) its not selected and even selected views color not changing....

**Comment by JavkhlanK** [comment]
Was able to reproduce, thanks for reporting!

**Comment by JavkhlanK** [comment]
Fixed with commit f3814234e2d9457bbdfaeccff9a83e412bc71bdc.
