### ISSUE TITLE
When I access "Components menager"  app crashes

### ISSUE THREAD

**Issue by InfiniteLoops87** [Sketchware-Pro/Sketchware-Pro#690]
This is the latest version  (v6.4.0 Public Beta 5 fix 1). This issue is also in older versions!

# This is the resulting debug after that crash:

![Screenshot_2023-01-03-12-05-29-400_com.sketchware.remod.jpg](https://user-images.githubusercontent.com/104360334/210336242-807ba9c8-4341-4d35-ad28-166ed8477392.jpg)

Please can you find the error that causes the app to crash. Thank you in advance!

**Comment by JavkhlanK** [comment]
Sketchware Pro v6.4.0-rc05 is the latest version, not Public Beta 5 fix1.

Anyway that's caused by one of your Custom Components being broken. If you want Component Manager to work immediately, rename /Internal storage/.sketchware/data/system/component.json to something else, or fix the JSON file manually.

**Comment by JavkhlanK** [comment]
Seems like the app would still crash if an invalid Custom Component is in component.json. Marking this as bug therefore.

**Comment by InfiniteLoops87** [comment]
> Seems like the app would still crash if an invalid Custom Component is in component.json. Marking this as bug therefore.

Yeah, I'm not very knowledgeable, sorry about that, and thanks for the help

**Comment by InfiniteLoops87** [comment]
> Seems like the app would still crash if an invalid Custom Component is in component.json. Marking this as bug therefore.

Yeah, I'm not very knowledgeable, sorry about that, and thanks for the help

**Comment by InfiniteLoops87** [comment]
> Sketchware Pro v6.4.0-rc05 is the latest version, not Public Beta 5 fix1.
> 
> Anyway that's caused by one of your Custom Components being broken. If you want Component Manager to work immediately, rename /Internal storage/.sketchware/data/system/component.json to something else, or fix the JSON file manually.



Yeah, I'm not very knowledgeable, sorry about that, and thanks for the help
