### ISSUE TITLE
AppCompat Manager

### ISSUE THREAD

**Issue by AndroXStudiO** [Sketchware-Pro/Sketchware-Pro#691]
![Screenshot_2023-01-04-21-01-16-69_423e58f25c30a02453fa5d8c82fc37f2](https://user-images.githubusercontent.com/88816748/210584161-e6b94047-afb9-4f53-b325-4489ca5a0ad5.jpg)
its says attribute added but still not added....and some time its crashes app

**Comment by JavkhlanK** [comment]
Which Sketchware Pro version did you use? AppCompat Manager not working should be fixed in the latest snapshot builds.

**Comment by AndroXStudiO** [comment]
Trying beta version

**Comment by JavkhlanK** [comment]
Tell the exact version like v6.4.0-rc04.

**Comment by AndroXStudiO** [comment]
Problem solved with Snapshot version..
