### ISSUE TITLE
switch theme!

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#692]
Switch theme in the code editor without effect selected!

**Comment by JavkhlanK** [comment]
Could you please clarify yourself, for example with screenshots of what you're talking about?

**Comment by Win-one** [comment]
![Screenshot_20230107_165452_com sketchware remod](https://user-images.githubusercontent.com/39393649/211142519-838e6238-a5e8-4c8d-876d-28e1b7dbc60e.jpg)
Here it should be a single selection, but it is not displayed!

**Comment by JavkhlanK** [comment]
Oh yeah that. Could be fixed indeed.

**Comment by JavkhlanK** [comment]
I implemented that with commit 834de9e7fa2ec2e175c4e714c9c10f47a09b66b1. If you'd like to test a pre-release version out, get it from here: https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/4038564047

**Comment by JavkhlanK** [comment]
this was actually fixed just now with 0815f36aa07de931f1a0eacf5495275a374e818b, a test build for it is available here: https://nightly.link/Sketchware-Pro/Sketchware-Pro/actions/runs/5649339024
