### ISSUE TITLE
Library Error 

### ISSUE THREAD

**Issue by Kevin-developing** [Sketchware-Pro/Sketchware-Pro#693]
Onsignal Library is to old can we update it

**Comment by TechnicalStudioDevelopers** [comment]
> Onsignal Library is to old can we update it

Firebase library is also too old

**Comment by TechnicalStudioDevelopers** [comment]
> > Onsignal Library is to old can we update it
> 
> Firebase library is also too old

Is there anyway to update manually?

**Comment by JavkhlanK** [comment]
See #696, it's not (for now).
