### ISSUE TITLE
Can you upgrade Gradle to the latest version?

### ISSUE THREAD

**Issue by anthony-china** [Sketchware-Pro/Sketchware-Pro#694]
Can you upgrade Gradle to the latest version?

**Comment by JavkhlanK** [comment]
Sketchware Pro doesn't use Gradle if it's that what you're talking about. The version in build.gradle files generated by Sketchware Pro are only for Android Studio when projects get exported to it.

**Comment by TechnicalStudioDevelopers** [comment]
> Sketchware Pro doesn't use Gradle if it's that what you're talking about. The version in build.gradle files generated by Sketchware Pro are only for Android Studio when projects get exported to it.

Is there any way to update fb library to the latest version

**Comment by JavkhlanK** [comment]
> > Sketchware Pro doesn't use Gradle if it's that what you're talking about. The version in build.gradle files generated by Sketchware Pro are only for Android Studio when projects get exported to it.
> 
> Is there any way to update fb library to the latest version

Keep comments here relevant to this issue. Ask that in #693 instead.

**Comment by anthony-china** [comment]
Hopefully, we can improve Gradle so that, for example, we can import into other

**Comment by JavkhlanK** [comment]
What are you talking about?

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
