### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#698]
Kotlin library not working.

**Comment by JavkhlanK** [comment]
What exactly do you mean by "not working"? Show what you're trying to do, and maybe also what it should be like instead.

**Comment by subhash16** [comment]
dependencies {
    implementation 'kr.co.prnd:readmore-textview:x.x.x'
    //implementation 'kr.co.prnd:readmore-textview:1.0.0'    
}
This library is in kotlin and not working on sketchware

**Comment by JavkhlanK** [comment]
You're still not saying *how exactly* it isn't working. Did you add the Kotlin stdlib?

**Comment by subhash16** [comment]
Kotlin stdlib link plz

**Comment by PranavPurwar** [comment]
@subhash16 https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.8.0/kotlin-stdlib-1.8.0.jar

**Comment by PranavPurwar** [comment]
you need to dex it yourself using d8 tool or through termux idk

**Comment by subhash16** [comment]
Sir can you give me the readymade file of this coz I don't know how to do that

**Comment by subhash16** [comment]
> you need to dex it yourself using d8 tool or through termux idk

Please sir give the readymade file

**Comment by subhash16** [comment]
> you need to dex it yourself using d8 tool or through termux idk

Please give

**Comment by PranavPurwar** [comment]
use library manager

**Comment by subhash16** [comment]
> use library manager

Can you explain it briefly

**Comment by subhash16** [comment]
> > use library manager
> 
> Can you explain it briefly

Plz

**Comment by PranavPurwar** [comment]
no
