### ISSUE TITLE
Play protect error

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#705]
![Screenshot_2023-01-12-11-59-56-151_com android vending](https://user-images.githubusercontent.com/37414496/211994220-08e1b253-d0fb-49df-98e3-6d99a251dac2.jpg)

**Comment by subhash16** [comment]
![Screenshot_2023-01-12-17-19-01-079_com miui global packageinstaller](https://user-images.githubusercontent.com/37414496/212059336-6149356a-a77d-415e-bad8-417c78bc6b31.jpg)

**Comment by subhash16** [comment]
This error occurs when build a project then RUN the project.

**Comment by BeChris100** [comment]
So I'm not the only one here.

**Comment by JavkhlanK** [comment]
Looks like Play Protect started reporting apps signed with testkey as unsafe too, just like some Chinese OEMs' virus scanners sometime ago. I wonder why, as being signed with testkey doesn't necessarily have to mean the app's unsafe.

As the label says, this isn't really Sketchware Pro's fault.

**Comment by subhash16** [comment]
How to fix this

**Comment by JavkhlanK** [comment]
Try exporting your project as unsigned APK, then signing that file with e.g. apk-signer or MT Manager. Play Protect shouldn't report it as "unsafe" then.

**Comment by subhash16** [comment]
I have to upload on play store

**Comment by subhash16** [comment]
I got this error from today

**Comment by subhash16** [comment]
I have uninstalled the skpro deleted sketchware file on storage then reinstall not solved

**Comment by JavkhlanK** [comment]
Doing that won't change anything. The APK is being generated normally, it's just that Play Protect started finding APKs built when you press the Run button harmful now.

When publishing to Google Play you should be safe, as .aab files shouldn't get signed with testkey and you'd be using your own key store anyway.

**Comment by subhash16** [comment]
> Doing that won't change anything. The APK is being generated normally, it's just that Play Protect started finding APKs built when you press the Run button harmful now.
> 
> When publishing to Google Play you should be safe, as .aab files shouldn't get signed with testkey and you'd be using your own key store anyway.

I use my own key

**Comment by JorgeViais** [comment]
I also have an error in my app, I try to "Sign an APK" using "Sign using testekey" or create a key in "Create Release Keystore", the app runs in the "signed_apk" folder but it appears with a ". APK" and when I try opening it pops up an error "There was a problem parsing the package". I also tried "Don't sign" and the result is the same. I ask for your help. Thanks.

**Comment by EmStudio22** [comment]
Why is have Trojan
![Screenshot_20230114_190017_com android chrome](https://user-images.githubusercontent.com/114802272/212469384-b631ca81-6830-42b3-a293-f371f0906eb4.jpg)

**Comment by JavkhlanK** [comment]
> Looks like Play Protect started reporting apps signed with testkey as unsafe too, just like some Chinese OEMs' virus scanners sometime ago. I wonder why, as being signed with testkey doesn't necessarily have to mean the app's unsafe.
> 
> As the label says, this isn't really Sketchware Pro's fault.

@EmStudio22

**Comment by subhash16** [comment]
Play protect stop detecting as virus.
But still miui security avast detecting Trojans.

**Comment by JavkhlanK** [comment]
Nice! Not sure how to address that Xiaomi one though

**Comment by subhash16** [comment]
Google play solved

**Comment by JavkhlanK** [comment]
Update: I created a (hopefully) helpful guide for fixing that issue at #901.
