### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by EmStudio22** [Sketchware-Pro/Sketchware-Pro#707]
can you fix this

**Comment by EmStudio22** [comment]
![Uploading Screenshot_20230114_190017_com.android.chrome.jpg…]()

**Comment by EmStudio22** [comment]
![Screenshot_20230114_190017_com android chrome](https://user-images.githubusercontent.com/114802272/212469577-cc554f07-dec1-4bae-a30b-15cee648a114.jpg)

**Comment by JavkhlanK** [comment]
Duplicate of #705.
