### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [Sketchware-Pro/Sketchware-Pro#745]
I don't know this is my project error or Sketchware pro error but I got as follow
![Screenshot_2023-02-05-15-41-08-043_com sketchware remod](https://user-images.githubusercontent.com/96680248/216813139-3cdfedd9-04e7-478e-b776-6c5fd7a25260.jpg)

**Comment by TechnicalStudioDevelopers** [comment]
I got this error but my project doesn't stopped from compiling.My project compiled and I got this error I can't reproduce it.

**Comment by JavkhlanK** [comment]
Can you turn on line wrapping and send the error message again? Otherwise it's not readable like this.

**Comment by TechnicalStudioDeveloper** [comment]
> Can you turn on line wrapping and send the error message again? Otherwise it's not readable like this.

No.

**Comment by TechnicalStudioDeveloper** [comment]
> Can you turn on line wrapping and send the error message again? Otherwise it's not readable like this.

I just got this message only one time.So I can't send you..

**Comment by TechnicalStudioDeveloper** [comment]
@JavkhlanK I again got an error that is different but ...
Check yourself.
![Screenshot_2023-03-05-19-47-57-337_com sketchware remod](https://user-images.githubusercontent.com/96680248/222966023-6fdb1977-6373-4a3d-9654-ec42e9826f96.jpg)

**Comment by TechnicalStudioDeveloper** [comment]
> @JavkhlanK I again got an error that is different but ... Check yourself. ![Screenshot_2023-03-05-19-47-57-337_com sketchware remod](https://user-images.githubusercontent.com/96680248/222966023-6fdb1977-6373-4a3d-9654-ec42e9826f96.jpg)

And again sorry I cannot able to send it without word wrap.

**Comment by PranavPurwar** [comment]
the library at that path was deleted

**Comment by JavkhlanK** [comment]
Yeah, that happened, which isn't a Sketchware Pro bug.

> And again sorry I cannot able to send it without word wrap.

I hope you know that there's an option in the 3-dot menu in the error message viewer screen to enable that.

**Comment by TechnicalStudioDeveloper2** [comment]
> Yeah, that happened, which isn't a Sketchware Pro bug.
> 
> > And again sorry I cannot able to send it without word wrap.
> 
> I hope you know that there's an option in the 3-dot menu in the error message viewer screen to enable that.

I just suddenly captured and forget that.

**Comment by TechnicalStudioDeveloper2** [comment]
> Yeah, that happened, which isn't a Sketchware Pro bug.
> 
> > And again sorry I cannot able to send it without word wrap.
> 
> I hope you know that there's an option in the 3-dot menu in the error message viewer screen to enable that.

Bro this happened only one time and project keep compiling and builded successfully.

**Comment by TechnicalStudioDeveloper** [comment]
> the library at that path was deleted

I know about this and Sketchware still compiled broken app but build was completed.

**Comment by PranavPurwar** [comment]
then why the hell did you create this issue

**Comment by TechnicalStudioDeveloper** [comment]
> then why the hell did you create this issue

Because the error at top is not related to my project it it a bug.

**Comment by PranavPurwar** [comment]
Since you didn't send the whole error, its useless, and can't be fixed rn
