### ISSUE TITLE
Can anyone parse this json to skpro

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#750]
[{"PLOT_CLASSIFICATION":"বাইদ","OWNER_DETAIL":[{"GUARDIAN_NAME":"মহাদেব","OWNER_NAME":"মুক্তিপদ চট্টোপাধ্যায়","KHATIAN_SHARE_AREA":"0.0800","POSESSOR_NAME":"","POSESSOR_DETAIL":[],"KHATIAN_NO":"941","KHATIAN_SHARE":"0.3333"},{"GUARDIAN_NAME":"সেখ সাহাকুব আলি","OWNER_NAME":"মহঃ কলিমউদ্দিন","KHATIAN_SHARE_AREA":"0.0800","POSESSOR_NAME":"","POSESSOR_DETAIL":[],"KHATIAN_NO":"2714","KHATIAN_SHARE":"0.3333"},{"GUARDIAN_NAME":"সেখ সাহাকুব আলি","OWNER_NAME":"মহঃ আলিমুদ্দিন","KHATIAN_SHARE_AREA":"0.0800","POSESSOR_NAME":"","POSESSOR_DETAIL":[],"KHATIAN_NO":"3515","KHATIAN_SHARE":"0.3334"}],"PLOT_SHARE_AREA":"0.24","ERROR":"1","PLOT_NO":"120"}]

**Comment by JavkhlanK** [comment]
This is an issue tracker for bugs or other issues in Sketchware Pro, not general help.

**Comment by subhash16** [comment]
Plz someone help me
