### ISSUE TITLE
Missing the system setting to return to the home button!

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#752]
Missing the system setting to return to the home button, and also suggest adding the language switch option!

**Comment by JavkhlanK** [comment]
what exactly do you mean by "returning to the home button"?

the custom language option still exists, but most translations were only hosted on Sketchware's server which shut down, so we removed that activity. if you have an appropriate strings.xml file you can still place it in /Internal storage/sketchware/localization/ to use that as custom language though.

**Comment by Win-one** [comment]
Thank you for your interest！you fixed: Not showing back to home button on Feb 3, 2023,bu missing the system setting!

**Comment by JavkhlanK** [comment]
Fixed with commit e7af8147d9689d201e138cd60eff603dd906b369. Get the latest snapshot build to see it having been fixed.
