### ISSUE TITLE
Custom blocks not back up

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#758]
In latest version and latest snapshot version when I back up an app .
The back up file not included the custom blocks.

**Comment by subhash16** [comment]
4 days no response

**Comment by PranavPurwar** [comment]
the blocks are just saved for the project, not in the blocks manager meaning that you can only access them inside the project

**Comment by TechnicalStudioDeveloper** [comment]
> the blocks are just saved for the project, not in the blocks manager meaning that you can only access them inside the project

this is a problem which you have also faced @subhash16 I mentioned this in #756 but not one response it.

**Comment by PranavPurwar** [comment]
this is not a bug

**Comment by subhash16** [comment]
> this is not a bug

Yes it's a bug , blocks not back up in the project

**Comment by subhash16** [comment]
Back up a project then delete custom blocks,after restore the project the custom blocks is missing

**Comment by TechnicalStudioDeveloper** [comment]
> Back up a project then delete custom blocks,after restore the project the custom blocks is missing

Yeah!That was I trying to say in #756 but it is not a bug.

**Comment by JavkhlanK** [comment]
Could you maybe show a screen recording or something? I used snapshot build e125c121 and it the .swb contained /data/custom_blocks which contained all Custom Blocks used in the project.

**Comment by subhash16** [comment]
> Could you maybe show a screen recording or something? I used snapshot build [e125c12](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/e125c12122b14cb646a0d8b8b2c174ba67e17a16) and it the .swb contained /data/custom_blocks which contained all Custom Blocks used in the project.

Ok I will check in latest snapshot

**Comment by subhash16** [comment]
Which is latest snapshot I download the last one it corrupted plz tell

**Comment by subhash16** [comment]
Last two action file corrupt

**Comment by subhash16** [comment]
It's work ok fine
