### ISSUE TITLE
The title of the "sort options" is missing

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#759]
Today's fix caused  the title of the "sort options" is missing!

**Comment by JavkhlanK** [comment]
Please send a screenshot of what you mean.

**Comment by Win-one** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sketchware-Pro/Sketchware-Pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sketchware-Pro/Sketchware-Pro] The title of the "sort options" is missing (Issue #759)





 
Please send a screenshot of what you mean.

**Comment by JavkhlanK** [comment]
Based on what I assume this report to be, this should've already been fixed.
