### ISSUE TITLE
variable remove issues 

### ISSUE THREAD

**Issue by Ars-king** [Sketchware-Pro/Sketchware-Pro#791]
https://user-images.githubusercontent.com/72991279/221971284-49209188-03e2-4861-9712-ec710d26e495.mp4

**Comment by JavkhlanK** [comment]
Can you try using Sketchware Pro v6.3.0 fix1 to remove Variables? If that also doesn't work, you probably have a corrupted project.

**Comment by moderGamer** [comment]
> 

I have the same problem

**Comment by Ars-king** [comment]
> Can you try using Sketchware Pro v6.3.0 fix1 to remove Variables? If that also doesn't work, you probably have a corrupted project.

I tried using sketchware V6.3.0 fix1, but it also shows error. And yes I have been working on this project for almost 2 years, after updating the project I didn't remember to delete the variables so now this problem is showing, although if I don't delete the variables my ARS STORE Apk is working but I want the app to be faster.

**Comment by Ars-king** [comment]
https://user-images.githubusercontent.com/72991279/222948226-ac3bd654-8cbd-4bc8-91f4-6ec3cc5d2c31.mp4

@JavkhlanK
I tried using sketchware V6.3.0 fix1, but it also shows error. And yes I have been working on this project for almost 2 years, after updating the project I didn't remember to delete the variables so now this problem is showing, although if I don't delete the variables my ARS STORE Apk is working but I want the app to be faster.

**Comment by Ars-king** [comment]
Please help!

**Comment by PranavPurwar** [comment]
> @JavkhlanK I tried using sketchware V6.3.0 fix1, but it also shows error. And yes I have been working on this project for almost 2 years, after updating the project I didn't remember to delete the variables so now this problem is showing, although if I don't delete the variables my ARS STORE Apk is working but I want the app to be faster.

@Ars-king enable proguard to make your app **FASTER**

**Comment by Ars-king** [comment]
> > @JavkhlanK I tried using sketchware V6.3.0 fix1, but it also shows error. And yes I have been working on this project for almost 2 years, after updating the project I didn't remember to delete the variables so now this problem is showing, although if I don't delete the variables my ARS STORE Apk is working but I want the app to be faster.
> 
> @Ars-king enable proguard to make your app **FASTER**

My main problem is variable remove issues. 
Can you provide a solution to remove the variable?

**Comment by moderGamer** [comment]
> 
Use comment blocks

**Comment by Ars-king** [comment]
> > 
> Use comment blocks
> 

https://github.com/Sketchware-Pro/Sketchware-Pro/issues/791#issue-1603767958

See this video -

**Comment by Ars-king** [comment]
My problem is that it's not removing the variable

**Comment by JavkhlanK** [comment]
If v6.3.0 fix1 also crashes, it's most likely your project that's corrupt. Anyway, to find out more, a detailed error message is needed. Try doing the same steps as before in these screen recordings, and after the app "restarts", go to Recent apps, then your home screen, then open Sketchware Pro again from Recent apps. Repeat until you get a dialog saying "An error occurred" with long text under it, then upload a screenshot of the *entire* error message here.

**Comment by Ars-king** [comment]
> If v6.3.0 fix1 also crashes, it's most likely your project that's corrupt. Anyway, to find out more, a detailed error message is needed. Try doing the same steps as before in these screen recordings, and after the app "restarts", go to Recent apps, then your home screen, then open Sketchware Pro again from Recent apps. Repeat until you get a dialog saying "An error occurred" with long text under it, then upload a screenshot of the _entire_ error message here.

Oky 🙂

**Comment by developer-krushna** [comment]
> 

If you see your project's variable, which is too many and i think variables in a project were saved in json format in sketchware (i don't know really but guess only) because of this , sketchware failed to show your list variables in your project as no background processing loop were used here to show the list variables and that is why Sketchware automatically crashing... Alright 👍

And my request to the Modders  @JavkhlanK @PranavPurwar   who involved here to build such an amazing app , that they should use here a background loop with progress, for which app will not crash even there heavy load .. I think I suggest you sir from my little mind .. but exactly I don't know how the variables in an projects were saved ... But obvious that progress dialog is need here for preventing heavy load like variables..🙏


For fixing issue or how to avoid, then you should not make many variables in an project .. except this you can use  custom variables for short work...(Understand) and try to reduce the variables..

**Comment by Ars-king** [comment]
Thanks

And I'm found bypass solution this problems

**Comment by Ars-king** [comment]
> > 
> 
> If you see your project's variable, which is too many and i think variables in a project were saved in json format in sketchware (i don't know really but guess only) because of this , sketchware failed to show your list variables in your project as no background processing loop were used here to show the list variables and that is why Sketchware automatically crashing... Alright 👍
> 
> And my request to the Modders  @JavkhlanK @PranavPurwar   who involved here to build such an amazing app , that they should use here a background loop with progress, for which app will not crash even there heavy load .. I think I suggest you sir from my little mind .. but exactly I don't know how the variables in an projects were saved ... But obvious that progress dialog is need here for preventing heavy load like many variables..🙏
> 
> 
> For fixing issue or how to avoid, then you should not make many variables in an project .. except this you can use  custom variables for short work...(Understand) and try to reduce the variables..

$ (For fixing issue or how to avoid, then you should not make many variables in an project .. except this you can use custom variables for short work...(Understand) and try to reduce the variables..)

# you're right thanks a lot 💙
