### ISSUE TITLE
webview Error

### ISSUE THREAD

**Issue by moderGamer** [Sketchware-Pro/Sketchware-Pro#792]
hi me using sdk 33 in project for road html file 
![Screenshot_20230301-194000_web](https://user-images.githubusercontent.com/125615066/222245044-ba26e0a5-f313-4b3b-9ef3-506698667a60.jpg)

my code using 

```java


WebSettings webSettings = w.getSettings();
webSettings.setAllowContentAccess(true);
webSettings.setAllowFileAccess(true);

w.loadUrl("file:///".concat("/storage/emulated/0/Android/main.html"));
```

**Comment by JavkhlanK** [comment]
This is not a tracker for general Sketchware Pro development issues. It's for bugs and feature requests only, and this is neither of them.

**Comment by moderGamer** [comment]
> 

Thanks for the reply, can you help me to fix it?  I will be happy if you help me so that I can share a public project for others
