### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by moderGamer** [Sketchware-Pro/Sketchware-Pro#797]
Hello, I have activated Proguard, this R8 Shrick, if I have written it correctly, the Proguard program works fine, but it does not enter the program.
![Screenshot_20230305-132745_Sketchware Pro](https://user-images.githubusercontent.com/125615066/222954005-100b7c5f-be03-4f0f-b936-21599c224943.jpg)
![Screenshot_20230305-133241_One UI Home](https://user-images.githubusercontent.com/125615066/222954008-1cc3b165-aa08-4812-b314-cce76601199a.jpg)

Did you notice that there are default codes in Proguard.pro rules? I didn't type any code. Is this a bug?

![Screenshot_20230305-132158_Sketchware Pro](https://user-images.githubusercontent.com/125615066/222954057-0b9344c3-3106-4f67-a61c-f228ad0e1902.jpg)

**Comment by PranavPurwar** [comment]
Some code in your application was removed incorrectly, you would need to debug it yourself

**Comment by moderGamer** [comment]
> 

I checked with the mt manager, when proguard is activated, the program name package is deleted

**Comment by PranavPurwar** [comment]
> > 
> 
> I checked with the mt manager, when proguard is activated, the program name package is deleted

deleted or renamed?

**Comment by moderGamer** [comment]
> 

Deleted

**Comment by PranavPurwar** [comment]
send debug.txt

**Comment by moderGamer** [comment]
> send debug.txt

[debug.txt](https://github.com/Sketchware-Pro/Sketchware-Pro/files/10892816/debug.txt)

**Comment by PranavPurwar** [comment]
@moderGamer fixed

**Comment by moderGamer** [comment]
> @moderGamer fixed

tnks
