### ISSUE TITLE
[Property] Fast Compile App

### ISSUE THREAD

**Issue by moderGamer** [Sketchware-Pro/Sketchware-Pro#800]
Hello, can you implement a feature in Sketchware like Android Studio that will speed up the compilation speed of the program, that is, Sketchware will only go to the file that has been changed and compile it, not the rest of the files. I think that this will increase the compilation speed.  It will be much longer, maybe a second

@PranavPurwar

**Comment by JavkhlanK** [comment]
Closed due to spam by that user.
