### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#804]
3. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 22)
	View _view = _toast.getView();
	                    ^^^^^^^^^
The method getView() from the type Toast is deprecated
----------
4. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 31)
	_view.setBackgroundDrawable(_gradientDrawable);
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
5. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 53)
	View _view = _toast.getView();
	                    ^^^^^^^^^
The method getView() from the type Toast is deprecated
----------
6. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 64)
	_view.setBackgroundDrawable(_gradientDrawable);
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method setBackgroundDrawable(Drawable) from the type View is deprecated
----------
7. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 126)
	NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
	^^^^^^^^^^^
The type NetworkInfo is deprecated
----------
8. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 126)
	NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
	                                                      ^^^^^^^^^^^^^^^^^^^^^^
The method getActiveNetworkInfo() from the type ConnectivityManager is deprecated
----------
9. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 127)
	return _activeNetworkInfo != null && _activeNetworkInfo.isConnected();
	                                                        ^^^^^^^^^^^^^
The method isConnected() from the type NetworkInfo is deprecated
----------
10. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 148)
	_inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0);
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method toggleSoftInput(int, int) from the type InputMethodManager is deprecated
----------
11. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 153)
	_inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method toggleSoftInput(int, int) from the type InputMethodManager is deprecated
----------
12. WARNING in /storage/emulated/0/.sketchware/mysc/604/app/src/main/java/com/subhash/ghosh/sg/banglarbhumi/SketchwareUtil.java (at line 153)
	_inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
	                                                       ^^^^^^^^^^^
The field InputMethodManager.SHOW_FORCED is deprecated
----------

**Comment by subhash16** [comment]
SketchwareUtil.java there is deprecated code ,is it possible to replace the deprecated code

**Comment by JavkhlanK** [comment]
3. That code's part of custom toasts which won't work in newer Android versions at all. Unfixable without removing the Custom Toast Blocks.
4. Fixable
5. See 3.
6. Fixable
7. Unfixable, at least in the way the current Block is
8. Part of 7
9. Part of 7
10. Probably not fixable, I never found that IME code to 100 % work
11. See 11
12. See 12

**Comment by JavkhlanK** [comment]
I've fixed the currently fixable warnings with commit 8879a5cc4bbd8115b421af8ce7d7211d8e2bfb12.

**Comment by subhash16** [comment]
O

**Comment by JavkhlanK** [comment]
In this repo, Issues should be kept opened until a version fixing the Issue's problem(s) is released.

**Comment by subhash16** [comment]
I will not report anymore
