### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#817]
![Screenshot_2023-03-22-17-54-00-294_com vmos pro](https://user-images.githubusercontent.com/37414496/226905870-68eeb987-4111-4e3a-afc8-6a44287410a9.jpg)

**Comment by DereckySany** [comment]
Please also tell steps to reproduce that error, or even better, a screen recording when you upload stack traces here. If you can't, just use the in-app Send crash report button instead, please.

**Comment by subhash16** [comment]
> send crash button is broken because someone spammed it

I Didn't understand Sir

**Comment by subhash16** [comment]
.
