### ISSUE TITLE
Graphical glitch when displaying collection block contain missing moreblock

### ISSUE THREAD

**Issue by oong819** [Sketchware-Pro/Sketchware-Pro#824]
summary: read title

it's hard to explain, video: https://youtu.be/Fv1tsXZYes4

screenshot:
![Screenshot_20230401-233810](https://user-images.githubusercontent.com/76146430/229304855-c08a5f60-bd3c-4e2c-b33b-5b353d783e47.png)

**Comment by HAKANKOKCU** [comment]
it doesnt only happen in missing more block, it can always happen as i get them even with sketchware's own blocks

**Comment by adesonob** [comment]
What version of sk are you using?

**Comment by JavkhlanK** [comment]
Which *exact* Sketchware Pro version did you use? By that I mean e.g. v6.4.0-SNAPSHOT-9098f49d or v6.4.0-rc05, not less. Make sure the Blocks from Collections weren't saved with an old snapshot build that had Logic Editor bugs. The same goes for restoration of them.

**Comment by HAKANKOKCU** [comment]
in my case v6.4.0-rc05 when i saved and loaded in same project and version it was happening... same happens in my pull request bulid (i dont really know its version)

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this. There also haven't been any further reports like this, and see my message above.

Please re-open this or a new Issue only with more details.
