### ISSUE TITLE
bad display on last changes

### ISSUE THREAD

**Issue by adesonob** [Sketchware-Pro/Sketchware-Pro#825]
the edit fields do not show the typed text.
![Screenshot_20230402-121729_Sketchware Pro](https://user-images.githubusercontent.com/92691301/229362277-16b2409d-f06e-4521-81e1-f146e386fd28.png)

**Comment by JavkhlanK** [comment]
For comments and feedback on #821's changes, comment there and don't create new Issues until it's merged.

**Comment by TechnicalStudioDeveloper** [comment]
But this one is occurred automatically.And still not fixing.
