### ISSUE TITLE
Android studio sources code errors

### ISSUE THREAD

**Issue by aryan6205012057** [Sketchware-Pro/Sketchware-Pro#841]
Android studio export source code issu show many error in. Android studio Project for skechware please fix this errror

**Comment by aryan6205012057** [comment]
Android studio export source code issu show many error in. Android studio Project for skechware please fix this errror

**Comment by JavkhlanK** [comment]
Please learn how to file bugs correctly. [This blog post does a good job at explaining the process](https://marker.io/blog/how-to-write-bug-report). At least follow 1, 2, 3, and 5.

**Comment by JayMad18** [comment]
Can you show the error?

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
