### ISSUE TITLE
Fit Screen or Resolution Problem

### ISSUE THREAD

**Issue by MuhtasimHossain** [Sketchware-Pro/Sketchware-Pro#843]
Please bring a feature in Sketchware Pro so that any apps made in Sketchware Pro do not have any resolution problems in different devices.

**Comment by TechnicalStudioDeveloper** [comment]
> Please bring a feature in Sketchware Pro so that any apps made in Sketchware Pro do not have any resolution problems in different devices.

Your are using width property to set a width?
Like: 40dp,60dp,80dp to set width?

**Comment by MuhtasimHossain** [comment]
> > Please bring a feature in Sketchware Pro so that any apps made in Sketchware Pro do not have any resolution problems in different devices.
> 
> Your are using width property to set a width? Like: 40dp,60dp,80dp to set width?

**Comment by TechnicalStudioDeveloper** [comment]
> > > Please bring a feature in Sketchware Pro so that any apps made in Sketchware Pro do not have any resolution problems in different devices.
> > 
> > 
> > Your are using width property to set a width? Like: 40dp,60dp,80dp to set width?

??

**Comment by PranavPurwar** [comment]
@MuhtasimHossain Please start using sp and onConfigurationChange event to fix screen resolution. Nothing happens magically. Not everything can be done by swpro modders, please start realising that its not possible just like  a "feature", some things require skills and deep understanding of your layout and can only be done by the app dev instead of tool  dev

**Comment by MuhtasimHossain** [comment]
No, I have made an app but now it does not fit resolutions in some devices. Like in some devices half of my app disappears i.e. goes under the screen. I have made the linear layout match parent on both sides width and height . I want a solution to this.

**Comment by MuhtasimHossain** [comment]
What should I do?

**Comment by TechnicalStudioDeveloper** [comment]
Any screen shot?

**Comment by MuhtasimHossain** [comment]
Just tell me this how can my app fit any resolution?

**Comment by MuhtasimHossain** [comment]
?

**Comment by TechnicalStudioDeveloper** [comment]
> ?

Send the screen shot of app where it is unfit

**Comment by MuhtasimHossain** [comment]
![Screenshot_20230416-174059_Sketchware Pro](https://user-images.githubusercontent.com/122200961/232307454-404ffa2f-b3bc-4c4f-9666-81a7c8751235.jpg)

**Comment by MuhtasimHossain** [comment]
In this page I am facing the most problem. Here the bottom part of the app goes down in some devices. But in my device it's working properly.
This problem is happening in old devices. But why?

**Comment by MuhtasimHossain** [comment]
?

**Comment by TechnicalStudioDeveloper** [comment]
> In this page I am facing the most problem. Here the bottom part of the app goes down in some devices. But in my device it's working properly. This problem is happening in old devices. But why?

Just place a vscroll

**Comment by TechnicalStudioDeveloper** [comment]
> > In this page I am facing the most problem. Here the bottom part of the app goes down in some devices. But in my device it's working properly. This problem is happening in old devices. But why?
> 
> Just place a vscroll

And If you don't want to place a vscroll then just dm me on discord I will help you in project to fix it without a vscroll.

**Comment by MuhtasimHossain** [comment]
OK. Is there any code for it?

**Comment by TechnicalStudioDeveloper** [comment]
> OK. Is there any code for it?

Weight properly

**Comment by MuhtasimHossain** [comment]
Should I set the weight to 1? And is it necessary to set the weight sum 1?

**Comment by TechnicalStudioDeveloper** [comment]
> Should I set the weight to 1? And is it necessary to set the weight sum 1?

Contact on discord  
Username : TechnicalStudioDeveloper#1110

**Comment by MuhtasimHossain** [comment]
I have sent you request. 
My id: EUSHA#6503

**Comment by TechnicalStudioDeveloper** [comment]
I hope this error is solved now as discord chat.
