### ISSUE TITLE
Change Font: Crash & White Screen

### ISSUE THREAD

**Issue by DaichowDev** [Sketchware-Pro/Sketchware-Pro#845]
I have been experiencing this error in the latest debug version.
I have been trying to change the font of my application, but when I open the application it stays on a white screen.
This only happens in any activity that has been given the command to change the font.
Now, in an activity, I add a button that does exactly the same, the application closes automatically.

edited:
There is no debug or console errors, just a white screen in the case of doing it in onCreate. On the other hand, if there is an event like a button, when the application crashes there is no "console error" either.

**Comment by JavkhlanK** [comment]
Sounds like added Fonts got corrupted. Try removing all and adding them again.

**Comment by JavkhlanK** [comment]
Any updates?

**Comment by DaichowDev** [comment]
> Any updates?

The fonts are corrupted, some of them didn't work. I removed all fonts and I added it again. Just 3-4 fonts worked at least. Thanks!
