### ISSUE TITLE
Editing the manifest to add <uses-feature>...tag

### ISSUE THREAD

**Issue by CarlosCMD** [Sketchware-Pro/Sketchware-Pro#866]
Please add a way to edit the manifest(excluding the area inside "<application " tag. I want to add the following;
`<uses-feature
    android:name="android.hardware.camera"
    android:required="false"/>`
but it must not be inside the "<application" tag.

**Comment by JavkhlanK** [comment]
There already is a way to edit AndroidManifest.xml, actually all XML files generated by Sketchware Pro. You can edit them with XML Command Blocks which are located in the More Block Palette after enabling built-in Blocks in Mod Settings.

For a tutorial on them, [join the Discord server](http://discord.gg/kq39yhT4rX) and [check this and messages following it](https://discord.com/channels/790686719753846785/797801500276424724/798164544375619625) out.
