### ISSUE TITLE
Error while downloading new library: Snapshot Commit : b5a9628

### ISSUE THREAD

**Issue by InfiSoftApps** [Sketchware-Pro/Sketchware-Pro#870]
![Screenshot_2023-05-15-17-13-33-112_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/114339115/9ccaf296-42f7-4997-a780-656ab9beae99)

**Comment by JavkhlanK** [comment]
Same bug as in #862.
