### ISSUE TITLE
Google Material 1.9.0 Library Unsupported

### ISSUE THREAD

**Issue by guhg** [Sketchware-Pro/Sketchware-Pro#872]
I get this error when using the com.google.android.material:material:1.9.0 library, I want the new library (Could you guys make sketchware support it or something?):

`/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8625: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8626: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8627: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8628: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8629: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8630: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8631: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8632: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8633: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8634: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8635: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8636: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8637: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8638: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8639: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8640: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8641: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8642: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8643: error: unknown resource type 'macro'.
/storage/emulated/0/.sketchware/libs/local_libs/material_V_1.9.0/res/values/values.xml:8644: error: unknown resource type 'macro'.`

**Comment by TheRemakerMan** [comment]
The error appears because sketchware uses an old version of aapt2.

**Comment by guhg** [comment]
Could you guys update the aapt2 please or something?

**Comment by JavkhlanK** [comment]
If only building it from source was easy enough. Google doesn't provide any official arm/arm64 builds for Android, and other binaries from the internet aren't really trustworthy or are from repos with incompatible licenses.

I already tried building it myself, but I wasn't yet able to find enough time to finally get it to work.

**Comment by guhg** [comment]
Aw man. Well.... I believe in you! Bing AI and/or Bard can't help?

**Comment by JavkhlanK** [comment]
I can't find any license in that repo, so no unless it's added or explicitly allowed by the author.

**Comment by JavkhlanK** [comment]
Do you already have contact to them?

**Comment by MarvinStelter** [comment]
I guess, I'm not sure but it is possible that he is in the AndroidIDE community

**Comment by guhg** [comment]
Hmmm... It'd be awesome if that works. Have you tried it?

**Comment by Protonosgit** [comment]
https://github.com/RohitVerma882/aapt2/blob/main/LICENSE

**Comment by guhg** [comment]
If we could get the extraordinary advancement of the aapt2 feature in Sketchware Pro for its latest update can only be described as a mind-boggling concept. The intricate and intricate process of complication undoubtedly contributes to the cultivation of exceptionally sophisticated and resilient applications that push the boundaries of technological innovation.

**Comment by JavkhlanK** [comment]
Last weekend I was able to upgrade aapt2 to tag `platform-tools-33.0.3` with commit b16e7c2f89f4f96d9d8a40d454e8bf4836388640. Need to test compiling MDC v1.9.0 though.

**Comment by guhg** [comment]
Awesome. Let me know if you end up testing it.

**Comment by JavkhlanK** [comment]
This issue is present in the latest released version, so let's keep it open until it isn't anymore.

**Comment by guhg** [comment]
Okay, sorry. Check my feature request if you can. There's a new version of aapt2 I think we should update too, 34.0.3

**Comment by JavkhlanK** [comment]
any maintainer on GitHub sees new issues, there's no need to remind them.

**Comment by CyberXCoder-6649** [comment]
I think we can use build tools which AndroidIDE uses like aapt2, d8, etc from https://github.com/lzhiyong/android-sdk-tools

**Comment by JavkhlanK** [comment]
> Last weekend I was able to upgrade aapt2 to tag `platform-tools-33.0.3` with commit [b16e7c2](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/b16e7c2f89f4f96d9d8a40d454e8bf4836388640). Need to test compiling MDC v1.9.0 though.

(already done)

**Comment by tarekxr83-cyber** [comment]
/storage/emulated/0/.sketchware/libs/local_libs/
