### ISSUE TITLE
Firebase Cloud Message Notification

### ISSUE THREAD

**Issue by sketchlibpro** [Sketchware-Pro/Sketchware-Pro#873]
Firebase Cloud Message Notification is not showing in android 12 & android 13. First please fix it.

When I keep the Target SDK Version of any project below 30, then if I send a notification with the help of firebase cloud message, then that notification is shown, but if the Target SDK Version is kept above 30 or 30, the permission of POST NOTIFICATIONS is allowed. Notification does not come even after allowing, does not show

**Comment by AniketNS** [comment]
Hey @sketchlibpro, assign this to me. I'd like to work on this issue.

**Comment by sketchlibpro** [comment]
> Hey @sketchlibpro, assign this to me. I'd like to work on this issue.
 Can you send me some sources code for this.

**Comment by JavkhlanK** [comment]
hi, please improve this bug report by adding additional information [like explained here](https://birdeatsbug.com/blog/bug-report-template), thanks

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
