### ISSUE TITLE
Doesn't support viewpager2

### ISSUE THREAD

**Issue by devfreeguy** [Sketchware-Pro/Sketchware-Pro#876]
I can't use viewpager2, I have tons of errors

**Comment by JavkhlanK** [comment]
hi, please improve this bug report by adding additional information [like explained here](https://birdeatsbug.com/blog/bug-report-template), thanks

**Comment by JavkhlanK** [comment]
It doesn't look like you'll send more info about the issue anytime soon. Adding that to the policy of not adding any more built-in Components, Views, and/or Blocks (use custom ones instead), I'll close this.

Please re-open this or a new Issue only with more details.
