### ISSUE TITLE
Can't use content-type

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#878]
Hello,
I can't send content-type : multipart/form-data
in header all tried many ways but my server response is 
saying my content type was application json.
Where is the problem?
RequestNetworkController??

**Comment by JavkhlanK** [comment]
Show the Java code that tries to change the content type. At best, upload the activity's entire .java file here.

**Comment by hasrat-ali** [comment]
> Hello, I can't send content-type : multipart/form-data in header all tried many ways but my server response is saying my content type was application json. Where is the problem? RequestNetworkController??

Why you're sending `content-type: mutipart/form-data` when your server accept only `content-type: application/json` or that api return json type data?

**Comment by AmirSinaRZ** [comment]
I want to upload files on my server bro.
My problem solved it was from my server
