### ISSUE TITLE
Unability to access to the compile error saver 

### ISSUE THREAD

**Issue by hosni-fraj** [Sketchware-Pro/Sketchware-Pro#88]
I cant check my last error i didnt find anything in the `DesignActivity` for **_showing_** my last error

**Comment by hasrat-ali** [comment]
Then what's this?

https://github.com/Sketchware-Pro/Sketchware-Pro/blob/15278c1a6daa7d2fcd6a7209a61d69f628df370b/app/src/main/java/com/besome/sketch/design/DesignActivity.java#L210

**Comment by hasrat-ali** [comment]
And one more thing, do not make unnecessary issues.
