### ISSUE TITLE
Update firebase libraries

### ISSUE THREAD

**Issue by Bobur-777** [Sketchware-Pro/Sketchware-Pro#881]
Hello Sketchware Pro contributors. Can you update firebase libraries. When I build my app on 33 API app is not opening because firebase libraries is not upgraded. Please make it, thanks 👍

Screen record:
https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107874622/dcd5dfd2-7a34-4bf1-a859-7c9f3e0ced20

**Comment by PranavPurwar** [comment]
Hey, you can use the new exclude library feature to remove old libs and add custom ones with library manager

**Comment by Bobur-777** [comment]
> 

Ok i will try 🙂

**Comment by JavkhlanK** [comment]
See #469.

**Comment by Bobur-777** [comment]
But when I use exclude libs ... function app is not opening

**Comment by PranavPurwar** [comment]
> But when I use exclude libs ... function app is not opening

you need to remove and update all dependencies as well
