### ISSUE TITLE
Layouts Menu

### ISSUE THREAD

**Issue by JewelBP** [Sketchware-Pro/Sketchware-Pro#889]
YouTube player layout problem in this version. Apk Building success but  After install app not open.

**Comment by TechnicalStudioDeveloper** [comment]
You can use [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/5261962265) build all to fix your problem I think this might work.

**Comment by JavkhlanK** [comment]
Duplicate of #401.
