### ISSUE TITLE
Export error in my one app

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#891]
![Screenshot_2023-06-21-00-06-44-896_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/2b2d94a7-9abd-4ba0-986e-e47ae98d0362)

**Comment by JavkhlanK** [comment]
The error was thrown by the .dex file handling library that Sketchware Pro uses. Looking at its source code, I guess the .dex files weren't written properly or your project contains invalid UTF-8 content. Maybe it's also a storage device problem. Do you have enough free storage space?

**Comment by subhash16** [comment]
![Screenshot_2023-06-21-00-11-10-037_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/04713b22-e5f5-4b97-8d3e-46ef6537c2ea)

**Comment by subhash16** [comment]
> ![Screenshot_2023-06-21-00-11-10-037_com sketchware remod](https://user-images.githubusercontent.com/37414496/247545468-04713b22-e5f5-4b97-8d3e-46ef6537c2ea.jpg)

If I do this then no problem occurs.
But when selecting d8 and Java 1.8 the problem occurs

**Comment by subhash16** [comment]
I have no storage problem

**Comment by subhash16** [comment]
Same issue

**Comment by subhash16** [comment]
/
[Test.zip](https://github.com/Sketchware-Pro/Sketchware-Pro/files/11818784/Test.zip)
Please take a look.
Extract the zip you will get the swb fil

**Comment by JavkhlanK** [comment]
I tried compiling an Android project trying to set the same text on a TextView in Android Studio. This is the error message that I got:

`<file>: error: UTF8 representation for string "দ্বিতীয় খণ্ড – দ্বি..." is too long for the constant pool`

**Comment by subhash16** [comment]
Ok Sir then I have to two more issues
