### ISSUE TITLE
My app build on skateware pro has flags virus

### ISSUE THREAD

**Issue by Panharith-Dev** [Sketchware-Pro/Sketchware-Pro#892]
![Screenshot_20230619-165939](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/75765792/cd7e0e15-64d4-46ce-bc69-008cbc9b489f)
Do you have any way to fix that bug, please help

**Comment by JavkhlanK** [comment]
Duplicate issue. [See this comment for a quick probable fix.](https://github.com/Sketchware-Pro/Sketchware-Pro/issues/705#issuecomment-1380695209)
