### ISSUE TITLE
Simulate Touch Gesture on Phone Screen

### ISSUE THREAD

**Issue by jakesk43** [Sketchware-Pro/Sketchware-Pro#893]
Can you make a tutorial on how to simulate a touch event on the phone screen by pressing a button on a floating window or widget or action button on the phone home screen but dont let go of the touch after you release the button like holding a touch? And cancel the touch on the screen when you press the button again? Thanks

**Comment by JavkhlanK** [comment]
This isn't a general help forum for Sketchware or Sketchware Pro related issues. It's mostly for tracking bugs.
