### ISSUE TITLE
FilePicker not working on all/newer Android versions

### ISSUE THREAD

**Issue by Myanmar2dr** [Sketchware-Pro/Sketchware-Pro#897]
Hello Sirs My Android 13 not working storage Permissions in file picker. But Working below android 10.

**Comment by JavkhlanK** [comment]
Related: #293

The FilePicker Component just doesn't work on recent Android versions anymore. Its design is also flawed so that its code can't just be updated/fixed without breaking projects already using it.

**Comment by Myanmar2dr** [comment]
Hoke Sir . How to fix it. 😣
Can you Show me some ways!

**Comment by JavkhlanK** [comment]
Follow the [official Android guide on using the system file picker](https://developer.android.com/training/data-storage/shared/documents-files?hl=en#open-file).

**Comment by guhg** [comment]
Sir, I still can't make one based of that. 😔
