### ISSUE TITLE
App Crashes when compiled with latest versions of Sketchware

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#899]
I have ones made an app using Sketchware Pro v6.4.0 Beta 6[Sketchware Pro v6.4.0 Beta 6](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-beta.6) now in order to use firebase analytics I tried compiling my app with [Sketchware.Pro.v6.4.0-rc05-minApi26](https://github.com/Sketchware-Pro/Sketchware-Pro/releases/tag/v6.4.0-rc05) .
It compiled and gave a result APK file but the apk file crashes when I opens it.

Procedure:
• Compiled SWB file in Sketchware.Pro.v6.4.0-rc05-minApi26 
• Installed and Run
• App Crashes

You can try with the swb file I shared on sketchub [Download .swb file ](https://web.sketchub.in/p/18251)

**Comment by JavkhlanK** [comment]
Your project uses the YouTube Player View. See #401 for more details.
