### ISSUE TITLE
Error - AppCompat and Design

### ISSUE THREAD

**Issue by kaizendevelopers** [Sketchware-Pro/Sketchware-Pro#900]
It happens recently when I upgrade my Android System.
When I use Request Network Component and Activate AppCompat and Design Library.
When I install the app, it was detected as Malicious App.
Any estimated date for the new version of Sketchware Pro?

**Comment by JavkhlanK** [comment]
1st question: See #901 for details.  
2nd question: Development on Sketchware Pro isn't continuous so I can't give any estimates at all.
