### ISSUE TITLE
Lib download problem

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#908]
Lib download problem on latest snapshot.
Stack on this ...
![Screenshot_2023-07-12-20-39-40-890_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/d1617333-676f-4a33-b5a0-464357f0692c)

**Comment by subhash16** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/5142381496
This is working fine but have problem on latest snapshot

**Comment by PranavPurwar** [comment]
> Looks like the artifact's hosted on jitpack.io (while the default repos don't include that), but it nonetheless shouldn't hang on such a log message. @PranavPurwar, since you wrote the resolver, could you please look into this?

Jitpack is already included by the library itself

**Comment by PranavPurwar** [comment]
Btw, I think its because the resolver is resolving the androidx.appcompat dependency of the library. Is there any class where I could check if dependency is already resolved by sketchware pro? @JavkhlanK

**Comment by JavkhlanK** [comment]
if you mean already shipped as a built-in library, try `mod.jbk.build.BuiltInLibraries`, and if not, I don't think any such class exists yet

**Comment by PranavPurwar** [comment]
fixed

**Comment by JavkhlanK** [comment]
why wasn't this closed automatically lamo
