### ISSUE TITLE
Latest snapshot problem

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#909]
Latest snapshot not saving the project means when I add blocks anywhere the block vanish when I press back button.

**Comment by JavkhlanK** [comment]
yeah that was a bad idea by me in commit 963897c600ccccb32325d4d018d833a8bc234ae3, will be fixed soon

**Comment by subhash16** [comment]
Fixed or not

**Comment by JavkhlanK** [comment]
"closed as completed in …" means it was indeed fixed, yes. you just need to get a nightly build built containing that commit

**Comment by subhash16** [comment]
It fixed I tried in latest snapshot
