### ISSUE TITLE
Firebase Cloud Messaging & OneSignal is not works on 31+ API

### ISSUE THREAD

**Issue by Bobur-777** [Sketchware-Pro/Sketchware-Pro#910]
I know ehy it is not working (Answer: i need to update Firebase Messaging library and android libraries), but when I use custom local library app is building without errors but app is not works (error: FLAG_IMMUTABLE ........). I used exclude local libraries function too, but again app is not working.
1. I granted permission for posting notifications. 
2. I updated messaging library from dexs.zip and libs.zip but error.
3. I replaced all "0" flag of pending intent to "const v0, 0x1000  # PendingIntent.FLAG_IMMUTABLE" and again error
4. ...
But when i use android studio it is not crashing. But i want to work in sketchware pro. Please fix this issue

**Comment by InfiSoftApps** [comment]
@Bobur-777, pls share the screenshot. I have the same issue as well.
But presently I don't have same implemented in any of my app so unable to share.

**Comment by adesonob** [comment]
It doesn't show an error. It just doesn't notify.

**Comment by InfiSoftApps** [comment]
Hmm. thats the main issue.

**Comment by JavkhlanK** [comment]
> It doesn't show an error. It just doesn't notify.

well this says otherwise:
> but app is not works (error: FLAG_IMMUTABLE ........)

@Bobur-777 any chance you could show it?

**Comment by Bobur-777** [comment]
@JavkhlanK No beo. App is not opening. Error log 
![Screenshot_2023-08-19-14-22-40-108_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/107874622/c8e685cf-0900-4e1c-a109-0db441ba6025)

**Comment by JavkhlanK** [comment]
didn't you exclude fcm using exclude built-in libraries? of course it's going to crash if you don't add a custom version using Local library Manager

**Comment by Bobur-777** [comment]
@JavkhlanK I used exclude fcm and other libs because Firebase Messaging and Firebase IID library version is low for Android 13. I used all features but it is not working. And i generated a new Sketchware Pro and I deleted firebase messaging and iid library from the Sketchware Pro but again it not work 😁.

How to fix it?

**Comment by JavkhlanK** [comment]
first of all, don't exclude a library and not add a custom version of it via Local library Manager, that's only gonna make your app crash like it does now.

secondly idk I didn't implement FCM and neither do I have a project to test it out. I'll see if I can upgrade its version though.

**Comment by Bobur-777** [comment]
@JavkhlanK Ok i think you can't fix it. I need to use Android Studio if I use my projects FCM, but Sketchware is easy and fast for develope apps. Thanks bro for your qork

**Comment by JavkhlanK** [comment]
alright I checked the release notes of FCM and fixes for Android 13 are available since 23.0.6 (2022-07-15), but before that there's been a breaking change with 22.0.0 (2021-05-11) which might break some projects. i guess this is unfixable unless you use a custom version from Local library Manager.

**Comment by Bobur-777** [comment]
@JavkhlanK Bro can you create it for me please if works perfectly i will give you $100 for project . Please 🥺

**Comment by kaat656** [comment]
Yes, Firebase notifications do not appear to the user sdk31+How can I solve this problem? All my applications are like this. Can you send us the solution?I hope for help. I have been asking for a solution for a year and have not found a way to do so

**Comment by H-uey** [comment]
Do you know of any solution found? Custom lib crash due to former AndroidManifest config

**Comment by InfiSoftApps** [comment]
Sorry. Haven't found any solution yet.
