### ISSUE TITLE
Double splash screen

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#911]
![IMG_20230713_205706](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/3015ccc8-455e-4749-8876-3eb13b065aac)

**Comment by subhash16** [comment]
The problem occurs only on Android 12 and above, Created a separate page for splash screen but Android 12 I think generate a default splash screen through the API

**Comment by JavkhlanK** [comment]
> To fix this issue, update your app to use the SplashScreen API.

it's not a bug in Sketchware Pro or Android, it's your app's behavior

**Comment by subhash16** [comment]
How to implement May I ask you?

**Comment by JavkhlanK** [comment]
there's view details and learn more buttons, use them
