### ISSUE TITLE
Resize blocks and add editor java

### ISSUE THREAD

**Issue by nalcwap** [Sketchware-Pro/Sketchware-Pro#920]
Is possible add a resize blocks option to scale blocks up? And if possible add the removed code source editor removed from original because i find that editor in an old mod but in this last mod i nit find the editor of souce,please add thus 2 options

**Comment by JavkhlanK** [comment]
the Direct Source Code Editor has been removed for the following reason ([message in the Discord server is here](https://discord.com/channels/790686719753846785/790749749522464779/908817727878201424)):  
![image](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/40118124/4cc21cb5-e70d-475e-9ccb-8d9edc5eefef)

and "resizing" Blocks (zooming in/out, I assume) is already an idea we are aware of but not currently striving for. keep in mind that the app is a mod and adding features like that to parts from vanilla Sketchware is hard.
