### ISSUE TITLE
About Exporting Projects to Android Studio

### ISSUE THREAD

**Issue by anthony-china** [Sketchware-Pro/Sketchware-Pro#925]
The project cannot be imported to the latest version of Android Studio

**Comment by anthony-china** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Users\������\xiangmu\app\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.application'.
   > Your project path contains non-ASCII characters. This will most likely cause the build to fail on Windows. Please move your project to a different directory. See http://b.android.com/95744 for details. This warning can be disabled by adding the line 'android.overridePathCheck=true' to gradle.properties file in the project directory.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by ilyassesalama** [comment]
As Jbk0 mentioned, try to read the error message first. Anyways, the error says that the path where you project is located is not valid, you may want to change the project location or rename the directory.
