### ISSUE TITLE
There is a lot of deprecated code in the project

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#933]
Due to Google's update, there is a lot of deprecated code in the project, causing the apk build to fail!

**Comment by Win-one** [comment]
eg:Java.securty.Accesscontroller

**Comment by JavkhlanK** [comment]
show *exact* error messages and try to explain your problem better please

**Comment by Win-one** [comment]
Sketchware-Pro\jaxp\internal\src\main\java\org\openjdk\com\sun\org\apache\bcel\internal\util\SecuritySupport.java:29: ����: [removal] java.security �е� AccessController �ѹ�ʱ, �ұ��Ϊ��ɾ��
import java.security.AccessController;

**Comment by JavkhlanK** [comment]
Just ignore that, it's no use caring about. It doesn't hinder build anyway.
