### ISSUE TITLE
Some errors when run

### ISSUE THREAD

**Issue by hussin7466** [Sketchware-Pro/Sketchware-Pro#937]

**Comment by JavkhlanK** [comment]
hi, please improve this bug report by adding additional information [like explained here](https://birdeatsbug.com/blog/bug-report-template), thanks

**Comment by mikaaamoe** [comment]
> _No description provided._

provide a more detailed explanation, kid moments.

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
