### ISSUE TITLE
Implementing Home Screen Widgets

### ISSUE THREAD

**Issue by Magnogen** [Sketchware-Pro/Sketchware-Pro#938]
I wanted to ask, as the original Sketchware doesn't have any capacity for this.

Would it be possible to add a component, a dedicated View type, or something like that for making widgets? I'd love to be able to make my own with Sketchware.

In the meantime, is it possible to do it with the features this project has already added? I've tried following tutorials, but I couldn't get any to work for some reason.

Lots of love and hundreds of happinesses,
\- Mag

**Comment by ilyassesalama** [comment]
Home screen widgets aren't stuff that you can simply drag and drop in the view editor then they'll work just like that. You may check [this article](https://developer.android.com/develop/ui/views/appwidgets#java) by Google, it is very descriptive.

**Comment by Magnogen** [comment]
ooh thats a handy reference, thank you
