### ISSUE TITLE
Add Confirm cancel option

### ISSUE THREAD

**Issue by Memehub-Network** [Sketchware-Pro/Sketchware-Pro#940]
This problem always affects me unintentionally when compilation is running.I may cancel the build even if the compilation is almost finished.

**LOGIC**

I just wanted to have a confirmation dialog pop-up that alerts whether to cancel or continue building.
It'll save some of us.🙏

**Comment by subhash16** [comment]
Good

**Comment by adesonob** [comment]
I liked the idea

**Comment by Memehub-Network** [comment]
That's nice.It mostly matters alot to me and others😁✔️

**Comment by JavkhlanK** [comment]
just a question: why didn't you use the feature request Issue template?

**Comment by ilyassesalama** [comment]
It took a while but this feature has been added with [583ce1f](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/583ce1f8a76b50adb4eda69de85ca0c685446e44) and [7ffd0f2](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/7ffd0f2c2a98b6a6ae03bddd5655484e941421b3). This feature is available in both the [redesigned version](https://github.com/Sketchware-Pro/Sketchware-Pro/tree/material-redesign) of Sketchware Pro and the main version.

**Comment by JavkhlanK** [comment]
I think feature requests should stay opened until a version containing that feature is released.
