### ISSUE TITLE
Back button not working 

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#941]
Back button not working on library download page
See screenshot
![Screenshot_2023-08-06-12-43-53-009_com sketchware remod](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/8d69bbfe-90ce-40d3-8f50-7766adf53a29)

On latest snapshot 
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/5775455545

**Comment by JavkhlanK** [comment]
should be fixed
