### ISSUE TITLE
Defining AdMob app ID not enforced -> easy, hard to debug runtime crash

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#943]
On latest snapshot when I build the old project make from rc05 are build successfully but app crashes 

If old project uses local library then this thing happens specially.I try to redownload the library but it's also download so many library I can't tell you .but redownload not solved the problem.

![IMG_20230806_192850](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/cc8d0f6a-4dcd-4d68-9bcd-ef3696987007)
I download red mark toast library but it also download the yellow marks.

**Comment by PranavPurwar** [comment]
> On latest snapshot when I build the old project make from rc05 are build successfully but app crashes
> 
> If old project uses local library then this thing happens specially.I try to redownload the library but it's also download so many library I can't tell you .but redownload not solved the problem.
> 
> ![IMG_20230806_192850](https://user-images.githubusercontent.com/37414496/258647133-cc8d0f6a-4dcd-4d68-9bcd-ef3696987007.jpg) I download red mark toast library but it also download the yellow marks.

It is because the red library needs the yellow libraries to work. You can unselect them, but note that they may break the red library. After all, not an SWPro bug

**Comment by subhash16** [comment]
But which not use library that app also crash

**Comment by PranavPurwar** [comment]
Send proper details about the crash. I cannot just guess the issue just by hearing "It's crashing."

**Comment by subhash16** [comment]
[Crash.swb.zip](https://github.com/Sketchware-Pro/Sketchware-Pro/files/12269863/Crash.swb.zip)
Build this bundle in latest snapshot it's built in rc05

**Comment by subhash16** [comment]
Just remove .zip

**Comment by subhash16** [comment]
[Crash.swb.zip](https://github.com/Sketchware-Pro/Sketchware-Pro/files/12269943/Crash.swb.zip)
Just remove .zip and restore the swb you will face the problem in latest snapshot but no problem in rc05

**Comment by subhash16** [comment]
Note:- I found why the app crash.

If I remove all admob interstitial ads and off ads then no problem when readding problem occurs

**Comment by PranavPurwar** [comment]
I didn't ask for SWB, but the crash log.

**Comment by JavkhlanK** [comment]
> Note:- I found why the app crash.
> 
> If I remove all admob interstitial ads and off ads then no problem when readding problem occurs

that's why the app's crashing, you didn't define the AdMob app ID using the Component-blue setAdmobAppId Block from the View Palette

**Comment by JavkhlanK** [comment]
i already had this on my todo list but anyway the app shouldn't allow building projects using AdMob when the app ID isn't set.

also the way to define the app ID really should be changed from a Block to a setting

**Comment by subhash16** [comment]
Where to set app I'd I in the same activity on "onCreat" or where I load or show the ads

**Comment by JavkhlanK** [comment]
it doesn't matter, the Block contains no code.

**Comment by JavkhlanK** [comment]
also @subhash16, *please* always tell which **exact** snapshot build you used, **never just "latest snapshot version"** since you could be out-of date.

so: e.g. "v6.4.0-SNAPSHOT-78f64546-minApi21" instead of "latest snapshot"

**Comment by subhash16** [comment]
> also @subhash16, _please_ always tell which **exact** snapshot build you used, **never just "latest snapshot version"** since you could be out-of date.
> 
> so: e.g. "v6.4.0-SNAPSHOT-78f64546-minApi21" instead of "latest snapshot"

https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/5776697634

v6.4.0-SNAPSHOT-789b95d-minApi26
I used all recent actions

**Comment by subhash16** [comment]
Currently using as stable this snapshot has no problem like that.
v6.4.0-SNAPSHOT-c056ca0-minApi26

**Comment by JavkhlanK** [comment]
I was just telling what you should start doing in the future in all bug reports, not just Sketchware Pro stuff. Exact version names help identify problems better than "latest version" since they can't be ambiguous.

**Comment by subhash16** [comment]
> I was just telling what you should start doing in the future in all bug reports, not just Sketchware Pro stuff. Exact version names help identify problems better than "latest version" since they can't be ambiguous.

Sir, I am really sorry for that I didn't follow the provided instructions.

**Comment by subhash16** [comment]
Sorry for disturbance, Plz fix this as soon as possible

**Comment by subhash16** [comment]
Hey I have an idea to fix this and it's working 
Open project> 
then goto Configuration (three dot)>
AndroidMenifest>
App Components>
Then paste this code


<meta-data
android:name="com.google.android.gms.ads.APPLICATION_ID"
android:value="ca-app-pub-3940256099942544~3347511713"/>


NB:- ca-app-pub-3940256099942544~3347511713
Is your admob app ID

**Comment by subhash16** [comment]
Solved the issue

**Comment by JavkhlanK** [comment]
> i already had this on my todo list but anyway the app shouldn't allow building projects using AdMob when the app ID isn't set.
> 
> also the way to define the app ID really should be changed from a Block to a setting

**Comment by subhash16** [comment]
Good

**Comment by subhash16** [comment]
I have an issue related to this
Do that also currently I have to this manual
android:name="com.google.android.gms.permission.AD_ID"
Also do that when admob enable this permission also enable or give a setting

**Comment by JavkhlanK** [comment]
use a newer nightly build, that's already been fixed

**Comment by subhash16** [comment]
![IMG_20230910_215805](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/7672e7c8-5a1c-4fb1-ab7f-e5bb4a6e747d)
Oh yes I didn't notice that because I already set that manually.But there is no duplicate issue see the ss. Anyways thanks for that

**Comment by subhash16** [comment]
.

**Comment by subhash16** [comment]
.

**Comment by JavkhlanK** [comment]
why did you close all your issues…

**Comment by subhash16** [comment]
Don't reopen

**Comment by JavkhlanK** [comment]
Enough is enough, stop spamming.

**Comment by subhash16** [comment]
Solve in recent changes

**Comment by subhash16** [comment]
Solve in recent changes
