### ISSUE TITLE
Custom Variable show errors

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#947]
Custom Variable detect as invalid 
![IMG_20230810_202754](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/c9090677-862e-4ff7-bc92-3b4e4c54b993)
![IMG_20230810_202826](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/7b0a0007-c1d0-4985-8a75-d5a76f5aa591)
![IMG_20230810_202850](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/c2afd43c-22fc-446a-8ce1-200b8fdc90a0)
Version v6.4.0-SNAPSHOT-c056ca0-minApi26

**Comment by JavkhlanK** [comment]
Also see #912

**Comment by subhash16** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/5791506498
Same problem
