### ISSUE TITLE
Menu variable not showing

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#949]
Menu variable not showing

Version v6.4.0-SNAPSHOT-c056ca0-minApi26
![IMG_20230817_230114](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/a18dd88f-dd87-44bd-b357-662f0159bfb1)

**Comment by JavkhlanK** [comment]
1. you used a very old snapshot build built from a PR, try using a newer version first
2. that menu selector lists menu files in menu/ in Resource Manager and it works for me using v6.4.0-SNAPHOT-c22110b

**Comment by JavkhlanK** [comment]
try using a newer nightly build and/or check first that you really did create a menu file there

**Comment by subhash16** [comment]
> try using a newer nightly build and/or check first that you really did create a menu file there

New version have admob problem

**Comment by JavkhlanK** [comment]
well since you're not even gonna try and I can't reproduce the issue, I'll close this

**Comment by subhash16** [comment]
https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/6157446527
Still I can't select menu.
Do I need to create anything. Becoz earlier some version I forget the version,that version just select the menu,menu1,menu2,menu3

**Comment by JavkhlanK** [comment]
i have 0 knowledge about those Blocks but my test project randomly failed to show the menu so this somehow really is an issue

**Comment by subhash16** [comment]
> i have 0 knowledge about those Blocks but my test project randomly failed to show the menu so this somehow really is an issue

Are you OK?

**Comment by subhash16** [comment]
Closing, reopening

**Comment by guhg** [comment]
I have same but sometimes

**Comment by hasrat-ali** [comment]
You need to create menu in `Resource Manager >> menu `.

![Screenshot_20230914-083857](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/42956453/e4c7c4a6-fb21-4afe-b7a5-f689ba59f57d)
![Screenshot_20230914-083536](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/42956453/b36adc19-900b-443e-ab2d-bbcbcbc68b1f)

**Comment by JavkhlanK** [comment]
> Closing, reopening

did you not get my message? i was able to reproduce the bug, that's why

**Comment by JavkhlanK** [comment]
@hasrat-ali idk how it's triggered but sometimes those menus just aren't shown

**Comment by hasrat-ali** [comment]
How i can reproduce that?

**Comment by elfilibusterismo** [comment]
> How i can reproduce that?

Just delete the files in /.sketchware/resources/block/Menu Block/

**Comment by subhash16** [comment]
> > How i can reproduce that?
> 
> Just delete the files in /.sketchware/resources/block/Menu Block/

Nothing happen

**Comment by subhash16** [comment]
I have to manually create a sample file in resource>Menu > xyz.xml
It's not created automatically.

**Comment by subhash16** [comment]
Menu file should be in-built.

**Comment by subhash16** [comment]
I will not report anymore
