### ISSUE TITLE
Disable feature for download sub-dependencies.

### ISSUE THREAD

**Issue by Bobur-777** [Sketchware-Pro/Sketchware-Pro#950]
I am waiting 10-20 minutes for every download dependencies. Add a new button to **download library** dialog and when I turn off it download only dependencies not sub-dependencies.

_Thanks for read my issue, sorry for my English and add that feature 👍_

**Comment by CyberXCoder-6649** [comment]
I think DependencyResolver need to be enhanced, BTW I have done some enhancements in #942 which speed up dependency resolution process by addung caching mechanism in DependencyResolver

**Comment by CyberXCoder-6649** [comment]
I have tested #942 but still it requires further testing and enhancement
