### ISSUE TITLE
VirusTotal showing Malware in Sketchware created application 

### ISSUE THREAD

**Issue by PrakharDoneria** [Sketchware-Pro/Sketchware-Pro#952]
**An application made with Sketchware Pro Latest Release shows signs of containing malware in APK produced**
An example app [HTML Editor PRO ](https://web.sketchub.in/p/18251) that is been made with Sketchware latest version shows malware error even when secure libraries are been used. According to VirusTotal scan report and Jio Security scanner the app contains malware. The report can be seen on [Uptodown App Store ](https://com-protecgames-htmleditor.en.uptodown.com/android) 
**Procedure**
Follow the steps to see problem yourself:
1. Create new project 
2. Simply add some layout and Compile 
3. Scan APK file with VirusTotal

**Expected behavior**
The APK must not contain Malware like Android Studio outputs.
**Screenshots**
![chrome_screenshot_1692508596556](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/92568876/5b400a6e-15db-4ce5-bfb9-3605cf468114)

Device and Sketchware Pro-related info:
 - Device: Infinix Hot Play 12
 - OS: Android 11
 - Sketchware Pro version: Sketchware.Pro.v6.4.0-rc05-minApi26 ( Sketchware Pro v6.4.0 test build 05 )

**Comment by JavkhlanK** [comment]
See #901.
