### ISSUE TITLE
Add option in all projects for adaptive icon support

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#958]
**Is your feature request related to a problem? Please describe.**
No, just a quality-of-life enhancement. [...]

**Describe the solution you'd like**
Similar to Android Studio but maybe less advanced, add the ability to upload adaptive icon qualities to an app. Give a section to upload foreground, background, and monochrome for projects.

**Describe alternatives you've considered**
It's already possible to programably do it, and I've done it by using command blocks, adjusting cons in the dependency loader, and attaching the files in drawable. This feature I have requested would just make it easier for reverse support with devices below Android 8 and easier on the amount of time it takes for each app we develop.

**Additional context**
Please don't spam the comments saying, "This is already possible by... blah blah" I know it's already possible, but it would be nice to have the feature integrated into Sketchware so we don't have to go through unnecessary trouble and improve the consistency in the code.

**Comment by guhg** [comment]
This would be very useful

**Comment by guhg** [comment]
Yes, exactly my thoughts. Would be an awesome feature, just need someone willing to do it.

**Comment by appt2** [comment]
> Hmm, this would require an entire implementation of something completely new. Maybe a new activity called "Launcher icon manager" since you have to choose a foreground (image), background (image or color), and monochrome (SVG that must be converted to XML). I wonder who's ready to implement such a feature in Sketchware Pro.

@ilyassesalama omm you

**Comment by Mustiy0** [comment]
Added in #1396 
@trindadedev13 also close this one, ty.
