### ISSUE TITLE
andoid studio import code face many issu plese help me sir

### ISSUE THREAD

**Issue by aryan6205012057** [Sketchware-Pro/Sketchware-Pro#959]
**Describe the bug**
Please give us a clear and concise description of what the bug is.

**To Reproduce**
1. Step 1
2. Step 2
3. Step 3
...

**Expected behavior**

**Screenshots**

Device and Sketchware Pro-related info:
 - Device: [e.g. Xiaomi Note 10]
 - OS: [e.g. Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT-3d484a9-minApi26]

**Additional context**

sir there is a lot of error while importing app in android studio please ise shi kese kre plese gelp me sir😢

**Comment by aryan6205012057** [comment]
sir there is a lot of error while importing app in android studio please ise shi kese kre plese gelp me sir😢

**Comment by JavkhlanK** [comment]
The pre-filled text when creating an Issue isn't just there to be ignored. Read it and put details in.

**Comment by JavkhlanK** [comment]
It doesn't look like any more info about the issue will be sent anytime soon, so I'll close this.

Please re-open this or a new Issue only with more details.
