### ISSUE TITLE
Firebase API Not Working

### ISSUE THREAD

**Issue by khaled-0** [Sketchware-Pro/Sketchware-Pro#98]
Firebase api & code is Deprecated & not working properly.
For realtime database : it doesn't work with the project is provided by firebase. 
Hotfix(not recommend) : use the rtdb path in project is without any http

Default Authentication works but
 Phone auth doesn't work,
 it doesn't sends otp request as it says  Can't verify application. 
Wich usually occurs when u don't add correct Sha 1 signatures. (Which I did correctly)

**Comment by JavkhlanK** [comment]
Alright, what's so deprecated about using `DatabaseReference` and `DataSnapshot`?
The database URL being wrong is known, but we're trying to fix it.

You have to sign an APK with an external tool for now, as Sketchware Pro currently doesn't support exporting a project as APK. Use the SHA1 signature of the APK signed with another tool then, that'll work.

**Comment by khaled-0** [comment]
Thanks. It looks like I will have to use 
"default-rtdb" after project I'd for now.
