### ISSUE TITLE
Performance issues (laggy, very slow)

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#984]
**Issue Description**
Upon executing the most recent snapshot of Sketchware Pro from the material-redesign branch, a significant degradation in performance was observed. The application exhibits considerable latency, with extended loading times for projects and events, protracted durations for app exports, and frequent crashes. This performance anomaly is particularly unexpected given the robust specifications of the device in use, a Samsung Galaxy Tab S8 equipped with a Snapdragon 8 Gen 1 CPU. The current experience starkly contrasts with the fluidity and efficiency encountered in Sketchware Pro Beta 5, suggesting a regression in performance metrics.

**Steps to Replicate**
To observe the reported behavior, one may:
1. Launch the latest Sketchware Pro snapshot from the material-redesign branch.
2. Observe the diminished speed and increased latency within the application.

**Anticipated Behavior**
The expectation for Sketchware Pro is an experience characterized by seamless operation, minimal RAM consumption, and swift interactions with projects, events, and export functions.

**Visual Evidence**
A video demonstrating the issue is available at the provided link: https://drive.google.com/file/d/1r9JFoeu6DEVztKS5MuEqcZd6iSQ1zf0C/view?usp=drivesdk

**Device and Application Information**
- Device: Samsung Galaxy Tab S8
- Operating System: Android 13, One UI 5.1.1
- Sketchware Pro Version: v6.4.0-SNAPSHOT-464522f-minApi26 (Still an issue in newer snapshots as of April 19, 2024)

**Supplementary Information**
The scope of this issue's impact, whether isolated to this specific snapshot or more widespread, remains uncertain. However, it is evident that the performance in Sketchware Pro Beta 5 was substantially superior.

**Comment by ilyassesalama** [comment]
This is the best bug report I've ever seen so far. May I ask, since when this is happening? Is it new or old?

**Comment by guhg** [comment]
Thank you sir. This started happening about a week ago but seems to have gotten worse over the course of several snapshots. Pretty new I'd say.

**Comment by ilyassesalama** [comment]
I think this issue is device-specific. I tried running the latest snapshot on 4 devices, all of them worked smoothly. Also, the debug version of Sketchware Pro will always be slow since it's not compiled for production. When we're going to release a stable version, it'll be compiled with the production rules to remove any debugging codes.

**Comment by guhg** [comment]
Yes sir. Thank you.

**Comment by ilyassesalama** [comment]
I haven't tested on Samsung devices. I'll investigate more in this issue if more users are impcated. For now, I don't think I can do anything.

**Comment by guhg** [comment]
Okay, thank you very much.

**Comment by Ohyeah66h** [comment]
I have this same issue on my Samsung device but worse. I have the s21 ultra and the latest snapshot is super slow and glitchy.

**Comment by ilyassesalama** [comment]
Good, I need a few more confirmations from different devices.

**Comment by JavkhlanK** [comment]
Works fine for me on my SM-S908B, SM-A526B, and SM-A705FN lol. The Galaxy S22 Ultra's running Android 13, security patch level 2023-09-01, the Galaxy A52 5G is running Android 13, security patch level 2023-08-01, and the Galaxy A70 however Android 11, security patch level 2022-12-01.

Maybe your devices were doing other background tasks. For example, opening the app right after installation usually makes it sluggish, but I blame app optimization for that. I waited around 1 min after installing and the app always felt as fluid as ever.  
I also have things like Samsung's virus scanner as well as Google Play Protect off. Maybe those were running on your devices.

**Comment by guhg** [comment]
That's so weird because I tested it on both my friends A14 and my own Galaxy Tab S8 and the sketchware material redesign snapshot performs very poorly and lags as shown in the video. I have no apps in the background and when I roll back to beta 5, no issues at all.

**Comment by adesonob** [comment]
I'm using it on an A7 tab, there's a little delay but nothing major.

**Comment by subhash16** [comment]
No Performance issues in Redmi Note 10 Pro/Max

**Comment by guhg** [comment]
Yes we are talking about Samsung

**Comment by ilyassesalama** [comment]
I tested this commit `464522f` on Samsung S22, the app works smoother than my Redmi Note 10 Pro. I highly doubt this is related to Samsung devices.


https://github.com/Sketchware-Pro/Sketchware-Pro/assets/46769766/aab18419-9a00-46eb-9708-ae6c9f9a228e

**Comment by guhg** [comment]
Very odd. Have you tested it on a project with a lot of code, components resources etc? Also it makes no since because my device lags a lot on the material redesign beta. Virus protection is off, no apps are open, and Sketchware beta 5 works perfectly

**Comment by JavkhlanK** [comment]
Any chance you could share some project(s) with bad performance for you?

**Comment by guhg** [comment]
Well, those projects are kinda for my company and I wouldn't like releasing
the source code if you understand

**Comment by guhg** [comment]
I honestly wouldn't like giving out my projects. Theyre apart of my company

**Comment by ilyassesalama** [comment]
That's alright. May I ask, I think the app lags for you even in the projects list not just when opening a project, right?

**Comment by subhash16** [comment]
> Very odd. Have you tested it on a project with a lot of code, components resources etc? Also it makes no since because my device lags a lot on the material redesign beta. Virus protection is off, no apps are open, and Sketchware beta 5 works perfectly

If you have lots of code in a single event then separate the code with the help of moreblock, lots of code in a single event will lag in all version I face the issues on older version then I separate the code with moreblock no issues occur till now

**Comment by guhg** [comment]
> That's alright. May I ask, I think the app lags for you even in the projects list not just when opening a project, right?

Yes, but not all the time. There's random stutters and pages when clicked have a very slight delay. If I roll back to beta 5 everything is fast again though. Just the most annoying thing is when I'm trying to quickly work on a project and when I click on onClick events and onCreate events, it takes a long time and shows a black screen when trying to load a lot of code but it never used to do that

**Comment by ahmedbarwari** [comment]
this is right, it has been 2 days iam facing this problem, its so sad this is happening i wish someone could figure out the solution, my phone is Samsung a72 and it laggs and so slow even when i open an empty project and it takes aroud 5 seconds just to open an empty OnClick listener

**Comment by adesonob** [comment]
It's a little delay.
I really liked the new design, but even though the delay is small, the important thing is performance.

It may be small for me, but for others it may be a big delay.

**Comment by guhg** [comment]
Yes, performance is quite bad.

**Comment by subhash16** [comment]
> Yes, performance is quite bad. Lag while scrolling, slow loading of projects and onClick events, etc. Everything is very slow and laggy.

Latest snapshot same issue

**Comment by ilyassesalama** [comment]
Alright, it seems like I’ve got enough reports to look into this problem. Though, this may take a while.

**Comment by guhg** [comment]
Thanks

**Comment by appt2** [comment]
I have also tested the same problem on several different mobiles, Poco x5&  Poco F5 and Samsung s22

**Comment by ilyassesalama** [comment]
After a few tests, I also faced the same problem in the redesigned version on my Redmi Note 10 Pro (Android 13 - Pixel ROM). However, I tried to track the issue but couldn't find what causes it.

**Comment by appt2** [comment]
> After a few tests, I also faced the same problem in the redesigned version on my Redmi Note 10 Pro (Android 13 - Pixel ROM). However, I tried to track the issue but couldn't find what causes it.
> 
> I think that this problem is caused by a memory leak since the app works fine at first then gradually becomes worse.

Can you implement the operation in a new thread?

**Comment by DevKumar00001** [comment]
> After a few tests, I also faced the same problem in the redesigned version on my Redmi Note 10 Pro (Android 13 - Pixel ROM). However, I tried to track the issue but couldn't find what causes it.
> 
> I think that this problem is caused by a memory leak since the app works fine at first then gradually becomes worse.

Do heavy tasks in a saparate threads not in UI main thread.
### For example: Loading project
Load project list in `ArrayList` - Can be done in a non ui Thread
Show progress of loading project - UI Thread
Show project when list ready - UI thread

Only doing UI related task in main thread and rest of all that can be done in background progress out it in background task and show progress bar instead of directly loading through main thread.

This can prevent lagging imo.

**Comment by JavkhlanK** [comment]
instead of speculating, have a look at the code, that's already the case

**Comment by ilyassesalama** [comment]
You all are giving me obvious ways to handle heavy threads, and I already know how to do that. As Jbk0 said, have a look at the code to understand what’s going on.

This issue will take time to resolve since the project is quite big and complicated. Help is really needed in this case.

**Comment by Ohyeah66h** [comment]
I have returned from conducting a thorough performance analysis on the following devices: Galaxy S22, Tab A7, Galaxy Note 7, Pixel 6A, and the Motorola Razer+. I have observed that all of these devices exhibit performance degradation in the material redesign branch. Some other snapshots also show signs of reduced performance, but to a lesser extent. I have compared these results with the latest Sketchware Pro beta release, which performed flawlessly. The Pixel 6A device seemed to suffer the most from the lag issue. This is a serious problem that requires immediate attention, as it affects the speed and responsiveness of the application, especially in the material redesign branch. The possible causes of this issue could include a memory leak or other inefficiencies in the code.

**Comment by guhg** [comment]
Yes, Sketchware should obviously not perform that bad. ESPECIALLY if it's
on a pretty high end device and in my case, mine is pretty good and I was
having very bad lag and terrible issues. My snapdragon 8 gen 1 device was
performing that bad so it should be even worse for lower end devices.
Crazy. But was must get to the bottom of this and not just discuss about
the issue. Let's get to the root of the problem.

**Comment by DevKumar00001** [comment]
If memory leaks then LeakCanary.

**Comment by appt2** [comment]
> > @ilyassesalama can you send Link class?
> 
> What class? Also, better to continue this discussion on our Discord server if you're willing to contribute.

I got kicked out of the discord server because some idiot thinks I'm a ninja coder, it's the result of delusions of taking drugs and comparing me to others.

**Comment by guhg** [comment]
True

**Comment by LasagnaGG** [comment]
Same issue here. My galaxy a12 performing bad performance with the sketchware pro (latest snapshot)

Another thing even only some few blocks (oncreate) it will make the app unusable or unresponsive..

**Comment by guhg** [comment]
Why is it closed

**Comment by ilyassesalama** [comment]
> Why is it closed

It is not closed. Jbk0 linked another issue with this one to prevent duplicated issues.

**Comment by guhg** [comment]
Ah ok

**Comment by Ohyeah66h** [comment]
Man.

**Comment by hleihzue** [comment]
I am facing this problem, it's so sad this is happening, my phone is Redmi note 11 S and it lags and so slow even when i open an empty project and it takes around 5 seconds just to open an empty OnClick listener.🥲

**Comment by guhg** [comment]
I ran a high work load test and it seems that Sketchware Pro indeed has either a memory leak or high intensity impact on the CPU.

**Comment by ilyassesalama** [comment]
On my side, I can only pin this issue to make it more noticeable since it's a bit serious, hoping someone notices and tries to fix it, as this problem requires a lot of investigation and time, neither of which the current modders have at the moment.

**Comment by nethical6** [comment]
Remove encryption and replace json files with CSV when

**Comment by guhg** [comment]
> After reading all messages finally I discovered that app loading actually late and there may be several reasons for example
> 
> 1. Project decryption because of large project( AES Encryption which generally used in Skechware for view and block code encryption)
> 2. Even a project is too small but the front page mean MainActivity have so many views then this may produce delay even it can produce ANR issue also
> 3. If a project uses too much custom blocks or even More blocks..this might be a reason
> 
> For opening logic editor if you face delay then this might be because of
> 
> 1. Use of large numbers of Blocks especially custom blocks
> 2. If you have  so many variables in one activity then it might load lazily but it don't effect much as I remembered
> 3. Even if you don't use much blocks but you still using add source directly block for adding lots of codes then this can reproduce lag while opening logic editor(But not much)
> 
> At last if you have so many activity even it don't have much codes but many activities then this may slow while opening project even though the logic editor(Not much lag if you really have a less number of codes but high possibility of lag for large projects keep it in mind)
> 
> I was facing this issue in my Lenovo M8 tablet android 10 while building My Project Modder Hub..but I never gets irritate because I know what's the reason behind it 😊.. If you want to know my project building information then see
> 
> 1. about 1 min or more for opening the project
> 2. about 10 to 20 sec for restore if you know
> 3. about 20 to 30 sec for opening large view Based activity (I have a really very large 😁)
> 4. about 20 sec for opening image import activity
> 5. Even it take about 5 second to add new blocks because of project size
> 6. 4 to 5 minutes for project compilation
> 7. 30 min for proguard and project compilation
> 8. I don't remember 😁 but i don't care
> 
> Anyway thanks to whole modder team who developed this marvelous tool for us

Most of the things you said, I don't agree with. First off, the terrible performance this report is about is ONLY IN the material-redesign branch. 2nd, this happens to brand new created apps that have zero code or activities in them and over time the performance progressively gets worse while in the project. When you switch over to the non-material redesign performance is back to the normal self. And after tests, I concluded that there must be some type of memory leak or the UI is too hard to load in the material redesign version of sketchware.

**Comment by developer-krushna** [comment]
@guhg Oh then sorry .. I think it's your device problem(even you are a Higher android user).. because I have seen many of mine strong encrypted based project always slow down or even it throw OutOfMememoryException  in some of the newer android while the same project working really good from android 5 to android 11 and 12..I still not understand where i made the mistake in that project. And this is really a strange thing.

 I was using the api21 (Material) in my android 5 phone and api26 for my android 10 Lenovo.. it was working just like normal UI sk Pro and I have seen bugs like sudden crash , edit text field small size,  but I didn't see any UI lag problem just like you mentioned.
That key points are usually happens because of the above reasons which I mentioned..

If you still facing issues then i recommend you to use Normal SK Pro

**Comment by Ohyeah66h** [comment]
If you don't have anything helpful to say in helping fix this bug that
several people are experiencing in material-redesign then don't add useless
comments please.

**Comment by developer-krushna** [comment]
> "developer-krushna," If you don't have anything helpful to say in helping **fix this bug** that several people are experiencing in material-redesign then don't add useless comments please.

Hmm I apologize for the invalid answer

**Comment by Ohyeah66h** [comment]
No problem man. Thank you for the help anyway 👍

**Comment by khaled-0** [comment]
@guhg Did you maybe forgot to enable "All files access" on the app.
It improves performance by a lot

**Comment by nethical6** [comment]
It lags even after enabling

**Comment by hasrat-ali** [comment]
Can anyone send a that project that cause lag

**Comment by nethical6** [comment]
For me it lags even on a complete empty project.

**Comment by HanzoDev1375** [comment]
fixed in #1171 
now sk pro good work tnks in @ilyassesalama

**Comment by guhg** [comment]
> fixed in #1171 now sk pro good work tnks in @ilyassesalama

Huh? Was it really fixed? How ...

**Comment by PranavPurwar** [comment]
It might be worthwhile to setup leakcanary on Sketchware Pro to address most of these performance issues.

**Comment by HehehBoiii78** [comment]
I'm currently running v6.4.0-SNAPSHOT-bad20a2-minApi26 and it runs so, so much faster! This is probably due to the addition of LeakCanary in Sketchware Pro. Thanks to all developers! ❤️

**Comment by ilyassesalama** [comment]
> I'm currently running v6.4.0-SNAPSHOT-bad20a2-minApi26 and it runs so, so much faster! This is surely due to the addition of LeakCanary in Sketchware Pro that I can see as an app named "Leaks" on my home screen. Thanks to all developers! ❤️

Actually, LeakCanary make apps slow due to heavy processing (you may want to delete LeakCanary folder in downloads directory from time to time since it takes up to 1GB of storage). I don't know what might have fixed the slow performance for you but LeakCanary isn't the reason for sure.

**Comment by HehehBoiii78** [comment]
> > I'm currently running v6.4.0-SNAPSHOT-bad20a2-minApi26 and it runs so, so much faster! This is surely due to the addition of LeakCanary in Sketchware Pro that I can see as an app named "Leaks" on my home screen. Thanks to all developers! ❤️
> 
> Actually, LeakCanary make apps slow due to heavy processing (you may want to delete LeakCanary folder in downloads directory from time to time since it takes up to 1GB of storage). I don't know what might have fixed the slow performance for you but LeakCanary isn't the reason for sure.

I freshly installed the app, and LeakCanary hasn't made that big of a folder yet, that may be the reason for this speed boost. But LeakCanary hasn't made the app slow *yet*, but it does occasionally freeze the app saying "LeakCanary is dumping memory to investigate leaks" so  while that doesn't make the app "slow", it briefly freezes it, but that's not annoying me because of the speed boost, nonetheless.

**Comment by subhash16** [comment]
> > Yes, performance is quite bad. Lag while scrolling, slow loading of projects and onClick events, etc. Everything is very slow and laggy.
> 
> Latest snapshot same issue

No problem now at all

**Comment by guhg** [comment]
Doesn't seem much better. Experience the issue still.

**Comment by RoyTheReal** [comment]
The newer snapshots don't seem to be as slow as it used too, which is great but it still doesn't perform as good as it did before the redesign

**Comment by ilyassesalama** [comment]
> The newer snapshots don't seem to be as slow as it used too, which is great but it still doesn't perform as good as it did before the redesign

That issues related to performance were because of memory/resource leaks. A few of them should be fixed by now. Sketchware Pro seems noticeably faster now, we need more people to confirm if that's correct.

You can download the latest nightly version of the app either from GitHub actions or our Telegram group.

**Comment by trindadedev13** [comment]
> need

Last year, on my cell phone, sketchware crashed a lot, nowadays, it runs much better (or maybe it's because I barely use it and don't notice it lol)

**Comment by Yamenher** [comment]
Guyz is it me or only you having this lag I never had lag with this phone, lemme explain :
Project opens instantly (every activity does except overloaded ones, they only take 1~3s)

• a bit of lag when adding blocks in huge events (with blocks I mean) but it doesn't matter

• Compiling project with Firebase and Google MDC takes usually 30~50 s

•Proguarding and stringfog together takes from 3m~13m depending on project size

Well, about my phone specs :

• Device : Redmi note 13 pro 5g
• Android version : 14
• RAM/ROM : 8+8 / 256

Important note : The performance was a bit laggy in My phone stock ROM tbh, but since I flashed an AOSP ROM, the lagging has been reduced by up to 93% to be precise, idrk why AOSP makes sketchware pro very fast, it's so weird :/

Idk what's happening with you but everything is fine except actual bugs that hasn't been fixed :/

**Comment by soiadmahedi** [comment]
This problem is here:
android:debuggable="true" if you changed by false debuggable using APK tools M to fix this problem and Sketchware work Perfectly.
My device Realme C55. Android 14.

**Comment by hasrat-ali** [comment]
You are using older build. Try [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/12097874141).

**Comment by barikansri3-maker** [comment]
Barik
