### ISSUE TITLE
Download Loop while downloading OneSignal SDK

### ISSUE THREAD

**Issue by InfiSoftApps** [Sketchware-Pro/Sketchware-Pro#985]
https://github.com/Sketchware-Pro/Sketchware-Pro/assets/114339115/a49d99d7-5dda-4629-bd90-90e3e13b05a4

Download stuck on various loops as shown in screen recording while downloading local library 
com.onesignal:OneSignal:5.0.1

Device and Sketchware Pro-related info:
 - Device: RedmiNote9Pro
 - OS: A.12
 - Sketchware Pro version: v6.4.0-SNAPSHOT-1b55d8a-minApi26

**Comment by ilyassesalama** [comment]
This doesn't seem like an infinite loop. It seems like your internet is slow and the downloader is taking time. Can you leave the downloader run for a longer period of time, and let me know?

**Comment by InfiSoftApps** [comment]
Sir, I waiting for almost 10 mins but it's stuck in the same.
Internet speed is fine.
I tried downloading the same with our release versions, (rc-05), it downloaded within 10-15 seconds max.

**Comment by ilyassesalama** [comment]
To be honest, the current libraries download is broken and needs to be reimplemented from scratch.

**Comment by InfiSoftApps** [comment]
Oh fine. 
Request you to please fix the same ASAP, if possible.
Thank You

**Comment by InfiSoftApps** [comment]
Oh fine.
Request you to please fix the same ASAP, if possible.
Thank You

**Comment by hasrat-ali** [comment]
Hey, i tried downloading onesignal SDK with [this](https://github.com/Sketchware-Pro/Sketchware-Pro/actions/runs/10007105414) build. And it just work fine for me.
