### ISSUE TITLE
Admob setting icon, Preview frame not visible

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#986]
![IMG_20230921_010929](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/91f91140-767b-4691-8a8b-fb452ee0615a)
![IMG_20230921_011117](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/37414496/607e8ffc-fc1e-4499-9278-7885892defdc)

**Comment by JavkhlanK** [comment]
We're still working on the UI redesign and we know which activities are broken. Please do not report anything, that'll just waste your time.

**Comment by subhash16** [comment]
Ok Sir

**Comment by subhash16** [comment]
Everytime I open sketchware I have to refresh,then the project appears
