### ISSUE TITLE
Issue with projects list, refresh is always needed to load the list

### ISSUE THREAD

**Issue by Win-one** [Sketchware-Pro/Sketchware-Pro#987]
With the latest built apk, every time I enter I need to refresh to show my project

**Comment by subhash16** [comment]
Same problem

**Comment by ilyassesalama** [comment]
Are you talking about the redesign branch, or the main branch?

**Comment by devendar2** [comment]
Buy now option not

**Comment by devendar2** [comment]
Buy now option not 
![Uploading Screenshot_20230924-022025_Shopsy Store.jpg…]()

**Comment by ilyassesalama** [comment]
Uploaded image isn't working. Though, we already know about this issue if you're talking about the redesign version of Sketchware Pro.

**Comment by ilyassesalama** [comment]
Been a while, but this issue should now be fixed with commit [93bc602](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/93bc602c2135bc54cdcbf6b4eae1a7fb9acc1906).
