### ISSUE TITLE
Upgrade to aapt2 of platform-tools-34.0.3

### ISSUE THREAD

**Issue by RoyTheReal** [Sketchware-Pro/Sketchware-Pro#988]
In https://github.com/lzhiyong/android-sdk-tools, there's a new version that Sketchware Pro should update to. The new version is 34.0.3. This will make Sketchware Pro a bit more future proof for developers.

**Comment by guhg** [comment]
Please?

**Comment by Ohyeah66h** [comment]
YES PLEASE

**Comment by guhg** [comment]
Yeah still waiting lol
