### ISSUE TITLE
sub-dependencies loop

### ISSUE THREAD

**Issue by AmirSinaRZ** [Sketchware-Pro/Sketchware-Pro#991]
When i want add 
```ir.tapsell.plus:tapsell-plus-sdk-android:2.2.3```
To my project with sub dependencies its looping for solving sub dependencies. I waited about 10 minutes but still resolving...

Device and Sketchware Pro-related info:
 - Device: [Xiaomi Poco F3]
 - OS: [Android 13]
 - Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT- f85522d-minApi26] last in main branch

**Comment by CyberXCoder-6649** [comment]
I try to resolve this issue earlier in #942 by adding caching mechanism. But @PranavPurwar said that:  caching mechanism is already implemented in Sub-Dependency Resolver

**Comment by AmirSinaRZ** [comment]
@CyberXCoder-6649 so, can i try it?

**Comment by CyberXCoder-6649** [comment]
> @CyberXCoder-6649 so, can i try it?

If you want, you can try it, but it's no longer being updated, so there may be some issues.

**Comment by PranavPurwar** [comment]
> When i want add `ir.tapsell.plus:tapsell-plus-sdk-android:2.2.3` To my project with sub dependencies its looping for solving sub dependencies. I waited about 10 minutes but still resolving...
> 
> Device and Sketchware Pro-related info:
> 
> * Device: [Xiaomi Poco F3]
> * OS: [Android 13]
> * Sketchware Pro version: [e.g. v6.4.0-SNAPSHOT- [f85522d](https://github.com/Sketchware-Pro/Sketchware-Pro/commit/f85522db24a46df0cdc81dfaeb2e55426ce07195)-minApi26] last in main branch

If you check carefully, it will show what exact dependency its processing at that moment. It's slow because of some Android limitations and because its also parsing androidx dependencies which are a lot in number.
