### ISSUE TITLE
Need admob GDPR in-built

### ISSUE THREAD

**Issue by subhash16** [Sketchware-Pro/Sketchware-Pro#997]
Need admob GDPR in-built also Give an update

**Comment by PranavPurwar** [comment]
Not everything has to be done by us, these things should only be done by users. Won't be added.

**Comment by subhash16** [comment]
It's very complicated to implement GDPR

**Comment by subhash16** [comment]
There is no single tutorial present

**Comment by ilyassesalama** [comment]
> Not everything has to be done by us, these things should only be done by users. Won't be added.

As far as I know, to fix this issue, Admob library must be updated for it to support GDPR. And Admob library in Sketchware Pro is so old.

**Comment by subhash16** [comment]
> > Not everything has to be done by us, these things should only be done by users. Won't be added.
> 
> As far as I know, to fix this issue, Admob library must be updated for it to support GDPR. And Admob library in Sketchware Pro is so old.

Need only UMP library .
Library add successfully but implementation is so complicated.
What happened if I don't implement GDPR in the app

**Comment by ilyassesalama** [comment]
You have to implement GDPR in Admob’s dashboard. No code is needed.

**Comment by subhash16** [comment]
> You have to implement GDPR in Admob’s dashboard. No code is needed.

Who told you,

**Comment by subhash16** [comment]
> You have to implement GDPR in Admob’s dashboard. No code is needed.
Look
https://developers.google.com/admob/android/privacy

**Comment by MEDSTUDIO360** [comment]
> > You have to implement GDPR in Admob’s dashboard. No code is needed.
> > Look
> > https://developers.google.com/admob/android/privacy


Here's a tutorial how to add GDPR Message to your project : https://youtu.be/eSHXgqqCcS4?si=lJWLPXPG83KGdfsG

**Comment by subhash16** [comment]
> > > You have to implement GDPR in Admob’s dashboard. No code is needed.
> > > Look
> > > https://developers.google.com/admob/android/privacy
> 
> Here's a tutorial how to add GDPR Message to your project : https://youtu.be/eSHXgqqCcS4?si=lJWLPXPG83KGdfsG

Good to see wait I will check

**Comment by subhash16** [comment]
> > > You have to implement GDPR in Admob’s dashboard. No code is needed.
> > > Look
> > > https://developers.google.com/admob/android/privacy
> 
> Here's a tutorial how to add GDPR Message to your project : https://youtu.be/eSHXgqqCcS4?si=lJWLPXPG83KGdfsG

App Crash in latest snapshot sketchware build

**Comment by MEDSTUDIO360** [comment]
Show me screenshot !

**Comment by MEDSTUDIO360** [comment]
> > > > You have to implement GDPR in Admob’s dashboard. No code is needed.
> > > > Look
> > > > https://developers.google.com/admob/android/privacy
> > 
> > 
> > Here's a tutorial how to add GDPR Message to your project : https://youtu.be/eSHXgqqCcS4?si=lJWLPXPG83KGdfsG
> 
> App Crash in latest snapshot sketchware build

Show me screenshot, I will try to help you

**Comment by subhash16** [comment]
I will not report anymore

**Comment by subhash16** [comment]
।
